// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7

// ignore_for_file: implementation_imports, unused_import, unnecessary_import, unnecessary_cast, invalid_use_of_protected_member, deprecated_member_use, sort_child_properties_last

import 'package:dartic/dartic.dart';
import 'package:dartic/dartic_internal.dart';
import 'package:flutter/src/rendering/editable.dart';
import 'dart:math' as math;
import 'dart:ui' as ui show BoxHeightStyle, BoxWidthStyle, Clip, Color, LineMetrics, Locale, Offset, Radius, Rect, SemanticsInputType, Size, TextAlign, TextBaseline, TextBox, TextDirection, TextHeightBehavior, TextPosition, TextRange;
import 'package:characters/characters.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/semantics.dart';
import 'package:flutter/services.dart';
import 'package:flutter/src/rendering/box.dart';
import 'package:flutter/src/rendering/custom_paint.dart';
import 'package:flutter/src/rendering/layer.dart';
import 'package:flutter/src/rendering/layout_helper.dart';
import 'package:flutter/src/rendering/object.dart';
import 'package:flutter/src/rendering/paragraph.dart';
import 'package:flutter/src/rendering/viewport_offset.dart';
import 'package:flutter/src/services/text_editing.dart';
import 'package:flutter/src/semantics/semantics.dart';
import 'package:flutter/src/gestures/events.dart';
import 'package:flutter/src/gestures/tap.dart';
import 'package:flutter/src/services/text_input.dart';
import 'package:vector_math/vector_math_64.dart';
import 'package:flutter/src/foundation/diagnostics.dart';
import 'package:flutter/src/painting/text_painter.dart';
import 'package:flutter/painting.dart';
import 'package:flutter/src/foundation/change_notifier.dart';
import 'package:flutter/src/painting/inline_span.dart';
import 'package:flutter/src/painting/strut_style.dart';
import 'package:flutter/src/painting/text_scaler.dart';
import 'package:flutter/src/painting/edge_insets.dart';
import 'package:flutter/src/foundation/assertions.dart';
import 'package:flutter/src/gestures/hit_test.dart';
import 'package:flutter/src/semantics/semantics_event.dart';
import 'package:flutter/src/animation/curves.dart';
import 'package:flutter/animation.dart';

abstract final class RenderEditableBindings {
  static void register(DarticPluginContext ctx) {
    ctx.registerClass(
      name: 'package:flutter/src/rendering/editable.dart::RenderEditable',
      type: RenderEditable,
      test: (o) => o is RenderEditable,
      methods: methodMap(),
      superclasses: ['package:flutter/src/rendering/box.dart::RenderBox', 'package:flutter/src/rendering/object.dart::RenderObject', 'package:flutter/src/gestures/hit_test.dart::HitTestTarget', 'package:flutter/src/foundation/diagnostics.dart::DiagnosticableTreeMixin', 'package:flutter/src/foundation/diagnostics.dart::DiagnosticableTree', 'package:flutter/src/foundation/diagnostics.dart::Diagnosticable', 'package:flutter/src/services/text_layout_metrics.dart::TextLayoutMetrics', 'package:flutter/src/rendering/object.dart::RelayoutWhenSystemFontsChangeMixin', 'package:flutter/src/rendering/object.dart::ContainerRenderObjectMixin', 'package:flutter/src/rendering/paragraph.dart::RenderInlineChildrenContainerDefaults'],
    );
  }

  static Map<String, Object? Function(List<Object?>)> methodMap() => {
        'dispose#0': (args) { (args[0] as RenderEditable).dispose(); return null; },
        'getLineAtOffset#1': (args) => (args[0] as RenderEditable).getLineAtOffset(args[1] as ui.TextPosition),
        'getWordBoundary#1': (args) => (args[0] as RenderEditable).getWordBoundary(args[1] as ui.TextPosition),
        'getTextPositionAbove#1': (args) => (args[0] as RenderEditable).getTextPositionAbove(args[1] as ui.TextPosition),
        'getTextPositionBelow#1': (args) => (args[0] as RenderEditable).getTextPositionBelow(args[1] as ui.TextPosition),
        'markNeedsPaint#0': (args) { (args[0] as RenderEditable).markNeedsPaint(); return null; },
        'systemFontsDidChange#0': (args) { (args[0] as RenderEditable).systemFontsDidChange(); return null; },
        'setPromptRectRange#1': (args) { (args[0] as RenderEditable).setPromptRectRange(args[1] as ui.TextRange?); return null; },
        'getBoxesForSelection#1': (args) => (args[0] as RenderEditable).getBoxesForSelection(args[1] as TextSelection),
        'describeSemanticsConfiguration#1': (args) { (args[0] as RenderEditable).describeSemanticsConfiguration(args[1] as SemanticsConfiguration); return null; },
        'assembleSemanticsNode#3': (args) { (args[0] as RenderEditable).assembleSemanticsNode(args[1] as SemanticsNode, args[2] as SemanticsConfiguration, (args[3] as Iterable).cast<SemanticsNode>()); return null; },
        'attach#1': (args) { (args[0] as RenderEditable).attach(args[1] as PipelineOwner); return null; },
        'detach#0': (args) { (args[0] as RenderEditable).detach(); return null; },
        'redepthChildren#0': (args) { (args[0] as RenderEditable).redepthChildren(); return null; },
        'visitChildren#1': (args) { (args[0] as RenderEditable).visitChildren((a) => (args[1] as Function)(a)); return null; },
        'getEndpointsForSelection#1': (args) => (args[0] as RenderEditable).getEndpointsForSelection(args[1] as TextSelection),
        'getRectForComposingRange#1': (args) => (args[0] as RenderEditable).getRectForComposingRange(args[1] as ui.TextRange),
        'getPositionForPoint#1': (args) => (args[0] as RenderEditable).getPositionForPoint(args[1] as ui.Offset),
        'getLocalRectForCaret#1': (args) => (args[0] as RenderEditable).getLocalRectForCaret(args[1] as ui.TextPosition),
        'computeMinIntrinsicWidth#1': (args) => (args[0] as RenderEditable).computeMinIntrinsicWidth(args[1] as double),
        'computeMaxIntrinsicWidth#1': (args) => (args[0] as RenderEditable).computeMaxIntrinsicWidth(args[1] as double),
        'computeMinIntrinsicHeight#1': (args) => (args[0] as RenderEditable).computeMinIntrinsicHeight(args[1] as double),
        'computeMaxIntrinsicHeight#1': (args) => (args[0] as RenderEditable).computeMaxIntrinsicHeight(args[1] as double),
        'computeDistanceToActualBaseline#1': (args) => (args[0] as RenderEditable).computeDistanceToActualBaseline(args[1] as ui.TextBaseline),
        'hitTestSelf#1': (args) => (args[0] as RenderEditable).hitTestSelf(args[1] as ui.Offset),
        'hitTestChildren#2': (args) => (args[0] as RenderEditable).hitTestChildren(args[1] as BoxHitTestResult, position: args[2] as ui.Offset),
        'handleEvent#2': (args) { (args[0] as RenderEditable).handleEvent(args[1] as PointerEvent, args[2] as BoxHitTestEntry); return null; },
        'handleSecondaryTapDown#1': (args) { (args[0] as RenderEditable).handleSecondaryTapDown(args[1] as TapDownDetails); return null; },
        'handleTapDown#1': (args) { (args[0] as RenderEditable).handleTapDown(args[1] as TapDownDetails); return null; },
        'handleTap#0': (args) { (args[0] as RenderEditable).handleTap(); return null; },
        'handleDoubleTap#0': (args) { (args[0] as RenderEditable).handleDoubleTap(); return null; },
        'handleLongPress#0': (args) { (args[0] as RenderEditable).handleLongPress(); return null; },
        'selectPosition#1': (args) { (args[0] as RenderEditable).selectPosition(cause: args[1] as SelectionChangedCause); return null; },
        'selectPositionAt#3': (args) { (args[0] as RenderEditable).selectPositionAt(from: args[1] as ui.Offset, to: identical(args[2], darticAbsent) ? null : args[2] as ui.Offset?, cause: args[3] as SelectionChangedCause); return null; },
        'selectWord#1': (args) { (args[0] as RenderEditable).selectWord(cause: args[1] as SelectionChangedCause); return null; },
        'selectWordsInRange#3': (args) { (args[0] as RenderEditable).selectWordsInRange(from: args[1] as ui.Offset, to: identical(args[2], darticAbsent) ? null : args[2] as ui.Offset?, cause: args[3] as SelectionChangedCause); return null; },
        'selectWordEdge#1': (args) { (args[0] as RenderEditable).selectWordEdge(cause: args[1] as SelectionChangedCause); return null; },
        'getWordAtOffset#1': (args) => (args[0] as RenderEditable).getWordAtOffset(args[1] as ui.TextPosition),
        'computeDryLayout#1': (args) => (args[0] as RenderEditable).computeDryLayout(args[1] as BoxConstraints),
        'computeDryBaseline#2': (args) => (args[0] as RenderEditable).computeDryBaseline(args[1] as BoxConstraints, args[2] as ui.TextBaseline),
        'performLayout#0': (args) { (args[0] as RenderEditable).performLayout(); return null; },
        'calculateBoundedFloatingCursorOffset#2': (args) => (args[0] as RenderEditable).calculateBoundedFloatingCursorOffset(args[1] as ui.Offset, shouldResetOrigin: identical(args[2], darticAbsent) ? null : args[2] as bool?),
        'setFloatingCursor#4': (args) { (args[0] as RenderEditable).setFloatingCursor(args[1] as FloatingCursorDragState, args[2] as ui.Offset, args[3] as ui.TextPosition, resetLerpValue: identical(args[4], darticAbsent) ? null : args[4] as double?); return null; },
        'startVerticalCaretMovement#1': (args) => (args[0] as RenderEditable).startVerticalCaretMovement(args[1] as ui.TextPosition),
        'applyPaintTransform#2': (args) { (args[0] as RenderEditable).applyPaintTransform(args[1] as RenderBox, args[2] as Matrix4); return null; },
        'paint#2': (args) { (args[0] as RenderEditable).paint(args[1] as PaintingContext, args[2] as ui.Offset); return null; },
        'describeApproximatePaintClip#1': (args) => (args[0] as RenderEditable).describeApproximatePaintClip(args[1] as RenderObject),
        'debugFillProperties#1': (args) { (args[0] as RenderEditable).debugFillProperties(args[1] as DiagnosticPropertiesBuilder); return null; },
        'debugDescribeChildren#0': (args) => (args[0] as RenderEditable).debugDescribeChildren(),
        'toString#1': (args) => (args[0] as RenderEditable).toString(minLevel: identical(args[1], darticAbsent) ? DiagnosticLevel.info : args[1] as DiagnosticLevel),
        'setupParentData#1': (args) { (args[0] as RenderEditable).setupParentData(args[1] as RenderBox); return null; },
        'getMinIntrinsicWidth#1': (args) => (args[0] as RenderEditable).getMinIntrinsicWidth(args[1] as double),
        'getMaxIntrinsicWidth#1': (args) => (args[0] as RenderEditable).getMaxIntrinsicWidth(args[1] as double),
        'getMinIntrinsicHeight#1': (args) => (args[0] as RenderEditable).getMinIntrinsicHeight(args[1] as double),
        'getMaxIntrinsicHeight#1': (args) => (args[0] as RenderEditable).getMaxIntrinsicHeight(args[1] as double),
        'getDryLayout#1': (args) => (args[0] as RenderEditable).getDryLayout(args[1] as BoxConstraints),
        'getDryBaseline#2': (args) => (args[0] as RenderEditable).getDryBaseline(args[1] as BoxConstraints, args[2] as ui.TextBaseline),
        'debugCannotComputeDryLayout#2': (args) => (args[0] as RenderEditable).debugCannotComputeDryLayout(reason: identical(args[1], darticAbsent) ? null : args[1] as String?, error: identical(args[2], darticAbsent) ? null : args[2] as FlutterError?),
        'debugAdoptSize#1': (args) => (args[0] as RenderEditable).debugAdoptSize(args[1] as ui.Size),
        'debugResetSize#0': (args) { (args[0] as RenderEditable).debugResetSize(); return null; },
        'getDistanceToBaseline#2': (args) => (args[0] as RenderEditable).getDistanceToBaseline(args[1] as ui.TextBaseline, onlyReal: identical(args[2], darticAbsent) ? false : args[2] as bool),
        'getDistanceToActualBaseline#1': (args) => (args[0] as RenderEditable).getDistanceToActualBaseline(args[1] as ui.TextBaseline),
        'debugAssertDoesMeetConstraints#0': (args) { (args[0] as RenderEditable).debugAssertDoesMeetConstraints(); return null; },
        'markNeedsLayout#0': (args) { (args[0] as RenderEditable).markNeedsLayout(); return null; },
        'performResize#0': (args) { (args[0] as RenderEditable).performResize(); return null; },
        'hitTest#2': (args) => (args[0] as RenderEditable).hitTest(args[1] as BoxHitTestResult, position: args[2] as ui.Offset),
        'globalToLocal#2': (args) => (args[0] as RenderEditable).globalToLocal(args[1] as ui.Offset, ancestor: identical(args[2], darticAbsent) ? null : args[2] as RenderObject?),
        'localToGlobal#2': (args) => (args[0] as RenderEditable).localToGlobal(args[1] as ui.Offset, ancestor: identical(args[2], darticAbsent) ? null : args[2] as RenderObject?),
        'debugHandleEvent#2': (args) => (args[0] as RenderEditable).debugHandleEvent(args[1] as PointerEvent, args[2] as HitTestEntry<HitTestTarget>),
        'debugPaint#2': (args) { (args[0] as RenderEditable).debugPaint(args[1] as PaintingContext, args[2] as ui.Offset); return null; },
        'debugPaintSize#2': (args) { (args[0] as RenderEditable).debugPaintSize(args[1] as PaintingContext, args[2] as ui.Offset); return null; },
        'debugPaintBaselines#2': (args) { (args[0] as RenderEditable).debugPaintBaselines(args[1] as PaintingContext, args[2] as ui.Offset); return null; },
        'debugPaintPointers#2': (args) { (args[0] as RenderEditable).debugPaintPointers(args[1] as PaintingContext, args[2] as ui.Offset); return null; },
        'reassemble#0': (args) { (args[0] as RenderEditable).reassemble(); return null; },
        'redepthChild#1': (args) { (args[0] as RenderEditable).redepthChild(args[1] as RenderObject); return null; },
        'adoptChild#1': (args) { (args[0] as RenderEditable).adoptChild(args[1] as RenderObject); return null; },
        'dropChild#1': (args) { (args[0] as RenderEditable).dropChild(args[1] as RenderObject); return null; },
        'markParentNeedsLayout#0': (args) { (args[0] as RenderEditable).markParentNeedsLayout(); return null; },
        'markNeedsLayoutForSizedByParentChange#0': (args) { (args[0] as RenderEditable).markNeedsLayoutForSizedByParentChange(); return null; },
        'scheduleInitialLayout#0': (args) { (args[0] as RenderEditable).scheduleInitialLayout(); return null; },
        'layout#2': (args) { (args[0] as RenderEditable).layout(args[1] as Constraints, parentUsesSize: identical(args[2], darticAbsent) ? false : args[2] as bool); return null; },
        'invokeLayoutCallback#1': (args) { (args[0] as RenderEditable).invokeLayoutCallback((a) => (args[1] as Function)(a)); return null; },
        'debugRegisterRepaintBoundaryPaint#2': (args) { (args[0] as RenderEditable).debugRegisterRepaintBoundaryPaint(includedParent: identical(args[1], darticAbsent) ? true : args[1] as bool, includedChild: identical(args[2], darticAbsent) ? false : args[2] as bool); return null; },
        'updateCompositedLayer#1': (args) => (args[0] as RenderEditable).updateCompositedLayer(oldLayer: args[1] as OffsetLayer?),
        'markNeedsCompositingBitsUpdate#0': (args) { (args[0] as RenderEditable).markNeedsCompositingBitsUpdate(); return null; },
        'markNeedsCompositedLayerUpdate#0': (args) { (args[0] as RenderEditable).markNeedsCompositedLayerUpdate(); return null; },
        'scheduleInitialPaint#1': (args) { (args[0] as RenderEditable).scheduleInitialPaint(args[1] as ContainerLayer); return null; },
        'replaceRootLayer#1': (args) { (args[0] as RenderEditable).replaceRootLayer(args[1] as OffsetLayer); return null; },
        'paintsChild#1': (args) => (args[0] as RenderEditable).paintsChild(args[1] as RenderObject),
        'getTransformTo#1': (args) => (args[0] as RenderEditable).getTransformTo(args[1] as RenderObject?),
        'describeSemanticsClip#1': (args) => (args[0] as RenderEditable).describeSemanticsClip(args[1] as RenderObject?),
        'scheduleInitialSemantics#0': (args) { (args[0] as RenderEditable).scheduleInitialSemantics(); return null; },
        'sendSemanticsEvent#1': (args) { (args[0] as RenderEditable).sendSemanticsEvent(args[1] as SemanticsEvent); return null; },
        'clearSemantics#0': (args) { (args[0] as RenderEditable).clearSemantics(); return null; },
        'markNeedsSemanticsUpdate#0': (args) { (args[0] as RenderEditable).markNeedsSemanticsUpdate(); return null; },
        'visitChildrenForSemantics#1': (args) { (args[0] as RenderEditable).visitChildrenForSemantics((a) => (args[1] as Function)(a)); return null; },
        'toStringShort#0': (args) => (args[0] as RenderEditable).toStringShort(),
        'toStringDeep#4': (args) => (args[0] as RenderEditable).toStringDeep(prefixLineOne: identical(args[1], darticAbsent) ? '' : args[1] as String, prefixOtherLines: identical(args[2], darticAbsent) ? null : args[2] as String?, minLevel: identical(args[3], darticAbsent) ? DiagnosticLevel.debug : args[3] as DiagnosticLevel, wrapWidth: identical(args[4], darticAbsent) ? 65 : args[4] as int),
        'toStringShallow#2': (args) => (args[0] as RenderEditable).toStringShallow(joiner: identical(args[1], darticAbsent) ? ', ' : args[1] as String, minLevel: identical(args[2], darticAbsent) ? DiagnosticLevel.debug : args[2] as DiagnosticLevel),
        'showOnScreen#4': (args) { (args[0] as RenderEditable).showOnScreen(descendant: identical(args[1], darticAbsent) ? null : args[1] as RenderObject?, rect: identical(args[2], darticAbsent) ? null : args[2] as ui.Rect?, duration: identical(args[3], darticAbsent) ? Duration.zero : args[3] as Duration, curve: identical(args[4], darticAbsent) ? Curves.ease : args[4] as Curve); return null; },
        'describeForError#2': (args) => (args[0] as RenderEditable).describeForError(args[1] as String, style: identical(args[2], darticAbsent) ? DiagnosticsTreeStyle.shallow : args[2] as DiagnosticsTreeStyle),
        'toDiagnosticsNode#2': (args) => (args[0] as RenderEditable).toDiagnosticsNode(name: identical(args[1], darticAbsent) ? null : args[1] as String?, style: identical(args[2], darticAbsent) ? null : args[2] as DiagnosticsTreeStyle?),
        'debugValidateChild#1': (args) => (args[0] as RenderEditable).debugValidateChild(args[1] as RenderObject),
        'insert#2': (args) { (args[0] as RenderEditable).insert(args[1] as RenderBox, after: identical(args[2], darticAbsent) ? null : args[2] as RenderBox?); return null; },
        'add#1': (args) { (args[0] as RenderEditable).add(args[1] as RenderBox); return null; },
        'addAll#1': (args) { (args[0] as RenderEditable).addAll(args[1] == null ? null : (args[1] as List).cast<RenderBox>()); return null; },
        'remove#1': (args) { (args[0] as RenderEditable).remove(args[1] as RenderBox); return null; },
        'removeAll#0': (args) { (args[0] as RenderEditable).removeAll(); return null; },
        'move#2': (args) { (args[0] as RenderEditable).move(args[1] as RenderBox, after: identical(args[2], darticAbsent) ? null : args[2] as RenderBox?); return null; },
        'childBefore#1': (args) => (args[0] as RenderEditable).childBefore(args[1] as RenderBox),
        'childAfter#1': (args) => (args[0] as RenderEditable).childAfter(args[1] as RenderBox),
        'layoutInlineChildren#3': (args) => (args[0] as RenderEditable).layoutInlineChildren(args[1] as double, (a, b) => (args[2] as Function)(a, b) as ui.Size, (a, b, c) => (args[3] as Function)(a, b, c) as double?),
        'positionInlineChildren#1': (args) { (args[0] as RenderEditable).positionInlineChildren((args[1] as List).cast<ui.TextBox>()); return null; },
        'defaultApplyPaintTransform#2': (args) { (args[0] as RenderEditable).defaultApplyPaintTransform(args[1] as RenderBox, args[2] as Matrix4); return null; },
        'paintInlineChildren#2': (args) { (args[0] as RenderEditable).paintInlineChildren(args[1] as PaintingContext, args[2] as ui.Offset); return null; },
        'hitTestInlineChildren#2': (args) => (args[0] as RenderEditable).hitTestInlineChildren(args[1] as BoxHitTestResult, args[2] as ui.Offset),
        'foregroundPainter#0': (args) => (args[0] as RenderEditable).foregroundPainter,
        'painter#0': (args) => (args[0] as RenderEditable).painter,
        'ignorePointer#0': (args) => (args[0] as RenderEditable).ignorePointer,
        'textHeightBehavior#0': (args) => (args[0] as RenderEditable).textHeightBehavior,
        'textWidthBasis#0': (args) => (args[0] as RenderEditable).textWidthBasis,
        'devicePixelRatio#0': (args) => (args[0] as RenderEditable).devicePixelRatio,
        'obscuringCharacter#0': (args) => (args[0] as RenderEditable).obscuringCharacter,
        'obscureText#0': (args) => (args[0] as RenderEditable).obscureText,
        'selectionHeightStyle#0': (args) => (args[0] as RenderEditable).selectionHeightStyle,
        'selectionWidthStyle#0': (args) => (args[0] as RenderEditable).selectionWidthStyle,
        'textSelectionDelegate#0': (args) => (args[0] as RenderEditable).textSelectionDelegate,
        'selectionStartInViewport#0': (args) => (args[0] as RenderEditable).selectionStartInViewport,
        'selectionEndInViewport#0': (args) => (args[0] as RenderEditable).selectionEndInViewport,
        'plainText#0': (args) => (args[0] as RenderEditable).plainText,
        'text#0': (args) => (args[0] as RenderEditable).text,
        'textAlign#0': (args) => (args[0] as RenderEditable).textAlign,
        'textDirection#0': (args) => (args[0] as RenderEditable).textDirection,
        'locale#0': (args) => (args[0] as RenderEditable).locale,
        'strutStyle#0': (args) => (args[0] as RenderEditable).strutStyle,
        'cursorColor#0': (args) => (args[0] as RenderEditable).cursorColor,
        'backgroundCursorColor#0': (args) => (args[0] as RenderEditable).backgroundCursorColor,
        'showCursor#0': (args) => (args[0] as RenderEditable).showCursor,
        'hasFocus#0': (args) => (args[0] as RenderEditable).hasFocus,
        'forceLine#0': (args) => (args[0] as RenderEditable).forceLine,
        'readOnly#0': (args) => (args[0] as RenderEditable).readOnly,
        'maxLines#0': (args) => (args[0] as RenderEditable).maxLines,
        'minLines#0': (args) => (args[0] as RenderEditable).minLines,
        'expands#0': (args) => (args[0] as RenderEditable).expands,
        'selectionColor#0': (args) => (args[0] as RenderEditable).selectionColor,
        'textScaleFactor#0': (args) => (args[0] as RenderEditable).textScaleFactor,
        'textScaler#0': (args) => (args[0] as RenderEditable).textScaler,
        'selection#0': (args) => (args[0] as RenderEditable).selection,
        'offset#0': (args) => (args[0] as RenderEditable).offset,
        'cursorWidth#0': (args) => (args[0] as RenderEditable).cursorWidth,
        'cursorHeight#0': (args) => (args[0] as RenderEditable).cursorHeight,
        'paintCursorAboveText#0': (args) => (args[0] as RenderEditable).paintCursorAboveText,
        'cursorOffset#0': (args) => (args[0] as RenderEditable).cursorOffset,
        'cursorRadius#0': (args) => (args[0] as RenderEditable).cursorRadius,
        'startHandleLayerLink#0': (args) => (args[0] as RenderEditable).startHandleLayerLink,
        'endHandleLayerLink#0': (args) => (args[0] as RenderEditable).endHandleLayerLink,
        'floatingCursorAddedMargin#0': (args) => (args[0] as RenderEditable).floatingCursorAddedMargin,
        'floatingCursorOn#0': (args) => (args[0] as RenderEditable).floatingCursorOn,
        'enableInteractiveSelection#0': (args) => (args[0] as RenderEditable).enableInteractiveSelection,
        'selectionEnabled#0': (args) => (args[0] as RenderEditable).selectionEnabled,
        'promptRectColor#0': (args) => (args[0] as RenderEditable).promptRectColor,
        'maxScrollExtent#0': (args) => (args[0] as RenderEditable).maxScrollExtent,
        'clipBehavior#0': (args) => (args[0] as RenderEditable).clipBehavior,
        'preferredLineHeight#0': (args) => (args[0] as RenderEditable).preferredLineHeight,
        'lastSecondaryTapDownPosition#0': (args) => (args[0] as RenderEditable).lastSecondaryTapDownPosition,
        'wordBoundaries#0': (args) => (args[0] as RenderEditable).wordBoundaries,
        'hashCode#0': (args) => (args[0] as RenderEditable).hashCode,
        'hasSize#0': (args) => (args[0] as RenderEditable).hasSize,
        'size#0': (args) => (args[0] as RenderEditable).size,
        'semanticBounds#0': (args) => (args[0] as RenderEditable).semanticBounds,
        'constraints#0': (args) => (args[0] as RenderEditable).constraints,
        'paintBounds#0': (args) => (args[0] as RenderEditable).paintBounds,
        'debugDisposed#0': (args) => (args[0] as RenderEditable).debugDisposed,
        'parentData#0': (args) => (args[0] as RenderEditable).parentData,
        'depth#0': (args) => (args[0] as RenderEditable).depth,
        'parent#0': (args) => (args[0] as RenderEditable).parent,
        'semanticsParent#0': (args) => (args[0] as RenderEditable).semanticsParent,
        'debugCreator#0': (args) => (args[0] as RenderEditable).debugCreator,
        'debugDoingThisResize#0': (args) => (args[0] as RenderEditable).debugDoingThisResize,
        'debugDoingThisLayout#0': (args) => (args[0] as RenderEditable).debugDoingThisLayout,
        'debugCanParentUseSize#0': (args) => (args[0] as RenderEditable).debugCanParentUseSize,
        'debugLayoutParent#0': (args) => (args[0] as RenderEditable).debugLayoutParent,
        'owner#0': (args) => (args[0] as RenderEditable).owner,
        'attached#0': (args) => (args[0] as RenderEditable).attached,
        'debugNeedsLayout#0': (args) => (args[0] as RenderEditable).debugNeedsLayout,
        'debugDoingThisLayoutWithCallback#0': (args) => (args[0] as RenderEditable).debugDoingThisLayoutWithCallback,
        'sizedByParent#0': (args) => (args[0] as RenderEditable).sizedByParent,
        'debugDoingThisPaint#0': (args) => (args[0] as RenderEditable).debugDoingThisPaint,
        'isRepaintBoundary#0': (args) => (args[0] as RenderEditable).isRepaintBoundary,
        'alwaysNeedsCompositing#0': (args) => (args[0] as RenderEditable).alwaysNeedsCompositing,
        'layer#0': (args) => (args[0] as RenderEditable).layer,
        'debugLayer#0': (args) => (args[0] as RenderEditable).debugLayer,
        'needsCompositing#0': (args) => (args[0] as RenderEditable).needsCompositing,
        'debugNeedsPaint#0': (args) => (args[0] as RenderEditable).debugNeedsPaint,
        'debugNeedsCompositedLayerUpdate#0': (args) => (args[0] as RenderEditable).debugNeedsCompositedLayerUpdate,
        'debugNeedsSemanticsUpdate#0': (args) => (args[0] as RenderEditable).debugNeedsSemanticsUpdate,
        'debugSemantics#0': (args) => (args[0] as RenderEditable).debugSemantics,
        'childCount#0': (args) => (args[0] as RenderEditable).childCount,
        'firstChild#0': (args) => (args[0] as RenderEditable).firstChild,
        'lastChild#0': (args) => (args[0] as RenderEditable).lastChild,
        'foregroundPainter=#1': (args) { (args[0] as RenderEditable).foregroundPainter = args[1] as RenderEditablePainter?; return args[1]; },
        'painter=#1': (args) { (args[0] as RenderEditable).painter = args[1] as RenderEditablePainter?; return args[1]; },
        'ignorePointer=#1': (args) { (args[0] as RenderEditable).ignorePointer = args[1] as bool; return args[1]; },
        'textHeightBehavior=#1': (args) { (args[0] as RenderEditable).textHeightBehavior = args[1] as ui.TextHeightBehavior?; return args[1]; },
        'textWidthBasis=#1': (args) { (args[0] as RenderEditable).textWidthBasis = args[1] as TextWidthBasis; return args[1]; },
        'devicePixelRatio=#1': (args) { (args[0] as RenderEditable).devicePixelRatio = args[1] as double; return args[1]; },
        'obscuringCharacter=#1': (args) { (args[0] as RenderEditable).obscuringCharacter = args[1] as String; return args[1]; },
        'obscureText=#1': (args) { (args[0] as RenderEditable).obscureText = args[1] as bool; return args[1]; },
        'selectionHeightStyle=#1': (args) { (args[0] as RenderEditable).selectionHeightStyle = args[1] as ui.BoxHeightStyle; return args[1]; },
        'selectionWidthStyle=#1': (args) { (args[0] as RenderEditable).selectionWidthStyle = args[1] as ui.BoxWidthStyle; return args[1]; },
        'textSelectionDelegate=#1': (args) { (args[0] as RenderEditable).textSelectionDelegate = args[1] as TextSelectionDelegate; return args[1]; },
        'text=#1': (args) { (args[0] as RenderEditable).text = args[1] as InlineSpan?; return args[1]; },
        'textAlign=#1': (args) { (args[0] as RenderEditable).textAlign = args[1] as ui.TextAlign; return args[1]; },
        'textDirection=#1': (args) { (args[0] as RenderEditable).textDirection = args[1] as ui.TextDirection; return args[1]; },
        'locale=#1': (args) { (args[0] as RenderEditable).locale = args[1] as ui.Locale?; return args[1]; },
        'strutStyle=#1': (args) { (args[0] as RenderEditable).strutStyle = args[1] as StrutStyle?; return args[1]; },
        'cursorColor=#1': (args) { (args[0] as RenderEditable).cursorColor = args[1] as ui.Color?; return args[1]; },
        'backgroundCursorColor=#1': (args) { (args[0] as RenderEditable).backgroundCursorColor = args[1] as ui.Color?; return args[1]; },
        'showCursor=#1': (args) { (args[0] as RenderEditable).showCursor = args[1] as ValueNotifier<bool>; return args[1]; },
        'hasFocus=#1': (args) { (args[0] as RenderEditable).hasFocus = args[1] as bool; return args[1]; },
        'forceLine=#1': (args) { (args[0] as RenderEditable).forceLine = args[1] as bool; return args[1]; },
        'readOnly=#1': (args) { (args[0] as RenderEditable).readOnly = args[1] as bool; return args[1]; },
        'maxLines=#1': (args) { (args[0] as RenderEditable).maxLines = args[1] as int?; return args[1]; },
        'minLines=#1': (args) { (args[0] as RenderEditable).minLines = args[1] as int?; return args[1]; },
        'expands=#1': (args) { (args[0] as RenderEditable).expands = args[1] as bool; return args[1]; },
        'selectionColor=#1': (args) { (args[0] as RenderEditable).selectionColor = args[1] as ui.Color?; return args[1]; },
        'textScaleFactor=#1': (args) { (args[0] as RenderEditable).textScaleFactor = args[1] as double; return args[1]; },
        'textScaler=#1': (args) { (args[0] as RenderEditable).textScaler = args[1] as TextScaler; return args[1]; },
        'selection=#1': (args) { (args[0] as RenderEditable).selection = args[1] as TextSelection?; return args[1]; },
        'offset=#1': (args) { (args[0] as RenderEditable).offset = args[1] as ViewportOffset; return args[1]; },
        'cursorWidth=#1': (args) { (args[0] as RenderEditable).cursorWidth = args[1] as double; return args[1]; },
        'cursorHeight=#1': (args) { (args[0] as RenderEditable).cursorHeight = args[1] as double?; return args[1]; },
        'paintCursorAboveText=#1': (args) { (args[0] as RenderEditable).paintCursorAboveText = args[1] as bool; return args[1]; },
        'cursorOffset=#1': (args) { (args[0] as RenderEditable).cursorOffset = args[1] as ui.Offset; return args[1]; },
        'cursorRadius=#1': (args) { (args[0] as RenderEditable).cursorRadius = args[1] as ui.Radius?; return args[1]; },
        'startHandleLayerLink=#1': (args) { (args[0] as RenderEditable).startHandleLayerLink = args[1] as LayerLink; return args[1]; },
        'endHandleLayerLink=#1': (args) { (args[0] as RenderEditable).endHandleLayerLink = args[1] as LayerLink; return args[1]; },
        'floatingCursorAddedMargin=#1': (args) { (args[0] as RenderEditable).floatingCursorAddedMargin = args[1] as EdgeInsets; return args[1]; },
        'enableInteractiveSelection=#1': (args) { (args[0] as RenderEditable).enableInteractiveSelection = args[1] as bool?; return args[1]; },
        'promptRectColor=#1': (args) { (args[0] as RenderEditable).promptRectColor = args[1] as ui.Color?; return args[1]; },
        'clipBehavior=#1': (args) { (args[0] as RenderEditable).clipBehavior = args[1] as ui.Clip; return args[1]; },
        'size=#1': (args) { (args[0] as RenderEditable).size = args[1] as ui.Size; return args[1]; },
        'parentData=#1': (args) { (args[0] as RenderEditable).parentData = args[1] as ParentData?; return args[1]; },
        'debugCreator=#1': (args) { (args[0] as RenderEditable).debugCreator = args[1]; return args[1]; },
        'layer=#1': (args) { (args[0] as RenderEditable).layer = args[1] as ContainerLayer?; return args[1]; },
        '==#1': (args) => (args[0] as RenderEditable) == (args[1] as Object),
        '#43': (args) => RenderEditable(text: identical(args[0], darticAbsent) ? null : args[0] as InlineSpan?, textDirection: args[1] as ui.TextDirection, textAlign: identical(args[2], darticAbsent) ? TextAlign.start : args[2] as ui.TextAlign, cursorColor: identical(args[3], darticAbsent) ? null : args[3] as ui.Color?, backgroundCursorColor: identical(args[4], darticAbsent) ? null : args[4] as ui.Color?, showCursor: identical(args[5], darticAbsent) ? null : args[5] as ValueNotifier<bool>?, hasFocus: identical(args[6], darticAbsent) ? null : args[6] as bool?, startHandleLayerLink: args[7] as LayerLink, endHandleLayerLink: args[8] as LayerLink, maxLines: identical(args[9], darticAbsent) ? null : args[9] as int?, minLines: identical(args[10], darticAbsent) ? null : args[10] as int?, expands: identical(args[11], darticAbsent) ? false : args[11] as bool, strutStyle: identical(args[12], darticAbsent) ? null : args[12] as StrutStyle?, selectionColor: identical(args[13], darticAbsent) ? null : args[13] as ui.Color?, textScaleFactor: identical(args[14], darticAbsent) ? 1.0 : args[14] as double, textScaler: identical(args[15], darticAbsent) ? TextScaler.noScaling : args[15] as TextScaler, selection: identical(args[16], darticAbsent) ? null : args[16] as TextSelection?, offset: args[17] as ViewportOffset, ignorePointer: identical(args[18], darticAbsent) ? false : args[18] as bool, readOnly: identical(args[19], darticAbsent) ? false : args[19] as bool, forceLine: identical(args[20], darticAbsent) ? true : args[20] as bool, textHeightBehavior: identical(args[21], darticAbsent) ? null : args[21] as ui.TextHeightBehavior?, textWidthBasis: identical(args[22], darticAbsent) ? TextWidthBasis.parent : args[22] as TextWidthBasis, obscuringCharacter: identical(args[23], darticAbsent) ? '•' : args[23] as String, obscureText: identical(args[24], darticAbsent) ? false : args[24] as bool, locale: identical(args[25], darticAbsent) ? null : args[25] as ui.Locale?, cursorWidth: identical(args[26], darticAbsent) ? 1.0 : args[26] as double, cursorHeight: identical(args[27], darticAbsent) ? null : args[27] as double?, cursorRadius: identical(args[28], darticAbsent) ? null : args[28] as ui.Radius?, paintCursorAboveText: identical(args[29], darticAbsent) ? false : args[29] as bool, cursorOffset: identical(args[30], darticAbsent) ? Offset.zero : args[30] as ui.Offset, devicePixelRatio: identical(args[31], darticAbsent) ? 1.0 : args[31] as double, selectionHeightStyle: identical(args[32], darticAbsent) ? ui.BoxHeightStyle.max : args[32] as ui.BoxHeightStyle, selectionWidthStyle: identical(args[33], darticAbsent) ? ui.BoxWidthStyle.max : args[33] as ui.BoxWidthStyle, enableInteractiveSelection: identical(args[34], darticAbsent) ? null : args[34] as bool?, floatingCursorAddedMargin: identical(args[35], darticAbsent) ? const EdgeInsets.fromLTRB(4, 4, 4, 5) : args[35] as EdgeInsets, promptRectRange: identical(args[36], darticAbsent) ? null : args[36] as ui.TextRange?, promptRectColor: identical(args[37], darticAbsent) ? null : args[37] as ui.Color?, clipBehavior: identical(args[38], darticAbsent) ? Clip.hardEdge : args[38] as ui.Clip, textSelectionDelegate: args[39] as TextSelectionDelegate, painter: identical(args[40], darticAbsent) ? null : args[40] as RenderEditablePainter?, foregroundPainter: identical(args[41], darticAbsent) ? null : args[41] as RenderEditablePainter?, children: identical(args[42], darticAbsent) ? null : args[42] == null ? null : (args[42] as List).cast<RenderBox>()),
      };
}
