// GENERATED by dartic gen --emit-tests. DO NOT EDIT.
// Regenerate: dartic gen <config> --emit-tests
import 'package:flutter_test/flutter_test.dart';
// ignore_for_file: implementation_imports
import 'package:dartic_flutter/src/bindings/painting/notched_shape_bindings.g.dart';
import 'package:dartic_flutter/src/bindings/widgets/state_bindings.g.dart';
import 'package:dartic_flutter/src/bindings/widgets/stateful_widget_bindings.g.dart';
import 'package:dartic_flutter/src/bindings/widgets/stateless_widget_bindings.g.dart';

void main() {
  group('Binding completeness', () {
    test('NotchedShapeBindings.methodMap has expected keys', () {
      final map = NotchedShapeBindings.methodMap();
      expect(map.keys, containsAll(['getOuterPath#2']));
    });

    test('StatelessWidgetBindings.methodMap has expected keys', () {
      final map = StatelessWidgetBindings.methodMap();
      expect(map.keys, containsAll([
        'createElement#0',
        'build#1',
        'toStringShort#0',
        'debugFillProperties#1',
        'toStringShallow#2',
        'toStringDeep#4',
        'toDiagnosticsNode#2',
        'debugDescribeChildren#0',
        'key#0',
      ]));
    });

    test('StatefulWidgetBindings.methodMap has expected keys', () {
      final map = StatefulWidgetBindings.methodMap();
      expect(map.keys, containsAll([
        'createElement#0',
        'createState#0',
        'toStringShort#0',
        'debugFillProperties#1',
        'toStringShallow#2',
        'toStringDeep#4',
        'toDiagnosticsNode#2',
        'debugDescribeChildren#0',
        'key#0',
      ]));
    });

    test('StateBindings.methodMap has expected keys', () {
      final map = StateBindings.methodMap();
      expect(map.keys, containsAll([
        'initState#0',
        'didUpdateWidget#1',
        'reassemble#0',
        'setState#1',
        'deactivate#0',
        'activate#0',
        'dispose#0',
        'build#1',
        'didChangeDependencies#0',
        'debugFillProperties#1',
        'toStringShort#0',
        'toDiagnosticsNode#2',
        'widget#0',
        'context#0',
        'mounted#0',
      ]));
    });

  });
}
