// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7
// Generator: dartic_generator

// ignore_for_file: unused_import, unnecessary_import, implementation_imports

import 'package:dartic/dartic.dart';
import '../bindings/cupertino/cupertino_action_sheet_bindings.g.dart';
import '../bindings/cupertino/cupertino_action_sheet_action_bindings.g.dart';
import '../bindings/cupertino/cupertino_activity_indicator_bindings.g.dart';
import '../bindings/cupertino/cupertino_adaptive_text_selection_toolbar_bindings.g.dart';
import '../bindings/cupertino/cupertino_alert_dialog_bindings.g.dart';
import '../bindings/cupertino/cupertino_app_bindings.g.dart';
import '../bindings/cupertino/cupertino_button_bindings.g.dart';
import '../bindings/cupertino/cupertino_button_size_bindings.g.dart';
import '../bindings/cupertino/cupertino_checkbox_bindings.g.dart';
import '../bindings/cupertino/cupertino_colors_bindings.g.dart';
import '../bindings/cupertino/cupertino_context_menu_bindings.g.dart';
import '../bindings/cupertino/cupertino_context_menu_action_bindings.g.dart';
import '../bindings/cupertino/cupertino_date_picker_bindings.g.dart';
import '../bindings/cupertino/cupertino_date_picker_mode_bindings.g.dart';
import '../bindings/cupertino/cupertino_desktop_text_selection_controls_bindings.g.dart';
import '../bindings/cupertino/cupertino_desktop_text_selection_toolbar_bindings.g.dart';
import '../bindings/cupertino/cupertino_desktop_text_selection_toolbar_button_bindings.g.dart';
import '../bindings/cupertino/cupertino_dialog_action_bindings.g.dart';
import '../bindings/cupertino/cupertino_dialog_route_bindings.g.dart';
import '../bindings/cupertino/cupertino_dynamic_color_bindings.g.dart';
import '../bindings/cupertino/cupertino_expansion_tile_bindings.g.dart';
import '../bindings/cupertino/cupertino_form_row_bindings.g.dart';
import '../bindings/cupertino/cupertino_form_section_bindings.g.dart';
import '../bindings/cupertino/cupertino_fullscreen_dialog_transition_bindings.g.dart';
import '../bindings/cupertino/cupertino_icon_theme_data_bindings.g.dart';
import '../bindings/cupertino/cupertino_icons_bindings.g.dart';
import '../bindings/cupertino/cupertino_linear_activity_indicator_bindings.g.dart';
import '../bindings/cupertino/cupertino_list_section_bindings.g.dart';
import '../bindings/cupertino/cupertino_list_section_type_bindings.g.dart';
import '../bindings/cupertino/cupertino_list_tile_bindings.g.dart';
import '../bindings/cupertino/cupertino_list_tile_chevron_bindings.g.dart';
import '../bindings/cupertino/cupertino_localizations_bindings.g.dart';
import '../bindings/cupertino/cupertino_magnifier_bindings.g.dart';
import '../bindings/cupertino/cupertino_modal_popup_route_bindings.g.dart';
import '../bindings/cupertino/cupertino_navigation_bar_bindings.g.dart';
import '../bindings/cupertino/cupertino_navigation_bar_back_button_bindings.g.dart';
import '../bindings/cupertino/cupertino_page_bindings.g.dart';
import '../bindings/cupertino/cupertino_page_route_bindings.g.dart';
import '../bindings/cupertino/cupertino_page_scaffold_bindings.g.dart';
import '../bindings/cupertino/cupertino_page_scaffold_background_color_bindings.g.dart';
import '../bindings/cupertino/cupertino_page_transition_bindings.g.dart';
import '../bindings/cupertino/cupertino_picker_bindings.g.dart';
import '../bindings/cupertino/cupertino_picker_default_selection_overlay_bindings.g.dart';
import '../bindings/cupertino/cupertino_popup_surface_bindings.g.dart';
import '../bindings/cupertino/cupertino_radio_bindings.g.dart';
import '../bindings/cupertino/cupertino_route_transition_mixin_bindings.g.dart';
import '../bindings/cupertino/cupertino_scroll_behavior_bindings.g.dart';
import '../bindings/cupertino/cupertino_scrollbar_bindings.g.dart';
import '../bindings/cupertino/cupertino_search_text_field_bindings.g.dart';
import '../bindings/cupertino/cupertino_segmented_control_bindings.g.dart';
import '../bindings/cupertino/cupertino_sheet_route_bindings.g.dart';
import '../bindings/cupertino/cupertino_sheet_transition_bindings.g.dart';
import '../bindings/cupertino/cupertino_slider_bindings.g.dart';
import '../bindings/cupertino/cupertino_sliding_segmented_control_bindings.g.dart';
import '../bindings/cupertino/cupertino_sliver_navigation_bar_bindings.g.dart';
import '../bindings/cupertino/cupertino_sliver_refresh_control_bindings.g.dart';
import '../bindings/cupertino/cupertino_spell_check_suggestions_toolbar_bindings.g.dart';
import '../bindings/cupertino/cupertino_switch_bindings.g.dart';
import '../bindings/cupertino/cupertino_tab_bar_bindings.g.dart';
import '../bindings/cupertino/cupertino_tab_controller_bindings.g.dart';
import '../bindings/cupertino/cupertino_tab_scaffold_bindings.g.dart';
import '../bindings/cupertino/cupertino_tab_view_bindings.g.dart';
import '../bindings/cupertino/cupertino_text_field_bindings.g.dart';
import '../bindings/cupertino/cupertino_text_form_field_row_bindings.g.dart';
import '../bindings/cupertino/cupertino_text_magnifier_bindings.g.dart';
import '../bindings/cupertino/cupertino_text_selection_controls_bindings.g.dart';
import '../bindings/cupertino/cupertino_text_selection_handle_controls_bindings.g.dart';
import '../bindings/cupertino/cupertino_text_selection_toolbar_bindings.g.dart';
import '../bindings/cupertino/cupertino_text_selection_toolbar_button_bindings.g.dart';
import '../bindings/cupertino/cupertino_text_theme_data_bindings.g.dart';
import '../bindings/cupertino/cupertino_theme_bindings.g.dart';
import '../bindings/cupertino/cupertino_theme_data_bindings.g.dart';
import '../bindings/cupertino/cupertino_thumb_painter_bindings.g.dart';
import '../bindings/cupertino/cupertino_timer_picker_bindings.g.dart';
import '../bindings/cupertino/cupertino_timer_picker_mode_bindings.g.dart';
import '../bindings/cupertino/cupertino_user_interface_level_bindings.g.dart';
import '../bindings/cupertino/cupertino_user_interface_level_data_bindings.g.dart';
import '../bindings/cupertino/date_picker_date_order_bindings.g.dart';
import '../bindings/cupertino/date_picker_date_time_order_bindings.g.dart';
import '../bindings/cupertino/default_cupertino_localizations_bindings.g.dart';
import '../bindings/cupertino/expansion_tile_transition_mode_bindings.g.dart';
import '../bindings/cupertino/inherited_cupertino_theme_bindings.g.dart';
import '../bindings/cupertino/navigation_bar_bottom_mode_bindings.g.dart';
import '../bindings/cupertino/no_default_cupertino_theme_data_bindings.g.dart';
import '../bindings/cupertino/obstructing_preferred_size_widget_bindings.g.dart';
import '../bindings/cupertino/overlay_visibility_mode_bindings.g.dart';
import '../bindings/cupertino/refresh_indicator_mode_bindings.g.dart';
import '../bindings/cupertino/restorable_cupertino_tab_controller_bindings.g.dart';

class CupertinoPlugin extends DarticPlugin {
  @override
  String get name => 'package:flutter/src/cupertino';

  @override
  void register(DarticPluginContext ctx) {
    CupertinoActionSheetBindings.register(ctx);
    CupertinoActionSheetActionBindings.register(ctx);
    CupertinoActivityIndicatorBindings.register(ctx);
    CupertinoAdaptiveTextSelectionToolbarBindings.register(ctx);
    CupertinoAlertDialogBindings.register(ctx);
    CupertinoAppBindings.register(ctx);
    CupertinoButtonBindings.register(ctx);
    CupertinoButtonSizeBindings.register(ctx);
    CupertinoCheckboxBindings.register(ctx);
    CupertinoColorsBindings.register(ctx);
    CupertinoContextMenuBindings.register(ctx);
    CupertinoContextMenuActionBindings.register(ctx);
    CupertinoDatePickerBindings.register(ctx);
    CupertinoDatePickerModeBindings.register(ctx);
    CupertinoDesktopTextSelectionControlsBindings.register(ctx);
    CupertinoDesktopTextSelectionToolbarBindings.register(ctx);
    CupertinoDesktopTextSelectionToolbarButtonBindings.register(ctx);
    CupertinoDialogActionBindings.register(ctx);
    CupertinoDialogRouteBindings.register(ctx);
    CupertinoDynamicColorBindings.register(ctx);
    CupertinoExpansionTileBindings.register(ctx);
    CupertinoFormRowBindings.register(ctx);
    CupertinoFormSectionBindings.register(ctx);
    CupertinoFullscreenDialogTransitionBindings.register(ctx);
    CupertinoIconThemeDataBindings.register(ctx);
    CupertinoIconsBindings.register(ctx);
    CupertinoLinearActivityIndicatorBindings.register(ctx);
    CupertinoListSectionBindings.register(ctx);
    CupertinoListSectionTypeBindings.register(ctx);
    CupertinoListTileBindings.register(ctx);
    CupertinoListTileChevronBindings.register(ctx);
    CupertinoLocalizationsBindings.register(ctx);
    CupertinoMagnifierBindings.register(ctx);
    CupertinoModalPopupRouteBindings.register(ctx);
    CupertinoNavigationBarBindings.register(ctx);
    CupertinoNavigationBarBackButtonBindings.register(ctx);
    CupertinoPageBindings.register(ctx);
    CupertinoPageRouteBindings.register(ctx);
    CupertinoPageScaffoldBindings.register(ctx);
    CupertinoPageScaffoldBackgroundColorBindings.register(ctx);
    CupertinoPageTransitionBindings.register(ctx);
    CupertinoPickerBindings.register(ctx);
    CupertinoPickerDefaultSelectionOverlayBindings.register(ctx);
    CupertinoPopupSurfaceBindings.register(ctx);
    CupertinoRadioBindings.register(ctx);
    CupertinoRouteTransitionMixinBindings.register(ctx);
    CupertinoScrollBehaviorBindings.register(ctx);
    CupertinoScrollbarBindings.register(ctx);
    CupertinoSearchTextFieldBindings.register(ctx);
    CupertinoSegmentedControlBindings.register(ctx);
    CupertinoSheetRouteBindings.register(ctx);
    CupertinoSheetTransitionBindings.register(ctx);
    CupertinoSliderBindings.register(ctx);
    CupertinoSlidingSegmentedControlBindings.register(ctx);
    CupertinoSliverNavigationBarBindings.register(ctx);
    CupertinoSliverRefreshControlBindings.register(ctx);
    CupertinoSpellCheckSuggestionsToolbarBindings.register(ctx);
    CupertinoSwitchBindings.register(ctx);
    CupertinoTabBarBindings.register(ctx);
    CupertinoTabControllerBindings.register(ctx);
    CupertinoTabScaffoldBindings.register(ctx);
    CupertinoTabViewBindings.register(ctx);
    CupertinoTextFieldBindings.register(ctx);
    CupertinoTextFormFieldRowBindings.register(ctx);
    CupertinoTextMagnifierBindings.register(ctx);
    CupertinoTextSelectionControlsBindings.register(ctx);
    CupertinoTextSelectionHandleControlsBindings.register(ctx);
    CupertinoTextSelectionToolbarBindings.register(ctx);
    CupertinoTextSelectionToolbarButtonBindings.register(ctx);
    CupertinoTextThemeDataBindings.register(ctx);
    CupertinoThemeBindings.register(ctx);
    CupertinoThemeDataBindings.register(ctx);
    CupertinoThumbPainterBindings.register(ctx);
    CupertinoTimerPickerBindings.register(ctx);
    CupertinoTimerPickerModeBindings.register(ctx);
    CupertinoUserInterfaceLevelBindings.register(ctx);
    CupertinoUserInterfaceLevelDataBindings.register(ctx);
    DatePickerDateOrderBindings.register(ctx);
    DatePickerDateTimeOrderBindings.register(ctx);
    DefaultCupertinoLocalizationsBindings.register(ctx);
    ExpansionTileTransitionModeBindings.register(ctx);
    InheritedCupertinoThemeBindings.register(ctx);
    NavigationBarBottomModeBindings.register(ctx);
    NoDefaultCupertinoThemeDataBindings.register(ctx);
    ObstructingPreferredSizeWidgetBindings.register(ctx);
    OverlayVisibilityModeBindings.register(ctx);
    RefreshIndicatorModeBindings.register(ctx);
    RestorableCupertinoTabControllerBindings.register(ctx);
  }
}
