// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7
// Generator: dartic_generator

// ignore_for_file: unused_import, unnecessary_import, implementation_imports

import 'package:dartic/dartic.dart';
import '../bindings/foundation/abstract_node_bindings.g.dart';
import '../bindings/foundation/aggregated_timed_block_bindings.g.dart';
import '../bindings/foundation/aggregated_timings_bindings.g.dart';
import '../bindings/foundation/binding_base_bindings.g.dart';
import '../bindings/foundation/bit_field_bindings.g.dart';
import '../bindings/foundation/caching_iterable_bindings.g.dart';
import '../bindings/foundation/category_bindings.g.dart';
import '../bindings/foundation/change_notifier_bindings.g.dart';
import '../bindings/foundation/diagnostic_level_bindings.g.dart';
import '../bindings/foundation/diagnostic_properties_builder_bindings.g.dart';
import '../bindings/foundation/diagnosticable_bindings.g.dart';
import '../bindings/foundation/diagnosticable_node_bindings.g.dart';
import '../bindings/foundation/diagnosticable_tree_bindings.g.dart';
import '../bindings/foundation/diagnosticable_tree_mixin_bindings.g.dart';
import '../bindings/foundation/diagnosticable_tree_node_bindings.g.dart';
import '../bindings/foundation/diagnostics_block_bindings.g.dart';
import '../bindings/foundation/diagnostics_node_bindings.g.dart';
import '../bindings/foundation/diagnostics_property_bindings.g.dart';
import '../bindings/foundation/diagnostics_serialization_delegate_bindings.g.dart';
import '../bindings/foundation/diagnostics_stack_trace_bindings.g.dart';
import '../bindings/foundation/diagnostics_tree_style_bindings.g.dart';
import '../bindings/foundation/documentation_icon_bindings.g.dart';
import '../bindings/foundation/double_property_bindings.g.dart';
import '../bindings/foundation/enum_property_bindings.g.dart';
import '../bindings/foundation/error_description_bindings.g.dart';
import '../bindings/foundation/error_hint_bindings.g.dart';
import '../bindings/foundation/error_spacer_bindings.g.dart';
import '../bindings/foundation/error_summary_bindings.g.dart';
import '../bindings/foundation/factory_bindings.g.dart';
import '../bindings/foundation/flag_property_bindings.g.dart';
import '../bindings/foundation/flags_summary_bindings.g.dart';
import '../bindings/foundation/flutter_error_bindings.g.dart';
import '../bindings/foundation/flutter_error_details_bindings.g.dart';
import '../bindings/foundation/flutter_memory_allocations_bindings.g.dart';
import '../bindings/foundation/flutter_timeline_bindings.g.dart';
import '../bindings/foundation/foundation_service_extensions_bindings.g.dart';
import '../bindings/foundation/hashed_observer_list_bindings.g.dart';
import '../bindings/foundation/int_property_bindings.g.dart';
import '../bindings/foundation/iterable_property_bindings.g.dart';
import '../bindings/foundation/key_bindings.g.dart';
import '../bindings/foundation/license_entry_bindings.g.dart';
import '../bindings/foundation/license_entry_with_line_breaks_bindings.g.dart';
import '../bindings/foundation/license_paragraph_bindings.g.dart';
import '../bindings/foundation/license_registry_bindings.g.dart';
import '../bindings/foundation/listenable_bindings.g.dart';
import '../bindings/foundation/local_key_bindings.g.dart';
import '../bindings/foundation/message_property_bindings.g.dart';
import '../bindings/foundation/object_created_bindings.g.dart';
import '../bindings/foundation/object_disposed_bindings.g.dart';
import '../bindings/foundation/object_event_bindings.g.dart';
import '../bindings/foundation/object_flag_property_bindings.g.dart';
import '../bindings/foundation/observer_list_bindings.g.dart';
import '../bindings/foundation/partial_stack_frame_bindings.g.dart';
import '../bindings/foundation/percent_property_bindings.g.dart';
import '../bindings/foundation/persistent_hash_map_bindings.g.dart';
import '../bindings/foundation/read_buffer_bindings.g.dart';
import '../bindings/foundation/repetitive_stack_frame_filter_bindings.g.dart';
import '../bindings/foundation/stack_filter_bindings.g.dart';
import '../bindings/foundation/stack_frame_bindings.g.dart';
import '../bindings/foundation/string_property_bindings.g.dart';
import '../bindings/foundation/summary_bindings.g.dart';
import '../bindings/foundation/synchronous_future_bindings.g.dart';
import '../bindings/foundation/target_platform_bindings.g.dart';
import '../bindings/foundation/text_tree_configuration_bindings.g.dart';
import '../bindings/foundation/text_tree_renderer_bindings.g.dart';
import '../bindings/foundation/timed_block_bindings.g.dart';
import '../bindings/foundation/unicode_bindings.g.dart';
import '../bindings/foundation/unique_key_bindings.g.dart';
import '../bindings/foundation/value_key_bindings.g.dart';
import '../bindings/foundation/value_listenable_bindings.g.dart';
import '../bindings/foundation/value_notifier_bindings.g.dart';
import '../bindings/foundation/write_buffer_bindings.g.dart';

class FoundationPlugin extends DarticPlugin {
  @override
  String get name => 'package:flutter/src/foundation';

  @override
  void register(DarticPluginContext ctx) {
    AbstractNodeBindings.register(ctx);
    AggregatedTimedBlockBindings.register(ctx);
    AggregatedTimingsBindings.register(ctx);
    BindingBaseBindings.register(ctx);
    BitFieldBindings.register(ctx);
    CachingIterableBindings.register(ctx);
    CategoryBindings.register(ctx);
    ChangeNotifierBindings.register(ctx);
    DiagnosticLevelBindings.register(ctx);
    DiagnosticPropertiesBuilderBindings.register(ctx);
    DiagnosticableBindings.register(ctx);
    DiagnosticableNodeBindings.register(ctx);
    DiagnosticableTreeBindings.register(ctx);
    DiagnosticableTreeMixinBindings.register(ctx);
    DiagnosticableTreeNodeBindings.register(ctx);
    DiagnosticsBlockBindings.register(ctx);
    DiagnosticsNodeBindings.register(ctx);
    DiagnosticsPropertyBindings.register(ctx);
    DiagnosticsSerializationDelegateBindings.register(ctx);
    DiagnosticsStackTraceBindings.register(ctx);
    DiagnosticsTreeStyleBindings.register(ctx);
    DocumentationIconBindings.register(ctx);
    DoublePropertyBindings.register(ctx);
    EnumPropertyBindings.register(ctx);
    ErrorDescriptionBindings.register(ctx);
    ErrorHintBindings.register(ctx);
    ErrorSpacerBindings.register(ctx);
    ErrorSummaryBindings.register(ctx);
    FactoryBindings.register(ctx);
    FlagPropertyBindings.register(ctx);
    FlagsSummaryBindings.register(ctx);
    FlutterErrorBindings.register(ctx);
    FlutterErrorDetailsBindings.register(ctx);
    FlutterMemoryAllocationsBindings.register(ctx);
    FlutterTimelineBindings.register(ctx);
    FoundationServiceExtensionsBindings.register(ctx);
    HashedObserverListBindings.register(ctx);
    IntPropertyBindings.register(ctx);
    IterablePropertyBindings.register(ctx);
    KeyBindings.register(ctx);
    LicenseEntryBindings.register(ctx);
    LicenseEntryWithLineBreaksBindings.register(ctx);
    LicenseParagraphBindings.register(ctx);
    LicenseRegistryBindings.register(ctx);
    ListenableBindings.register(ctx);
    LocalKeyBindings.register(ctx);
    MessagePropertyBindings.register(ctx);
    ObjectCreatedBindings.register(ctx);
    ObjectDisposedBindings.register(ctx);
    ObjectEventBindings.register(ctx);
    ObjectFlagPropertyBindings.register(ctx);
    ObserverListBindings.register(ctx);
    PartialStackFrameBindings.register(ctx);
    PercentPropertyBindings.register(ctx);
    PersistentHashMapBindings.register(ctx);
    ReadBufferBindings.register(ctx);
    RepetitiveStackFrameFilterBindings.register(ctx);
    StackFilterBindings.register(ctx);
    StackFrameBindings.register(ctx);
    StringPropertyBindings.register(ctx);
    SummaryBindings.register(ctx);
    SynchronousFutureBindings.register(ctx);
    TargetPlatformBindings.register(ctx);
    TextTreeConfigurationBindings.register(ctx);
    TextTreeRendererBindings.register(ctx);
    TimedBlockBindings.register(ctx);
    UnicodeBindings.register(ctx);
    UniqueKeyBindings.register(ctx);
    ValueKeyBindings.register(ctx);
    ValueListenableBindings.register(ctx);
    ValueNotifierBindings.register(ctx);
    WriteBufferBindings.register(ctx);
  }
}
