// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7
// Generator: dartic_generator

// ignore_for_file: unused_import, unnecessary_import, implementation_imports

import 'package:dartic/dartic.dart';
import '../bindings/gestures/base_tap_and_drag_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/base_tap_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/delayed_multi_drag_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/device_gesture_settings_bindings.g.dart';
import '../bindings/gestures/double_tap_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/drag_bindings.g.dart';
import '../bindings/gestures/drag_down_details_bindings.g.dart';
import '../bindings/gestures/drag_end_details_bindings.g.dart';
import '../bindings/gestures/drag_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/drag_start_behavior_bindings.g.dart';
import '../bindings/gestures/drag_start_details_bindings.g.dart';
import '../bindings/gestures/drag_update_details_bindings.g.dart';
import '../bindings/gestures/eager_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/flutter_error_details_for_pointer_event_dispatcher_bindings.g.dart';
import '../bindings/gestures/force_press_details_bindings.g.dart';
import '../bindings/gestures/force_press_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/gesture_arena_entry_bindings.g.dart';
import '../bindings/gestures/gesture_arena_manager_bindings.g.dart';
import '../bindings/gestures/gesture_arena_member_bindings.g.dart';
import '../bindings/gestures/gesture_arena_team_bindings.g.dart';
import '../bindings/gestures/gesture_binding_bindings.g.dart';
import '../bindings/gestures/gesture_disposition_bindings.g.dart';
import '../bindings/gestures/gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/gesture_recognizer_state_bindings.g.dart';
import '../bindings/gestures/hit_test_dispatcher_bindings.g.dart';
import '../bindings/gestures/hit_test_entry_bindings.g.dart';
import '../bindings/gestures/hit_test_result_bindings.g.dart';
import '../bindings/gestures/hit_test_target_bindings.g.dart';
import '../bindings/gestures/hit_testable_bindings.g.dart';
import '../bindings/gestures/horizontal_drag_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/horizontal_multi_drag_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/i_o_s_scroll_view_fling_velocity_tracker_bindings.g.dart';
import '../bindings/gestures/immediate_multi_drag_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/least_squares_solver_bindings.g.dart';
import '../bindings/gestures/long_press_down_details_bindings.g.dart';
import '../bindings/gestures/long_press_end_details_bindings.g.dart';
import '../bindings/gestures/long_press_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/long_press_move_update_details_bindings.g.dart';
import '../bindings/gestures/long_press_start_details_bindings.g.dart';
import '../bindings/gestures/mac_o_s_scroll_view_fling_velocity_tracker_bindings.g.dart';
import '../bindings/gestures/multi_drag_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/multi_drag_pointer_state_bindings.g.dart';
import '../bindings/gestures/multi_tap_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/multitouch_drag_strategy_bindings.g.dart';
import '../bindings/gestures/offset_pair_bindings.g.dart';
import '../bindings/gestures/one_sequence_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/pan_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/pointer_added_event_bindings.g.dart';
import '../bindings/gestures/pointer_cancel_event_bindings.g.dart';
import '../bindings/gestures/pointer_down_event_bindings.g.dart';
import '../bindings/gestures/pointer_enter_event_bindings.g.dart';
import '../bindings/gestures/pointer_event_bindings.g.dart';
import '../bindings/gestures/pointer_event_converter_bindings.g.dart';
import '../bindings/gestures/pointer_event_resampler_bindings.g.dart';
import '../bindings/gestures/pointer_exit_event_bindings.g.dart';
import '../bindings/gestures/pointer_hover_event_bindings.g.dart';
import '../bindings/gestures/pointer_move_event_bindings.g.dart';
import '../bindings/gestures/pointer_pan_zoom_end_event_bindings.g.dart';
import '../bindings/gestures/pointer_pan_zoom_start_event_bindings.g.dart';
import '../bindings/gestures/pointer_pan_zoom_update_event_bindings.g.dart';
import '../bindings/gestures/pointer_removed_event_bindings.g.dart';
import '../bindings/gestures/pointer_router_bindings.g.dart';
import '../bindings/gestures/pointer_scale_event_bindings.g.dart';
import '../bindings/gestures/pointer_scroll_event_bindings.g.dart';
import '../bindings/gestures/pointer_scroll_inertia_cancel_event_bindings.g.dart';
import '../bindings/gestures/pointer_signal_event_bindings.g.dart';
import '../bindings/gestures/pointer_signal_resolver_bindings.g.dart';
import '../bindings/gestures/pointer_up_event_bindings.g.dart';
import '../bindings/gestures/polynomial_fit_bindings.g.dart';
import '../bindings/gestures/positioned_gesture_details_bindings.g.dart';
import '../bindings/gestures/primary_pointer_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/sampling_clock_bindings.g.dart';
import '../bindings/gestures/scale_end_details_bindings.g.dart';
import '../bindings/gestures/scale_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/scale_start_details_bindings.g.dart';
import '../bindings/gestures/scale_update_details_bindings.g.dart';
import '../bindings/gestures/serial_tap_cancel_details_bindings.g.dart';
import '../bindings/gestures/serial_tap_down_details_bindings.g.dart';
import '../bindings/gestures/serial_tap_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/serial_tap_up_details_bindings.g.dart';
import '../bindings/gestures/tap_and_drag_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/tap_and_horizontal_drag_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/tap_and_pan_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/tap_down_details_bindings.g.dart';
import '../bindings/gestures/tap_drag_down_details_bindings.g.dart';
import '../bindings/gestures/tap_drag_end_details_bindings.g.dart';
import '../bindings/gestures/tap_drag_start_details_bindings.g.dart';
import '../bindings/gestures/tap_drag_up_details_bindings.g.dart';
import '../bindings/gestures/tap_drag_update_details_bindings.g.dart';
import '../bindings/gestures/tap_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/tap_move_details_bindings.g.dart';
import '../bindings/gestures/tap_up_details_bindings.g.dart';
import '../bindings/gestures/velocity_bindings.g.dart';
import '../bindings/gestures/velocity_estimate_bindings.g.dart';
import '../bindings/gestures/velocity_tracker_bindings.g.dart';
import '../bindings/gestures/vertical_drag_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/vertical_multi_drag_gesture_recognizer_bindings.g.dart';
import '../bindings/gestures/gestures_top_level_bindings.g.dart';

class GesturesPlugin extends DarticPlugin {
  @override
  String get name => 'package:flutter/src/gestures';

  @override
  void register(DarticPluginContext ctx) {
    BaseTapAndDragGestureRecognizerBindings.register(ctx);
    BaseTapGestureRecognizerBindings.register(ctx);
    DelayedMultiDragGestureRecognizerBindings.register(ctx);
    DeviceGestureSettingsBindings.register(ctx);
    DoubleTapGestureRecognizerBindings.register(ctx);
    DragBindings.register(ctx);
    DragDownDetailsBindings.register(ctx);
    DragEndDetailsBindings.register(ctx);
    DragGestureRecognizerBindings.register(ctx);
    DragStartBehaviorBindings.register(ctx);
    DragStartDetailsBindings.register(ctx);
    DragUpdateDetailsBindings.register(ctx);
    EagerGestureRecognizerBindings.register(ctx);
    FlutterErrorDetailsForPointerEventDispatcherBindings.register(ctx);
    ForcePressDetailsBindings.register(ctx);
    ForcePressGestureRecognizerBindings.register(ctx);
    GestureArenaEntryBindings.register(ctx);
    GestureArenaManagerBindings.register(ctx);
    GestureArenaMemberBindings.register(ctx);
    GestureArenaTeamBindings.register(ctx);
    GestureBindingBindings.register(ctx);
    GestureDispositionBindings.register(ctx);
    GestureRecognizerBindings.register(ctx);
    GestureRecognizerStateBindings.register(ctx);
    HitTestDispatcherBindings.register(ctx);
    HitTestEntryBindings.register(ctx);
    HitTestResultBindings.register(ctx);
    HitTestTargetBindings.register(ctx);
    HitTestableBindings.register(ctx);
    HorizontalDragGestureRecognizerBindings.register(ctx);
    HorizontalMultiDragGestureRecognizerBindings.register(ctx);
    IOSScrollViewFlingVelocityTrackerBindings.register(ctx);
    ImmediateMultiDragGestureRecognizerBindings.register(ctx);
    LeastSquaresSolverBindings.register(ctx);
    LongPressDownDetailsBindings.register(ctx);
    LongPressEndDetailsBindings.register(ctx);
    LongPressGestureRecognizerBindings.register(ctx);
    LongPressMoveUpdateDetailsBindings.register(ctx);
    LongPressStartDetailsBindings.register(ctx);
    MacOSScrollViewFlingVelocityTrackerBindings.register(ctx);
    MultiDragGestureRecognizerBindings.register(ctx);
    MultiDragPointerStateBindings.register(ctx);
    MultiTapGestureRecognizerBindings.register(ctx);
    MultitouchDragStrategyBindings.register(ctx);
    OffsetPairBindings.register(ctx);
    OneSequenceGestureRecognizerBindings.register(ctx);
    PanGestureRecognizerBindings.register(ctx);
    PointerAddedEventBindings.register(ctx);
    PointerCancelEventBindings.register(ctx);
    PointerDownEventBindings.register(ctx);
    PointerEnterEventBindings.register(ctx);
    PointerEventBindings.register(ctx);
    PointerEventConverterBindings.register(ctx);
    PointerEventResamplerBindings.register(ctx);
    PointerExitEventBindings.register(ctx);
    PointerHoverEventBindings.register(ctx);
    PointerMoveEventBindings.register(ctx);
    PointerPanZoomEndEventBindings.register(ctx);
    PointerPanZoomStartEventBindings.register(ctx);
    PointerPanZoomUpdateEventBindings.register(ctx);
    PointerRemovedEventBindings.register(ctx);
    PointerRouterBindings.register(ctx);
    PointerScaleEventBindings.register(ctx);
    PointerScrollEventBindings.register(ctx);
    PointerScrollInertiaCancelEventBindings.register(ctx);
    PointerSignalEventBindings.register(ctx);
    PointerSignalResolverBindings.register(ctx);
    PointerUpEventBindings.register(ctx);
    PolynomialFitBindings.register(ctx);
    PositionedGestureDetailsBindings.register(ctx);
    PrimaryPointerGestureRecognizerBindings.register(ctx);
    SamplingClockBindings.register(ctx);
    ScaleEndDetailsBindings.register(ctx);
    ScaleGestureRecognizerBindings.register(ctx);
    ScaleStartDetailsBindings.register(ctx);
    ScaleUpdateDetailsBindings.register(ctx);
    SerialTapCancelDetailsBindings.register(ctx);
    SerialTapDownDetailsBindings.register(ctx);
    SerialTapGestureRecognizerBindings.register(ctx);
    SerialTapUpDetailsBindings.register(ctx);
    TapAndDragGestureRecognizerBindings.register(ctx);
    TapAndHorizontalDragGestureRecognizerBindings.register(ctx);
    TapAndPanGestureRecognizerBindings.register(ctx);
    TapDownDetailsBindings.register(ctx);
    TapDragDownDetailsBindings.register(ctx);
    TapDragEndDetailsBindings.register(ctx);
    TapDragStartDetailsBindings.register(ctx);
    TapDragUpDetailsBindings.register(ctx);
    TapDragUpdateDetailsBindings.register(ctx);
    TapGestureRecognizerBindings.register(ctx);
    TapMoveDetailsBindings.register(ctx);
    TapUpDetailsBindings.register(ctx);
    VelocityBindings.register(ctx);
    VelocityEstimateBindings.register(ctx);
    VelocityTrackerBindings.register(ctx);
    VerticalDragGestureRecognizerBindings.register(ctx);
    VerticalMultiDragGestureRecognizerBindings.register(ctx);
    GesturesTopLevelBindings.register(ctx);
  }
}
