// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7
// Generator: dartic_generator

// ignore_for_file: unused_import, unnecessary_import, implementation_imports

import 'package:dartic/dartic.dart';
import 'package:dartic/dartic_internal.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'dart:ui';
import '../bindings/material/material_app_bindings.g.dart';
import '../bindings/material/scaffold_bindings.g.dart';
import '../bindings/material/app_bar_bindings.g.dart';
import '../bindings/material/elevated_button_bindings.g.dart';
import '../bindings/material/text_button_bindings.g.dart';
import '../bindings/material/floating_action_button_bindings.g.dart';
import '../bindings/material/card_bindings.g.dart';
import '../bindings/material/list_tile_bindings.g.dart';
import '../bindings/material/theme_data_bindings.g.dart';
import '../bindings/material/theme_bindings.g.dart';
import '../bindings/material/animated_theme_bindings.g.dart';
import '../bindings/material/color_scheme_bindings.g.dart';
import '../bindings/material/text_theme_bindings.g.dart';
import '../bindings/material/button_style_bindings.g.dart';
import '../bindings/material/input_decoration_bindings.g.dart';
import '../bindings/material/input_decoration_theme_bindings.g.dart';
import '../bindings/material/visual_density_bindings.g.dart';
import '../bindings/material/icon_theme_data_bindings.g.dart';
import '../bindings/material/input_border_bindings.g.dart';
import '../bindings/material/underline_input_border_bindings.g.dart';
import '../bindings/material/outline_input_border_bindings.g.dart';
import '../bindings/material/material_tap_target_size_bindings.g.dart';
import '../bindings/material/floating_label_behavior_bindings.g.dart';
import '../bindings/material/text_field_bindings.g.dart';
import '../bindings/material/checkbox_bindings.g.dart';
import '../bindings/material/switch_bindings.g.dart';
import '../bindings/material/slider_bindings.g.dart';
import '../bindings/material/dialog_bindings.g.dart';
import '../bindings/material/alert_dialog_bindings.g.dart';
import '../bindings/material/simple_dialog_bindings.g.dart';
import '../bindings/material/simple_dialog_option_bindings.g.dart';
import '../bindings/material/bottom_sheet_bindings.g.dart';
import '../bindings/material/drawer_bindings.g.dart';
import '../bindings/material/navigation_bar_bindings.g.dart';
import '../bindings/material/navigation_destination_bindings.g.dart';
import '../bindings/material/navigation_rail_bindings.g.dart';
import '../bindings/material/bottom_navigation_bar_bindings.g.dart';
import '../bindings/material/bottom_app_bar_bindings.g.dart';
import '../bindings/material/drawer_alignment_bindings.g.dart';
import '../bindings/material/navigation_destination_label_behavior_bindings.g.dart';
import '../bindings/material/snack_bar_closed_reason_bindings.g.dart';
import '../bindings/material/tab_bar_bindings.g.dart';
import '../bindings/material/tab_bar_view_bindings.g.dart';
import '../bindings/material/tab_bindings.g.dart';
import '../bindings/material/tab_page_selector_bindings.g.dart';
import '../bindings/material/tab_page_selector_indicator_bindings.g.dart';
import '../bindings/material/snack_bar_bindings.g.dart';
import '../bindings/material/snack_bar_action_bindings.g.dart';
import '../bindings/material/chip_bindings.g.dart';
import '../bindings/material/action_chip_bindings.g.dart';
import '../bindings/material/choice_chip_bindings.g.dart';
import '../bindings/material/filter_chip_bindings.g.dart';
import '../bindings/material/input_chip_bindings.g.dart';
import '../bindings/material/expansion_tile_bindings.g.dart';
import '../bindings/material/circle_avatar_bindings.g.dart';
import '../bindings/material/badge_bindings.g.dart';
import '../bindings/material/divider_bindings.g.dart';
import '../bindings/material/expand_icon_bindings.g.dart';
import '../bindings/material/linear_progress_indicator_bindings.g.dart';
import '../bindings/material/circular_progress_indicator_bindings.g.dart';
import '../bindings/material/refresh_progress_indicator_bindings.g.dart';
import '../bindings/material/grid_tile_bindings.g.dart';
import '../bindings/material/grid_tile_bar_bindings.g.dart';
import '../bindings/material/icon_button_bindings.g.dart';
import '../bindings/material/outlined_button_bindings.g.dart';
import '../bindings/material/filled_button_bindings.g.dart';
import '../bindings/material/material_page_route_bindings.g.dart';
import '../bindings/material/material_color_bindings.g.dart';
import '../bindings/material/drawer_header_bindings.g.dart';
import '../bindings/material/tab_bar_indicator_size_bindings.g.dart';
import '../bindings/material/tab_alignment_bindings.g.dart';

class MaterialPlugin extends DarticPlugin {
  @override
  String get name => 'package:flutter/material.dart';

  @override
  void register(DarticPluginContext ctx) {
    MaterialAppBindings.register(ctx);
    ScaffoldBindings.register(ctx);
    AppBarBindings.register(ctx);
    ElevatedButtonBindings.register(ctx);
    TextButtonBindings.register(ctx);
    FloatingActionButtonBindings.register(ctx);
    CardBindings.register(ctx);
    ListTileBindings.register(ctx);
    ThemeDataBindings.register(ctx);
    ThemeBindings.register(ctx);
    AnimatedThemeBindings.register(ctx);
    ColorSchemeBindings.register(ctx);
    TextThemeBindings.register(ctx);
    ButtonStyleBindings.register(ctx);
    InputDecorationBindings.register(ctx);
    InputDecorationThemeBindings.register(ctx);
    VisualDensityBindings.register(ctx);
    IconThemeDataBindings.register(ctx);
    InputBorderBindings.register(ctx);
    UnderlineInputBorderBindings.register(ctx);
    OutlineInputBorderBindings.register(ctx);
    MaterialTapTargetSizeBindings.register(ctx);
    FloatingLabelBehaviorBindings.register(ctx);
    TextFieldBindings.register(ctx);
    CheckboxBindings.register(ctx);
    SwitchBindings.register(ctx);
    SliderBindings.register(ctx);
    DialogBindings.register(ctx);
    AlertDialogBindings.register(ctx);
    SimpleDialogBindings.register(ctx);
    SimpleDialogOptionBindings.register(ctx);
    BottomSheetBindings.register(ctx);
    DrawerBindings.register(ctx);
    NavigationBarBindings.register(ctx);
    NavigationDestinationBindings.register(ctx);
    NavigationRailBindings.register(ctx);
    BottomNavigationBarBindings.register(ctx);
    BottomAppBarBindings.register(ctx);
    DrawerAlignmentBindings.register(ctx);
    NavigationDestinationLabelBehaviorBindings.register(ctx);
    SnackBarClosedReasonBindings.register(ctx);
    TabBarBindings.register(ctx);
    TabBarViewBindings.register(ctx);
    TabBindings.register(ctx);
    TabPageSelectorBindings.register(ctx);
    TabPageSelectorIndicatorBindings.register(ctx);
    SnackBarBindings.register(ctx);
    SnackBarActionBindings.register(ctx);
    ChipBindings.register(ctx);
    ActionChipBindings.register(ctx);
    ChoiceChipBindings.register(ctx);
    FilterChipBindings.register(ctx);
    InputChipBindings.register(ctx);
    ExpansionTileBindings.register(ctx);
    CircleAvatarBindings.register(ctx);
    BadgeBindings.register(ctx);
    DividerBindings.register(ctx);
    ExpandIconBindings.register(ctx);
    LinearProgressIndicatorBindings.register(ctx);
    CircularProgressIndicatorBindings.register(ctx);
    RefreshProgressIndicatorBindings.register(ctx);
    GridTileBindings.register(ctx);
    GridTileBarBindings.register(ctx);
    IconButtonBindings.register(ctx);
    OutlinedButtonBindings.register(ctx);
    FilledButtonBindings.register(ctx);
    MaterialPageRouteBindings.register(ctx);
    MaterialColorBindings.register(ctx);
    DrawerHeaderBindings.register(ctx);
    TabBarIndicatorSizeBindings.register(ctx);
    TabAlignmentBindings.register(ctx);
  }
}
