// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7
// Generator: dartic_generator

// ignore_for_file: unused_import, unnecessary_import, implementation_imports

import 'package:dartic/dartic.dart';
import '../bindings/material/popup_menu_divider_bindings.g.dart';
import '../bindings/material/about_dialog_bindings.g.dart';
import '../bindings/material/about_list_tile_bindings.g.dart';
import '../bindings/material/action_chip_bindings.g.dart';
import '../bindings/material/action_icon_theme_bindings.g.dart';
import '../bindings/material/action_icon_theme_data_bindings.g.dart';
import '../bindings/material/adaptation_bindings.g.dart';
import '../bindings/material/adaptive_text_selection_toolbar_bindings.g.dart';
import '../bindings/material/alert_dialog_bindings.g.dart';
import '../bindings/material/animated_icon_bindings.g.dart';
import '../bindings/material/animated_icon_data_bindings.g.dart';
import '../bindings/material/animated_icons_bindings.g.dart';
import '../bindings/material/animated_theme_bindings.g.dart';
import '../bindings/material/app_bar_bindings.g.dart';
import '../bindings/material/app_bar_theme_bindings.g.dart';
import '../bindings/material/app_bar_theme_data_bindings.g.dart';
import '../bindings/material/autocomplete_bindings.g.dart';
import '../bindings/material/back_button_bindings.g.dart';
import '../bindings/material/back_button_icon_bindings.g.dart';
import '../bindings/material/badge_bindings.g.dart';
import '../bindings/material/badge_theme_bindings.g.dart';
import '../bindings/material/badge_theme_data_bindings.g.dart';
import '../bindings/material/base_range_slider_track_shape_bindings.g.dart';
import '../bindings/material/base_slider_track_shape_bindings.g.dart';
import '../bindings/material/bottom_app_bar_bindings.g.dart';
import '../bindings/material/bottom_app_bar_theme_bindings.g.dart';
import '../bindings/material/bottom_app_bar_theme_data_bindings.g.dart';
import '../bindings/material/bottom_navigation_bar_bindings.g.dart';
import '../bindings/material/bottom_navigation_bar_landscape_layout_bindings.g.dart';
import '../bindings/material/bottom_navigation_bar_theme_bindings.g.dart';
import '../bindings/material/bottom_navigation_bar_theme_data_bindings.g.dart';
import '../bindings/material/bottom_navigation_bar_type_bindings.g.dart';
import '../bindings/material/bottom_sheet_bindings.g.dart';
import '../bindings/material/bottom_sheet_theme_data_bindings.g.dart';
import '../bindings/material/button_bar_bindings.g.dart';
import '../bindings/material/button_bar_layout_behavior_bindings.g.dart';
import '../bindings/material/button_bar_theme_bindings.g.dart';
import '../bindings/material/button_bar_theme_data_bindings.g.dart';
import '../bindings/material/button_segment_bindings.g.dart';
import '../bindings/material/button_style_bindings.g.dart';
import '../bindings/material/button_style_button_bindings.g.dart';
import '../bindings/material/button_text_theme_bindings.g.dart';
import '../bindings/material/button_theme_bindings.g.dart';
import '../bindings/material/button_theme_data_bindings.g.dart';
import '../bindings/material/calendar_date_picker_bindings.g.dart';
import '../bindings/material/calendar_delegate_bindings.g.dart';
import '../bindings/material/card_bindings.g.dart';
import '../bindings/material/card_theme_bindings.g.dart';
import '../bindings/material/card_theme_data_bindings.g.dart';
import '../bindings/material/carousel_controller_bindings.g.dart';
import '../bindings/material/carousel_scroll_physics_bindings.g.dart';
import '../bindings/material/carousel_view_bindings.g.dart';
import '../bindings/material/carousel_view_theme_bindings.g.dart';
import '../bindings/material/carousel_view_theme_data_bindings.g.dart';
import '../bindings/material/checkbox_bindings.g.dart';
import '../bindings/material/checkbox_list_tile_bindings.g.dart';
import '../bindings/material/checkbox_menu_button_bindings.g.dart';
import '../bindings/material/checkbox_theme_bindings.g.dart';
import '../bindings/material/checkbox_theme_data_bindings.g.dart';
import '../bindings/material/checked_popup_menu_item_bindings.g.dart';
import '../bindings/material/checkmarkable_chip_attributes_bindings.g.dart';
import '../bindings/material/chip_bindings.g.dart';
import '../bindings/material/chip_animation_style_bindings.g.dart';
import '../bindings/material/chip_attributes_bindings.g.dart';
import '../bindings/material/chip_theme_bindings.g.dart';
import '../bindings/material/chip_theme_data_bindings.g.dart';
import '../bindings/material/choice_chip_bindings.g.dart';
import '../bindings/material/circle_avatar_bindings.g.dart';
import '../bindings/material/circular_progress_indicator_bindings.g.dart';
import '../bindings/material/close_button_bindings.g.dart';
import '../bindings/material/close_button_icon_bindings.g.dart';
import '../bindings/material/collapse_mode_bindings.g.dart';
import '../bindings/material/color_scheme_bindings.g.dart';
import '../bindings/material/colors_bindings.g.dart';
import '../bindings/material/controls_details_bindings.g.dart';
import '../bindings/material/cupertino_based_material_theme_data_bindings.g.dart';
import '../bindings/material/cupertino_page_transitions_builder_bindings.g.dart';
import '../bindings/material/data_cell_bindings.g.dart';
import '../bindings/material/data_column_bindings.g.dart';
import '../bindings/material/data_row_bindings.g.dart';
import '../bindings/material/data_table_bindings.g.dart';
import '../bindings/material/data_table_source_bindings.g.dart';
import '../bindings/material/data_table_theme_bindings.g.dart';
import '../bindings/material/data_table_theme_data_bindings.g.dart';
import '../bindings/material/date_picker_dialog_bindings.g.dart';
import '../bindings/material/date_picker_entry_mode_bindings.g.dart';
import '../bindings/material/date_picker_mode_bindings.g.dart';
import '../bindings/material/date_picker_theme_bindings.g.dart';
import '../bindings/material/date_picker_theme_data_bindings.g.dart';
import '../bindings/material/date_range_picker_dialog_bindings.g.dart';
import '../bindings/material/date_time_range_bindings.g.dart';
import '../bindings/material/date_utils_bindings.g.dart';
import '../bindings/material/day_period_bindings.g.dart';
import '../bindings/material/default_material_localizations_bindings.g.dart';
import '../bindings/material/default_tab_controller_bindings.g.dart';
import '../bindings/material/deletable_chip_attributes_bindings.g.dart';
import '../bindings/material/desktop_text_selection_controls_bindings.g.dart';
import '../bindings/material/desktop_text_selection_toolbar_bindings.g.dart';
import '../bindings/material/desktop_text_selection_toolbar_button_bindings.g.dart';
import '../bindings/material/dialog_bindings.g.dart';
import '../bindings/material/dialog_route_bindings.g.dart';
import '../bindings/material/dialog_theme_bindings.g.dart';
import '../bindings/material/dialog_theme_data_bindings.g.dart';
import '../bindings/material/disabled_chip_attributes_bindings.g.dart';
import '../bindings/material/divider_bindings.g.dart';
import '../bindings/material/divider_theme_bindings.g.dart';
import '../bindings/material/divider_theme_data_bindings.g.dart';
import '../bindings/material/drawer_bindings.g.dart';
import '../bindings/material/drawer_alignment_bindings.g.dart';
import '../bindings/material/drawer_button_bindings.g.dart';
import '../bindings/material/drawer_button_icon_bindings.g.dart';
import '../bindings/material/drawer_controller_bindings.g.dart';
import '../bindings/material/drawer_controller_state_bindings.g.dart';
import '../bindings/material/drawer_header_bindings.g.dart';
import '../bindings/material/drawer_theme_bindings.g.dart';
import '../bindings/material/drawer_theme_data_bindings.g.dart';
import '../bindings/material/drop_range_slider_value_indicator_shape_bindings.g.dart';
import '../bindings/material/drop_slider_value_indicator_shape_bindings.g.dart';
import '../bindings/material/dropdown_button_bindings.g.dart';
import '../bindings/material/dropdown_button_form_field_bindings.g.dart';
import '../bindings/material/dropdown_button_hide_underline_bindings.g.dart';
import '../bindings/material/dropdown_menu_bindings.g.dart';
import '../bindings/material/dropdown_menu_close_behavior_bindings.g.dart';
import '../bindings/material/dropdown_menu_entry_bindings.g.dart';
import '../bindings/material/dropdown_menu_form_field_bindings.g.dart';
import '../bindings/material/dropdown_menu_item_bindings.g.dart';
import '../bindings/material/dropdown_menu_theme_bindings.g.dart';
import '../bindings/material/dropdown_menu_theme_data_bindings.g.dart';
import '../bindings/material/durations_bindings.g.dart';
import '../bindings/material/dynamic_scheme_variant_bindings.g.dart';
import '../bindings/material/easing_bindings.g.dart';
import '../bindings/material/elevated_button_bindings.g.dart';
import '../bindings/material/elevated_button_theme_bindings.g.dart';
import '../bindings/material/elevated_button_theme_data_bindings.g.dart';
import '../bindings/material/elevation_overlay_bindings.g.dart';
import '../bindings/material/end_drawer_button_bindings.g.dart';
import '../bindings/material/end_drawer_button_icon_bindings.g.dart';
import '../bindings/material/expand_icon_bindings.g.dart';
import '../bindings/material/expansion_panel_bindings.g.dart';
import '../bindings/material/expansion_panel_list_bindings.g.dart';
import '../bindings/material/expansion_panel_radio_bindings.g.dart';
import '../bindings/material/expansion_tile_bindings.g.dart';
import '../bindings/material/expansion_tile_theme_bindings.g.dart';
import '../bindings/material/expansion_tile_theme_data_bindings.g.dart';
import '../bindings/material/fab_center_offset_x_bindings.g.dart';
import '../bindings/material/fab_contained_offset_y_bindings.g.dart';
import '../bindings/material/fab_docked_offset_y_bindings.g.dart';
import '../bindings/material/fab_end_offset_x_bindings.g.dart';
import '../bindings/material/fab_float_offset_y_bindings.g.dart';
import '../bindings/material/fab_mini_offset_adjustment_bindings.g.dart';
import '../bindings/material/fab_start_offset_x_bindings.g.dart';
import '../bindings/material/fab_top_offset_y_bindings.g.dart';
import '../bindings/material/fade_forwards_page_transitions_builder_bindings.g.dart';
import '../bindings/material/fade_upwards_page_transitions_builder_bindings.g.dart';
import '../bindings/material/filled_button_bindings.g.dart';
import '../bindings/material/filled_button_theme_bindings.g.dart';
import '../bindings/material/filled_button_theme_data_bindings.g.dart';
import '../bindings/material/filter_chip_bindings.g.dart';
import '../bindings/material/flexible_space_bar_bindings.g.dart';
import '../bindings/material/flexible_space_bar_settings_bindings.g.dart';
import '../bindings/material/floating_action_button_bindings.g.dart';
import '../bindings/material/floating_action_button_animator_bindings.g.dart';
import '../bindings/material/floating_action_button_location_bindings.g.dart';
import '../bindings/material/floating_action_button_theme_data_bindings.g.dart';
import '../bindings/material/floating_label_alignment_bindings.g.dart';
import '../bindings/material/floating_label_behavior_bindings.g.dart';
import '../bindings/material/gapped_range_slider_track_shape_bindings.g.dart';
import '../bindings/material/gapped_slider_track_shape_bindings.g.dart';
import '../bindings/material/gregorian_calendar_delegate_bindings.g.dart';
import '../bindings/material/grid_tile_bindings.g.dart';
import '../bindings/material/grid_tile_bar_bindings.g.dart';
import '../bindings/material/handle_range_slider_thumb_shape_bindings.g.dart';
import '../bindings/material/handle_thumb_shape_bindings.g.dart';
import '../bindings/material/hour_format_bindings.g.dart';
import '../bindings/material/icon_alignment_bindings.g.dart';
import '../bindings/material/icon_button_bindings.g.dart';
import '../bindings/material/icon_button_theme_bindings.g.dart';
import '../bindings/material/icon_button_theme_data_bindings.g.dart';
import '../bindings/material/icons_bindings.g.dart';
import '../bindings/material/ink_bindings.g.dart';
import '../bindings/material/ink_decoration_bindings.g.dart';
import '../bindings/material/ink_feature_bindings.g.dart';
import '../bindings/material/ink_highlight_bindings.g.dart';
import '../bindings/material/ink_response_bindings.g.dart';
import '../bindings/material/ink_ripple_bindings.g.dart';
import '../bindings/material/ink_sparkle_bindings.g.dart';
import '../bindings/material/ink_splash_bindings.g.dart';
import '../bindings/material/ink_well_bindings.g.dart';
import '../bindings/material/input_border_bindings.g.dart';
import '../bindings/material/input_chip_bindings.g.dart';
import '../bindings/material/input_date_picker_form_field_bindings.g.dart';
import '../bindings/material/input_decoration_bindings.g.dart';
import '../bindings/material/input_decoration_theme_bindings.g.dart';
import '../bindings/material/input_decoration_theme_data_bindings.g.dart';
import '../bindings/material/input_decorator_bindings.g.dart';
import '../bindings/material/interactive_ink_feature_bindings.g.dart';
import '../bindings/material/interactive_ink_feature_factory_bindings.g.dart';
import '../bindings/material/license_page_bindings.g.dart';
import '../bindings/material/linear_progress_indicator_bindings.g.dart';
import '../bindings/material/list_tile_bindings.g.dart';
import '../bindings/material/list_tile_control_affinity_bindings.g.dart';
import '../bindings/material/list_tile_style_bindings.g.dart';
import '../bindings/material/list_tile_theme_bindings.g.dart';
import '../bindings/material/list_tile_theme_data_bindings.g.dart';
import '../bindings/material/list_tile_title_alignment_bindings.g.dart';
import '../bindings/material/magnifier_bindings.g.dart';
import '../bindings/material/material_bindings.g.dart';
import '../bindings/material/material_accent_color_bindings.g.dart';
import '../bindings/material/material_app_bindings.g.dart';
import '../bindings/material/material_banner_bindings.g.dart';
import '../bindings/material/material_banner_closed_reason_bindings.g.dart';
import '../bindings/material/material_banner_theme_bindings.g.dart';
import '../bindings/material/material_banner_theme_data_bindings.g.dart';
import '../bindings/material/material_based_cupertino_theme_data_bindings.g.dart';
import '../bindings/material/material_button_bindings.g.dart';
import '../bindings/material/material_color_bindings.g.dart';
import '../bindings/material/material_gap_bindings.g.dart';
import '../bindings/material/material_ink_controller_bindings.g.dart';
import '../bindings/material/material_localizations_bindings.g.dart';
import '../bindings/material/material_page_bindings.g.dart';
import '../bindings/material/material_page_route_bindings.g.dart';
import '../bindings/material/material_point_arc_tween_bindings.g.dart';
import '../bindings/material/material_rect_arc_tween_bindings.g.dart';
import '../bindings/material/material_rect_center_arc_tween_bindings.g.dart';
import '../bindings/material/material_route_transition_mixin_bindings.g.dart';
import '../bindings/material/material_scroll_behavior_bindings.g.dart';
import '../bindings/material/material_slice_bindings.g.dart';
import '../bindings/material/material_state_mixin_bindings.g.dart';
import '../bindings/material/material_state_outline_input_border_bindings.g.dart';
import '../bindings/material/material_state_underline_input_border_bindings.g.dart';
import '../bindings/material/material_tap_target_size_bindings.g.dart';
import '../bindings/material/material_text_selection_controls_bindings.g.dart';
import '../bindings/material/material_text_selection_handle_controls_bindings.g.dart';
import '../bindings/material/material_type_bindings.g.dart';
import '../bindings/material/menu_accelerator_callback_binding_bindings.g.dart';
import '../bindings/material/menu_accelerator_label_bindings.g.dart';
import '../bindings/material/menu_anchor_bindings.g.dart';
import '../bindings/material/menu_bar_bindings.g.dart';
import '../bindings/material/menu_bar_theme_bindings.g.dart';
import '../bindings/material/menu_bar_theme_data_bindings.g.dart';
import '../bindings/material/menu_button_theme_bindings.g.dart';
import '../bindings/material/menu_button_theme_data_bindings.g.dart';
import '../bindings/material/menu_item_button_bindings.g.dart';
import '../bindings/material/menu_style_bindings.g.dart';
import '../bindings/material/menu_theme_bindings.g.dart';
import '../bindings/material/menu_theme_data_bindings.g.dart';
import '../bindings/material/mergeable_material_bindings.g.dart';
import '../bindings/material/mergeable_material_item_bindings.g.dart';
import '../bindings/material/modal_bottom_sheet_route_bindings.g.dart';
import '../bindings/material/navigation_bar_bindings.g.dart';
import '../bindings/material/navigation_bar_theme_bindings.g.dart';
import '../bindings/material/navigation_bar_theme_data_bindings.g.dart';
import '../bindings/material/navigation_destination_bindings.g.dart';
import '../bindings/material/navigation_destination_label_behavior_bindings.g.dart';
import '../bindings/material/navigation_drawer_bindings.g.dart';
import '../bindings/material/navigation_drawer_destination_bindings.g.dart';
import '../bindings/material/navigation_drawer_theme_bindings.g.dart';
import '../bindings/material/navigation_drawer_theme_data_bindings.g.dart';
import '../bindings/material/navigation_indicator_bindings.g.dart';
import '../bindings/material/navigation_rail_bindings.g.dart';
import '../bindings/material/navigation_rail_destination_bindings.g.dart';
import '../bindings/material/navigation_rail_label_type_bindings.g.dart';
import '../bindings/material/navigation_rail_theme_bindings.g.dart';
import '../bindings/material/navigation_rail_theme_data_bindings.g.dart';
import '../bindings/material/no_splash_bindings.g.dart';
import '../bindings/material/open_upwards_page_transitions_builder_bindings.g.dart';
import '../bindings/material/outline_input_border_bindings.g.dart';
import '../bindings/material/outlined_button_bindings.g.dart';
import '../bindings/material/outlined_button_theme_bindings.g.dart';
import '../bindings/material/outlined_button_theme_data_bindings.g.dart';
import '../bindings/material/paddle_range_slider_value_indicator_shape_bindings.g.dart';
import '../bindings/material/paddle_slider_value_indicator_shape_bindings.g.dart';
import '../bindings/material/page_transitions_theme_bindings.g.dart';
import '../bindings/material/paginated_data_table_bindings.g.dart';
import '../bindings/material/paginated_data_table_state_bindings.g.dart';
import '../bindings/material/persistent_bottom_sheet_controller_bindings.g.dart';
import '../bindings/material/platform_adaptive_icons_bindings.g.dart';
import '../bindings/material/popup_menu_button_bindings.g.dart';
import '../bindings/material/popup_menu_button_state_bindings.g.dart';
import '../bindings/material/popup_menu_entry_bindings.g.dart';
import '../bindings/material/popup_menu_item_bindings.g.dart';
import '../bindings/material/popup_menu_item_state_bindings.g.dart';
import '../bindings/material/popup_menu_position_bindings.g.dart';
import '../bindings/material/popup_menu_theme_bindings.g.dart';
import '../bindings/material/popup_menu_theme_data_bindings.g.dart';
import '../bindings/material/predictive_back_fullscreen_page_transitions_builder_bindings.g.dart';
import '../bindings/material/predictive_back_page_transitions_builder_bindings.g.dart';
import '../bindings/material/progress_indicator_bindings.g.dart';
import '../bindings/material/progress_indicator_theme_bindings.g.dart';
import '../bindings/material/progress_indicator_theme_data_bindings.g.dart';
import '../bindings/material/radio_bindings.g.dart';
import '../bindings/material/radio_list_tile_bindings.g.dart';
import '../bindings/material/radio_menu_button_bindings.g.dart';
import '../bindings/material/radio_theme_bindings.g.dart';
import '../bindings/material/radio_theme_data_bindings.g.dart';
import '../bindings/material/range_labels_bindings.g.dart';
import '../bindings/material/range_slider_bindings.g.dart';
import '../bindings/material/range_slider_thumb_shape_bindings.g.dart';
import '../bindings/material/range_slider_tick_mark_shape_bindings.g.dart';
import '../bindings/material/range_slider_track_shape_bindings.g.dart';
import '../bindings/material/range_slider_value_indicator_shape_bindings.g.dart';
import '../bindings/material/range_values_bindings.g.dart';
import '../bindings/material/raw_chip_bindings.g.dart';
import '../bindings/material/raw_material_button_bindings.g.dart';
import '../bindings/material/rectangular_range_slider_track_shape_bindings.g.dart';
import '../bindings/material/rectangular_range_slider_value_indicator_shape_bindings.g.dart';
import '../bindings/material/rectangular_slider_track_shape_bindings.g.dart';
import '../bindings/material/rectangular_slider_value_indicator_shape_bindings.g.dart';
import '../bindings/material/refresh_indicator_bindings.g.dart';
import '../bindings/material/refresh_indicator_state_bindings.g.dart';
import '../bindings/material/refresh_indicator_status_bindings.g.dart';
import '../bindings/material/refresh_indicator_trigger_mode_bindings.g.dart';
import '../bindings/material/refresh_progress_indicator_bindings.g.dart';
import '../bindings/material/reorderable_list_view_bindings.g.dart';
import '../bindings/material/restorable_time_of_day_bindings.g.dart';
import '../bindings/material/round_range_slider_thumb_shape_bindings.g.dart';
import '../bindings/material/round_range_slider_tick_mark_shape_bindings.g.dart';
import '../bindings/material/round_slider_overlay_shape_bindings.g.dart';
import '../bindings/material/round_slider_thumb_shape_bindings.g.dart';
import '../bindings/material/round_slider_tick_mark_shape_bindings.g.dart';
import '../bindings/material/rounded_rect_range_slider_track_shape_bindings.g.dart';
import '../bindings/material/rounded_rect_range_slider_value_indicator_shape_bindings.g.dart';
import '../bindings/material/rounded_rect_slider_track_shape_bindings.g.dart';
import '../bindings/material/rounded_rect_slider_value_indicator_shape_bindings.g.dart';
import '../bindings/material/scaffold_bindings.g.dart';
import '../bindings/material/scaffold_feature_controller_bindings.g.dart';
import '../bindings/material/scaffold_geometry_bindings.g.dart';
import '../bindings/material/scaffold_messenger_bindings.g.dart';
import '../bindings/material/scaffold_messenger_state_bindings.g.dart';
import '../bindings/material/scaffold_prelayout_geometry_bindings.g.dart';
import '../bindings/material/scaffold_state_bindings.g.dart';
import '../bindings/material/script_category_bindings.g.dart';
import '../bindings/material/scrollbar_bindings.g.dart';
import '../bindings/material/scrollbar_theme_bindings.g.dart';
import '../bindings/material/scrollbar_theme_data_bindings.g.dart';
import '../bindings/material/search_anchor_bindings.g.dart';
import '../bindings/material/search_bar_bindings.g.dart';
import '../bindings/material/search_bar_theme_bindings.g.dart';
import '../bindings/material/search_bar_theme_data_bindings.g.dart';
import '../bindings/material/search_controller_bindings.g.dart';
import '../bindings/material/search_delegate_bindings.g.dart';
import '../bindings/material/search_view_theme_bindings.g.dart';
import '../bindings/material/search_view_theme_data_bindings.g.dart';
import '../bindings/material/segmented_button_bindings.g.dart';
import '../bindings/material/segmented_button_state_bindings.g.dart';
import '../bindings/material/segmented_button_theme_bindings.g.dart';
import '../bindings/material/segmented_button_theme_data_bindings.g.dart';
import '../bindings/material/selectable_chip_attributes_bindings.g.dart';
import '../bindings/material/selectable_text_bindings.g.dart';
import '../bindings/material/selection_area_bindings.g.dart';
import '../bindings/material/selection_area_state_bindings.g.dart';
import '../bindings/material/shape_border_tween_bindings.g.dart';
import '../bindings/material/show_value_indicator_bindings.g.dart';
import '../bindings/material/simple_dialog_bindings.g.dart';
import '../bindings/material/simple_dialog_option_bindings.g.dart';
import '../bindings/material/slider_bindings.g.dart';
import '../bindings/material/slider_component_shape_bindings.g.dart';
import '../bindings/material/slider_interaction_bindings.g.dart';
import '../bindings/material/slider_theme_bindings.g.dart';
import '../bindings/material/slider_theme_data_bindings.g.dart';
import '../bindings/material/slider_tick_mark_shape_bindings.g.dart';
import '../bindings/material/slider_track_shape_bindings.g.dart';
import '../bindings/material/sliver_app_bar_bindings.g.dart';
import '../bindings/material/snack_bar_bindings.g.dart';
import '../bindings/material/snack_bar_action_bindings.g.dart';
import '../bindings/material/snack_bar_behavior_bindings.g.dart';
import '../bindings/material/snack_bar_closed_reason_bindings.g.dart';
import '../bindings/material/snack_bar_theme_data_bindings.g.dart';
import '../bindings/material/spell_check_suggestions_toolbar_bindings.g.dart';
import '../bindings/material/spell_check_suggestions_toolbar_layout_delegate_bindings.g.dart';
import '../bindings/material/standard_fab_location_bindings.g.dart';
import '../bindings/material/step_bindings.g.dart';
import '../bindings/material/step_state_bindings.g.dart';
import '../bindings/material/step_style_bindings.g.dart';
import '../bindings/material/stepper_bindings.g.dart';
import '../bindings/material/stepper_type_bindings.g.dart';
import '../bindings/material/stretch_mode_bindings.g.dart';
import '../bindings/material/submenu_button_bindings.g.dart';
import '../bindings/material/switch_bindings.g.dart';
import '../bindings/material/switch_list_tile_bindings.g.dart';
import '../bindings/material/switch_theme_bindings.g.dart';
import '../bindings/material/switch_theme_data_bindings.g.dart';
import '../bindings/material/tab_bindings.g.dart';
import '../bindings/material/tab_alignment_bindings.g.dart';
import '../bindings/material/tab_bar_bindings.g.dart';
import '../bindings/material/tab_bar_indicator_size_bindings.g.dart';
import '../bindings/material/tab_bar_theme_bindings.g.dart';
import '../bindings/material/tab_bar_theme_data_bindings.g.dart';
import '../bindings/material/tab_bar_view_bindings.g.dart';
import '../bindings/material/tab_controller_bindings.g.dart';
import '../bindings/material/tab_indicator_animation_bindings.g.dart';
import '../bindings/material/tab_page_selector_bindings.g.dart';
import '../bindings/material/tab_page_selector_indicator_bindings.g.dart';
import '../bindings/material/table_row_ink_well_bindings.g.dart';
import '../bindings/material/tappable_chip_attributes_bindings.g.dart';
import '../bindings/material/text_button_bindings.g.dart';
import '../bindings/material/text_button_theme_bindings.g.dart';
import '../bindings/material/text_button_theme_data_bindings.g.dart';
import '../bindings/material/text_field_bindings.g.dart';
import '../bindings/material/text_form_field_bindings.g.dart';
import '../bindings/material/text_magnifier_bindings.g.dart';
import '../bindings/material/text_selection_theme_bindings.g.dart';
import '../bindings/material/text_selection_theme_data_bindings.g.dart';
import '../bindings/material/text_selection_toolbar_bindings.g.dart';
import '../bindings/material/text_selection_toolbar_text_button_bindings.g.dart';
import '../bindings/material/text_theme_bindings.g.dart';
import '../bindings/material/theme_bindings.g.dart';
import '../bindings/material/theme_data_bindings.g.dart';
import '../bindings/material/theme_data_tween_bindings.g.dart';
import '../bindings/material/theme_extension_bindings.g.dart';
import '../bindings/material/theme_mode_bindings.g.dart';
import '../bindings/material/thumb_bindings.g.dart';
import '../bindings/material/time_of_day_bindings.g.dart';
import '../bindings/material/time_of_day_format_bindings.g.dart';
import '../bindings/material/time_picker_dialog_bindings.g.dart';
import '../bindings/material/time_picker_entry_mode_bindings.g.dart';
import '../bindings/material/time_picker_theme_bindings.g.dart';
import '../bindings/material/time_picker_theme_data_bindings.g.dart';
import '../bindings/material/toggle_buttons_bindings.g.dart';
import '../bindings/material/toggle_buttons_theme_bindings.g.dart';
import '../bindings/material/toggle_buttons_theme_data_bindings.g.dart';
import '../bindings/material/tooltip_bindings.g.dart';
import '../bindings/material/tooltip_state_bindings.g.dart';
import '../bindings/material/tooltip_theme_bindings.g.dart';
import '../bindings/material/tooltip_theme_data_bindings.g.dart';
import '../bindings/material/tooltip_trigger_mode_bindings.g.dart';
import '../bindings/material/tooltip_visibility_bindings.g.dart';
import '../bindings/material/typography_bindings.g.dart';
import '../bindings/material/underline_input_border_bindings.g.dart';
import '../bindings/material/underline_tab_indicator_bindings.g.dart';
import '../bindings/material/user_accounts_drawer_header_bindings.g.dart';
import '../bindings/material/vertical_divider_bindings.g.dart';
import '../bindings/material/visual_density_bindings.g.dart';
import '../bindings/material/widget_state_input_border_bindings.g.dart';
import '../bindings/material/year_picker_bindings.g.dart';
import '../bindings/material/zoom_page_transitions_builder_bindings.g.dart';
import '../bindings/material/material_top_level_bindings.g.dart';

class MaterialPlugin extends DarticPlugin {
  @override
  String get name => 'package:flutter/src/material';

  @override
  void register(DarticPluginContext ctx) {
    PopupMenuDividerBindings.register(ctx);
    AboutDialogBindings.register(ctx);
    AboutListTileBindings.register(ctx);
    ActionChipBindings.register(ctx);
    ActionIconThemeBindings.register(ctx);
    ActionIconThemeDataBindings.register(ctx);
    AdaptationBindings.register(ctx);
    AdaptiveTextSelectionToolbarBindings.register(ctx);
    AlertDialogBindings.register(ctx);
    AnimatedIconBindings.register(ctx);
    AnimatedIconDataBindings.register(ctx);
    AnimatedIconsBindings.register(ctx);
    AnimatedThemeBindings.register(ctx);
    AppBarBindings.register(ctx);
    AppBarThemeBindings.register(ctx);
    AppBarThemeDataBindings.register(ctx);
    AutocompleteBindings.register(ctx);
    BackButtonBindings.register(ctx);
    BackButtonIconBindings.register(ctx);
    BadgeBindings.register(ctx);
    BadgeThemeBindings.register(ctx);
    BadgeThemeDataBindings.register(ctx);
    BaseRangeSliderTrackShapeBindings.register(ctx);
    BaseSliderTrackShapeBindings.register(ctx);
    BottomAppBarBindings.register(ctx);
    BottomAppBarThemeBindings.register(ctx);
    BottomAppBarThemeDataBindings.register(ctx);
    BottomNavigationBarBindings.register(ctx);
    BottomNavigationBarLandscapeLayoutBindings.register(ctx);
    BottomNavigationBarThemeBindings.register(ctx);
    BottomNavigationBarThemeDataBindings.register(ctx);
    BottomNavigationBarTypeBindings.register(ctx);
    BottomSheetBindings.register(ctx);
    BottomSheetThemeDataBindings.register(ctx);
    ButtonBarBindings.register(ctx);
    ButtonBarLayoutBehaviorBindings.register(ctx);
    ButtonBarThemeBindings.register(ctx);
    ButtonBarThemeDataBindings.register(ctx);
    ButtonSegmentBindings.register(ctx);
    ButtonStyleBindings.register(ctx);
    ButtonStyleButtonBindings.register(ctx);
    ButtonTextThemeBindings.register(ctx);
    ButtonThemeBindings.register(ctx);
    ButtonThemeDataBindings.register(ctx);
    CalendarDatePickerBindings.register(ctx);
    CalendarDelegateBindings.register(ctx);
    CardBindings.register(ctx);
    CardThemeBindings.register(ctx);
    CardThemeDataBindings.register(ctx);
    CarouselControllerBindings.register(ctx);
    CarouselScrollPhysicsBindings.register(ctx);
    CarouselViewBindings.register(ctx);
    CarouselViewThemeBindings.register(ctx);
    CarouselViewThemeDataBindings.register(ctx);
    CheckboxBindings.register(ctx);
    CheckboxListTileBindings.register(ctx);
    CheckboxMenuButtonBindings.register(ctx);
    CheckboxThemeBindings.register(ctx);
    CheckboxThemeDataBindings.register(ctx);
    CheckedPopupMenuItemBindings.register(ctx);
    CheckmarkableChipAttributesBindings.register(ctx);
    ChipBindings.register(ctx);
    ChipAnimationStyleBindings.register(ctx);
    ChipAttributesBindings.register(ctx);
    ChipThemeBindings.register(ctx);
    ChipThemeDataBindings.register(ctx);
    ChoiceChipBindings.register(ctx);
    CircleAvatarBindings.register(ctx);
    CircularProgressIndicatorBindings.register(ctx);
    CloseButtonBindings.register(ctx);
    CloseButtonIconBindings.register(ctx);
    CollapseModeBindings.register(ctx);
    ColorSchemeBindings.register(ctx);
    ColorsBindings.register(ctx);
    ControlsDetailsBindings.register(ctx);
    CupertinoBasedMaterialThemeDataBindings.register(ctx);
    CupertinoPageTransitionsBuilderBindings.register(ctx);
    DataCellBindings.register(ctx);
    DataColumnBindings.register(ctx);
    DataRowBindings.register(ctx);
    DataTableBindings.register(ctx);
    DataTableSourceBindings.register(ctx);
    DataTableThemeBindings.register(ctx);
    DataTableThemeDataBindings.register(ctx);
    DatePickerDialogBindings.register(ctx);
    DatePickerEntryModeBindings.register(ctx);
    DatePickerModeBindings.register(ctx);
    DatePickerThemeBindings.register(ctx);
    DatePickerThemeDataBindings.register(ctx);
    DateRangePickerDialogBindings.register(ctx);
    DateTimeRangeBindings.register(ctx);
    DateUtilsBindings.register(ctx);
    DayPeriodBindings.register(ctx);
    DefaultMaterialLocalizationsBindings.register(ctx);
    DefaultTabControllerBindings.register(ctx);
    DeletableChipAttributesBindings.register(ctx);
    DesktopTextSelectionControlsBindings.register(ctx);
    DesktopTextSelectionToolbarBindings.register(ctx);
    DesktopTextSelectionToolbarButtonBindings.register(ctx);
    DialogBindings.register(ctx);
    DialogRouteBindings.register(ctx);
    DialogThemeBindings.register(ctx);
    DialogThemeDataBindings.register(ctx);
    DisabledChipAttributesBindings.register(ctx);
    DividerBindings.register(ctx);
    DividerThemeBindings.register(ctx);
    DividerThemeDataBindings.register(ctx);
    DrawerBindings.register(ctx);
    DrawerAlignmentBindings.register(ctx);
    DrawerButtonBindings.register(ctx);
    DrawerButtonIconBindings.register(ctx);
    DrawerControllerBindings.register(ctx);
    DrawerControllerStateBindings.register(ctx);
    DrawerHeaderBindings.register(ctx);
    DrawerThemeBindings.register(ctx);
    DrawerThemeDataBindings.register(ctx);
    DropRangeSliderValueIndicatorShapeBindings.register(ctx);
    DropSliderValueIndicatorShapeBindings.register(ctx);
    DropdownButtonBindings.register(ctx);
    DropdownButtonFormFieldBindings.register(ctx);
    DropdownButtonHideUnderlineBindings.register(ctx);
    DropdownMenuBindings.register(ctx);
    DropdownMenuCloseBehaviorBindings.register(ctx);
    DropdownMenuEntryBindings.register(ctx);
    DropdownMenuFormFieldBindings.register(ctx);
    DropdownMenuItemBindings.register(ctx);
    DropdownMenuThemeBindings.register(ctx);
    DropdownMenuThemeDataBindings.register(ctx);
    DurationsBindings.register(ctx);
    DynamicSchemeVariantBindings.register(ctx);
    EasingBindings.register(ctx);
    ElevatedButtonBindings.register(ctx);
    ElevatedButtonThemeBindings.register(ctx);
    ElevatedButtonThemeDataBindings.register(ctx);
    ElevationOverlayBindings.register(ctx);
    EndDrawerButtonBindings.register(ctx);
    EndDrawerButtonIconBindings.register(ctx);
    ExpandIconBindings.register(ctx);
    ExpansionPanelBindings.register(ctx);
    ExpansionPanelListBindings.register(ctx);
    ExpansionPanelRadioBindings.register(ctx);
    ExpansionTileBindings.register(ctx);
    ExpansionTileThemeBindings.register(ctx);
    ExpansionTileThemeDataBindings.register(ctx);
    FabCenterOffsetXBindings.register(ctx);
    FabContainedOffsetYBindings.register(ctx);
    FabDockedOffsetYBindings.register(ctx);
    FabEndOffsetXBindings.register(ctx);
    FabFloatOffsetYBindings.register(ctx);
    FabMiniOffsetAdjustmentBindings.register(ctx);
    FabStartOffsetXBindings.register(ctx);
    FabTopOffsetYBindings.register(ctx);
    FadeForwardsPageTransitionsBuilderBindings.register(ctx);
    FadeUpwardsPageTransitionsBuilderBindings.register(ctx);
    FilledButtonBindings.register(ctx);
    FilledButtonThemeBindings.register(ctx);
    FilledButtonThemeDataBindings.register(ctx);
    FilterChipBindings.register(ctx);
    FlexibleSpaceBarBindings.register(ctx);
    FlexibleSpaceBarSettingsBindings.register(ctx);
    FloatingActionButtonBindings.register(ctx);
    FloatingActionButtonAnimatorBindings.register(ctx);
    FloatingActionButtonLocationBindings.register(ctx);
    FloatingActionButtonThemeDataBindings.register(ctx);
    FloatingLabelAlignmentBindings.register(ctx);
    FloatingLabelBehaviorBindings.register(ctx);
    GappedRangeSliderTrackShapeBindings.register(ctx);
    GappedSliderTrackShapeBindings.register(ctx);
    GregorianCalendarDelegateBindings.register(ctx);
    GridTileBindings.register(ctx);
    GridTileBarBindings.register(ctx);
    HandleRangeSliderThumbShapeBindings.register(ctx);
    HandleThumbShapeBindings.register(ctx);
    HourFormatBindings.register(ctx);
    IconAlignmentBindings.register(ctx);
    IconButtonBindings.register(ctx);
    IconButtonThemeBindings.register(ctx);
    IconButtonThemeDataBindings.register(ctx);
    IconsBindings.register(ctx);
    InkBindings.register(ctx);
    InkDecorationBindings.register(ctx);
    InkFeatureBindings.register(ctx);
    InkHighlightBindings.register(ctx);
    InkResponseBindings.register(ctx);
    InkRippleBindings.register(ctx);
    InkSparkleBindings.register(ctx);
    InkSplashBindings.register(ctx);
    InkWellBindings.register(ctx);
    InputBorderBindings.register(ctx);
    InputChipBindings.register(ctx);
    InputDatePickerFormFieldBindings.register(ctx);
    InputDecorationBindings.register(ctx);
    InputDecorationThemeBindings.register(ctx);
    InputDecorationThemeDataBindings.register(ctx);
    InputDecoratorBindings.register(ctx);
    InteractiveInkFeatureBindings.register(ctx);
    InteractiveInkFeatureFactoryBindings.register(ctx);
    LicensePageBindings.register(ctx);
    LinearProgressIndicatorBindings.register(ctx);
    ListTileBindings.register(ctx);
    ListTileControlAffinityBindings.register(ctx);
    ListTileStyleBindings.register(ctx);
    ListTileThemeBindings.register(ctx);
    ListTileThemeDataBindings.register(ctx);
    ListTileTitleAlignmentBindings.register(ctx);
    MagnifierBindings.register(ctx);
    MaterialBindings.register(ctx);
    MaterialAccentColorBindings.register(ctx);
    MaterialAppBindings.register(ctx);
    MaterialBannerBindings.register(ctx);
    MaterialBannerClosedReasonBindings.register(ctx);
    MaterialBannerThemeBindings.register(ctx);
    MaterialBannerThemeDataBindings.register(ctx);
    MaterialBasedCupertinoThemeDataBindings.register(ctx);
    MaterialButtonBindings.register(ctx);
    MaterialColorBindings.register(ctx);
    MaterialGapBindings.register(ctx);
    MaterialInkControllerBindings.register(ctx);
    MaterialLocalizationsBindings.register(ctx);
    MaterialPageBindings.register(ctx);
    MaterialPageRouteBindings.register(ctx);
    MaterialPointArcTweenBindings.register(ctx);
    MaterialRectArcTweenBindings.register(ctx);
    MaterialRectCenterArcTweenBindings.register(ctx);
    MaterialRouteTransitionMixinBindings.register(ctx);
    MaterialScrollBehaviorBindings.register(ctx);
    MaterialSliceBindings.register(ctx);
    MaterialStateMixinBindings.register(ctx);
    MaterialStateOutlineInputBorderBindings.register(ctx);
    MaterialStateUnderlineInputBorderBindings.register(ctx);
    MaterialTapTargetSizeBindings.register(ctx);
    MaterialTextSelectionControlsBindings.register(ctx);
    MaterialTextSelectionHandleControlsBindings.register(ctx);
    MaterialTypeBindings.register(ctx);
    MenuAcceleratorCallbackBindingBindings.register(ctx);
    MenuAcceleratorLabelBindings.register(ctx);
    MenuAnchorBindings.register(ctx);
    MenuBarBindings.register(ctx);
    MenuBarThemeBindings.register(ctx);
    MenuBarThemeDataBindings.register(ctx);
    MenuButtonThemeBindings.register(ctx);
    MenuButtonThemeDataBindings.register(ctx);
    MenuItemButtonBindings.register(ctx);
    MenuStyleBindings.register(ctx);
    MenuThemeBindings.register(ctx);
    MenuThemeDataBindings.register(ctx);
    MergeableMaterialBindings.register(ctx);
    MergeableMaterialItemBindings.register(ctx);
    ModalBottomSheetRouteBindings.register(ctx);
    NavigationBarBindings.register(ctx);
    NavigationBarThemeBindings.register(ctx);
    NavigationBarThemeDataBindings.register(ctx);
    NavigationDestinationBindings.register(ctx);
    NavigationDestinationLabelBehaviorBindings.register(ctx);
    NavigationDrawerBindings.register(ctx);
    NavigationDrawerDestinationBindings.register(ctx);
    NavigationDrawerThemeBindings.register(ctx);
    NavigationDrawerThemeDataBindings.register(ctx);
    NavigationIndicatorBindings.register(ctx);
    NavigationRailBindings.register(ctx);
    NavigationRailDestinationBindings.register(ctx);
    NavigationRailLabelTypeBindings.register(ctx);
    NavigationRailThemeBindings.register(ctx);
    NavigationRailThemeDataBindings.register(ctx);
    NoSplashBindings.register(ctx);
    OpenUpwardsPageTransitionsBuilderBindings.register(ctx);
    OutlineInputBorderBindings.register(ctx);
    OutlinedButtonBindings.register(ctx);
    OutlinedButtonThemeBindings.register(ctx);
    OutlinedButtonThemeDataBindings.register(ctx);
    PaddleRangeSliderValueIndicatorShapeBindings.register(ctx);
    PaddleSliderValueIndicatorShapeBindings.register(ctx);
    PageTransitionsThemeBindings.register(ctx);
    PaginatedDataTableBindings.register(ctx);
    PaginatedDataTableStateBindings.register(ctx);
    PersistentBottomSheetControllerBindings.register(ctx);
    PlatformAdaptiveIconsBindings.register(ctx);
    PopupMenuButtonBindings.register(ctx);
    PopupMenuButtonStateBindings.register(ctx);
    PopupMenuEntryBindings.register(ctx);
    PopupMenuItemBindings.register(ctx);
    PopupMenuItemStateBindings.register(ctx);
    PopupMenuPositionBindings.register(ctx);
    PopupMenuThemeBindings.register(ctx);
    PopupMenuThemeDataBindings.register(ctx);
    PredictiveBackFullscreenPageTransitionsBuilderBindings.register(ctx);
    PredictiveBackPageTransitionsBuilderBindings.register(ctx);
    ProgressIndicatorBindings.register(ctx);
    ProgressIndicatorThemeBindings.register(ctx);
    ProgressIndicatorThemeDataBindings.register(ctx);
    RadioBindings.register(ctx);
    RadioListTileBindings.register(ctx);
    RadioMenuButtonBindings.register(ctx);
    RadioThemeBindings.register(ctx);
    RadioThemeDataBindings.register(ctx);
    RangeLabelsBindings.register(ctx);
    RangeSliderBindings.register(ctx);
    RangeSliderThumbShapeBindings.register(ctx);
    RangeSliderTickMarkShapeBindings.register(ctx);
    RangeSliderTrackShapeBindings.register(ctx);
    RangeSliderValueIndicatorShapeBindings.register(ctx);
    RangeValuesBindings.register(ctx);
    RawChipBindings.register(ctx);
    RawMaterialButtonBindings.register(ctx);
    RectangularRangeSliderTrackShapeBindings.register(ctx);
    RectangularRangeSliderValueIndicatorShapeBindings.register(ctx);
    RectangularSliderTrackShapeBindings.register(ctx);
    RectangularSliderValueIndicatorShapeBindings.register(ctx);
    RefreshIndicatorBindings.register(ctx);
    RefreshIndicatorStateBindings.register(ctx);
    RefreshIndicatorStatusBindings.register(ctx);
    RefreshIndicatorTriggerModeBindings.register(ctx);
    RefreshProgressIndicatorBindings.register(ctx);
    ReorderableListViewBindings.register(ctx);
    RestorableTimeOfDayBindings.register(ctx);
    RoundRangeSliderThumbShapeBindings.register(ctx);
    RoundRangeSliderTickMarkShapeBindings.register(ctx);
    RoundSliderOverlayShapeBindings.register(ctx);
    RoundSliderThumbShapeBindings.register(ctx);
    RoundSliderTickMarkShapeBindings.register(ctx);
    RoundedRectRangeSliderTrackShapeBindings.register(ctx);
    RoundedRectRangeSliderValueIndicatorShapeBindings.register(ctx);
    RoundedRectSliderTrackShapeBindings.register(ctx);
    RoundedRectSliderValueIndicatorShapeBindings.register(ctx);
    ScaffoldBindings.register(ctx);
    ScaffoldFeatureControllerBindings.register(ctx);
    ScaffoldGeometryBindings.register(ctx);
    ScaffoldMessengerBindings.register(ctx);
    ScaffoldMessengerStateBindings.register(ctx);
    ScaffoldPrelayoutGeometryBindings.register(ctx);
    ScaffoldStateBindings.register(ctx);
    ScriptCategoryBindings.register(ctx);
    ScrollbarBindings.register(ctx);
    ScrollbarThemeBindings.register(ctx);
    ScrollbarThemeDataBindings.register(ctx);
    SearchAnchorBindings.register(ctx);
    SearchBarBindings.register(ctx);
    SearchBarThemeBindings.register(ctx);
    SearchBarThemeDataBindings.register(ctx);
    SearchControllerBindings.register(ctx);
    SearchDelegateBindings.register(ctx);
    SearchViewThemeBindings.register(ctx);
    SearchViewThemeDataBindings.register(ctx);
    SegmentedButtonBindings.register(ctx);
    SegmentedButtonStateBindings.register(ctx);
    SegmentedButtonThemeBindings.register(ctx);
    SegmentedButtonThemeDataBindings.register(ctx);
    SelectableChipAttributesBindings.register(ctx);
    SelectableTextBindings.register(ctx);
    SelectionAreaBindings.register(ctx);
    SelectionAreaStateBindings.register(ctx);
    ShapeBorderTweenBindings.register(ctx);
    ShowValueIndicatorBindings.register(ctx);
    SimpleDialogBindings.register(ctx);
    SimpleDialogOptionBindings.register(ctx);
    SliderBindings.register(ctx);
    SliderComponentShapeBindings.register(ctx);
    SliderInteractionBindings.register(ctx);
    SliderThemeBindings.register(ctx);
    SliderThemeDataBindings.register(ctx);
    SliderTickMarkShapeBindings.register(ctx);
    SliderTrackShapeBindings.register(ctx);
    SliverAppBarBindings.register(ctx);
    SnackBarBindings.register(ctx);
    SnackBarActionBindings.register(ctx);
    SnackBarBehaviorBindings.register(ctx);
    SnackBarClosedReasonBindings.register(ctx);
    SnackBarThemeDataBindings.register(ctx);
    SpellCheckSuggestionsToolbarBindings.register(ctx);
    SpellCheckSuggestionsToolbarLayoutDelegateBindings.register(ctx);
    StandardFabLocationBindings.register(ctx);
    StepBindings.register(ctx);
    StepStateBindings.register(ctx);
    StepStyleBindings.register(ctx);
    StepperBindings.register(ctx);
    StepperTypeBindings.register(ctx);
    StretchModeBindings.register(ctx);
    SubmenuButtonBindings.register(ctx);
    SwitchBindings.register(ctx);
    SwitchListTileBindings.register(ctx);
    SwitchThemeBindings.register(ctx);
    SwitchThemeDataBindings.register(ctx);
    TabBindings.register(ctx);
    TabAlignmentBindings.register(ctx);
    TabBarBindings.register(ctx);
    TabBarIndicatorSizeBindings.register(ctx);
    TabBarThemeBindings.register(ctx);
    TabBarThemeDataBindings.register(ctx);
    TabBarViewBindings.register(ctx);
    TabControllerBindings.register(ctx);
    TabIndicatorAnimationBindings.register(ctx);
    TabPageSelectorBindings.register(ctx);
    TabPageSelectorIndicatorBindings.register(ctx);
    TableRowInkWellBindings.register(ctx);
    TappableChipAttributesBindings.register(ctx);
    TextButtonBindings.register(ctx);
    TextButtonThemeBindings.register(ctx);
    TextButtonThemeDataBindings.register(ctx);
    TextFieldBindings.register(ctx);
    TextFormFieldBindings.register(ctx);
    TextMagnifierBindings.register(ctx);
    TextSelectionThemeBindings.register(ctx);
    TextSelectionThemeDataBindings.register(ctx);
    TextSelectionToolbarBindings.register(ctx);
    TextSelectionToolbarTextButtonBindings.register(ctx);
    TextThemeBindings.register(ctx);
    ThemeBindings.register(ctx);
    ThemeDataBindings.register(ctx);
    ThemeDataTweenBindings.register(ctx);
    ThemeExtensionBindings.register(ctx);
    ThemeModeBindings.register(ctx);
    ThumbBindings.register(ctx);
    TimeOfDayBindings.register(ctx);
    TimeOfDayFormatBindings.register(ctx);
    TimePickerDialogBindings.register(ctx);
    TimePickerEntryModeBindings.register(ctx);
    TimePickerThemeBindings.register(ctx);
    TimePickerThemeDataBindings.register(ctx);
    ToggleButtonsBindings.register(ctx);
    ToggleButtonsThemeBindings.register(ctx);
    ToggleButtonsThemeDataBindings.register(ctx);
    TooltipBindings.register(ctx);
    TooltipStateBindings.register(ctx);
    TooltipThemeBindings.register(ctx);
    TooltipThemeDataBindings.register(ctx);
    TooltipTriggerModeBindings.register(ctx);
    TooltipVisibilityBindings.register(ctx);
    TypographyBindings.register(ctx);
    UnderlineInputBorderBindings.register(ctx);
    UnderlineTabIndicatorBindings.register(ctx);
    UserAccountsDrawerHeaderBindings.register(ctx);
    VerticalDividerBindings.register(ctx);
    VisualDensityBindings.register(ctx);
    WidgetStateInputBorderBindings.register(ctx);
    YearPickerBindings.register(ctx);
    ZoomPageTransitionsBuilderBindings.register(ctx);
    MaterialTopLevelBindings.register(ctx);
  }
}
