// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7
// Generator: dartic_generator

// ignore_for_file: unused_import, unnecessary_import, implementation_imports

import 'package:dartic/dartic.dart';
import 'package:dartic/src/api/dartic_absent.dart';
import 'package:dartic/src/runtime/object.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'dart:ui';
import '../bindings/material_app_bindings.g.dart';
import '../bindings/scaffold_bindings.g.dart';
import '../bindings/app_bar_bindings.g.dart';
import '../bindings/elevated_button_bindings.g.dart';
import '../bindings/text_button_bindings.g.dart';
import '../bindings/floating_action_button_bindings.g.dart';
import '../bindings/card_bindings.g.dart';
import '../bindings/list_tile_bindings.g.dart';
import '../bindings/theme_data_bindings.g.dart';
import '../bindings/theme_bindings.g.dart';
import '../bindings/animated_theme_bindings.g.dart';
import '../bindings/color_scheme_bindings.g.dart';
import '../bindings/text_theme_bindings.g.dart';
import '../bindings/button_style_bindings.g.dart';
import '../bindings/input_decoration_bindings.g.dart';
import '../bindings/input_decoration_theme_bindings.g.dart';
import '../bindings/visual_density_bindings.g.dart';
import '../bindings/icon_theme_data_bindings.g.dart';
import '../bindings/input_border_bindings.g.dart';
import '../bindings/underline_input_border_bindings.g.dart';
import '../bindings/outline_input_border_bindings.g.dart';
import '../bindings/material_tap_target_size_bindings.g.dart';
import '../bindings/floating_label_behavior_bindings.g.dart';
import '../bindings/text_field_bindings.g.dart';
import '../bindings/checkbox_bindings.g.dart';
import '../bindings/switch_bindings.g.dart';
import '../bindings/slider_bindings.g.dart';
import '../bindings/dialog_bindings.g.dart';
import '../bindings/alert_dialog_bindings.g.dart';
import '../bindings/simple_dialog_bindings.g.dart';
import '../bindings/simple_dialog_option_bindings.g.dart';
import '../bindings/bottom_sheet_bindings.g.dart';
import '../bindings/drawer_bindings.g.dart';
import '../bindings/navigation_bar_bindings.g.dart';
import '../bindings/navigation_destination_bindings.g.dart';
import '../bindings/navigation_rail_bindings.g.dart';
import '../bindings/bottom_navigation_bar_bindings.g.dart';
import '../bindings/bottom_app_bar_bindings.g.dart';
import '../bindings/drawer_alignment_bindings.g.dart';
import '../bindings/navigation_destination_label_behavior_bindings.g.dart';
import '../bindings/snack_bar_closed_reason_bindings.g.dart';
import '../bindings/tab_bar_bindings.g.dart';
import '../bindings/tab_bar_view_bindings.g.dart';
import '../bindings/tab_bindings.g.dart';
import '../bindings/tab_page_selector_bindings.g.dart';
import '../bindings/tab_page_selector_indicator_bindings.g.dart';
import '../bindings/snack_bar_bindings.g.dart';
import '../bindings/snack_bar_action_bindings.g.dart';
import '../bindings/chip_bindings.g.dart';
import '../bindings/action_chip_bindings.g.dart';
import '../bindings/choice_chip_bindings.g.dart';
import '../bindings/filter_chip_bindings.g.dart';
import '../bindings/input_chip_bindings.g.dart';
import '../bindings/expansion_tile_bindings.g.dart';
import '../bindings/circle_avatar_bindings.g.dart';
import '../bindings/badge_bindings.g.dart';
import '../bindings/divider_bindings.g.dart';
import '../bindings/expand_icon_bindings.g.dart';
import '../bindings/linear_progress_indicator_bindings.g.dart';
import '../bindings/circular_progress_indicator_bindings.g.dart';
import '../bindings/refresh_progress_indicator_bindings.g.dart';
import '../bindings/grid_tile_bindings.g.dart';
import '../bindings/grid_tile_bar_bindings.g.dart';
import '../bindings/icon_button_bindings.g.dart';
import '../bindings/outlined_button_bindings.g.dart';
import '../bindings/filled_button_bindings.g.dart';
import '../bindings/material_page_route_bindings.g.dart';
import '../bindings/tab_bar_indicator_size_bindings.g.dart';
import '../bindings/tab_alignment_bindings.g.dart';

class MaterialPlugin extends DarticPlugin {
  @override
  String get name => 'package:flutter/material.dart';

  @override
  void register(DarticPluginContext ctx) {
    MaterialAppBindings.register(ctx);
    ScaffoldBindings.register(ctx);
    AppBarBindings.register(ctx);
    ElevatedButtonBindings.register(ctx);
    TextButtonBindings.register(ctx);
    FloatingActionButtonBindings.register(ctx);
    CardBindings.register(ctx);
    ListTileBindings.register(ctx);
    ThemeDataBindings.register(ctx);
    ThemeBindings.register(ctx);
    AnimatedThemeBindings.register(ctx);
    ColorSchemeBindings.register(ctx);
    TextThemeBindings.register(ctx);
    ButtonStyleBindings.register(ctx);
    InputDecorationBindings.register(ctx);
    InputDecorationThemeBindings.register(ctx);
    VisualDensityBindings.register(ctx);
    IconThemeDataBindings.register(ctx);
    InputBorderBindings.register(ctx);
    UnderlineInputBorderBindings.register(ctx);
    OutlineInputBorderBindings.register(ctx);
    MaterialTapTargetSizeBindings.register(ctx);
    FloatingLabelBehaviorBindings.register(ctx);
    TextFieldBindings.register(ctx);
    CheckboxBindings.register(ctx);
    SwitchBindings.register(ctx);
    SliderBindings.register(ctx);
    DialogBindings.register(ctx);
    AlertDialogBindings.register(ctx);
    SimpleDialogBindings.register(ctx);
    SimpleDialogOptionBindings.register(ctx);
    BottomSheetBindings.register(ctx);
    DrawerBindings.register(ctx);
    NavigationBarBindings.register(ctx);
    NavigationDestinationBindings.register(ctx);
    NavigationRailBindings.register(ctx);
    BottomNavigationBarBindings.register(ctx);
    BottomAppBarBindings.register(ctx);
    DrawerAlignmentBindings.register(ctx);
    NavigationDestinationLabelBehaviorBindings.register(ctx);
    SnackBarClosedReasonBindings.register(ctx);
    TabBarBindings.register(ctx);
    TabBarViewBindings.register(ctx);
    TabBindings.register(ctx);
    TabPageSelectorBindings.register(ctx);
    TabPageSelectorIndicatorBindings.register(ctx);
    SnackBarBindings.register(ctx);
    SnackBarActionBindings.register(ctx);
    ChipBindings.register(ctx);
    ActionChipBindings.register(ctx);
    ChoiceChipBindings.register(ctx);
    FilterChipBindings.register(ctx);
    InputChipBindings.register(ctx);
    ExpansionTileBindings.register(ctx);
    CircleAvatarBindings.register(ctx);
    BadgeBindings.register(ctx);
    DividerBindings.register(ctx);
    ExpandIconBindings.register(ctx);
    LinearProgressIndicatorBindings.register(ctx);
    CircularProgressIndicatorBindings.register(ctx);
    RefreshProgressIndicatorBindings.register(ctx);
    GridTileBindings.register(ctx);
    GridTileBarBindings.register(ctx);
    IconButtonBindings.register(ctx);
    OutlinedButtonBindings.register(ctx);
    FilledButtonBindings.register(ctx);
    MaterialPageRouteBindings.register(ctx);
    TabBarIndicatorSizeBindings.register(ctx);
    TabAlignmentBindings.register(ctx);
  }
}
