// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7
// Generator: dartic_generator

// ignore_for_file: unused_import, unnecessary_import, implementation_imports

import 'package:dartic/dartic.dart';
import '../bindings/painting/notched_shape_bindings.g.dart';
import '../bindings/painting/accumulator_bindings.g.dart';
import '../bindings/painting/alignment_bindings.g.dart';
import '../bindings/painting/alignment_directional_bindings.g.dart';
import '../bindings/painting/alignment_geometry_bindings.g.dart';
import '../bindings/painting/asset_bundle_image_key_bindings.g.dart';
import '../bindings/painting/asset_bundle_image_provider_bindings.g.dart';
import '../bindings/painting/asset_image_bindings.g.dart';
import '../bindings/painting/automatic_notched_shape_bindings.g.dart';
import '../bindings/painting/axis_bindings.g.dart';
import '../bindings/painting/axis_direction_bindings.g.dart';
import '../bindings/painting/beveled_rectangle_border_bindings.g.dart';
import '../bindings/painting/border_bindings.g.dart';
import '../bindings/painting/border_directional_bindings.g.dart';
import '../bindings/painting/border_radius_bindings.g.dart';
import '../bindings/painting/border_radius_directional_bindings.g.dart';
import '../bindings/painting/border_radius_geometry_bindings.g.dart';
import '../bindings/painting/border_side_bindings.g.dart';
import '../bindings/painting/border_style_bindings.g.dart';
import '../bindings/painting/box_border_bindings.g.dart';
import '../bindings/painting/box_decoration_bindings.g.dart';
import '../bindings/painting/box_fit_bindings.g.dart';
import '../bindings/painting/box_painter_bindings.g.dart';
import '../bindings/painting/box_shadow_bindings.g.dart';
import '../bindings/painting/box_shape_bindings.g.dart';
import '../bindings/painting/circle_border_bindings.g.dart';
import '../bindings/painting/circular_notched_rectangle_bindings.g.dart';
import '../bindings/painting/clip_context_bindings.g.dart';
import '../bindings/painting/color_property_bindings.g.dart';
import '../bindings/painting/color_swatch_bindings.g.dart';
import '../bindings/painting/continuous_rectangle_border_bindings.g.dart';
import '../bindings/painting/decoration_bindings.g.dart';
import '../bindings/painting/decoration_image_bindings.g.dart';
import '../bindings/painting/decoration_image_painter_bindings.g.dart';
import '../bindings/painting/edge_insets_bindings.g.dart';
import '../bindings/painting/edge_insets_directional_bindings.g.dart';
import '../bindings/painting/edge_insets_geometry_bindings.g.dart';
import '../bindings/painting/exact_asset_image_bindings.g.dart';
import '../bindings/painting/file_image_bindings.g.dart';
import '../bindings/painting/fitted_sizes_bindings.g.dart';
import '../bindings/painting/flutter_logo_decoration_bindings.g.dart';
import '../bindings/painting/flutter_logo_style_bindings.g.dart';
import '../bindings/painting/fractional_offset_bindings.g.dart';
import '../bindings/painting/gradient_bindings.g.dart';
import '../bindings/painting/gradient_rotation_bindings.g.dart';
import '../bindings/painting/gradient_transform_bindings.g.dart';
import '../bindings/painting/h_s_l_color_bindings.g.dart';
import '../bindings/painting/h_s_v_color_bindings.g.dart';
import '../bindings/painting/image_cache_bindings.g.dart';
import '../bindings/painting/image_cache_status_bindings.g.dart';
import '../bindings/painting/image_chunk_event_bindings.g.dart';
import '../bindings/painting/image_configuration_bindings.g.dart';
import '../bindings/painting/image_info_bindings.g.dart';
import '../bindings/painting/image_provider_bindings.g.dart';
import '../bindings/painting/image_repeat_bindings.g.dart';
import '../bindings/painting/image_size_info_bindings.g.dart';
import '../bindings/painting/image_stream_bindings.g.dart';
import '../bindings/painting/image_stream_completer_bindings.g.dart';
import '../bindings/painting/image_stream_completer_handle_bindings.g.dart';
import '../bindings/painting/image_stream_listener_bindings.g.dart';
import '../bindings/painting/inline_span_bindings.g.dart';
import '../bindings/painting/inline_span_semantics_information_bindings.g.dart';
import '../bindings/painting/linear_border_bindings.g.dart';
import '../bindings/painting/linear_border_edge_bindings.g.dart';
import '../bindings/painting/linear_gradient_bindings.g.dart';
import '../bindings/painting/matrix_utils_bindings.g.dart';
import '../bindings/painting/memory_image_bindings.g.dart';
import '../bindings/painting/multi_frame_image_stream_completer_bindings.g.dart';
import '../bindings/painting/network_image_load_exception_bindings.g.dart';
import '../bindings/painting/one_frame_image_stream_completer_bindings.g.dart';
import '../bindings/painting/outlined_border_bindings.g.dart';
import '../bindings/painting/oval_border_bindings.g.dart';
import '../bindings/painting/painting_binding_bindings.g.dart';
import '../bindings/painting/placeholder_dimensions_bindings.g.dart';
import '../bindings/painting/placeholder_span_bindings.g.dart';
import '../bindings/painting/radial_gradient_bindings.g.dart';
import '../bindings/painting/render_comparison_bindings.g.dart';
import '../bindings/painting/resize_image_bindings.g.dart';
import '../bindings/painting/resize_image_key_bindings.g.dart';
import '../bindings/painting/resize_image_policy_bindings.g.dart';
import '../bindings/painting/rounded_rectangle_border_bindings.g.dart';
import '../bindings/painting/rounded_superellipse_border_bindings.g.dart';
import '../bindings/painting/shader_warm_up_bindings.g.dart';
import '../bindings/painting/shape_border_bindings.g.dart';
import '../bindings/painting/shape_decoration_bindings.g.dart';
import '../bindings/painting/stadium_border_bindings.g.dart';
import '../bindings/painting/star_border_bindings.g.dart';
import '../bindings/painting/strut_style_bindings.g.dart';
import '../bindings/painting/sweep_gradient_bindings.g.dart';
import '../bindings/painting/text_align_vertical_bindings.g.dart';
import '../bindings/painting/text_overflow_bindings.g.dart';
import '../bindings/painting/text_painter_bindings.g.dart';
import '../bindings/painting/text_scaler_bindings.g.dart';
import '../bindings/painting/text_span_bindings.g.dart';
import '../bindings/painting/text_style_bindings.g.dart';
import '../bindings/painting/text_width_basis_bindings.g.dart';
import '../bindings/painting/transform_property_bindings.g.dart';
import '../bindings/painting/vertical_direction_bindings.g.dart';
import '../bindings/painting/web_html_element_strategy_bindings.g.dart';
import '../bindings/painting/web_image_info_bindings.g.dart';
import '../bindings/painting/word_boundary_bindings.g.dart';

class PaintingPlugin extends DarticPlugin {
  @override
  String get name => 'package:flutter/src/painting';

  @override
  void register(DarticPluginContext ctx) {
    NotchedShapeBindings.register(ctx);
    AccumulatorBindings.register(ctx);
    AlignmentBindings.register(ctx);
    AlignmentDirectionalBindings.register(ctx);
    AlignmentGeometryBindings.register(ctx);
    AssetBundleImageKeyBindings.register(ctx);
    AssetBundleImageProviderBindings.register(ctx);
    AssetImageBindings.register(ctx);
    AutomaticNotchedShapeBindings.register(ctx);
    AxisBindings.register(ctx);
    AxisDirectionBindings.register(ctx);
    BeveledRectangleBorderBindings.register(ctx);
    BorderBindings.register(ctx);
    BorderDirectionalBindings.register(ctx);
    BorderRadiusBindings.register(ctx);
    BorderRadiusDirectionalBindings.register(ctx);
    BorderRadiusGeometryBindings.register(ctx);
    BorderSideBindings.register(ctx);
    BorderStyleBindings.register(ctx);
    BoxBorderBindings.register(ctx);
    BoxDecorationBindings.register(ctx);
    BoxFitBindings.register(ctx);
    BoxPainterBindings.register(ctx);
    BoxShadowBindings.register(ctx);
    BoxShapeBindings.register(ctx);
    CircleBorderBindings.register(ctx);
    CircularNotchedRectangleBindings.register(ctx);
    ClipContextBindings.register(ctx);
    ColorPropertyBindings.register(ctx);
    ColorSwatchBindings.register(ctx);
    ContinuousRectangleBorderBindings.register(ctx);
    DecorationBindings.register(ctx);
    DecorationImageBindings.register(ctx);
    DecorationImagePainterBindings.register(ctx);
    EdgeInsetsBindings.register(ctx);
    EdgeInsetsDirectionalBindings.register(ctx);
    EdgeInsetsGeometryBindings.register(ctx);
    ExactAssetImageBindings.register(ctx);
    FileImageBindings.register(ctx);
    FittedSizesBindings.register(ctx);
    FlutterLogoDecorationBindings.register(ctx);
    FlutterLogoStyleBindings.register(ctx);
    FractionalOffsetBindings.register(ctx);
    GradientBindings.register(ctx);
    GradientRotationBindings.register(ctx);
    GradientTransformBindings.register(ctx);
    HSLColorBindings.register(ctx);
    HSVColorBindings.register(ctx);
    ImageCacheBindings.register(ctx);
    ImageCacheStatusBindings.register(ctx);
    ImageChunkEventBindings.register(ctx);
    ImageConfigurationBindings.register(ctx);
    ImageInfoBindings.register(ctx);
    ImageProviderBindings.register(ctx);
    ImageRepeatBindings.register(ctx);
    ImageSizeInfoBindings.register(ctx);
    ImageStreamBindings.register(ctx);
    ImageStreamCompleterBindings.register(ctx);
    ImageStreamCompleterHandleBindings.register(ctx);
    ImageStreamListenerBindings.register(ctx);
    InlineSpanBindings.register(ctx);
    InlineSpanSemanticsInformationBindings.register(ctx);
    LinearBorderBindings.register(ctx);
    LinearBorderEdgeBindings.register(ctx);
    LinearGradientBindings.register(ctx);
    MatrixUtilsBindings.register(ctx);
    MemoryImageBindings.register(ctx);
    MultiFrameImageStreamCompleterBindings.register(ctx);
    NetworkImageLoadExceptionBindings.register(ctx);
    OneFrameImageStreamCompleterBindings.register(ctx);
    OutlinedBorderBindings.register(ctx);
    OvalBorderBindings.register(ctx);
    PaintingBindingBindings.register(ctx);
    PlaceholderDimensionsBindings.register(ctx);
    PlaceholderSpanBindings.register(ctx);
    RadialGradientBindings.register(ctx);
    RenderComparisonBindings.register(ctx);
    ResizeImageBindings.register(ctx);
    ResizeImageKeyBindings.register(ctx);
    ResizeImagePolicyBindings.register(ctx);
    RoundedRectangleBorderBindings.register(ctx);
    RoundedSuperellipseBorderBindings.register(ctx);
    ShaderWarmUpBindings.register(ctx);
    ShapeBorderBindings.register(ctx);
    ShapeDecorationBindings.register(ctx);
    StadiumBorderBindings.register(ctx);
    StarBorderBindings.register(ctx);
    StrutStyleBindings.register(ctx);
    SweepGradientBindings.register(ctx);
    TextAlignVerticalBindings.register(ctx);
    TextOverflowBindings.register(ctx);
    TextPainterBindings.register(ctx);
    TextScalerBindings.register(ctx);
    TextSpanBindings.register(ctx);
    TextStyleBindings.register(ctx);
    TextWidthBasisBindings.register(ctx);
    TransformPropertyBindings.register(ctx);
    VerticalDirectionBindings.register(ctx);
    WebHtmlElementStrategyBindings.register(ctx);
    WebImageInfoBindings.register(ctx);
    WordBoundaryBindings.register(ctx);
  }
}
