// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7
// Generator: dartic_generator

// ignore_for_file: unused_import, unnecessary_import, implementation_imports

import 'package:dartic/dartic.dart';
import '../bindings/rendering/alignment_geometry_tween_bindings.g.dart';
import '../bindings/rendering/alignment_tween_bindings.g.dart';
import '../bindings/rendering/annotated_region_layer_bindings.g.dart';
import '../bindings/rendering/annotation_entry_bindings.g.dart';
import '../bindings/rendering/annotation_result_bindings.g.dart';
import '../bindings/rendering/backdrop_filter_layer_bindings.g.dart';
import '../bindings/rendering/backdrop_key_bindings.g.dart';
import '../bindings/rendering/box_constraints_bindings.g.dart';
import '../bindings/rendering/box_hit_test_entry_bindings.g.dart';
import '../bindings/rendering/box_hit_test_result_bindings.g.dart';
import '../bindings/rendering/box_parent_data_bindings.g.dart';
import '../bindings/rendering/cache_extent_style_bindings.g.dart';
import '../bindings/rendering/child_layout_helper_bindings.g.dart';
import '../bindings/rendering/clear_selection_event_bindings.g.dart';
import '../bindings/rendering/clip_path_layer_bindings.g.dart';
import '../bindings/rendering/clip_r_rect_layer_bindings.g.dart';
import '../bindings/rendering/clip_r_superellipse_layer_bindings.g.dart';
import '../bindings/rendering/clip_rect_layer_bindings.g.dart';
import '../bindings/rendering/color_filter_layer_bindings.g.dart';
import '../bindings/rendering/constraints_bindings.g.dart';
import '../bindings/rendering/container_box_parent_data_bindings.g.dart';
import '../bindings/rendering/container_layer_bindings.g.dart';
import '../bindings/rendering/container_parent_data_mixin_bindings.g.dart';
import '../bindings/rendering/container_render_object_mixin_bindings.g.dart';
import '../bindings/rendering/cross_axis_alignment_bindings.g.dart';
import '../bindings/rendering/custom_clipper_bindings.g.dart';
import '../bindings/rendering/custom_painter_bindings.g.dart';
import '../bindings/rendering/custom_painter_semantics_bindings.g.dart';
import '../bindings/rendering/debug_overflow_indicator_mixin_bindings.g.dart';
import '../bindings/rendering/decoration_position_bindings.g.dart';
import '../bindings/rendering/diagnostics_debug_creator_bindings.g.dart';
import '../bindings/rendering/directionally_extend_selection_event_bindings.g.dart';
import '../bindings/rendering/fixed_column_width_bindings.g.dart';
import '../bindings/rendering/flex_column_width_bindings.g.dart';
import '../bindings/rendering/flex_fit_bindings.g.dart';
import '../bindings/rendering/flex_parent_data_bindings.g.dart';
import '../bindings/rendering/floating_header_snap_configuration_bindings.g.dart';
import '../bindings/rendering/flow_delegate_bindings.g.dart';
import '../bindings/rendering/flow_painting_context_bindings.g.dart';
import '../bindings/rendering/flow_parent_data_bindings.g.dart';
import '../bindings/rendering/follower_layer_bindings.g.dart';
import '../bindings/rendering/fraction_column_width_bindings.g.dart';
import '../bindings/rendering/fractional_offset_tween_bindings.g.dart';
import '../bindings/rendering/granularly_extend_selection_event_bindings.g.dart';
import '../bindings/rendering/growth_direction_bindings.g.dart';
import '../bindings/rendering/hit_test_behavior_bindings.g.dart';
import '../bindings/rendering/image_filter_layer_bindings.g.dart';
import '../bindings/rendering/intrinsic_column_width_bindings.g.dart';
import '../bindings/rendering/keep_alive_parent_data_mixin_bindings.g.dart';
import '../bindings/rendering/layer_bindings.g.dart';
import '../bindings/rendering/layer_handle_bindings.g.dart';
import '../bindings/rendering/layer_link_bindings.g.dart';
import '../bindings/rendering/leader_layer_bindings.g.dart';
import '../bindings/rendering/list_body_parent_data_bindings.g.dart';
import '../bindings/rendering/list_wheel_child_manager_bindings.g.dart';
import '../bindings/rendering/list_wheel_parent_data_bindings.g.dart';
import '../bindings/rendering/main_axis_alignment_bindings.g.dart';
import '../bindings/rendering/main_axis_size_bindings.g.dart';
import '../bindings/rendering/max_column_width_bindings.g.dart';
import '../bindings/rendering/min_column_width_bindings.g.dart';
import '../bindings/rendering/mouse_tracker_bindings.g.dart';
import '../bindings/rendering/multi_child_layout_delegate_bindings.g.dart';
import '../bindings/rendering/multi_child_layout_parent_data_bindings.g.dart';
import '../bindings/rendering/offset_layer_bindings.g.dart';
import '../bindings/rendering/opacity_layer_bindings.g.dart';
import '../bindings/rendering/over_scroll_header_stretch_configuration_bindings.g.dart';
import '../bindings/rendering/overflow_box_fit_bindings.g.dart';
import '../bindings/rendering/painting_context_bindings.g.dart';
import '../bindings/rendering/parent_data_bindings.g.dart';
import '../bindings/rendering/performance_overlay_layer_bindings.g.dart';
import '../bindings/rendering/performance_overlay_option_bindings.g.dart';
import '../bindings/rendering/persistent_header_show_on_screen_configuration_bindings.g.dart';
import '../bindings/rendering/picture_layer_bindings.g.dart';
import '../bindings/rendering/pipeline_manifold_bindings.g.dart';
import '../bindings/rendering/pipeline_owner_bindings.g.dart';
import '../bindings/rendering/placeholder_span_index_semantics_tag_bindings.g.dart';
import '../bindings/rendering/platform_view_hit_test_behavior_bindings.g.dart';
import '../bindings/rendering/platform_view_layer_bindings.g.dart';
import '../bindings/rendering/platform_view_render_box_bindings.g.dart';
import '../bindings/rendering/relative_rect_bindings.g.dart';
import '../bindings/rendering/relayout_when_system_fonts_change_mixin_bindings.g.dart';
import '../bindings/rendering/render_absorb_pointer_bindings.g.dart';
import '../bindings/rendering/render_abstract_viewport_bindings.g.dart';
import '../bindings/rendering/render_aligning_shifted_box_bindings.g.dart';
import '../bindings/rendering/render_android_view_bindings.g.dart';
import '../bindings/rendering/render_animated_opacity_bindings.g.dart';
import '../bindings/rendering/render_animated_opacity_mixin_bindings.g.dart';
import '../bindings/rendering/render_animated_size_bindings.g.dart';
import '../bindings/rendering/render_animated_size_state_bindings.g.dart';
import '../bindings/rendering/render_annotated_region_bindings.g.dart';
import '../bindings/rendering/render_app_kit_view_bindings.g.dart';
import '../bindings/rendering/render_aspect_ratio_bindings.g.dart';
import '../bindings/rendering/render_backdrop_filter_bindings.g.dart';
import '../bindings/rendering/render_baseline_bindings.g.dart';
import '../bindings/rendering/render_block_semantics_bindings.g.dart';
import '../bindings/rendering/render_box_bindings.g.dart';
import '../bindings/rendering/render_box_container_defaults_mixin_bindings.g.dart';
import '../bindings/rendering/render_clip_oval_bindings.g.dart';
import '../bindings/rendering/render_clip_path_bindings.g.dart';
import '../bindings/rendering/render_clip_r_rect_bindings.g.dart';
import '../bindings/rendering/render_clip_r_superellipse_bindings.g.dart';
import '../bindings/rendering/render_clip_rect_bindings.g.dart';
import '../bindings/rendering/render_constrained_box_bindings.g.dart';
import '../bindings/rendering/render_constrained_overflow_box_bindings.g.dart';
import '../bindings/rendering/render_constraints_transform_box_bindings.g.dart';
import '../bindings/rendering/render_custom_multi_child_layout_box_bindings.g.dart';
import '../bindings/rendering/render_custom_paint_bindings.g.dart';
import '../bindings/rendering/render_custom_single_child_layout_box_bindings.g.dart';
import '../bindings/rendering/render_darwin_platform_view_bindings.g.dart';
import '../bindings/rendering/render_decorated_box_bindings.g.dart';
import '../bindings/rendering/render_decorated_sliver_bindings.g.dart';
import '../bindings/rendering/render_editable_bindings.g.dart';
import '../bindings/rendering/render_editable_painter_bindings.g.dart';
import '../bindings/rendering/render_error_box_bindings.g.dart';
import '../bindings/rendering/render_exclude_semantics_bindings.g.dart';
import '../bindings/rendering/render_fitted_box_bindings.g.dart';
import '../bindings/rendering/render_flex_bindings.g.dart';
import '../bindings/rendering/render_flow_bindings.g.dart';
import '../bindings/rendering/render_follower_layer_bindings.g.dart';
import '../bindings/rendering/render_fractional_translation_bindings.g.dart';
import '../bindings/rendering/render_fractionally_sized_overflow_box_bindings.g.dart';
import '../bindings/rendering/render_ignore_baseline_bindings.g.dart';
import '../bindings/rendering/render_ignore_pointer_bindings.g.dart';
import '../bindings/rendering/render_image_bindings.g.dart';
import '../bindings/rendering/render_indexed_semantics_bindings.g.dart';
import '../bindings/rendering/render_indexed_stack_bindings.g.dart';
import '../bindings/rendering/render_inline_children_container_defaults_bindings.g.dart';
import '../bindings/rendering/render_intrinsic_height_bindings.g.dart';
import '../bindings/rendering/render_intrinsic_width_bindings.g.dart';
import '../bindings/rendering/render_leader_layer_bindings.g.dart';
import '../bindings/rendering/render_limited_box_bindings.g.dart';
import '../bindings/rendering/render_list_body_bindings.g.dart';
import '../bindings/rendering/render_list_wheel_viewport_bindings.g.dart';
import '../bindings/rendering/render_merge_semantics_bindings.g.dart';
import '../bindings/rendering/render_meta_data_bindings.g.dart';
import '../bindings/rendering/render_mouse_region_bindings.g.dart';
import '../bindings/rendering/render_object_bindings.g.dart';
import '../bindings/rendering/render_object_with_child_mixin_bindings.g.dart';
import '../bindings/rendering/render_object_with_layout_callback_mixin_bindings.g.dart';
import '../bindings/rendering/render_offstage_bindings.g.dart';
import '../bindings/rendering/render_opacity_bindings.g.dart';
import '../bindings/rendering/render_padding_bindings.g.dart';
import '../bindings/rendering/render_paragraph_bindings.g.dart';
import '../bindings/rendering/render_performance_overlay_bindings.g.dart';
import '../bindings/rendering/render_physical_model_bindings.g.dart';
import '../bindings/rendering/render_physical_shape_bindings.g.dart';
import '../bindings/rendering/render_pointer_listener_bindings.g.dart';
import '../bindings/rendering/render_positioned_box_bindings.g.dart';
import '../bindings/rendering/render_proxy_box_bindings.g.dart';
import '../bindings/rendering/render_proxy_box_mixin_bindings.g.dart';
import '../bindings/rendering/render_proxy_box_with_hit_test_behavior_bindings.g.dart';
import '../bindings/rendering/render_proxy_sliver_bindings.g.dart';
import '../bindings/rendering/render_repaint_boundary_bindings.g.dart';
import '../bindings/rendering/render_rotated_box_bindings.g.dart';
import '../bindings/rendering/render_semantics_annotations_bindings.g.dart';
import '../bindings/rendering/render_semantics_gesture_handler_bindings.g.dart';
import '../bindings/rendering/render_shader_mask_bindings.g.dart';
import '../bindings/rendering/render_shifted_box_bindings.g.dart';
import '../bindings/rendering/render_shrink_wrapping_viewport_bindings.g.dart';
import '../bindings/rendering/render_sized_overflow_box_bindings.g.dart';
import '../bindings/rendering/render_sliver_bindings.g.dart';
import '../bindings/rendering/render_sliver_animated_opacity_bindings.g.dart';
import '../bindings/rendering/render_sliver_box_child_manager_bindings.g.dart';
import '../bindings/rendering/render_sliver_constrained_cross_axis_bindings.g.dart';
import '../bindings/rendering/render_sliver_cross_axis_group_bindings.g.dart';
import '../bindings/rendering/render_sliver_edge_insets_padding_bindings.g.dart';
import '../bindings/rendering/render_sliver_fill_remaining_bindings.g.dart';
import '../bindings/rendering/render_sliver_fill_remaining_and_overscroll_bindings.g.dart';
import '../bindings/rendering/render_sliver_fill_remaining_with_scrollable_bindings.g.dart';
import '../bindings/rendering/render_sliver_fill_viewport_bindings.g.dart';
import '../bindings/rendering/render_sliver_fixed_extent_box_adaptor_bindings.g.dart';
import '../bindings/rendering/render_sliver_fixed_extent_list_bindings.g.dart';
import '../bindings/rendering/render_sliver_floating_persistent_header_bindings.g.dart';
import '../bindings/rendering/render_sliver_floating_pinned_persistent_header_bindings.g.dart';
import '../bindings/rendering/render_sliver_grid_bindings.g.dart';
import '../bindings/rendering/render_sliver_helpers_bindings.g.dart';
import '../bindings/rendering/render_sliver_ignore_pointer_bindings.g.dart';
import '../bindings/rendering/render_sliver_list_bindings.g.dart';
import '../bindings/rendering/render_sliver_main_axis_group_bindings.g.dart';
import '../bindings/rendering/render_sliver_multi_box_adaptor_bindings.g.dart';
import '../bindings/rendering/render_sliver_offstage_bindings.g.dart';
import '../bindings/rendering/render_sliver_opacity_bindings.g.dart';
import '../bindings/rendering/render_sliver_padding_bindings.g.dart';
import '../bindings/rendering/render_sliver_persistent_header_bindings.g.dart';
import '../bindings/rendering/render_sliver_pinned_persistent_header_bindings.g.dart';
import '../bindings/rendering/render_sliver_scrolling_persistent_header_bindings.g.dart';
import '../bindings/rendering/render_sliver_semantics_annotations_bindings.g.dart';
import '../bindings/rendering/render_sliver_single_box_adapter_bindings.g.dart';
import '../bindings/rendering/render_sliver_to_box_adapter_bindings.g.dart';
import '../bindings/rendering/render_sliver_varied_extent_list_bindings.g.dart';
import '../bindings/rendering/render_sliver_with_keep_alive_mixin_bindings.g.dart';
import '../bindings/rendering/render_stack_bindings.g.dart';
import '../bindings/rendering/render_table_bindings.g.dart';
import '../bindings/rendering/render_transform_bindings.g.dart';
import '../bindings/rendering/render_tree_sliver_bindings.g.dart';
import '../bindings/rendering/render_ui_kit_view_bindings.g.dart';
import '../bindings/rendering/render_view_bindings.g.dart';
import '../bindings/rendering/render_viewport_bindings.g.dart';
import '../bindings/rendering/render_viewport_base_bindings.g.dart';
import '../bindings/rendering/render_wrap_bindings.g.dart';
import '../bindings/rendering/renderer_binding_bindings.g.dart';
import '../bindings/rendering/rendering_flutter_binding_bindings.g.dart';
import '../bindings/rendering/rendering_service_extensions_bindings.g.dart';
import '../bindings/rendering/revealed_offset_bindings.g.dart';
import '../bindings/rendering/scroll_direction_bindings.g.dart';
import '../bindings/rendering/select_all_selection_event_bindings.g.dart';
import '../bindings/rendering/select_paragraph_selection_event_bindings.g.dart';
import '../bindings/rendering/select_word_selection_event_bindings.g.dart';
import '../bindings/rendering/selectable_bindings.g.dart';
import '../bindings/rendering/selected_content_bindings.g.dart';
import '../bindings/rendering/selected_content_range_bindings.g.dart';
import '../bindings/rendering/selection_edge_update_event_bindings.g.dart';
import '../bindings/rendering/selection_event_bindings.g.dart';
import '../bindings/rendering/selection_event_type_bindings.g.dart';
import '../bindings/rendering/selection_extend_direction_bindings.g.dart';
import '../bindings/rendering/selection_geometry_bindings.g.dart';
import '../bindings/rendering/selection_handler_bindings.g.dart';
import '../bindings/rendering/selection_point_bindings.g.dart';
import '../bindings/rendering/selection_registrant_bindings.g.dart';
import '../bindings/rendering/selection_registrar_bindings.g.dart';
import '../bindings/rendering/selection_result_bindings.g.dart';
import '../bindings/rendering/selection_status_bindings.g.dart';
import '../bindings/rendering/selection_utils_bindings.g.dart';
import '../bindings/rendering/semantics_annotations_mixin_bindings.g.dart';
import '../bindings/rendering/shader_mask_layer_bindings.g.dart';
import '../bindings/rendering/shape_border_clipper_bindings.g.dart';
import '../bindings/rendering/single_child_layout_delegate_bindings.g.dart';
import '../bindings/rendering/sliver_constraints_bindings.g.dart';
import '../bindings/rendering/sliver_geometry_bindings.g.dart';
import '../bindings/rendering/sliver_grid_delegate_bindings.g.dart';
import '../bindings/rendering/sliver_grid_delegate_with_fixed_cross_axis_count_bindings.g.dart';
import '../bindings/rendering/sliver_grid_delegate_with_max_cross_axis_extent_bindings.g.dart';
import '../bindings/rendering/sliver_grid_geometry_bindings.g.dart';
import '../bindings/rendering/sliver_grid_layout_bindings.g.dart';
import '../bindings/rendering/sliver_grid_parent_data_bindings.g.dart';
import '../bindings/rendering/sliver_grid_regular_tile_layout_bindings.g.dart';
import '../bindings/rendering/sliver_hit_test_entry_bindings.g.dart';
import '../bindings/rendering/sliver_hit_test_result_bindings.g.dart';
import '../bindings/rendering/sliver_layout_dimensions_bindings.g.dart';
import '../bindings/rendering/sliver_logical_container_parent_data_bindings.g.dart';
import '../bindings/rendering/sliver_logical_parent_data_bindings.g.dart';
import '../bindings/rendering/sliver_multi_box_adaptor_parent_data_bindings.g.dart';
import '../bindings/rendering/sliver_paint_order_bindings.g.dart';
import '../bindings/rendering/sliver_physical_container_parent_data_bindings.g.dart';
import '../bindings/rendering/sliver_physical_parent_data_bindings.g.dart';
import '../bindings/rendering/stack_fit_bindings.g.dart';
import '../bindings/rendering/stack_parent_data_bindings.g.dart';
import '../bindings/rendering/table_border_bindings.g.dart';
import '../bindings/rendering/table_cell_parent_data_bindings.g.dart';
import '../bindings/rendering/table_cell_vertical_alignment_bindings.g.dart';
import '../bindings/rendering/table_column_width_bindings.g.dart';
import '../bindings/rendering/text_granularity_bindings.g.dart';
import '../bindings/rendering/text_parent_data_bindings.g.dart';
import '../bindings/rendering/text_selection_handle_type_bindings.g.dart';
import '../bindings/rendering/text_selection_point_bindings.g.dart';
import '../bindings/rendering/texture_box_bindings.g.dart';
import '../bindings/rendering/texture_layer_bindings.g.dart';
import '../bindings/rendering/transform_layer_bindings.g.dart';
import '../bindings/rendering/tree_sliver_indentation_type_bindings.g.dart';
import '../bindings/rendering/tree_sliver_node_parent_data_bindings.g.dart';
import '../bindings/rendering/vertical_caret_movement_run_bindings.g.dart';
import '../bindings/rendering/view_configuration_bindings.g.dart';
import '../bindings/rendering/viewport_offset_bindings.g.dart';
import '../bindings/rendering/wrap_alignment_bindings.g.dart';
import '../bindings/rendering/wrap_cross_alignment_bindings.g.dart';
import '../bindings/rendering/wrap_parent_data_bindings.g.dart';
import '../bindings/rendering/rendering_top_level_bindings.g.dart';

class RenderingPlugin extends DarticPlugin {
  @override
  String get name => 'package:flutter/src/rendering';

  @override
  void register(DarticPluginContext ctx) {
    AlignmentGeometryTweenBindings.register(ctx);
    AlignmentTweenBindings.register(ctx);
    AnnotatedRegionLayerBindings.register(ctx);
    AnnotationEntryBindings.register(ctx);
    AnnotationResultBindings.register(ctx);
    BackdropFilterLayerBindings.register(ctx);
    BackdropKeyBindings.register(ctx);
    BoxConstraintsBindings.register(ctx);
    BoxHitTestEntryBindings.register(ctx);
    BoxHitTestResultBindings.register(ctx);
    BoxParentDataBindings.register(ctx);
    CacheExtentStyleBindings.register(ctx);
    ChildLayoutHelperBindings.register(ctx);
    ClearSelectionEventBindings.register(ctx);
    ClipPathLayerBindings.register(ctx);
    ClipRRectLayerBindings.register(ctx);
    ClipRSuperellipseLayerBindings.register(ctx);
    ClipRectLayerBindings.register(ctx);
    ColorFilterLayerBindings.register(ctx);
    ConstraintsBindings.register(ctx);
    ContainerBoxParentDataBindings.register(ctx);
    ContainerLayerBindings.register(ctx);
    ContainerParentDataMixinBindings.register(ctx);
    ContainerRenderObjectMixinBindings.register(ctx);
    CrossAxisAlignmentBindings.register(ctx);
    CustomClipperBindings.register(ctx);
    CustomPainterBindings.register(ctx);
    CustomPainterSemanticsBindings.register(ctx);
    DebugOverflowIndicatorMixinBindings.register(ctx);
    DecorationPositionBindings.register(ctx);
    DiagnosticsDebugCreatorBindings.register(ctx);
    DirectionallyExtendSelectionEventBindings.register(ctx);
    FixedColumnWidthBindings.register(ctx);
    FlexColumnWidthBindings.register(ctx);
    FlexFitBindings.register(ctx);
    FlexParentDataBindings.register(ctx);
    FloatingHeaderSnapConfigurationBindings.register(ctx);
    FlowDelegateBindings.register(ctx);
    FlowPaintingContextBindings.register(ctx);
    FlowParentDataBindings.register(ctx);
    FollowerLayerBindings.register(ctx);
    FractionColumnWidthBindings.register(ctx);
    FractionalOffsetTweenBindings.register(ctx);
    GranularlyExtendSelectionEventBindings.register(ctx);
    GrowthDirectionBindings.register(ctx);
    HitTestBehaviorBindings.register(ctx);
    ImageFilterLayerBindings.register(ctx);
    IntrinsicColumnWidthBindings.register(ctx);
    KeepAliveParentDataMixinBindings.register(ctx);
    LayerBindings.register(ctx);
    LayerHandleBindings.register(ctx);
    LayerLinkBindings.register(ctx);
    LeaderLayerBindings.register(ctx);
    ListBodyParentDataBindings.register(ctx);
    ListWheelChildManagerBindings.register(ctx);
    ListWheelParentDataBindings.register(ctx);
    MainAxisAlignmentBindings.register(ctx);
    MainAxisSizeBindings.register(ctx);
    MaxColumnWidthBindings.register(ctx);
    MinColumnWidthBindings.register(ctx);
    MouseTrackerBindings.register(ctx);
    MultiChildLayoutDelegateBindings.register(ctx);
    MultiChildLayoutParentDataBindings.register(ctx);
    OffsetLayerBindings.register(ctx);
    OpacityLayerBindings.register(ctx);
    OverScrollHeaderStretchConfigurationBindings.register(ctx);
    OverflowBoxFitBindings.register(ctx);
    PaintingContextBindings.register(ctx);
    ParentDataBindings.register(ctx);
    PerformanceOverlayLayerBindings.register(ctx);
    PerformanceOverlayOptionBindings.register(ctx);
    PersistentHeaderShowOnScreenConfigurationBindings.register(ctx);
    PictureLayerBindings.register(ctx);
    PipelineManifoldBindings.register(ctx);
    PipelineOwnerBindings.register(ctx);
    PlaceholderSpanIndexSemanticsTagBindings.register(ctx);
    PlatformViewHitTestBehaviorBindings.register(ctx);
    PlatformViewLayerBindings.register(ctx);
    PlatformViewRenderBoxBindings.register(ctx);
    RelativeRectBindings.register(ctx);
    RelayoutWhenSystemFontsChangeMixinBindings.register(ctx);
    RenderAbsorbPointerBindings.register(ctx);
    RenderAbstractViewportBindings.register(ctx);
    RenderAligningShiftedBoxBindings.register(ctx);
    RenderAndroidViewBindings.register(ctx);
    RenderAnimatedOpacityBindings.register(ctx);
    RenderAnimatedOpacityMixinBindings.register(ctx);
    RenderAnimatedSizeBindings.register(ctx);
    RenderAnimatedSizeStateBindings.register(ctx);
    RenderAnnotatedRegionBindings.register(ctx);
    RenderAppKitViewBindings.register(ctx);
    RenderAspectRatioBindings.register(ctx);
    RenderBackdropFilterBindings.register(ctx);
    RenderBaselineBindings.register(ctx);
    RenderBlockSemanticsBindings.register(ctx);
    RenderBoxBindings.register(ctx);
    RenderBoxContainerDefaultsMixinBindings.register(ctx);
    RenderClipOvalBindings.register(ctx);
    RenderClipPathBindings.register(ctx);
    RenderClipRRectBindings.register(ctx);
    RenderClipRSuperellipseBindings.register(ctx);
    RenderClipRectBindings.register(ctx);
    RenderConstrainedBoxBindings.register(ctx);
    RenderConstrainedOverflowBoxBindings.register(ctx);
    RenderConstraintsTransformBoxBindings.register(ctx);
    RenderCustomMultiChildLayoutBoxBindings.register(ctx);
    RenderCustomPaintBindings.register(ctx);
    RenderCustomSingleChildLayoutBoxBindings.register(ctx);
    RenderDarwinPlatformViewBindings.register(ctx);
    RenderDecoratedBoxBindings.register(ctx);
    RenderDecoratedSliverBindings.register(ctx);
    RenderEditableBindings.register(ctx);
    RenderEditablePainterBindings.register(ctx);
    RenderErrorBoxBindings.register(ctx);
    RenderExcludeSemanticsBindings.register(ctx);
    RenderFittedBoxBindings.register(ctx);
    RenderFlexBindings.register(ctx);
    RenderFlowBindings.register(ctx);
    RenderFollowerLayerBindings.register(ctx);
    RenderFractionalTranslationBindings.register(ctx);
    RenderFractionallySizedOverflowBoxBindings.register(ctx);
    RenderIgnoreBaselineBindings.register(ctx);
    RenderIgnorePointerBindings.register(ctx);
    RenderImageBindings.register(ctx);
    RenderIndexedSemanticsBindings.register(ctx);
    RenderIndexedStackBindings.register(ctx);
    RenderInlineChildrenContainerDefaultsBindings.register(ctx);
    RenderIntrinsicHeightBindings.register(ctx);
    RenderIntrinsicWidthBindings.register(ctx);
    RenderLeaderLayerBindings.register(ctx);
    RenderLimitedBoxBindings.register(ctx);
    RenderListBodyBindings.register(ctx);
    RenderListWheelViewportBindings.register(ctx);
    RenderMergeSemanticsBindings.register(ctx);
    RenderMetaDataBindings.register(ctx);
    RenderMouseRegionBindings.register(ctx);
    RenderObjectBindings.register(ctx);
    RenderObjectWithChildMixinBindings.register(ctx);
    RenderObjectWithLayoutCallbackMixinBindings.register(ctx);
    RenderOffstageBindings.register(ctx);
    RenderOpacityBindings.register(ctx);
    RenderPaddingBindings.register(ctx);
    RenderParagraphBindings.register(ctx);
    RenderPerformanceOverlayBindings.register(ctx);
    RenderPhysicalModelBindings.register(ctx);
    RenderPhysicalShapeBindings.register(ctx);
    RenderPointerListenerBindings.register(ctx);
    RenderPositionedBoxBindings.register(ctx);
    RenderProxyBoxBindings.register(ctx);
    RenderProxyBoxMixinBindings.register(ctx);
    RenderProxyBoxWithHitTestBehaviorBindings.register(ctx);
    RenderProxySliverBindings.register(ctx);
    RenderRepaintBoundaryBindings.register(ctx);
    RenderRotatedBoxBindings.register(ctx);
    RenderSemanticsAnnotationsBindings.register(ctx);
    RenderSemanticsGestureHandlerBindings.register(ctx);
    RenderShaderMaskBindings.register(ctx);
    RenderShiftedBoxBindings.register(ctx);
    RenderShrinkWrappingViewportBindings.register(ctx);
    RenderSizedOverflowBoxBindings.register(ctx);
    RenderSliverBindings.register(ctx);
    RenderSliverAnimatedOpacityBindings.register(ctx);
    RenderSliverBoxChildManagerBindings.register(ctx);
    RenderSliverConstrainedCrossAxisBindings.register(ctx);
    RenderSliverCrossAxisGroupBindings.register(ctx);
    RenderSliverEdgeInsetsPaddingBindings.register(ctx);
    RenderSliverFillRemainingBindings.register(ctx);
    RenderSliverFillRemainingAndOverscrollBindings.register(ctx);
    RenderSliverFillRemainingWithScrollableBindings.register(ctx);
    RenderSliverFillViewportBindings.register(ctx);
    RenderSliverFixedExtentBoxAdaptorBindings.register(ctx);
    RenderSliverFixedExtentListBindings.register(ctx);
    RenderSliverFloatingPersistentHeaderBindings.register(ctx);
    RenderSliverFloatingPinnedPersistentHeaderBindings.register(ctx);
    RenderSliverGridBindings.register(ctx);
    RenderSliverHelpersBindings.register(ctx);
    RenderSliverIgnorePointerBindings.register(ctx);
    RenderSliverListBindings.register(ctx);
    RenderSliverMainAxisGroupBindings.register(ctx);
    RenderSliverMultiBoxAdaptorBindings.register(ctx);
    RenderSliverOffstageBindings.register(ctx);
    RenderSliverOpacityBindings.register(ctx);
    RenderSliverPaddingBindings.register(ctx);
    RenderSliverPersistentHeaderBindings.register(ctx);
    RenderSliverPinnedPersistentHeaderBindings.register(ctx);
    RenderSliverScrollingPersistentHeaderBindings.register(ctx);
    RenderSliverSemanticsAnnotationsBindings.register(ctx);
    RenderSliverSingleBoxAdapterBindings.register(ctx);
    RenderSliverToBoxAdapterBindings.register(ctx);
    RenderSliverVariedExtentListBindings.register(ctx);
    RenderSliverWithKeepAliveMixinBindings.register(ctx);
    RenderStackBindings.register(ctx);
    RenderTableBindings.register(ctx);
    RenderTransformBindings.register(ctx);
    RenderTreeSliverBindings.register(ctx);
    RenderUiKitViewBindings.register(ctx);
    RenderViewBindings.register(ctx);
    RenderViewportBindings.register(ctx);
    RenderViewportBaseBindings.register(ctx);
    RenderWrapBindings.register(ctx);
    RendererBindingBindings.register(ctx);
    RenderingFlutterBindingBindings.register(ctx);
    RenderingServiceExtensionsBindings.register(ctx);
    RevealedOffsetBindings.register(ctx);
    ScrollDirectionBindings.register(ctx);
    SelectAllSelectionEventBindings.register(ctx);
    SelectParagraphSelectionEventBindings.register(ctx);
    SelectWordSelectionEventBindings.register(ctx);
    SelectableBindings.register(ctx);
    SelectedContentBindings.register(ctx);
    SelectedContentRangeBindings.register(ctx);
    SelectionEdgeUpdateEventBindings.register(ctx);
    SelectionEventBindings.register(ctx);
    SelectionEventTypeBindings.register(ctx);
    SelectionExtendDirectionBindings.register(ctx);
    SelectionGeometryBindings.register(ctx);
    SelectionHandlerBindings.register(ctx);
    SelectionPointBindings.register(ctx);
    SelectionRegistrantBindings.register(ctx);
    SelectionRegistrarBindings.register(ctx);
    SelectionResultBindings.register(ctx);
    SelectionStatusBindings.register(ctx);
    SelectionUtilsBindings.register(ctx);
    SemanticsAnnotationsMixinBindings.register(ctx);
    ShaderMaskLayerBindings.register(ctx);
    ShapeBorderClipperBindings.register(ctx);
    SingleChildLayoutDelegateBindings.register(ctx);
    SliverConstraintsBindings.register(ctx);
    SliverGeometryBindings.register(ctx);
    SliverGridDelegateBindings.register(ctx);
    SliverGridDelegateWithFixedCrossAxisCountBindings.register(ctx);
    SliverGridDelegateWithMaxCrossAxisExtentBindings.register(ctx);
    SliverGridGeometryBindings.register(ctx);
    SliverGridLayoutBindings.register(ctx);
    SliverGridParentDataBindings.register(ctx);
    SliverGridRegularTileLayoutBindings.register(ctx);
    SliverHitTestEntryBindings.register(ctx);
    SliverHitTestResultBindings.register(ctx);
    SliverLayoutDimensionsBindings.register(ctx);
    SliverLogicalContainerParentDataBindings.register(ctx);
    SliverLogicalParentDataBindings.register(ctx);
    SliverMultiBoxAdaptorParentDataBindings.register(ctx);
    SliverPaintOrderBindings.register(ctx);
    SliverPhysicalContainerParentDataBindings.register(ctx);
    SliverPhysicalParentDataBindings.register(ctx);
    StackFitBindings.register(ctx);
    StackParentDataBindings.register(ctx);
    TableBorderBindings.register(ctx);
    TableCellParentDataBindings.register(ctx);
    TableCellVerticalAlignmentBindings.register(ctx);
    TableColumnWidthBindings.register(ctx);
    TextGranularityBindings.register(ctx);
    TextParentDataBindings.register(ctx);
    TextSelectionHandleTypeBindings.register(ctx);
    TextSelectionPointBindings.register(ctx);
    TextureBoxBindings.register(ctx);
    TextureLayerBindings.register(ctx);
    TransformLayerBindings.register(ctx);
    TreeSliverIndentationTypeBindings.register(ctx);
    TreeSliverNodeParentDataBindings.register(ctx);
    VerticalCaretMovementRunBindings.register(ctx);
    ViewConfigurationBindings.register(ctx);
    ViewportOffsetBindings.register(ctx);
    WrapAlignmentBindings.register(ctx);
    WrapCrossAlignmentBindings.register(ctx);
    WrapParentDataBindings.register(ctx);
    RenderingTopLevelBindings.register(ctx);
  }
}
