// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7
// Generator: dartic_generator

// ignore_for_file: unused_import, unnecessary_import, implementation_imports

import 'package:dartic/dartic.dart';
import '../bindings/services/android_motion_event_bindings.g.dart';
import '../bindings/services/android_pointer_coords_bindings.g.dart';
import '../bindings/services/android_pointer_properties_bindings.g.dart';
import '../bindings/services/android_view_controller_bindings.g.dart';
import '../bindings/services/app_kit_view_controller_bindings.g.dart';
import '../bindings/services/application_switcher_description_bindings.g.dart';
import '../bindings/services/asset_bundle_bindings.g.dart';
import '../bindings/services/asset_manifest_bindings.g.dart';
import '../bindings/services/asset_metadata_bindings.g.dart';
import '../bindings/services/autofill_client_bindings.g.dart';
import '../bindings/services/autofill_configuration_bindings.g.dart';
import '../bindings/services/autofill_hints_bindings.g.dart';
import '../bindings/services/autofill_scope_bindings.g.dart';
import '../bindings/services/autofill_scope_mixin_bindings.g.dart';
import '../bindings/services/background_isolate_binary_messenger_bindings.g.dart';
import '../bindings/services/basic_message_channel_bindings.g.dart';
import '../bindings/services/binary_codec_bindings.g.dart';
import '../bindings/services/binary_messenger_bindings.g.dart';
import '../bindings/services/browser_context_menu_bindings.g.dart';
import '../bindings/services/caching_asset_bundle_bindings.g.dart';
import '../bindings/services/character_boundary_bindings.g.dart';
import '../bindings/services/clipboard_bindings.g.dart';
import '../bindings/services/clipboard_data_bindings.g.dart';
import '../bindings/services/content_sensitivity_bindings.g.dart';
import '../bindings/services/darwin_platform_view_controller_bindings.g.dart';
import '../bindings/services/default_process_text_service_bindings.g.dart';
import '../bindings/services/default_spell_check_service_bindings.g.dart';
import '../bindings/services/deferred_component_bindings.g.dart';
import '../bindings/services/delta_text_input_client_bindings.g.dart';
import '../bindings/services/device_orientation_bindings.g.dart';
import '../bindings/services/document_boundary_bindings.g.dart';
import '../bindings/services/event_channel_bindings.g.dart';
import '../bindings/services/expensive_android_view_controller_bindings.g.dart';
import '../bindings/services/filtering_text_input_formatter_bindings.g.dart';
import '../bindings/services/floating_cursor_drag_state_bindings.g.dart';
import '../bindings/services/flutter_version_bindings.g.dart';
import '../bindings/services/font_loader_bindings.g.dart';
import '../bindings/services/g_l_f_w_key_helper_bindings.g.dart';
import '../bindings/services/gtk_key_helper_bindings.g.dart';
import '../bindings/services/haptic_feedback_bindings.g.dart';
import '../bindings/services/hardware_keyboard_bindings.g.dart';
import '../bindings/services/hybrid_android_view_controller_bindings.g.dart';
import '../bindings/services/i_o_s_system_context_menu_item_data_bindings.g.dart';
import '../bindings/services/i_o_s_system_context_menu_item_data_copy_bindings.g.dart';
import '../bindings/services/i_o_s_system_context_menu_item_data_custom_bindings.g.dart';
import '../bindings/services/i_o_s_system_context_menu_item_data_cut_bindings.g.dart';
import '../bindings/services/i_o_s_system_context_menu_item_data_live_text_bindings.g.dart';
import '../bindings/services/i_o_s_system_context_menu_item_data_look_up_bindings.g.dart';
import '../bindings/services/i_o_s_system_context_menu_item_data_paste_bindings.g.dart';
import '../bindings/services/i_o_s_system_context_menu_item_data_search_web_bindings.g.dart';
import '../bindings/services/i_o_s_system_context_menu_item_data_select_all_bindings.g.dart';
import '../bindings/services/i_o_s_system_context_menu_item_data_share_bindings.g.dart';
import '../bindings/services/j_s_o_n_message_codec_bindings.g.dart';
import '../bindings/services/j_s_o_n_method_codec_bindings.g.dart';
import '../bindings/services/key_data_transit_mode_bindings.g.dart';
import '../bindings/services/key_down_event_bindings.g.dart';
import '../bindings/services/key_event_bindings.g.dart';
import '../bindings/services/key_event_manager_bindings.g.dart';
import '../bindings/services/key_helper_bindings.g.dart';
import '../bindings/services/key_message_bindings.g.dart';
import '../bindings/services/key_repeat_event_bindings.g.dart';
import '../bindings/services/key_up_event_bindings.g.dart';
import '../bindings/services/keyboard_inserted_content_bindings.g.dart';
import '../bindings/services/keyboard_key_bindings.g.dart';
import '../bindings/services/keyboard_lock_mode_bindings.g.dart';
import '../bindings/services/keyboard_side_bindings.g.dart';
import '../bindings/services/length_limiting_text_input_formatter_bindings.g.dart';
import '../bindings/services/line_boundary_bindings.g.dart';
import '../bindings/services/live_text_bindings.g.dart';
import '../bindings/services/logical_keyboard_key_bindings.g.dart';
import '../bindings/services/max_length_enforcement_bindings.g.dart';
import '../bindings/services/message_codec_bindings.g.dart';
import '../bindings/services/method_call_bindings.g.dart';
import '../bindings/services/method_channel_bindings.g.dart';
import '../bindings/services/method_codec_bindings.g.dart';
import '../bindings/services/missing_plugin_exception_bindings.g.dart';
import '../bindings/services/modifier_key_bindings.g.dart';
import '../bindings/services/mouse_cursor_bindings.g.dart';
import '../bindings/services/mouse_cursor_manager_bindings.g.dart';
import '../bindings/services/mouse_cursor_session_bindings.g.dart';
import '../bindings/services/mouse_tracker_annotation_bindings.g.dart';
import '../bindings/services/network_asset_bundle_bindings.g.dart';
import '../bindings/services/optional_method_channel_bindings.g.dart';
import '../bindings/services/paragraph_boundary_bindings.g.dart';
import '../bindings/services/physical_keyboard_key_bindings.g.dart';
import '../bindings/services/platform_asset_bundle_bindings.g.dart';
import '../bindings/services/platform_exception_bindings.g.dart';
import '../bindings/services/platform_view_controller_bindings.g.dart';
import '../bindings/services/platform_views_registry_bindings.g.dart';
import '../bindings/services/platform_views_service_bindings.g.dart';
import '../bindings/services/predictive_back_event_bindings.g.dart';
import '../bindings/services/process_text_action_bindings.g.dart';
import '../bindings/services/process_text_service_bindings.g.dart';
import '../bindings/services/raw_floating_cursor_point_bindings.g.dart';
import '../bindings/services/raw_key_down_event_bindings.g.dart';
import '../bindings/services/raw_key_event_bindings.g.dart';
import '../bindings/services/raw_key_event_data_bindings.g.dart';
import '../bindings/services/raw_key_event_data_android_bindings.g.dart';
import '../bindings/services/raw_key_event_data_fuchsia_bindings.g.dart';
import '../bindings/services/raw_key_event_data_ios_bindings.g.dart';
import '../bindings/services/raw_key_event_data_linux_bindings.g.dart';
import '../bindings/services/raw_key_event_data_mac_os_bindings.g.dart';
import '../bindings/services/raw_key_event_data_web_bindings.g.dart';
import '../bindings/services/raw_key_event_data_windows_bindings.g.dart';
import '../bindings/services/raw_key_up_event_bindings.g.dart';
import '../bindings/services/raw_keyboard_bindings.g.dart';
import '../bindings/services/restoration_bucket_bindings.g.dart';
import '../bindings/services/restoration_manager_bindings.g.dart';
import '../bindings/services/scribble_client_bindings.g.dart';
import '../bindings/services/scribe_bindings.g.dart';
import '../bindings/services/selection_changed_cause_bindings.g.dart';
import '../bindings/services/selection_rect_bindings.g.dart';
import '../bindings/services/sensitive_content_service_bindings.g.dart';
import '../bindings/services/services_binding_bindings.g.dart';
import '../bindings/services/services_service_extensions_bindings.g.dart';
import '../bindings/services/smart_dashes_type_bindings.g.dart';
import '../bindings/services/smart_quotes_type_bindings.g.dart';
import '../bindings/services/spell_check_results_bindings.g.dart';
import '../bindings/services/spell_check_service_bindings.g.dart';
import '../bindings/services/standard_message_codec_bindings.g.dart';
import '../bindings/services/standard_method_codec_bindings.g.dart';
import '../bindings/services/string_codec_bindings.g.dart';
import '../bindings/services/suggestion_span_bindings.g.dart';
import '../bindings/services/surface_android_view_controller_bindings.g.dart';
import '../bindings/services/swipe_edge_bindings.g.dart';
import '../bindings/services/system_channels_bindings.g.dart';
import '../bindings/services/system_chrome_bindings.g.dart';
import '../bindings/services/system_context_menu_client_bindings.g.dart';
import '../bindings/services/system_context_menu_controller_bindings.g.dart';
import '../bindings/services/system_mouse_cursor_bindings.g.dart';
import '../bindings/services/system_mouse_cursors_bindings.g.dart';
import '../bindings/services/system_navigator_bindings.g.dart';
import '../bindings/services/system_sound_bindings.g.dart';
import '../bindings/services/system_sound_type_bindings.g.dart';
import '../bindings/services/system_ui_mode_bindings.g.dart';
import '../bindings/services/system_ui_overlay_bindings.g.dart';
import '../bindings/services/system_ui_overlay_style_bindings.g.dart';
import '../bindings/services/text_boundary_bindings.g.dart';
import '../bindings/services/text_capitalization_bindings.g.dart';
import '../bindings/services/text_editing_delta_bindings.g.dart';
import '../bindings/services/text_editing_delta_deletion_bindings.g.dart';
import '../bindings/services/text_editing_delta_insertion_bindings.g.dart';
import '../bindings/services/text_editing_delta_non_text_update_bindings.g.dart';
import '../bindings/services/text_editing_delta_replacement_bindings.g.dart';
import '../bindings/services/text_editing_value_bindings.g.dart';
import '../bindings/services/text_input_bindings.g.dart';
import '../bindings/services/text_input_action_bindings.g.dart';
import '../bindings/services/text_input_client_bindings.g.dart';
import '../bindings/services/text_input_configuration_bindings.g.dart';
import '../bindings/services/text_input_connection_bindings.g.dart';
import '../bindings/services/text_input_control_bindings.g.dart';
import '../bindings/services/text_input_formatter_bindings.g.dart';
import '../bindings/services/text_input_type_bindings.g.dart';
import '../bindings/services/text_layout_metrics_bindings.g.dart';
import '../bindings/services/text_selection_bindings.g.dart';
import '../bindings/services/text_selection_delegate_bindings.g.dart';
import '../bindings/services/texture_android_view_controller_bindings.g.dart';
import '../bindings/services/ui_kit_view_controller_bindings.g.dart';
import '../bindings/services/undo_direction_bindings.g.dart';
import '../bindings/services/undo_manager_bindings.g.dart';
import '../bindings/services/undo_manager_client_bindings.g.dart';

class ServicesPlugin extends DarticPlugin {
  @override
  String get name => 'package:flutter/src/services';

  @override
  void register(DarticPluginContext ctx) {
    AndroidMotionEventBindings.register(ctx);
    AndroidPointerCoordsBindings.register(ctx);
    AndroidPointerPropertiesBindings.register(ctx);
    AndroidViewControllerBindings.register(ctx);
    AppKitViewControllerBindings.register(ctx);
    ApplicationSwitcherDescriptionBindings.register(ctx);
    AssetBundleBindings.register(ctx);
    AssetManifestBindings.register(ctx);
    AssetMetadataBindings.register(ctx);
    AutofillClientBindings.register(ctx);
    AutofillConfigurationBindings.register(ctx);
    AutofillHintsBindings.register(ctx);
    AutofillScopeBindings.register(ctx);
    AutofillScopeMixinBindings.register(ctx);
    BackgroundIsolateBinaryMessengerBindings.register(ctx);
    BasicMessageChannelBindings.register(ctx);
    BinaryCodecBindings.register(ctx);
    BinaryMessengerBindings.register(ctx);
    BrowserContextMenuBindings.register(ctx);
    CachingAssetBundleBindings.register(ctx);
    CharacterBoundaryBindings.register(ctx);
    ClipboardBindings.register(ctx);
    ClipboardDataBindings.register(ctx);
    ContentSensitivityBindings.register(ctx);
    DarwinPlatformViewControllerBindings.register(ctx);
    DefaultProcessTextServiceBindings.register(ctx);
    DefaultSpellCheckServiceBindings.register(ctx);
    DeferredComponentBindings.register(ctx);
    DeltaTextInputClientBindings.register(ctx);
    DeviceOrientationBindings.register(ctx);
    DocumentBoundaryBindings.register(ctx);
    EventChannelBindings.register(ctx);
    ExpensiveAndroidViewControllerBindings.register(ctx);
    FilteringTextInputFormatterBindings.register(ctx);
    FloatingCursorDragStateBindings.register(ctx);
    FlutterVersionBindings.register(ctx);
    FontLoaderBindings.register(ctx);
    GLFWKeyHelperBindings.register(ctx);
    GtkKeyHelperBindings.register(ctx);
    HapticFeedbackBindings.register(ctx);
    HardwareKeyboardBindings.register(ctx);
    HybridAndroidViewControllerBindings.register(ctx);
    IOSSystemContextMenuItemDataBindings.register(ctx);
    IOSSystemContextMenuItemDataCopyBindings.register(ctx);
    IOSSystemContextMenuItemDataCustomBindings.register(ctx);
    IOSSystemContextMenuItemDataCutBindings.register(ctx);
    IOSSystemContextMenuItemDataLiveTextBindings.register(ctx);
    IOSSystemContextMenuItemDataLookUpBindings.register(ctx);
    IOSSystemContextMenuItemDataPasteBindings.register(ctx);
    IOSSystemContextMenuItemDataSearchWebBindings.register(ctx);
    IOSSystemContextMenuItemDataSelectAllBindings.register(ctx);
    IOSSystemContextMenuItemDataShareBindings.register(ctx);
    JSONMessageCodecBindings.register(ctx);
    JSONMethodCodecBindings.register(ctx);
    KeyDataTransitModeBindings.register(ctx);
    KeyDownEventBindings.register(ctx);
    KeyEventBindings.register(ctx);
    KeyEventManagerBindings.register(ctx);
    KeyHelperBindings.register(ctx);
    KeyMessageBindings.register(ctx);
    KeyRepeatEventBindings.register(ctx);
    KeyUpEventBindings.register(ctx);
    KeyboardInsertedContentBindings.register(ctx);
    KeyboardKeyBindings.register(ctx);
    KeyboardLockModeBindings.register(ctx);
    KeyboardSideBindings.register(ctx);
    LengthLimitingTextInputFormatterBindings.register(ctx);
    LineBoundaryBindings.register(ctx);
    LiveTextBindings.register(ctx);
    LogicalKeyboardKeyBindings.register(ctx);
    MaxLengthEnforcementBindings.register(ctx);
    MessageCodecBindings.register(ctx);
    MethodCallBindings.register(ctx);
    MethodChannelBindings.register(ctx);
    MethodCodecBindings.register(ctx);
    MissingPluginExceptionBindings.register(ctx);
    ModifierKeyBindings.register(ctx);
    MouseCursorBindings.register(ctx);
    MouseCursorManagerBindings.register(ctx);
    MouseCursorSessionBindings.register(ctx);
    MouseTrackerAnnotationBindings.register(ctx);
    NetworkAssetBundleBindings.register(ctx);
    OptionalMethodChannelBindings.register(ctx);
    ParagraphBoundaryBindings.register(ctx);
    PhysicalKeyboardKeyBindings.register(ctx);
    PlatformAssetBundleBindings.register(ctx);
    PlatformExceptionBindings.register(ctx);
    PlatformViewControllerBindings.register(ctx);
    PlatformViewsRegistryBindings.register(ctx);
    PlatformViewsServiceBindings.register(ctx);
    PredictiveBackEventBindings.register(ctx);
    ProcessTextActionBindings.register(ctx);
    ProcessTextServiceBindings.register(ctx);
    RawFloatingCursorPointBindings.register(ctx);
    RawKeyDownEventBindings.register(ctx);
    RawKeyEventBindings.register(ctx);
    RawKeyEventDataBindings.register(ctx);
    RawKeyEventDataAndroidBindings.register(ctx);
    RawKeyEventDataFuchsiaBindings.register(ctx);
    RawKeyEventDataIosBindings.register(ctx);
    RawKeyEventDataLinuxBindings.register(ctx);
    RawKeyEventDataMacOsBindings.register(ctx);
    RawKeyEventDataWebBindings.register(ctx);
    RawKeyEventDataWindowsBindings.register(ctx);
    RawKeyUpEventBindings.register(ctx);
    RawKeyboardBindings.register(ctx);
    RestorationBucketBindings.register(ctx);
    RestorationManagerBindings.register(ctx);
    ScribbleClientBindings.register(ctx);
    ScribeBindings.register(ctx);
    SelectionChangedCauseBindings.register(ctx);
    SelectionRectBindings.register(ctx);
    SensitiveContentServiceBindings.register(ctx);
    ServicesBindingBindings.register(ctx);
    ServicesServiceExtensionsBindings.register(ctx);
    SmartDashesTypeBindings.register(ctx);
    SmartQuotesTypeBindings.register(ctx);
    SpellCheckResultsBindings.register(ctx);
    SpellCheckServiceBindings.register(ctx);
    StandardMessageCodecBindings.register(ctx);
    StandardMethodCodecBindings.register(ctx);
    StringCodecBindings.register(ctx);
    SuggestionSpanBindings.register(ctx);
    SurfaceAndroidViewControllerBindings.register(ctx);
    SwipeEdgeBindings.register(ctx);
    SystemChannelsBindings.register(ctx);
    SystemChromeBindings.register(ctx);
    SystemContextMenuClientBindings.register(ctx);
    SystemContextMenuControllerBindings.register(ctx);
    SystemMouseCursorBindings.register(ctx);
    SystemMouseCursorsBindings.register(ctx);
    SystemNavigatorBindings.register(ctx);
    SystemSoundBindings.register(ctx);
    SystemSoundTypeBindings.register(ctx);
    SystemUiModeBindings.register(ctx);
    SystemUiOverlayBindings.register(ctx);
    SystemUiOverlayStyleBindings.register(ctx);
    TextBoundaryBindings.register(ctx);
    TextCapitalizationBindings.register(ctx);
    TextEditingDeltaBindings.register(ctx);
    TextEditingDeltaDeletionBindings.register(ctx);
    TextEditingDeltaInsertionBindings.register(ctx);
    TextEditingDeltaNonTextUpdateBindings.register(ctx);
    TextEditingDeltaReplacementBindings.register(ctx);
    TextEditingValueBindings.register(ctx);
    TextInputBindings.register(ctx);
    TextInputActionBindings.register(ctx);
    TextInputClientBindings.register(ctx);
    TextInputConfigurationBindings.register(ctx);
    TextInputConnectionBindings.register(ctx);
    TextInputControlBindings.register(ctx);
    TextInputFormatterBindings.register(ctx);
    TextInputTypeBindings.register(ctx);
    TextLayoutMetricsBindings.register(ctx);
    TextSelectionBindings.register(ctx);
    TextSelectionDelegateBindings.register(ctx);
    TextureAndroidViewControllerBindings.register(ctx);
    UiKitViewControllerBindings.register(ctx);
    UndoDirectionBindings.register(ctx);
    UndoManagerBindings.register(ctx);
    UndoManagerClientBindings.register(ctx);
  }
}
