// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7
// Generator: dartic_generator

// ignore_for_file: unused_import, unnecessary_import, implementation_imports

import 'package:dartic/dartic.dart';
import '../bindings/ui/accessibility_features_bindings.g.dart';
import '../bindings/ui/app_exit_response_bindings.g.dart';
import '../bindings/ui/app_exit_type_bindings.g.dart';
import '../bindings/ui/app_lifecycle_state_bindings.g.dart';
import '../bindings/ui/backdrop_filter_engine_layer_bindings.g.dart';
import '../bindings/ui/blend_mode_bindings.g.dart';
import '../bindings/ui/blur_style_bindings.g.dart';
import '../bindings/ui/box_height_style_bindings.g.dart';
import '../bindings/ui/box_width_style_bindings.g.dart';
import '../bindings/ui/brightness_bindings.g.dart';
import '../bindings/ui/callback_handle_bindings.g.dart';
import '../bindings/ui/canvas_bindings.g.dart';
import '../bindings/ui/channel_buffers_bindings.g.dart';
import '../bindings/ui/checked_state_bindings.g.dart';
import '../bindings/ui/clip_bindings.g.dart';
import '../bindings/ui/clip_op_bindings.g.dart';
import '../bindings/ui/clip_path_engine_layer_bindings.g.dart';
import '../bindings/ui/clip_r_rect_engine_layer_bindings.g.dart';
import '../bindings/ui/clip_r_superellipse_engine_layer_bindings.g.dart';
import '../bindings/ui/clip_rect_engine_layer_bindings.g.dart';
import '../bindings/ui/codec_bindings.g.dart';
import '../bindings/ui/color_bindings.g.dart';
import '../bindings/ui/color_filter_bindings.g.dart';
import '../bindings/ui/color_filter_engine_layer_bindings.g.dart';
import '../bindings/ui/color_space_bindings.g.dart';
import '../bindings/ui/dart_performance_mode_bindings.g.dart';
import '../bindings/ui/dart_plugin_registrant_bindings.g.dart';
import '../bindings/ui/display_bindings.g.dart';
import '../bindings/ui/display_feature_bindings.g.dart';
import '../bindings/ui/display_feature_state_bindings.g.dart';
import '../bindings/ui/display_feature_type_bindings.g.dart';
import '../bindings/ui/engine_layer_bindings.g.dart';
import '../bindings/ui/filter_quality_bindings.g.dart';
import '../bindings/ui/flutter_view_bindings.g.dart';
import '../bindings/ui/font_feature_bindings.g.dart';
import '../bindings/ui/font_style_bindings.g.dart';
import '../bindings/ui/font_variation_bindings.g.dart';
import '../bindings/ui/font_weight_bindings.g.dart';
import '../bindings/ui/fragment_program_bindings.g.dart';
import '../bindings/ui/fragment_shader_bindings.g.dart';
import '../bindings/ui/frame_data_bindings.g.dart';
import '../bindings/ui/frame_info_bindings.g.dart';
import '../bindings/ui/frame_phase_bindings.g.dart';
import '../bindings/ui/frame_timing_bindings.g.dart';
import '../bindings/ui/gesture_settings_bindings.g.dart';
import '../bindings/ui/glyph_info_bindings.g.dart';
import '../bindings/ui/gradient_bindings.g.dart';
import '../bindings/ui/image_bindings.g.dart';
import '../bindings/ui/image_byte_format_bindings.g.dart';
import '../bindings/ui/image_descriptor_bindings.g.dart';
import '../bindings/ui/image_filter_bindings.g.dart';
import '../bindings/ui/image_filter_engine_layer_bindings.g.dart';
import '../bindings/ui/image_shader_bindings.g.dart';
import '../bindings/ui/immutable_buffer_bindings.g.dart';
import '../bindings/ui/isolate_name_server_bindings.g.dart';
import '../bindings/ui/key_data_bindings.g.dart';
import '../bindings/ui/key_event_device_type_bindings.g.dart';
import '../bindings/ui/key_event_type_bindings.g.dart';
import '../bindings/ui/line_metrics_bindings.g.dart';
import '../bindings/ui/locale_bindings.g.dart';
import '../bindings/ui/locale_string_attribute_bindings.g.dart';
import '../bindings/ui/mask_filter_bindings.g.dart';
import '../bindings/ui/offset_bindings.g.dart';
import '../bindings/ui/offset_base_bindings.g.dart';
import '../bindings/ui/offset_engine_layer_bindings.g.dart';
import '../bindings/ui/opacity_engine_layer_bindings.g.dart';
import '../bindings/ui/paint_bindings.g.dart';
import '../bindings/ui/painting_style_bindings.g.dart';
import '../bindings/ui/paragraph_bindings.g.dart';
import '../bindings/ui/paragraph_builder_bindings.g.dart';
import '../bindings/ui/paragraph_constraints_bindings.g.dart';
import '../bindings/ui/paragraph_style_bindings.g.dart';
import '../bindings/ui/path_bindings.g.dart';
import '../bindings/ui/path_fill_type_bindings.g.dart';
import '../bindings/ui/path_metric_bindings.g.dart';
import '../bindings/ui/path_metric_iterator_bindings.g.dart';
import '../bindings/ui/path_metrics_bindings.g.dart';
import '../bindings/ui/path_operation_bindings.g.dart';
import '../bindings/ui/picture_bindings.g.dart';
import '../bindings/ui/picture_rasterization_exception_bindings.g.dart';
import '../bindings/ui/picture_recorder_bindings.g.dart';
import '../bindings/ui/pixel_format_bindings.g.dart';
import '../bindings/ui/placeholder_alignment_bindings.g.dart';
import '../bindings/ui/platform_dispatcher_bindings.g.dart';
import '../bindings/ui/plugin_utilities_bindings.g.dart';
import '../bindings/ui/point_mode_bindings.g.dart';
import '../bindings/ui/pointer_change_bindings.g.dart';
import '../bindings/ui/pointer_data_bindings.g.dart';
import '../bindings/ui/pointer_data_packet_bindings.g.dart';
import '../bindings/ui/pointer_device_kind_bindings.g.dart';
import '../bindings/ui/pointer_signal_kind_bindings.g.dart';
import '../bindings/ui/r_rect_bindings.g.dart';
import '../bindings/ui/r_s_transform_bindings.g.dart';
import '../bindings/ui/r_superellipse_bindings.g.dart';
import '../bindings/ui/radius_bindings.g.dart';
import '../bindings/ui/rect_bindings.g.dart';
import '../bindings/ui/root_isolate_token_bindings.g.dart';
import '../bindings/ui/scene_bindings.g.dart';
import '../bindings/ui/scene_builder_bindings.g.dart';
import '../bindings/ui/semantics_action_bindings.g.dart';
import '../bindings/ui/semantics_action_event_bindings.g.dart';
import '../bindings/ui/semantics_flag_bindings.g.dart';
import '../bindings/ui/semantics_flags_bindings.g.dart';
import '../bindings/ui/semantics_input_type_bindings.g.dart';
import '../bindings/ui/semantics_role_bindings.g.dart';
import '../bindings/ui/semantics_update_bindings.g.dart';
import '../bindings/ui/semantics_update_builder_bindings.g.dart';
import '../bindings/ui/semantics_validation_result_bindings.g.dart';
import '../bindings/ui/shader_bindings.g.dart';
import '../bindings/ui/shader_mask_engine_layer_bindings.g.dart';
import '../bindings/ui/shadow_bindings.g.dart';
import '../bindings/ui/singleton_flutter_window_bindings.g.dart';
import '../bindings/ui/size_bindings.g.dart';
import '../bindings/ui/spell_out_string_attribute_bindings.g.dart';
import '../bindings/ui/string_attribute_bindings.g.dart';
import '../bindings/ui/stroke_cap_bindings.g.dart';
import '../bindings/ui/stroke_join_bindings.g.dart';
import '../bindings/ui/strut_style_bindings.g.dart';
import '../bindings/ui/system_color_bindings.g.dart';
import '../bindings/ui/system_color_palette_bindings.g.dart';
import '../bindings/ui/tangent_bindings.g.dart';
import '../bindings/ui/target_image_size_bindings.g.dart';
import '../bindings/ui/text_affinity_bindings.g.dart';
import '../bindings/ui/text_align_bindings.g.dart';
import '../bindings/ui/text_baseline_bindings.g.dart';
import '../bindings/ui/text_box_bindings.g.dart';
import '../bindings/ui/text_decoration_bindings.g.dart';
import '../bindings/ui/text_decoration_style_bindings.g.dart';
import '../bindings/ui/text_direction_bindings.g.dart';
import '../bindings/ui/text_height_behavior_bindings.g.dart';
import '../bindings/ui/text_leading_distribution_bindings.g.dart';
import '../bindings/ui/text_position_bindings.g.dart';
import '../bindings/ui/text_range_bindings.g.dart';
import '../bindings/ui/text_style_bindings.g.dart';
import '../bindings/ui/tile_mode_bindings.g.dart';
import '../bindings/ui/transform_engine_layer_bindings.g.dart';
import '../bindings/ui/tristate_bindings.g.dart';
import '../bindings/ui/vertex_mode_bindings.g.dart';
import '../bindings/ui/vertices_bindings.g.dart';
import '../bindings/ui/view_constraints_bindings.g.dart';
import '../bindings/ui/view_focus_direction_bindings.g.dart';
import '../bindings/ui/view_focus_event_bindings.g.dart';
import '../bindings/ui/view_focus_state_bindings.g.dart';
import '../bindings/ui/view_padding_bindings.g.dart';
import '../bindings/ui/ui_top_level_bindings.g.dart';

class UiPlugin extends DarticPlugin {
  @override
  String get name => 'dart:ui';

  @override
  void register(DarticPluginContext ctx) {
    AccessibilityFeaturesBindings.register(ctx);
    AppExitResponseBindings.register(ctx);
    AppExitTypeBindings.register(ctx);
    AppLifecycleStateBindings.register(ctx);
    BackdropFilterEngineLayerBindings.register(ctx);
    BlendModeBindings.register(ctx);
    BlurStyleBindings.register(ctx);
    BoxHeightStyleBindings.register(ctx);
    BoxWidthStyleBindings.register(ctx);
    BrightnessBindings.register(ctx);
    CallbackHandleBindings.register(ctx);
    CanvasBindings.register(ctx);
    ChannelBuffersBindings.register(ctx);
    CheckedStateBindings.register(ctx);
    ClipBindings.register(ctx);
    ClipOpBindings.register(ctx);
    ClipPathEngineLayerBindings.register(ctx);
    ClipRRectEngineLayerBindings.register(ctx);
    ClipRSuperellipseEngineLayerBindings.register(ctx);
    ClipRectEngineLayerBindings.register(ctx);
    CodecBindings.register(ctx);
    ColorBindings.register(ctx);
    ColorFilterBindings.register(ctx);
    ColorFilterEngineLayerBindings.register(ctx);
    ColorSpaceBindings.register(ctx);
    DartPerformanceModeBindings.register(ctx);
    DartPluginRegistrantBindings.register(ctx);
    DisplayBindings.register(ctx);
    DisplayFeatureBindings.register(ctx);
    DisplayFeatureStateBindings.register(ctx);
    DisplayFeatureTypeBindings.register(ctx);
    EngineLayerBindings.register(ctx);
    FilterQualityBindings.register(ctx);
    FlutterViewBindings.register(ctx);
    FontFeatureBindings.register(ctx);
    FontStyleBindings.register(ctx);
    FontVariationBindings.register(ctx);
    FontWeightBindings.register(ctx);
    FragmentProgramBindings.register(ctx);
    FragmentShaderBindings.register(ctx);
    FrameDataBindings.register(ctx);
    FrameInfoBindings.register(ctx);
    FramePhaseBindings.register(ctx);
    FrameTimingBindings.register(ctx);
    GestureSettingsBindings.register(ctx);
    GlyphInfoBindings.register(ctx);
    GradientBindings.register(ctx);
    ImageBindings.register(ctx);
    ImageByteFormatBindings.register(ctx);
    ImageDescriptorBindings.register(ctx);
    ImageFilterBindings.register(ctx);
    ImageFilterEngineLayerBindings.register(ctx);
    ImageShaderBindings.register(ctx);
    ImmutableBufferBindings.register(ctx);
    IsolateNameServerBindings.register(ctx);
    KeyDataBindings.register(ctx);
    KeyEventDeviceTypeBindings.register(ctx);
    KeyEventTypeBindings.register(ctx);
    LineMetricsBindings.register(ctx);
    LocaleBindings.register(ctx);
    LocaleStringAttributeBindings.register(ctx);
    MaskFilterBindings.register(ctx);
    OffsetBindings.register(ctx);
    OffsetBaseBindings.register(ctx);
    OffsetEngineLayerBindings.register(ctx);
    OpacityEngineLayerBindings.register(ctx);
    PaintBindings.register(ctx);
    PaintingStyleBindings.register(ctx);
    ParagraphBindings.register(ctx);
    ParagraphBuilderBindings.register(ctx);
    ParagraphConstraintsBindings.register(ctx);
    ParagraphStyleBindings.register(ctx);
    PathBindings.register(ctx);
    PathFillTypeBindings.register(ctx);
    PathMetricBindings.register(ctx);
    PathMetricIteratorBindings.register(ctx);
    PathMetricsBindings.register(ctx);
    PathOperationBindings.register(ctx);
    PictureBindings.register(ctx);
    PictureRasterizationExceptionBindings.register(ctx);
    PictureRecorderBindings.register(ctx);
    PixelFormatBindings.register(ctx);
    PlaceholderAlignmentBindings.register(ctx);
    PlatformDispatcherBindings.register(ctx);
    PluginUtilitiesBindings.register(ctx);
    PointModeBindings.register(ctx);
    PointerChangeBindings.register(ctx);
    PointerDataBindings.register(ctx);
    PointerDataPacketBindings.register(ctx);
    PointerDeviceKindBindings.register(ctx);
    PointerSignalKindBindings.register(ctx);
    RRectBindings.register(ctx);
    RSTransformBindings.register(ctx);
    RSuperellipseBindings.register(ctx);
    RadiusBindings.register(ctx);
    RectBindings.register(ctx);
    RootIsolateTokenBindings.register(ctx);
    SceneBindings.register(ctx);
    SceneBuilderBindings.register(ctx);
    SemanticsActionBindings.register(ctx);
    SemanticsActionEventBindings.register(ctx);
    SemanticsFlagBindings.register(ctx);
    SemanticsFlagsBindings.register(ctx);
    SemanticsInputTypeBindings.register(ctx);
    SemanticsRoleBindings.register(ctx);
    SemanticsUpdateBindings.register(ctx);
    SemanticsUpdateBuilderBindings.register(ctx);
    SemanticsValidationResultBindings.register(ctx);
    ShaderBindings.register(ctx);
    ShaderMaskEngineLayerBindings.register(ctx);
    ShadowBindings.register(ctx);
    SingletonFlutterWindowBindings.register(ctx);
    SizeBindings.register(ctx);
    SpellOutStringAttributeBindings.register(ctx);
    StringAttributeBindings.register(ctx);
    StrokeCapBindings.register(ctx);
    StrokeJoinBindings.register(ctx);
    StrutStyleBindings.register(ctx);
    SystemColorBindings.register(ctx);
    SystemColorPaletteBindings.register(ctx);
    TangentBindings.register(ctx);
    TargetImageSizeBindings.register(ctx);
    TextAffinityBindings.register(ctx);
    TextAlignBindings.register(ctx);
    TextBaselineBindings.register(ctx);
    TextBoxBindings.register(ctx);
    TextDecorationBindings.register(ctx);
    TextDecorationStyleBindings.register(ctx);
    TextDirectionBindings.register(ctx);
    TextHeightBehaviorBindings.register(ctx);
    TextLeadingDistributionBindings.register(ctx);
    TextPositionBindings.register(ctx);
    TextRangeBindings.register(ctx);
    TextStyleBindings.register(ctx);
    TileModeBindings.register(ctx);
    TransformEngineLayerBindings.register(ctx);
    TristateBindings.register(ctx);
    VertexModeBindings.register(ctx);
    VerticesBindings.register(ctx);
    ViewConstraintsBindings.register(ctx);
    ViewFocusDirectionBindings.register(ctx);
    ViewFocusEventBindings.register(ctx);
    ViewFocusStateBindings.register(ctx);
    ViewPaddingBindings.register(ctx);
    UiTopLevelBindings.register(ctx);
  }
}
