// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7
// Generator: dartic_generator

// ignore_for_file: unused_import, unnecessary_import, implementation_imports

import 'package:dartic/dartic.dart';
import 'package:dartic/src/api/dartic_absent.dart';
import 'package:dartic/src/runtime/object.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'dart:ui';
import '../bindings/widget_bindings.g.dart';
import '../bindings/stateless_widget_bindings.g.dart';
import '../bindings/stateful_widget_bindings.g.dart';
import '../bindings/state_bindings.g.dart';
import '../bindings/build_context_bindings.g.dart';
import '../bindings/navigator_bindings.g.dart';
import '../bindings/center_bindings.g.dart';
import '../bindings/column_bindings.g.dart';
import '../bindings/row_bindings.g.dart';
import '../bindings/sized_box_bindings.g.dart';
import '../bindings/padding_bindings.g.dart';
import '../bindings/expanded_bindings.g.dart';
import '../bindings/container_bindings.g.dart';
import '../bindings/text_bindings.g.dart';
import '../bindings/icon_bindings.g.dart';
import '../bindings/stack_bindings.g.dart';
import '../bindings/positioned_bindings.g.dart';
import '../bindings/positioned_directional_bindings.g.dart';
import '../bindings/indexed_stack_bindings.g.dart';
import '../bindings/flex_bindings.g.dart';
import '../bindings/flexible_bindings.g.dart';
import '../bindings/wrap_bindings.g.dart';
import '../bindings/align_bindings.g.dart';
import '../bindings/fitted_box_bindings.g.dart';
import '../bindings/fractionally_sized_box_bindings.g.dart';
import '../bindings/limited_box_bindings.g.dart';
import '../bindings/overflow_box_bindings.g.dart';
import '../bindings/aspect_ratio_bindings.g.dart';
import '../bindings/constrained_box_bindings.g.dart';
import '../bindings/unconstrained_box_bindings.g.dart';
import '../bindings/intrinsic_width_bindings.g.dart';
import '../bindings/intrinsic_height_bindings.g.dart';
import '../bindings/opacity_bindings.g.dart';
import '../bindings/clip_rect_bindings.g.dart';
import '../bindings/clip_r_rect_bindings.g.dart';
import '../bindings/clip_oval_bindings.g.dart';
import '../bindings/clip_path_bindings.g.dart';
import '../bindings/transform_bindings.g.dart';
import '../bindings/rotated_box_bindings.g.dart';
import '../bindings/fractional_translation_bindings.g.dart';
import '../bindings/offstage_bindings.g.dart';
import '../bindings/ignore_pointer_bindings.g.dart';
import '../bindings/absorb_pointer_bindings.g.dart';
import '../bindings/repaint_boundary_bindings.g.dart';
import '../bindings/colored_box_bindings.g.dart';
import '../bindings/physical_model_bindings.g.dart';
import '../bindings/physical_shape_bindings.g.dart';
import '../bindings/custom_paint_bindings.g.dart';
import '../bindings/directionality_bindings.g.dart';
import '../bindings/gesture_detector_bindings.g.dart';
import '../bindings/list_view_bindings.g.dart';
import '../bindings/grid_view_bindings.g.dart';
import '../bindings/custom_scroll_view_bindings.g.dart';
import '../bindings/single_child_scroll_view_bindings.g.dart';
import '../bindings/page_view_bindings.g.dart';
import '../bindings/builder_bindings.g.dart';
import '../bindings/stateful_builder_bindings.g.dart';
import '../bindings/fade_in_image_bindings.g.dart';
import '../bindings/form_bindings.g.dart';
import '../bindings/media_query_bindings.g.dart';
import '../bindings/default_text_style_bindings.g.dart';
import '../bindings/rich_text_bindings.g.dart';
import '../bindings/animated_container_bindings.g.dart';
import '../bindings/animated_padding_bindings.g.dart';
import '../bindings/animated_align_bindings.g.dart';
import '../bindings/animated_positioned_bindings.g.dart';
import '../bindings/animated_opacity_bindings.g.dart';
import '../bindings/animated_default_text_style_bindings.g.dart';
import '../bindings/animated_physical_model_bindings.g.dart';
import '../bindings/animated_scale_bindings.g.dart';
import '../bindings/animated_rotation_bindings.g.dart';
import '../bindings/animated_slide_bindings.g.dart';
import '../bindings/animated_switcher_bindings.g.dart';
import '../bindings/animated_size_bindings.g.dart';
import '../bindings/slide_transition_bindings.g.dart';
import '../bindings/scale_transition_bindings.g.dart';
import '../bindings/rotation_transition_bindings.g.dart';
import '../bindings/fade_transition_bindings.g.dart';
import '../bindings/size_transition_bindings.g.dart';
import '../bindings/decorated_box_transition_bindings.g.dart';
import '../bindings/hero_bindings.g.dart';
import '../bindings/page_route_builder_bindings.g.dart';
import '../bindings/route_settings_bindings.g.dart';
import '../bindings/dismissible_bindings.g.dart';
import '../bindings/draggable_scrollable_sheet_bindings.g.dart';
import '../bindings/placeholder_bindings.g.dart';
import '../bindings/preferred_size_bindings.g.dart';
import '../bindings/overlay_bindings.g.dart';
import '../bindings/overlay_entry_bindings.g.dart';
import '../bindings/layout_builder_bindings.g.dart';
import '../bindings/orientation_builder_bindings.g.dart';
import '../bindings/tooltip_bindings.g.dart';
import '../bindings/scroll_view_keyboard_dismiss_behavior_bindings.g.dart';
import '../bindings/connection_state_bindings.g.dart';
import '../bindings/autovalidate_mode_bindings.g.dart';
import '../bindings/orientation_bindings.g.dart';

class WidgetsPlugin extends DarticPlugin {
  @override
  String get name => 'package:flutter/widgets.dart';

  @override
  void register(DarticPluginContext ctx) {
    WidgetBindings.register(ctx);
    StatelessWidgetBindings.register(ctx);
    StatefulWidgetBindings.register(ctx);
    StateBindings.register(ctx);
    BuildContextBindings.register(ctx);
    NavigatorBindings.register(ctx);
    CenterBindings.register(ctx);
    ColumnBindings.register(ctx);
    RowBindings.register(ctx);
    SizedBoxBindings.register(ctx);
    PaddingBindings.register(ctx);
    ExpandedBindings.register(ctx);
    ContainerBindings.register(ctx);
    TextBindings.register(ctx);
    IconBindings.register(ctx);
    StackBindings.register(ctx);
    PositionedBindings.register(ctx);
    PositionedDirectionalBindings.register(ctx);
    IndexedStackBindings.register(ctx);
    FlexBindings.register(ctx);
    FlexibleBindings.register(ctx);
    WrapBindings.register(ctx);
    AlignBindings.register(ctx);
    FittedBoxBindings.register(ctx);
    FractionallySizedBoxBindings.register(ctx);
    LimitedBoxBindings.register(ctx);
    OverflowBoxBindings.register(ctx);
    AspectRatioBindings.register(ctx);
    ConstrainedBoxBindings.register(ctx);
    UnconstrainedBoxBindings.register(ctx);
    IntrinsicWidthBindings.register(ctx);
    IntrinsicHeightBindings.register(ctx);
    OpacityBindings.register(ctx);
    ClipRectBindings.register(ctx);
    ClipRRectBindings.register(ctx);
    ClipOvalBindings.register(ctx);
    ClipPathBindings.register(ctx);
    TransformBindings.register(ctx);
    RotatedBoxBindings.register(ctx);
    FractionalTranslationBindings.register(ctx);
    OffstageBindings.register(ctx);
    IgnorePointerBindings.register(ctx);
    AbsorbPointerBindings.register(ctx);
    RepaintBoundaryBindings.register(ctx);
    ColoredBoxBindings.register(ctx);
    PhysicalModelBindings.register(ctx);
    PhysicalShapeBindings.register(ctx);
    CustomPaintBindings.register(ctx);
    DirectionalityBindings.register(ctx);
    GestureDetectorBindings.register(ctx);
    ListViewBindings.register(ctx);
    GridViewBindings.register(ctx);
    CustomScrollViewBindings.register(ctx);
    SingleChildScrollViewBindings.register(ctx);
    PageViewBindings.register(ctx);
    BuilderBindings.register(ctx);
    StatefulBuilderBindings.register(ctx);
    FadeInImageBindings.register(ctx);
    FormBindings.register(ctx);
    MediaQueryBindings.register(ctx);
    DefaultTextStyleBindings.register(ctx);
    RichTextBindings.register(ctx);
    AnimatedContainerBindings.register(ctx);
    AnimatedPaddingBindings.register(ctx);
    AnimatedAlignBindings.register(ctx);
    AnimatedPositionedBindings.register(ctx);
    AnimatedOpacityBindings.register(ctx);
    AnimatedDefaultTextStyleBindings.register(ctx);
    AnimatedPhysicalModelBindings.register(ctx);
    AnimatedScaleBindings.register(ctx);
    AnimatedRotationBindings.register(ctx);
    AnimatedSlideBindings.register(ctx);
    AnimatedSwitcherBindings.register(ctx);
    AnimatedSizeBindings.register(ctx);
    SlideTransitionBindings.register(ctx);
    ScaleTransitionBindings.register(ctx);
    RotationTransitionBindings.register(ctx);
    FadeTransitionBindings.register(ctx);
    SizeTransitionBindings.register(ctx);
    DecoratedBoxTransitionBindings.register(ctx);
    HeroBindings.register(ctx);
    PageRouteBuilderBindings.register(ctx);
    RouteSettingsBindings.register(ctx);
    DismissibleBindings.register(ctx);
    DraggableScrollableSheetBindings.register(ctx);
    PlaceholderBindings.register(ctx);
    PreferredSizeBindings.register(ctx);
    OverlayBindings.register(ctx);
    OverlayEntryBindings.register(ctx);
    LayoutBuilderBindings.register(ctx);
    OrientationBuilderBindings.register(ctx);
    TooltipBindings.register(ctx);
    ScrollViewKeyboardDismissBehaviorBindings.register(ctx);
    ConnectionStateBindings.register(ctx);
    AutovalidateModeBindings.register(ctx);
    OrientationBindings.register(ctx);
  }
}
