// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7
// Generator: dartic_generator

// ignore_for_file: unused_import, unnecessary_import, implementation_imports

import 'package:dartic/dartic.dart';
import 'package:dartic/dartic_internal.dart';
import 'package:flutter/animation.dart';
import 'package:flutter/foundation.dart';
import '../bindings/animation/widget_bindings.g.dart';
import '../bindings/animation/stateless_widget_bindings.g.dart';
import '../bindings/animation/stateful_widget_bindings.g.dart';
import '../bindings/animation/state_bindings.g.dart';
import '../bindings/animation/build_context_bindings.g.dart';
import '../bindings/animation/navigator_bindings.g.dart';
import '../bindings/animation/center_bindings.g.dart';
import '../bindings/animation/column_bindings.g.dart';
import '../bindings/animation/row_bindings.g.dart';
import '../bindings/animation/sized_box_bindings.g.dart';
import '../bindings/animation/padding_bindings.g.dart';
import '../bindings/animation/expanded_bindings.g.dart';
import '../bindings/animation/container_bindings.g.dart';
import '../bindings/animation/text_bindings.g.dart';
import '../bindings/animation/icon_bindings.g.dart';
import '../bindings/animation/icon_data_bindings.g.dart';
import '../bindings/animation/stack_bindings.g.dart';
import '../bindings/animation/positioned_bindings.g.dart';
import '../bindings/animation/positioned_directional_bindings.g.dart';
import '../bindings/animation/indexed_stack_bindings.g.dart';
import '../bindings/animation/flex_bindings.g.dart';
import '../bindings/animation/flexible_bindings.g.dart';
import '../bindings/animation/wrap_bindings.g.dart';
import '../bindings/animation/align_bindings.g.dart';
import '../bindings/animation/fitted_box_bindings.g.dart';
import '../bindings/animation/fractionally_sized_box_bindings.g.dart';
import '../bindings/animation/limited_box_bindings.g.dart';
import '../bindings/animation/overflow_box_bindings.g.dart';
import '../bindings/animation/aspect_ratio_bindings.g.dart';
import '../bindings/animation/constrained_box_bindings.g.dart';
import '../bindings/animation/unconstrained_box_bindings.g.dart';
import '../bindings/animation/intrinsic_width_bindings.g.dart';
import '../bindings/animation/intrinsic_height_bindings.g.dart';
import '../bindings/animation/opacity_bindings.g.dart';
import '../bindings/animation/clip_rect_bindings.g.dart';
import '../bindings/animation/clip_r_rect_bindings.g.dart';
import '../bindings/animation/clip_oval_bindings.g.dart';
import '../bindings/animation/clip_path_bindings.g.dart';
import '../bindings/animation/transform_bindings.g.dart';
import '../bindings/animation/rotated_box_bindings.g.dart';
import '../bindings/animation/fractional_translation_bindings.g.dart';
import '../bindings/animation/offstage_bindings.g.dart';
import '../bindings/animation/ignore_pointer_bindings.g.dart';
import '../bindings/animation/absorb_pointer_bindings.g.dart';
import '../bindings/animation/repaint_boundary_bindings.g.dart';
import '../bindings/animation/colored_box_bindings.g.dart';
import '../bindings/animation/physical_model_bindings.g.dart';
import '../bindings/animation/physical_shape_bindings.g.dart';
import '../bindings/animation/custom_paint_bindings.g.dart';
import '../bindings/animation/directionality_bindings.g.dart';
import '../bindings/animation/gesture_detector_bindings.g.dart';
import '../bindings/animation/list_view_bindings.g.dart';
import '../bindings/animation/grid_view_bindings.g.dart';
import '../bindings/animation/custom_scroll_view_bindings.g.dart';
import '../bindings/animation/single_child_scroll_view_bindings.g.dart';
import '../bindings/animation/page_view_bindings.g.dart';
import '../bindings/animation/builder_bindings.g.dart';
import '../bindings/animation/stateful_builder_bindings.g.dart';
import '../bindings/animation/fade_in_image_bindings.g.dart';
import '../bindings/animation/form_bindings.g.dart';
import '../bindings/animation/media_query_bindings.g.dart';
import '../bindings/animation/default_text_style_bindings.g.dart';
import '../bindings/animation/rich_text_bindings.g.dart';
import '../bindings/animation/animated_container_bindings.g.dart';
import '../bindings/animation/animated_padding_bindings.g.dart';
import '../bindings/animation/animated_align_bindings.g.dart';
import '../bindings/animation/animated_positioned_bindings.g.dart';
import '../bindings/animation/animated_opacity_bindings.g.dart';
import '../bindings/animation/animated_default_text_style_bindings.g.dart';
import '../bindings/animation/animated_physical_model_bindings.g.dart';
import '../bindings/animation/animated_scale_bindings.g.dart';
import '../bindings/animation/animated_rotation_bindings.g.dart';
import '../bindings/animation/animated_slide_bindings.g.dart';
import '../bindings/animation/animated_switcher_bindings.g.dart';
import '../bindings/animation/animated_size_bindings.g.dart';
import '../bindings/animation/slide_transition_bindings.g.dart';
import '../bindings/animation/scale_transition_bindings.g.dart';
import '../bindings/animation/rotation_transition_bindings.g.dart';
import '../bindings/animation/fade_transition_bindings.g.dart';
import '../bindings/animation/size_transition_bindings.g.dart';
import '../bindings/animation/decorated_box_transition_bindings.g.dart';
import '../bindings/animation/hero_bindings.g.dart';
import '../bindings/animation/page_route_builder_bindings.g.dart';
import '../bindings/animation/route_settings_bindings.g.dart';
import '../bindings/animation/dismissible_bindings.g.dart';
import '../bindings/animation/draggable_scrollable_sheet_bindings.g.dart';
import '../bindings/animation/placeholder_bindings.g.dart';
import '../bindings/animation/preferred_size_bindings.g.dart';
import '../bindings/animation/overlay_bindings.g.dart';
import '../bindings/animation/overlay_entry_bindings.g.dart';
import '../bindings/animation/layout_builder_bindings.g.dart';
import '../bindings/animation/orientation_builder_bindings.g.dart';
import '../bindings/animation/tooltip_bindings.g.dart';
import '../bindings/animation/scroll_view_keyboard_dismiss_behavior_bindings.g.dart';
import '../bindings/animation/connection_state_bindings.g.dart';
import '../bindings/animation/autovalidate_mode_bindings.g.dart';
import '../bindings/animation/orientation_bindings.g.dart';

class WidgetsPlugin extends DarticPlugin {
  @override
  String get name => 'package:flutter/widgets.dart';

  @override
  void register(DarticPluginContext ctx) {
    WidgetBindings.register(ctx);
    StatelessWidgetBindings.register(ctx);
    StatefulWidgetBindings.register(ctx);
    StateBindings.register(ctx);
    BuildContextBindings.register(ctx);
    NavigatorBindings.register(ctx);
    CenterBindings.register(ctx);
    ColumnBindings.register(ctx);
    RowBindings.register(ctx);
    SizedBoxBindings.register(ctx);
    PaddingBindings.register(ctx);
    ExpandedBindings.register(ctx);
    ContainerBindings.register(ctx);
    TextBindings.register(ctx);
    IconBindings.register(ctx);
    IconDataBindings.register(ctx);
    StackBindings.register(ctx);
    PositionedBindings.register(ctx);
    PositionedDirectionalBindings.register(ctx);
    IndexedStackBindings.register(ctx);
    FlexBindings.register(ctx);
    FlexibleBindings.register(ctx);
    WrapBindings.register(ctx);
    AlignBindings.register(ctx);
    FittedBoxBindings.register(ctx);
    FractionallySizedBoxBindings.register(ctx);
    LimitedBoxBindings.register(ctx);
    OverflowBoxBindings.register(ctx);
    AspectRatioBindings.register(ctx);
    ConstrainedBoxBindings.register(ctx);
    UnconstrainedBoxBindings.register(ctx);
    IntrinsicWidthBindings.register(ctx);
    IntrinsicHeightBindings.register(ctx);
    OpacityBindings.register(ctx);
    ClipRectBindings.register(ctx);
    ClipRRectBindings.register(ctx);
    ClipOvalBindings.register(ctx);
    ClipPathBindings.register(ctx);
    TransformBindings.register(ctx);
    RotatedBoxBindings.register(ctx);
    FractionalTranslationBindings.register(ctx);
    OffstageBindings.register(ctx);
    IgnorePointerBindings.register(ctx);
    AbsorbPointerBindings.register(ctx);
    RepaintBoundaryBindings.register(ctx);
    ColoredBoxBindings.register(ctx);
    PhysicalModelBindings.register(ctx);
    PhysicalShapeBindings.register(ctx);
    CustomPaintBindings.register(ctx);
    DirectionalityBindings.register(ctx);
    GestureDetectorBindings.register(ctx);
    ListViewBindings.register(ctx);
    GridViewBindings.register(ctx);
    CustomScrollViewBindings.register(ctx);
    SingleChildScrollViewBindings.register(ctx);
    PageViewBindings.register(ctx);
    BuilderBindings.register(ctx);
    StatefulBuilderBindings.register(ctx);
    FadeInImageBindings.register(ctx);
    FormBindings.register(ctx);
    MediaQueryBindings.register(ctx);
    DefaultTextStyleBindings.register(ctx);
    RichTextBindings.register(ctx);
    AnimatedContainerBindings.register(ctx);
    AnimatedPaddingBindings.register(ctx);
    AnimatedAlignBindings.register(ctx);
    AnimatedPositionedBindings.register(ctx);
    AnimatedOpacityBindings.register(ctx);
    AnimatedDefaultTextStyleBindings.register(ctx);
    AnimatedPhysicalModelBindings.register(ctx);
    AnimatedScaleBindings.register(ctx);
    AnimatedRotationBindings.register(ctx);
    AnimatedSlideBindings.register(ctx);
    AnimatedSwitcherBindings.register(ctx);
    AnimatedSizeBindings.register(ctx);
    SlideTransitionBindings.register(ctx);
    ScaleTransitionBindings.register(ctx);
    RotationTransitionBindings.register(ctx);
    FadeTransitionBindings.register(ctx);
    SizeTransitionBindings.register(ctx);
    DecoratedBoxTransitionBindings.register(ctx);
    HeroBindings.register(ctx);
    PageRouteBuilderBindings.register(ctx);
    RouteSettingsBindings.register(ctx);
    DismissibleBindings.register(ctx);
    DraggableScrollableSheetBindings.register(ctx);
    PlaceholderBindings.register(ctx);
    PreferredSizeBindings.register(ctx);
    OverlayBindings.register(ctx);
    OverlayEntryBindings.register(ctx);
    LayoutBuilderBindings.register(ctx);
    OrientationBuilderBindings.register(ctx);
    TooltipBindings.register(ctx);
    ScrollViewKeyboardDismissBehaviorBindings.register(ctx);
    ConnectionStateBindings.register(ctx);
    AutovalidateModeBindings.register(ctx);
    OrientationBindings.register(ctx);
  }
}
