// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7
// Generator: dartic_generator

// ignore_for_file: unused_import, unnecessary_import, implementation_imports

import 'package:dartic/dartic.dart';
import 'package:dartic/dartic_internal.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'dart:ui';
import '../bindings/widgets/widget_bindings.g.dart';
import '../bindings/widgets/stateless_widget_bindings.g.dart';
import '../bindings/widgets/stateful_widget_bindings.g.dart';
import '../bindings/widgets/state_bindings.g.dart';
import '../bindings/widgets/build_context_bindings.g.dart';
import '../bindings/widgets/navigator_bindings.g.dart';
import '../bindings/widgets/center_bindings.g.dart';
import '../bindings/widgets/column_bindings.g.dart';
import '../bindings/widgets/row_bindings.g.dart';
import '../bindings/widgets/sized_box_bindings.g.dart';
import '../bindings/widgets/padding_bindings.g.dart';
import '../bindings/widgets/expanded_bindings.g.dart';
import '../bindings/widgets/container_bindings.g.dart';
import '../bindings/widgets/text_bindings.g.dart';
import '../bindings/widgets/icon_bindings.g.dart';
import '../bindings/widgets/icon_data_bindings.g.dart';
import '../bindings/widgets/stack_bindings.g.dart';
import '../bindings/widgets/positioned_bindings.g.dart';
import '../bindings/widgets/positioned_directional_bindings.g.dart';
import '../bindings/widgets/indexed_stack_bindings.g.dart';
import '../bindings/widgets/flex_bindings.g.dart';
import '../bindings/widgets/flexible_bindings.g.dart';
import '../bindings/widgets/wrap_bindings.g.dart';
import '../bindings/widgets/align_bindings.g.dart';
import '../bindings/widgets/fitted_box_bindings.g.dart';
import '../bindings/widgets/fractionally_sized_box_bindings.g.dart';
import '../bindings/widgets/limited_box_bindings.g.dart';
import '../bindings/widgets/overflow_box_bindings.g.dart';
import '../bindings/widgets/aspect_ratio_bindings.g.dart';
import '../bindings/widgets/constrained_box_bindings.g.dart';
import '../bindings/widgets/unconstrained_box_bindings.g.dart';
import '../bindings/widgets/intrinsic_width_bindings.g.dart';
import '../bindings/widgets/intrinsic_height_bindings.g.dart';
import '../bindings/widgets/opacity_bindings.g.dart';
import '../bindings/widgets/clip_rect_bindings.g.dart';
import '../bindings/widgets/clip_r_rect_bindings.g.dart';
import '../bindings/widgets/clip_oval_bindings.g.dart';
import '../bindings/widgets/clip_path_bindings.g.dart';
import '../bindings/widgets/transform_bindings.g.dart';
import '../bindings/widgets/rotated_box_bindings.g.dart';
import '../bindings/widgets/fractional_translation_bindings.g.dart';
import '../bindings/widgets/offstage_bindings.g.dart';
import '../bindings/widgets/ignore_pointer_bindings.g.dart';
import '../bindings/widgets/absorb_pointer_bindings.g.dart';
import '../bindings/widgets/repaint_boundary_bindings.g.dart';
import '../bindings/widgets/colored_box_bindings.g.dart';
import '../bindings/widgets/physical_model_bindings.g.dart';
import '../bindings/widgets/physical_shape_bindings.g.dart';
import '../bindings/widgets/custom_paint_bindings.g.dart';
import '../bindings/widgets/directionality_bindings.g.dart';
import '../bindings/widgets/gesture_detector_bindings.g.dart';
import '../bindings/widgets/list_view_bindings.g.dart';
import '../bindings/widgets/grid_view_bindings.g.dart';
import '../bindings/widgets/custom_scroll_view_bindings.g.dart';
import '../bindings/widgets/single_child_scroll_view_bindings.g.dart';
import '../bindings/widgets/page_view_bindings.g.dart';
import '../bindings/widgets/builder_bindings.g.dart';
import '../bindings/widgets/stateful_builder_bindings.g.dart';
import '../bindings/widgets/fade_in_image_bindings.g.dart';
import '../bindings/widgets/form_bindings.g.dart';
import '../bindings/widgets/media_query_bindings.g.dart';
import '../bindings/widgets/default_text_style_bindings.g.dart';
import '../bindings/widgets/rich_text_bindings.g.dart';
import '../bindings/widgets/animated_container_bindings.g.dart';
import '../bindings/widgets/animated_padding_bindings.g.dart';
import '../bindings/widgets/animated_align_bindings.g.dart';
import '../bindings/widgets/animated_positioned_bindings.g.dart';
import '../bindings/widgets/animated_opacity_bindings.g.dart';
import '../bindings/widgets/animated_default_text_style_bindings.g.dart';
import '../bindings/widgets/animated_physical_model_bindings.g.dart';
import '../bindings/widgets/animated_scale_bindings.g.dart';
import '../bindings/widgets/animated_rotation_bindings.g.dart';
import '../bindings/widgets/animated_slide_bindings.g.dart';
import '../bindings/widgets/animated_switcher_bindings.g.dart';
import '../bindings/widgets/animated_size_bindings.g.dart';
import '../bindings/widgets/slide_transition_bindings.g.dart';
import '../bindings/widgets/scale_transition_bindings.g.dart';
import '../bindings/widgets/rotation_transition_bindings.g.dart';
import '../bindings/widgets/fade_transition_bindings.g.dart';
import '../bindings/widgets/size_transition_bindings.g.dart';
import '../bindings/widgets/decorated_box_transition_bindings.g.dart';
import '../bindings/widgets/hero_bindings.g.dart';
import '../bindings/widgets/page_route_builder_bindings.g.dart';
import '../bindings/widgets/route_settings_bindings.g.dart';
import '../bindings/widgets/dismissible_bindings.g.dart';
import '../bindings/widgets/draggable_scrollable_sheet_bindings.g.dart';
import '../bindings/widgets/placeholder_bindings.g.dart';
import '../bindings/widgets/preferred_size_bindings.g.dart';
import '../bindings/widgets/overlay_bindings.g.dart';
import '../bindings/widgets/overlay_entry_bindings.g.dart';
import '../bindings/widgets/layout_builder_bindings.g.dart';
import '../bindings/widgets/orientation_builder_bindings.g.dart';
import '../bindings/widgets/tooltip_bindings.g.dart';
import '../bindings/widgets/scroll_view_keyboard_dismiss_behavior_bindings.g.dart';
import '../bindings/widgets/connection_state_bindings.g.dart';
import '../bindings/widgets/autovalidate_mode_bindings.g.dart';
import '../bindings/widgets/orientation_bindings.g.dart';

class WidgetsPlugin extends DarticPlugin {
  @override
  String get name => 'package:flutter/widgets.dart';

  @override
  void register(DarticPluginContext ctx) {
    WidgetBindings.register(ctx);
    StatelessWidgetBindings.register(ctx);
    StatefulWidgetBindings.register(ctx);
    StateBindings.register(ctx);
    BuildContextBindings.register(ctx);
    NavigatorBindings.register(ctx);
    CenterBindings.register(ctx);
    ColumnBindings.register(ctx);
    RowBindings.register(ctx);
    SizedBoxBindings.register(ctx);
    PaddingBindings.register(ctx);
    ExpandedBindings.register(ctx);
    ContainerBindings.register(ctx);
    TextBindings.register(ctx);
    IconBindings.register(ctx);
    IconDataBindings.register(ctx);
    StackBindings.register(ctx);
    PositionedBindings.register(ctx);
    PositionedDirectionalBindings.register(ctx);
    IndexedStackBindings.register(ctx);
    FlexBindings.register(ctx);
    FlexibleBindings.register(ctx);
    WrapBindings.register(ctx);
    AlignBindings.register(ctx);
    FittedBoxBindings.register(ctx);
    FractionallySizedBoxBindings.register(ctx);
    LimitedBoxBindings.register(ctx);
    OverflowBoxBindings.register(ctx);
    AspectRatioBindings.register(ctx);
    ConstrainedBoxBindings.register(ctx);
    UnconstrainedBoxBindings.register(ctx);
    IntrinsicWidthBindings.register(ctx);
    IntrinsicHeightBindings.register(ctx);
    OpacityBindings.register(ctx);
    ClipRectBindings.register(ctx);
    ClipRRectBindings.register(ctx);
    ClipOvalBindings.register(ctx);
    ClipPathBindings.register(ctx);
    TransformBindings.register(ctx);
    RotatedBoxBindings.register(ctx);
    FractionalTranslationBindings.register(ctx);
    OffstageBindings.register(ctx);
    IgnorePointerBindings.register(ctx);
    AbsorbPointerBindings.register(ctx);
    RepaintBoundaryBindings.register(ctx);
    ColoredBoxBindings.register(ctx);
    PhysicalModelBindings.register(ctx);
    PhysicalShapeBindings.register(ctx);
    CustomPaintBindings.register(ctx);
    DirectionalityBindings.register(ctx);
    GestureDetectorBindings.register(ctx);
    ListViewBindings.register(ctx);
    GridViewBindings.register(ctx);
    CustomScrollViewBindings.register(ctx);
    SingleChildScrollViewBindings.register(ctx);
    PageViewBindings.register(ctx);
    BuilderBindings.register(ctx);
    StatefulBuilderBindings.register(ctx);
    FadeInImageBindings.register(ctx);
    FormBindings.register(ctx);
    MediaQueryBindings.register(ctx);
    DefaultTextStyleBindings.register(ctx);
    RichTextBindings.register(ctx);
    AnimatedContainerBindings.register(ctx);
    AnimatedPaddingBindings.register(ctx);
    AnimatedAlignBindings.register(ctx);
    AnimatedPositionedBindings.register(ctx);
    AnimatedOpacityBindings.register(ctx);
    AnimatedDefaultTextStyleBindings.register(ctx);
    AnimatedPhysicalModelBindings.register(ctx);
    AnimatedScaleBindings.register(ctx);
    AnimatedRotationBindings.register(ctx);
    AnimatedSlideBindings.register(ctx);
    AnimatedSwitcherBindings.register(ctx);
    AnimatedSizeBindings.register(ctx);
    SlideTransitionBindings.register(ctx);
    ScaleTransitionBindings.register(ctx);
    RotationTransitionBindings.register(ctx);
    FadeTransitionBindings.register(ctx);
    SizeTransitionBindings.register(ctx);
    DecoratedBoxTransitionBindings.register(ctx);
    HeroBindings.register(ctx);
    PageRouteBuilderBindings.register(ctx);
    RouteSettingsBindings.register(ctx);
    DismissibleBindings.register(ctx);
    DraggableScrollableSheetBindings.register(ctx);
    PlaceholderBindings.register(ctx);
    PreferredSizeBindings.register(ctx);
    OverlayBindings.register(ctx);
    OverlayEntryBindings.register(ctx);
    LayoutBuilderBindings.register(ctx);
    OrientationBuilderBindings.register(ctx);
    TooltipBindings.register(ctx);
    ScrollViewKeyboardDismissBehaviorBindings.register(ctx);
    ConnectionStateBindings.register(ctx);
    AutovalidateModeBindings.register(ctx);
    OrientationBindings.register(ctx);
  }
}
