name: dartic_cli
description: Command-line interface for dartic bytecode compiler and runner.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  dartic:
    path: ../../
  dartic_annotation:
    path: ../dartic_annotation
  dartic_compiler:
    path: ../dartic_compiler
  dartic_stdlib:
    path: ../dartic_stdlib
  analyzer: ^8.0.0
  args: ^2.6.0
  kernel:
    path: ../../vendor/dart-sdk/pkg/kernel
  mason_logger: ^0.3.1
  yaml: ^3.1.0
  path: ^1.9.0

dev_dependencies:
  test: ^1.25.6

executables:
  dartic: dartic
