name: dartic_generator
description: CLI code generator for dartic bindings and plugins.
version: 0.2.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^8.0.0
  yaml: ^3.1.0
  args: ^2.6.0
  path: ^1.9.0
  dartic_annotation:
    path: ../dartic_annotation

dev_dependencies:
  test: ^1.24.0
