// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7

// ignore_for_file: implementation_imports, unused_import, unnecessary_import, unnecessary_cast, invalid_use_of_protected_member, deprecated_member_use, sort_child_properties_last

import 'package:dartic/dartic.dart';
import 'package:dartic/src/runtime/object.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/material.dart';

abstract final class ElevatedButtonBindings {
  static void register(DarticPluginContext ctx) {
    ctx.registerClass(
      name: 'package:flutter/src/material/elevated_button.dart::ElevatedButton',
      type: ElevatedButton,
      test: (o) => o is ElevatedButton,
      methods: methodMap(),
      superclasses: ['package:flutter/src/material/button_style_button.dart::ButtonStyleButton', 'package:flutter/src/widgets/framework.dart::StatefulWidget', 'package:flutter/src/widgets/framework.dart::Widget', 'package:flutter/src/foundation/diagnostics.dart::DiagnosticableTree', 'package:flutter/src/foundation/diagnostics.dart::Diagnosticable'],
    );
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#0', (args) => ElevatedButton.styleFrom());
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#1', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#2', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#3', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#4', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#5', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#6', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#7', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#8', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#9', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#10', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?, disabledIconColor: args[9] as Color?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#11', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?, disabledIconColor: args[9] as Color?, overlayColor: args[10] as Color?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#12', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?, disabledIconColor: args[9] as Color?, overlayColor: args[10] as Color?, elevation: args[11] as double?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#13', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?, disabledIconColor: args[9] as Color?, overlayColor: args[10] as Color?, elevation: args[11] as double?, textStyle: args[12] as TextStyle?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#14', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?, disabledIconColor: args[9] as Color?, overlayColor: args[10] as Color?, elevation: args[11] as double?, textStyle: args[12] as TextStyle?, padding: args[13] as EdgeInsetsGeometry?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#15', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?, disabledIconColor: args[9] as Color?, overlayColor: args[10] as Color?, elevation: args[11] as double?, textStyle: args[12] as TextStyle?, padding: args[13] as EdgeInsetsGeometry?, minimumSize: args[14] as Size?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#16', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?, disabledIconColor: args[9] as Color?, overlayColor: args[10] as Color?, elevation: args[11] as double?, textStyle: args[12] as TextStyle?, padding: args[13] as EdgeInsetsGeometry?, minimumSize: args[14] as Size?, fixedSize: args[15] as Size?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#17', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?, disabledIconColor: args[9] as Color?, overlayColor: args[10] as Color?, elevation: args[11] as double?, textStyle: args[12] as TextStyle?, padding: args[13] as EdgeInsetsGeometry?, minimumSize: args[14] as Size?, fixedSize: args[15] as Size?, maximumSize: args[16] as Size?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#18', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?, disabledIconColor: args[9] as Color?, overlayColor: args[10] as Color?, elevation: args[11] as double?, textStyle: args[12] as TextStyle?, padding: args[13] as EdgeInsetsGeometry?, minimumSize: args[14] as Size?, fixedSize: args[15] as Size?, maximumSize: args[16] as Size?, side: args[17] as BorderSide?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#19', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?, disabledIconColor: args[9] as Color?, overlayColor: args[10] as Color?, elevation: args[11] as double?, textStyle: args[12] as TextStyle?, padding: args[13] as EdgeInsetsGeometry?, minimumSize: args[14] as Size?, fixedSize: args[15] as Size?, maximumSize: args[16] as Size?, side: args[17] as BorderSide?, shape: args[18] as OutlinedBorder?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#20', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?, disabledIconColor: args[9] as Color?, overlayColor: args[10] as Color?, elevation: args[11] as double?, textStyle: args[12] as TextStyle?, padding: args[13] as EdgeInsetsGeometry?, minimumSize: args[14] as Size?, fixedSize: args[15] as Size?, maximumSize: args[16] as Size?, side: args[17] as BorderSide?, shape: args[18] as OutlinedBorder?, enabledMouseCursor: args[19] as MouseCursor?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#21', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?, disabledIconColor: args[9] as Color?, overlayColor: args[10] as Color?, elevation: args[11] as double?, textStyle: args[12] as TextStyle?, padding: args[13] as EdgeInsetsGeometry?, minimumSize: args[14] as Size?, fixedSize: args[15] as Size?, maximumSize: args[16] as Size?, side: args[17] as BorderSide?, shape: args[18] as OutlinedBorder?, enabledMouseCursor: args[19] as MouseCursor?, disabledMouseCursor: args[20] as MouseCursor?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#22', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?, disabledIconColor: args[9] as Color?, overlayColor: args[10] as Color?, elevation: args[11] as double?, textStyle: args[12] as TextStyle?, padding: args[13] as EdgeInsetsGeometry?, minimumSize: args[14] as Size?, fixedSize: args[15] as Size?, maximumSize: args[16] as Size?, side: args[17] as BorderSide?, shape: args[18] as OutlinedBorder?, enabledMouseCursor: args[19] as MouseCursor?, disabledMouseCursor: args[20] as MouseCursor?, visualDensity: args[21] as VisualDensity?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#23', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?, disabledIconColor: args[9] as Color?, overlayColor: args[10] as Color?, elevation: args[11] as double?, textStyle: args[12] as TextStyle?, padding: args[13] as EdgeInsetsGeometry?, minimumSize: args[14] as Size?, fixedSize: args[15] as Size?, maximumSize: args[16] as Size?, side: args[17] as BorderSide?, shape: args[18] as OutlinedBorder?, enabledMouseCursor: args[19] as MouseCursor?, disabledMouseCursor: args[20] as MouseCursor?, visualDensity: args[21] as VisualDensity?, tapTargetSize: args[22] as MaterialTapTargetSize?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#24', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?, disabledIconColor: args[9] as Color?, overlayColor: args[10] as Color?, elevation: args[11] as double?, textStyle: args[12] as TextStyle?, padding: args[13] as EdgeInsetsGeometry?, minimumSize: args[14] as Size?, fixedSize: args[15] as Size?, maximumSize: args[16] as Size?, side: args[17] as BorderSide?, shape: args[18] as OutlinedBorder?, enabledMouseCursor: args[19] as MouseCursor?, disabledMouseCursor: args[20] as MouseCursor?, visualDensity: args[21] as VisualDensity?, tapTargetSize: args[22] as MaterialTapTargetSize?, animationDuration: args[23] as Duration?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#25', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?, disabledIconColor: args[9] as Color?, overlayColor: args[10] as Color?, elevation: args[11] as double?, textStyle: args[12] as TextStyle?, padding: args[13] as EdgeInsetsGeometry?, minimumSize: args[14] as Size?, fixedSize: args[15] as Size?, maximumSize: args[16] as Size?, side: args[17] as BorderSide?, shape: args[18] as OutlinedBorder?, enabledMouseCursor: args[19] as MouseCursor?, disabledMouseCursor: args[20] as MouseCursor?, visualDensity: args[21] as VisualDensity?, tapTargetSize: args[22] as MaterialTapTargetSize?, animationDuration: args[23] as Duration?, enableFeedback: args[24] as bool?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#26', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?, disabledIconColor: args[9] as Color?, overlayColor: args[10] as Color?, elevation: args[11] as double?, textStyle: args[12] as TextStyle?, padding: args[13] as EdgeInsetsGeometry?, minimumSize: args[14] as Size?, fixedSize: args[15] as Size?, maximumSize: args[16] as Size?, side: args[17] as BorderSide?, shape: args[18] as OutlinedBorder?, enabledMouseCursor: args[19] as MouseCursor?, disabledMouseCursor: args[20] as MouseCursor?, visualDensity: args[21] as VisualDensity?, tapTargetSize: args[22] as MaterialTapTargetSize?, animationDuration: args[23] as Duration?, enableFeedback: args[24] as bool?, alignment: args[25] as AlignmentGeometry?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#27', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?, disabledIconColor: args[9] as Color?, overlayColor: args[10] as Color?, elevation: args[11] as double?, textStyle: args[12] as TextStyle?, padding: args[13] as EdgeInsetsGeometry?, minimumSize: args[14] as Size?, fixedSize: args[15] as Size?, maximumSize: args[16] as Size?, side: args[17] as BorderSide?, shape: args[18] as OutlinedBorder?, enabledMouseCursor: args[19] as MouseCursor?, disabledMouseCursor: args[20] as MouseCursor?, visualDensity: args[21] as VisualDensity?, tapTargetSize: args[22] as MaterialTapTargetSize?, animationDuration: args[23] as Duration?, enableFeedback: args[24] as bool?, alignment: args[25] as AlignmentGeometry?, splashFactory: args[26] as InteractiveInkFeatureFactory?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#28', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?, disabledIconColor: args[9] as Color?, overlayColor: args[10] as Color?, elevation: args[11] as double?, textStyle: args[12] as TextStyle?, padding: args[13] as EdgeInsetsGeometry?, minimumSize: args[14] as Size?, fixedSize: args[15] as Size?, maximumSize: args[16] as Size?, side: args[17] as BorderSide?, shape: args[18] as OutlinedBorder?, enabledMouseCursor: args[19] as MouseCursor?, disabledMouseCursor: args[20] as MouseCursor?, visualDensity: args[21] as VisualDensity?, tapTargetSize: args[22] as MaterialTapTargetSize?, animationDuration: args[23] as Duration?, enableFeedback: args[24] as bool?, alignment: args[25] as AlignmentGeometry?, splashFactory: args[26] as InteractiveInkFeatureFactory?, backgroundBuilder: args[27] as Widget Function(BuildContext, Set<WidgetState>, Widget?)?));
    ctx.registerBinding('package:flutter/src/material/elevated_button.dart::ElevatedButton::styleFrom#29', (args) => ElevatedButton.styleFrom(foregroundColor: args[0] as Color?, backgroundColor: args[1] as Color?, disabledForegroundColor: args[2] as Color?, disabledBackgroundColor: args[3] as Color?, shadowColor: args[4] as Color?, surfaceTintColor: args[5] as Color?, iconColor: args[6] as Color?, iconSize: args[7] as double?, iconAlignment: args[8] as IconAlignment?, disabledIconColor: args[9] as Color?, overlayColor: args[10] as Color?, elevation: args[11] as double?, textStyle: args[12] as TextStyle?, padding: args[13] as EdgeInsetsGeometry?, minimumSize: args[14] as Size?, fixedSize: args[15] as Size?, maximumSize: args[16] as Size?, side: args[17] as BorderSide?, shape: args[18] as OutlinedBorder?, enabledMouseCursor: args[19] as MouseCursor?, disabledMouseCursor: args[20] as MouseCursor?, visualDensity: args[21] as VisualDensity?, tapTargetSize: args[22] as MaterialTapTargetSize?, animationDuration: args[23] as Duration?, enableFeedback: args[24] as bool?, alignment: args[25] as AlignmentGeometry?, splashFactory: args[26] as InteractiveInkFeatureFactory?, backgroundBuilder: args[27] as Widget Function(BuildContext, Set<WidgetState>, Widget?)?, foregroundBuilder: args[28] as Widget Function(BuildContext, Set<WidgetState>, Widget?)?));
  }

  static Map<String, Object? Function(List<Object?>)> methodMap() => {
        'defaultStyleOf#1': (args) => (args[0] as ElevatedButton).defaultStyleOf(args[1] as BuildContext),
        'themeStyleOf#1': (args) => (args[0] as ElevatedButton).themeStyleOf(args[1] as BuildContext),
        'createState#0': (args) => (args[0] as ElevatedButton).createState(),
        'debugFillProperties#1': (args) { (args[0] as ElevatedButton).debugFillProperties(args[1] as DiagnosticPropertiesBuilder); return null; },
        'createElement#0': (args) => (args[0] as ElevatedButton).createElement(),
        'toStringShort#0': (args) => (args[0] as ElevatedButton).toStringShort(),
        'toStringShallow#2': (args) => (args[0] as ElevatedButton).toStringShallow(joiner: args[1] as String, minLevel: args[2] as DiagnosticLevel),
        'toStringDeep#4': (args) => (args[0] as ElevatedButton).toStringDeep(prefixLineOne: args[1] as String, prefixOtherLines: args[2] as String?, minLevel: args[3] as DiagnosticLevel, wrapWidth: args[4] as int),
        'toDiagnosticsNode#2': (args) => (args[0] as ElevatedButton).toDiagnosticsNode(name: args[1] as String?, style: args[2] as DiagnosticsTreeStyle?),
        'debugDescribeChildren#0': (args) => (args[0] as ElevatedButton).debugDescribeChildren(),
        'onPressed#0': (args) => (args[0] as ElevatedButton).onPressed,
        'onLongPress#0': (args) => (args[0] as ElevatedButton).onLongPress,
        'onHover#0': (args) => (args[0] as ElevatedButton).onHover,
        'onFocusChange#0': (args) => (args[0] as ElevatedButton).onFocusChange,
        'style#0': (args) => (args[0] as ElevatedButton).style,
        'clipBehavior#0': (args) => (args[0] as ElevatedButton).clipBehavior,
        'focusNode#0': (args) => (args[0] as ElevatedButton).focusNode,
        'autofocus#0': (args) => (args[0] as ElevatedButton).autofocus,
        'statesController#0': (args) => (args[0] as ElevatedButton).statesController,
        'isSemanticButton#0': (args) => (args[0] as ElevatedButton).isSemanticButton,
        'iconAlignment#0': (args) => (args[0] as ElevatedButton).iconAlignment,
        'tooltip#0': (args) => (args[0] as ElevatedButton).tooltip,
        'child#0': (args) => (args[0] as ElevatedButton).child,
        'enabled#0': (args) => (args[0] as ElevatedButton).enabled,
        'key#0': (args) => (args[0] as ElevatedButton).key,
        '#11': (args) => ElevatedButton(key: args[0] as Key?, onPressed: args[1] as void Function()?, onLongPress: args[2] as void Function()?, onHover: args[3] as void Function(bool)?, onFocusChange: args[4] as void Function(bool)?, style: args[5] as ButtonStyle?, focusNode: args[6] as FocusNode?, autofocus: args[7] as bool, clipBehavior: args[8] as Clip?, statesController: args[9] as WidgetStatesController?, child: args[10] as Widget?),
        'icon#13': (args) => ElevatedButton.icon(key: args[0] as Key?, onPressed: args[1] as void Function()?, onLongPress: args[2] as void Function()?, onHover: args[3] as void Function(bool)?, onFocusChange: args[4] as void Function(bool)?, style: args[5] as ButtonStyle?, focusNode: args[6] as FocusNode?, autofocus: args[7] as bool?, clipBehavior: args[8] as Clip?, statesController: args[9] as WidgetStatesController?, icon: args[10] as Widget?, label: args[11] as Widget, iconAlignment: args[12] as IconAlignment?),
      };
}
