// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7

// ignore_for_file: implementation_imports, unused_import, unnecessary_import, unnecessary_cast, invalid_use_of_protected_member, deprecated_member_use, sort_child_properties_last

import 'package:dartic/dartic.dart';
import 'package:dartic/dartic_internal.dart';
import 'package:flutter/animation.dart';
import 'package:flutter/foundation.dart';

abstract final class AlertDialogBindings {
  static void register(DarticPluginContext ctx) {
    ctx.registerClass(
      name: 'package:flutter/src/material/dialog.dart::AlertDialog',
      type: AlertDialog,
      test: (o) => o is AlertDialog,
      methods: methodMap(),
      superclasses: ['package:flutter/src/widgets/framework.dart::StatelessWidget', 'package:flutter/src/widgets/framework.dart::Widget', 'package:flutter/src/foundation/diagnostics.dart::DiagnosticableTree', 'package:flutter/src/foundation/diagnostics.dart::Diagnosticable'],
    );
  }

  static Map<String, Object? Function(List<Object?>)> methodMap() => {
        'build#1': (args) => (args[0] as AlertDialog).build(args[1] as BuildContext),
        'createElement#0': (args) => (args[0] as AlertDialog).createElement(),
        'toStringShort#0': (args) => (args[0] as AlertDialog).toStringShort(),
        'debugFillProperties#1': (args) { (args[0] as AlertDialog).debugFillProperties(args[1] as DiagnosticPropertiesBuilder); return null; },
        'toStringShallow#2': (args) => (args[0] as AlertDialog).toStringShallow(joiner: identical(args[1], darticAbsent) ? ', ' : args[1] as String, minLevel: identical(args[2], darticAbsent) ? DiagnosticLevel.debug : args[2] as DiagnosticLevel),
        'toStringDeep#4': (args) => (args[0] as AlertDialog).toStringDeep(prefixLineOne: identical(args[1], darticAbsent) ? '' : args[1] as String, prefixOtherLines: identical(args[2], darticAbsent) ? null : args[2] as String?, minLevel: identical(args[3], darticAbsent) ? DiagnosticLevel.debug : args[3] as DiagnosticLevel, wrapWidth: identical(args[4], darticAbsent) ? 65 : args[4] as int),
        'toDiagnosticsNode#2': (args) => (args[0] as AlertDialog).toDiagnosticsNode(name: identical(args[1], darticAbsent) ? null : args[1] as String?, style: identical(args[2], darticAbsent) ? null : args[2] as DiagnosticsTreeStyle?),
        'debugDescribeChildren#0': (args) => (args[0] as AlertDialog).debugDescribeChildren(),
        'icon#0': (args) => (args[0] as AlertDialog).icon,
        'iconColor#0': (args) => (args[0] as AlertDialog).iconColor,
        'iconPadding#0': (args) => (args[0] as AlertDialog).iconPadding,
        'title#0': (args) => (args[0] as AlertDialog).title,
        'titlePadding#0': (args) => (args[0] as AlertDialog).titlePadding,
        'titleTextStyle#0': (args) => (args[0] as AlertDialog).titleTextStyle,
        'content#0': (args) => (args[0] as AlertDialog).content,
        'contentPadding#0': (args) => (args[0] as AlertDialog).contentPadding,
        'contentTextStyle#0': (args) => (args[0] as AlertDialog).contentTextStyle,
        'actions#0': (args) => (args[0] as AlertDialog).actions,
        'actionsPadding#0': (args) => (args[0] as AlertDialog).actionsPadding,
        'actionsAlignment#0': (args) => (args[0] as AlertDialog).actionsAlignment,
        'actionsOverflowAlignment#0': (args) => (args[0] as AlertDialog).actionsOverflowAlignment,
        'actionsOverflowDirection#0': (args) => (args[0] as AlertDialog).actionsOverflowDirection,
        'actionsOverflowButtonSpacing#0': (args) => (args[0] as AlertDialog).actionsOverflowButtonSpacing,
        'buttonPadding#0': (args) => (args[0] as AlertDialog).buttonPadding,
        'backgroundColor#0': (args) => (args[0] as AlertDialog).backgroundColor,
        'elevation#0': (args) => (args[0] as AlertDialog).elevation,
        'shadowColor#0': (args) => (args[0] as AlertDialog).shadowColor,
        'surfaceTintColor#0': (args) => (args[0] as AlertDialog).surfaceTintColor,
        'semanticLabel#0': (args) => (args[0] as AlertDialog).semanticLabel,
        'insetPadding#0': (args) => (args[0] as AlertDialog).insetPadding,
        'clipBehavior#0': (args) => (args[0] as AlertDialog).clipBehavior,
        'shape#0': (args) => (args[0] as AlertDialog).shape,
        'alignment#0': (args) => (args[0] as AlertDialog).alignment,
        'constraints#0': (args) => (args[0] as AlertDialog).constraints,
        'scrollable#0': (args) => (args[0] as AlertDialog).scrollable,
        'key#0': (args) => (args[0] as AlertDialog).key,
        '#28': (args) => AlertDialog(key: identical(args[0], darticAbsent) ? null : args[0] as Key?, icon: identical(args[1], darticAbsent) ? null : args[1] as Widget?, iconPadding: identical(args[2], darticAbsent) ? null : args[2] as EdgeInsetsGeometry?, iconColor: identical(args[3], darticAbsent) ? null : args[3] as Color?, title: identical(args[4], darticAbsent) ? null : args[4] as Widget?, titlePadding: identical(args[5], darticAbsent) ? null : args[5] as EdgeInsetsGeometry?, titleTextStyle: identical(args[6], darticAbsent) ? null : args[6] as TextStyle?, content: identical(args[7], darticAbsent) ? null : args[7] as Widget?, contentPadding: identical(args[8], darticAbsent) ? null : args[8] as EdgeInsetsGeometry?, contentTextStyle: identical(args[9], darticAbsent) ? null : args[9] as TextStyle?, actions: identical(args[10], darticAbsent) ? null : args[10] == null ? null : (args[10] as List).cast<Widget>(), actionsPadding: identical(args[11], darticAbsent) ? null : args[11] as EdgeInsetsGeometry?, actionsAlignment: identical(args[12], darticAbsent) ? null : args[12] as MainAxisAlignment?, actionsOverflowAlignment: identical(args[13], darticAbsent) ? null : args[13] as OverflowBarAlignment?, actionsOverflowDirection: identical(args[14], darticAbsent) ? null : args[14] as VerticalDirection?, actionsOverflowButtonSpacing: identical(args[15], darticAbsent) ? null : args[15] as double?, buttonPadding: identical(args[16], darticAbsent) ? null : args[16] as EdgeInsetsGeometry?, backgroundColor: identical(args[17], darticAbsent) ? null : args[17] as Color?, elevation: identical(args[18], darticAbsent) ? null : args[18] as double?, shadowColor: identical(args[19], darticAbsent) ? null : args[19] as Color?, surfaceTintColor: identical(args[20], darticAbsent) ? null : args[20] as Color?, semanticLabel: identical(args[21], darticAbsent) ? null : args[21] as String?, insetPadding: identical(args[22], darticAbsent) ? null : args[22] as EdgeInsets?, clipBehavior: identical(args[23], darticAbsent) ? null : args[23] as Clip?, shape: identical(args[24], darticAbsent) ? null : args[24] as ShapeBorder?, alignment: identical(args[25], darticAbsent) ? null : args[25] as AlignmentGeometry?, constraints: identical(args[26], darticAbsent) ? null : args[26] as BoxConstraints?, scrollable: identical(args[27], darticAbsent) ? false : args[27] as bool),
        'adaptive#32': (args) {
          if (identical(args[22], darticAbsent)) {
            if (identical(args[27], darticAbsent)) {
              if (identical(args[30], darticAbsent)) {
                if (identical(args[31], darticAbsent)) {
                  return AlertDialog.adaptive(key: identical(args[0], darticAbsent) ? null : args[0] as Key?, icon: identical(args[1], darticAbsent) ? null : args[1] as Widget?, iconPadding: identical(args[2], darticAbsent) ? null : args[2] as EdgeInsetsGeometry?, iconColor: identical(args[3], darticAbsent) ? null : args[3] as Color?, title: identical(args[4], darticAbsent) ? null : args[4] as Widget?, titlePadding: identical(args[5], darticAbsent) ? null : args[5] as EdgeInsetsGeometry?, titleTextStyle: identical(args[6], darticAbsent) ? null : args[6] as TextStyle?, content: identical(args[7], darticAbsent) ? null : args[7] as Widget?, contentPadding: identical(args[8], darticAbsent) ? null : args[8] as EdgeInsetsGeometry?, contentTextStyle: identical(args[9], darticAbsent) ? null : args[9] as TextStyle?, actions: identical(args[10], darticAbsent) ? null : args[10] == null ? null : (args[10] as List).cast<Widget>(), actionsPadding: identical(args[11], darticAbsent) ? null : args[11] as EdgeInsetsGeometry?, actionsAlignment: identical(args[12], darticAbsent) ? null : args[12] as MainAxisAlignment?, actionsOverflowAlignment: identical(args[13], darticAbsent) ? null : args[13] as OverflowBarAlignment?, actionsOverflowDirection: identical(args[14], darticAbsent) ? null : args[14] as VerticalDirection?, actionsOverflowButtonSpacing: identical(args[15], darticAbsent) ? null : args[15] as double?, buttonPadding: identical(args[16], darticAbsent) ? null : args[16] as EdgeInsetsGeometry?, backgroundColor: identical(args[17], darticAbsent) ? null : args[17] as Color?, elevation: identical(args[18], darticAbsent) ? null : args[18] as double?, shadowColor: identical(args[19], darticAbsent) ? null : args[19] as Color?, surfaceTintColor: identical(args[20], darticAbsent) ? null : args[20] as Color?, semanticLabel: identical(args[21], darticAbsent) ? null : args[21] as String?, clipBehavior: identical(args[23], darticAbsent) ? null : args[23] as Clip?, shape: identical(args[24], darticAbsent) ? null : args[24] as ShapeBorder?, alignment: identical(args[25], darticAbsent) ? null : args[25] as AlignmentGeometry?, constraints: identical(args[26], darticAbsent) ? null : args[26] as BoxConstraints?, scrollController: identical(args[28], darticAbsent) ? null : args[28] as ScrollController?, actionScrollController: identical(args[29], darticAbsent) ? null : args[29] as ScrollController?);
                } else {
                  return AlertDialog.adaptive(key: identical(args[0], darticAbsent) ? null : args[0] as Key?, icon: identical(args[1], darticAbsent) ? null : args[1] as Widget?, iconPadding: identical(args[2], darticAbsent) ? null : args[2] as EdgeInsetsGeometry?, iconColor: identical(args[3], darticAbsent) ? null : args[3] as Color?, title: identical(args[4], darticAbsent) ? null : args[4] as Widget?, titlePadding: identical(args[5], darticAbsent) ? null : args[5] as EdgeInsetsGeometry?, titleTextStyle: identical(args[6], darticAbsent) ? null : args[6] as TextStyle?, content: identical(args[7], darticAbsent) ? null : args[7] as Widget?, contentPadding: identical(args[8], darticAbsent) ? null : args[8] as EdgeInsetsGeometry?, contentTextStyle: identical(args[9], darticAbsent) ? null : args[9] as TextStyle?, actions: identical(args[10], darticAbsent) ? null : args[10] == null ? null : (args[10] as List).cast<Widget>(), actionsPadding: identical(args[11], darticAbsent) ? null : args[11] as EdgeInsetsGeometry?, actionsAlignment: identical(args[12], darticAbsent) ? null : args[12] as MainAxisAlignment?, actionsOverflowAlignment: identical(args[13], darticAbsent) ? null : args[13] as OverflowBarAlignment?, actionsOverflowDirection: identical(args[14], darticAbsent) ? null : args[14] as VerticalDirection?, actionsOverflowButtonSpacing: identical(args[15], darticAbsent) ? null : args[15] as double?, buttonPadding: identical(args[16], darticAbsent) ? null : args[16] as EdgeInsetsGeometry?, backgroundColor: identical(args[17], darticAbsent) ? null : args[17] as Color?, elevation: identical(args[18], darticAbsent) ? null : args[18] as double?, shadowColor: identical(args[19], darticAbsent) ? null : args[19] as Color?, surfaceTintColor: identical(args[20], darticAbsent) ? null : args[20] as Color?, semanticLabel: identical(args[21], darticAbsent) ? null : args[21] as String?, clipBehavior: identical(args[23], darticAbsent) ? null : args[23] as Clip?, shape: identical(args[24], darticAbsent) ? null : args[24] as ShapeBorder?, alignment: identical(args[25], darticAbsent) ? null : args[25] as AlignmentGeometry?, constraints: identical(args[26], darticAbsent) ? null : args[26] as BoxConstraints?, scrollController: identical(args[28], darticAbsent) ? null : args[28] as ScrollController?, actionScrollController: identical(args[29], darticAbsent) ? null : args[29] as ScrollController?, insetAnimationCurve: args[31] as Curve);
                }
              } else {
                if (identical(args[31], darticAbsent)) {
                  return AlertDialog.adaptive(key: identical(args[0], darticAbsent) ? null : args[0] as Key?, icon: identical(args[1], darticAbsent) ? null : args[1] as Widget?, iconPadding: identical(args[2], darticAbsent) ? null : args[2] as EdgeInsetsGeometry?, iconColor: identical(args[3], darticAbsent) ? null : args[3] as Color?, title: identical(args[4], darticAbsent) ? null : args[4] as Widget?, titlePadding: identical(args[5], darticAbsent) ? null : args[5] as EdgeInsetsGeometry?, titleTextStyle: identical(args[6], darticAbsent) ? null : args[6] as TextStyle?, content: identical(args[7], darticAbsent) ? null : args[7] as Widget?, contentPadding: identical(args[8], darticAbsent) ? null : args[8] as EdgeInsetsGeometry?, contentTextStyle: identical(args[9], darticAbsent) ? null : args[9] as TextStyle?, actions: identical(args[10], darticAbsent) ? null : args[10] == null ? null : (args[10] as List).cast<Widget>(), actionsPadding: identical(args[11], darticAbsent) ? null : args[11] as EdgeInsetsGeometry?, actionsAlignment: identical(args[12], darticAbsent) ? null : args[12] as MainAxisAlignment?, actionsOverflowAlignment: identical(args[13], darticAbsent) ? null : args[13] as OverflowBarAlignment?, actionsOverflowDirection: identical(args[14], darticAbsent) ? null : args[14] as VerticalDirection?, actionsOverflowButtonSpacing: identical(args[15], darticAbsent) ? null : args[15] as double?, buttonPadding: identical(args[16], darticAbsent) ? null : args[16] as EdgeInsetsGeometry?, backgroundColor: identical(args[17], darticAbsent) ? null : args[17] as Color?, elevation: identical(args[18], darticAbsent) ? null : args[18] as double?, shadowColor: identical(args[19], darticAbsent) ? null : args[19] as Color?, surfaceTintColor: identical(args[20], darticAbsent) ? null : args[20] as Color?, semanticLabel: identical(args[21], darticAbsent) ? null : args[21] as String?, clipBehavior: identical(args[23], darticAbsent) ? null : args[23] as Clip?, shape: identical(args[24], darticAbsent) ? null : args[24] as ShapeBorder?, alignment: identical(args[25], darticAbsent) ? null : args[25] as AlignmentGeometry?, constraints: identical(args[26], darticAbsent) ? null : args[26] as BoxConstraints?, scrollController: identical(args[28], darticAbsent) ? null : args[28] as ScrollController?, actionScrollController: identical(args[29], darticAbsent) ? null : args[29] as ScrollController?, insetAnimationDuration: args[30] as Duration);
                } else {
                  return AlertDialog.adaptive(key: identical(args[0], darticAbsent) ? null : args[0] as Key?, icon: identical(args[1], darticAbsent) ? null : args[1] as Widget?, iconPadding: identical(args[2], darticAbsent) ? null : args[2] as EdgeInsetsGeometry?, iconColor: identical(args[3], darticAbsent) ? null : args[3] as Color?, title: identical(args[4], darticAbsent) ? null : args[4] as Widget?, titlePadding: identical(args[5], darticAbsent) ? null : args[5] as EdgeInsetsGeometry?, titleTextStyle: identical(args[6], darticAbsent) ? null : args[6] as TextStyle?, content: identical(args[7], darticAbsent) ? null : args[7] as Widget?, contentPadding: identical(args[8], darticAbsent) ? null : args[8] as EdgeInsetsGeometry?, contentTextStyle: identical(args[9], darticAbsent) ? null : args[9] as TextStyle?, actions: identical(args[10], darticAbsent) ? null : args[10] == null ? null : (args[10] as List).cast<Widget>(), actionsPadding: identical(args[11], darticAbsent) ? null : args[11] as EdgeInsetsGeometry?, actionsAlignment: identical(args[12], darticAbsent) ? null : args[12] as MainAxisAlignment?, actionsOverflowAlignment: identical(args[13], darticAbsent) ? null : args[13] as OverflowBarAlignment?, actionsOverflowDirection: identical(args[14], darticAbsent) ? null : args[14] as VerticalDirection?, actionsOverflowButtonSpacing: identical(args[15], darticAbsent) ? null : args[15] as double?, buttonPadding: identical(args[16], darticAbsent) ? null : args[16] as EdgeInsetsGeometry?, backgroundColor: identical(args[17], darticAbsent) ? null : args[17] as Color?, elevation: identical(args[18], darticAbsent) ? null : args[18] as double?, shadowColor: identical(args[19], darticAbsent) ? null : args[19] as Color?, surfaceTintColor: identical(args[20], darticAbsent) ? null : args[20] as Color?, semanticLabel: identical(args[21], darticAbsent) ? null : args[21] as String?, clipBehavior: identical(args[23], darticAbsent) ? null : args[23] as Clip?, shape: identical(args[24], darticAbsent) ? null : args[24] as ShapeBorder?, alignment: identical(args[25], darticAbsent) ? null : args[25] as AlignmentGeometry?, constraints: identical(args[26], darticAbsent) ? null : args[26] as BoxConstraints?, scrollController: identical(args[28], darticAbsent) ? null : args[28] as ScrollController?, actionScrollController: identical(args[29], darticAbsent) ? null : args[29] as ScrollController?, insetAnimationDuration: args[30] as Duration, insetAnimationCurve: args[31] as Curve);
                }
              }
            } else {
              if (identical(args[30], darticAbsent)) {
                if (identical(args[31], darticAbsent)) {
                  return AlertDialog.adaptive(key: identical(args[0], darticAbsent) ? null : args[0] as Key?, icon: identical(args[1], darticAbsent) ? null : args[1] as Widget?, iconPadding: identical(args[2], darticAbsent) ? null : args[2] as EdgeInsetsGeometry?, iconColor: identical(args[3], darticAbsent) ? null : args[3] as Color?, title: identical(args[4], darticAbsent) ? null : args[4] as Widget?, titlePadding: identical(args[5], darticAbsent) ? null : args[5] as EdgeInsetsGeometry?, titleTextStyle: identical(args[6], darticAbsent) ? null : args[6] as TextStyle?, content: identical(args[7], darticAbsent) ? null : args[7] as Widget?, contentPadding: identical(args[8], darticAbsent) ? null : args[8] as EdgeInsetsGeometry?, contentTextStyle: identical(args[9], darticAbsent) ? null : args[9] as TextStyle?, actions: identical(args[10], darticAbsent) ? null : args[10] == null ? null : (args[10] as List).cast<Widget>(), actionsPadding: identical(args[11], darticAbsent) ? null : args[11] as EdgeInsetsGeometry?, actionsAlignment: identical(args[12], darticAbsent) ? null : args[12] as MainAxisAlignment?, actionsOverflowAlignment: identical(args[13], darticAbsent) ? null : args[13] as OverflowBarAlignment?, actionsOverflowDirection: identical(args[14], darticAbsent) ? null : args[14] as VerticalDirection?, actionsOverflowButtonSpacing: identical(args[15], darticAbsent) ? null : args[15] as double?, buttonPadding: identical(args[16], darticAbsent) ? null : args[16] as EdgeInsetsGeometry?, backgroundColor: identical(args[17], darticAbsent) ? null : args[17] as Color?, elevation: identical(args[18], darticAbsent) ? null : args[18] as double?, shadowColor: identical(args[19], darticAbsent) ? null : args[19] as Color?, surfaceTintColor: identical(args[20], darticAbsent) ? null : args[20] as Color?, semanticLabel: identical(args[21], darticAbsent) ? null : args[21] as String?, clipBehavior: identical(args[23], darticAbsent) ? null : args[23] as Clip?, shape: identical(args[24], darticAbsent) ? null : args[24] as ShapeBorder?, alignment: identical(args[25], darticAbsent) ? null : args[25] as AlignmentGeometry?, constraints: identical(args[26], darticAbsent) ? null : args[26] as BoxConstraints?, scrollable: args[27] as bool, scrollController: identical(args[28], darticAbsent) ? null : args[28] as ScrollController?, actionScrollController: identical(args[29], darticAbsent) ? null : args[29] as ScrollController?);
                } else {
                  return AlertDialog.adaptive(key: identical(args[0], darticAbsent) ? null : args[0] as Key?, icon: identical(args[1], darticAbsent) ? null : args[1] as Widget?, iconPadding: identical(args[2], darticAbsent) ? null : args[2] as EdgeInsetsGeometry?, iconColor: identical(args[3], darticAbsent) ? null : args[3] as Color?, title: identical(args[4], darticAbsent) ? null : args[4] as Widget?, titlePadding: identical(args[5], darticAbsent) ? null : args[5] as EdgeInsetsGeometry?, titleTextStyle: identical(args[6], darticAbsent) ? null : args[6] as TextStyle?, content: identical(args[7], darticAbsent) ? null : args[7] as Widget?, contentPadding: identical(args[8], darticAbsent) ? null : args[8] as EdgeInsetsGeometry?, contentTextStyle: identical(args[9], darticAbsent) ? null : args[9] as TextStyle?, actions: identical(args[10], darticAbsent) ? null : args[10] == null ? null : (args[10] as List).cast<Widget>(), actionsPadding: identical(args[11], darticAbsent) ? null : args[11] as EdgeInsetsGeometry?, actionsAlignment: identical(args[12], darticAbsent) ? null : args[12] as MainAxisAlignment?, actionsOverflowAlignment: identical(args[13], darticAbsent) ? null : args[13] as OverflowBarAlignment?, actionsOverflowDirection: identical(args[14], darticAbsent) ? null : args[14] as VerticalDirection?, actionsOverflowButtonSpacing: identical(args[15], darticAbsent) ? null : args[15] as double?, buttonPadding: identical(args[16], darticAbsent) ? null : args[16] as EdgeInsetsGeometry?, backgroundColor: identical(args[17], darticAbsent) ? null : args[17] as Color?, elevation: identical(args[18], darticAbsent) ? null : args[18] as double?, shadowColor: identical(args[19], darticAbsent) ? null : args[19] as Color?, surfaceTintColor: identical(args[20], darticAbsent) ? null : args[20] as Color?, semanticLabel: identical(args[21], darticAbsent) ? null : args[21] as String?, clipBehavior: identical(args[23], darticAbsent) ? null : args[23] as Clip?, shape: identical(args[24], darticAbsent) ? null : args[24] as ShapeBorder?, alignment: identical(args[25], darticAbsent) ? null : args[25] as AlignmentGeometry?, constraints: identical(args[26], darticAbsent) ? null : args[26] as BoxConstraints?, scrollable: args[27] as bool, scrollController: identical(args[28], darticAbsent) ? null : args[28] as ScrollController?, actionScrollController: identical(args[29], darticAbsent) ? null : args[29] as ScrollController?, insetAnimationCurve: args[31] as Curve);
                }
              } else {
                if (identical(args[31], darticAbsent)) {
                  return AlertDialog.adaptive(key: identical(args[0], darticAbsent) ? null : args[0] as Key?, icon: identical(args[1], darticAbsent) ? null : args[1] as Widget?, iconPadding: identical(args[2], darticAbsent) ? null : args[2] as EdgeInsetsGeometry?, iconColor: identical(args[3], darticAbsent) ? null : args[3] as Color?, title: identical(args[4], darticAbsent) ? null : args[4] as Widget?, titlePadding: identical(args[5], darticAbsent) ? null : args[5] as EdgeInsetsGeometry?, titleTextStyle: identical(args[6], darticAbsent) ? null : args[6] as TextStyle?, content: identical(args[7], darticAbsent) ? null : args[7] as Widget?, contentPadding: identical(args[8], darticAbsent) ? null : args[8] as EdgeInsetsGeometry?, contentTextStyle: identical(args[9], darticAbsent) ? null : args[9] as TextStyle?, actions: identical(args[10], darticAbsent) ? null : args[10] == null ? null : (args[10] as List).cast<Widget>(), actionsPadding: identical(args[11], darticAbsent) ? null : args[11] as EdgeInsetsGeometry?, actionsAlignment: identical(args[12], darticAbsent) ? null : args[12] as MainAxisAlignment?, actionsOverflowAlignment: identical(args[13], darticAbsent) ? null : args[13] as OverflowBarAlignment?, actionsOverflowDirection: identical(args[14], darticAbsent) ? null : args[14] as VerticalDirection?, actionsOverflowButtonSpacing: identical(args[15], darticAbsent) ? null : args[15] as double?, buttonPadding: identical(args[16], darticAbsent) ? null : args[16] as EdgeInsetsGeometry?, backgroundColor: identical(args[17], darticAbsent) ? null : args[17] as Color?, elevation: identical(args[18], darticAbsent) ? null : args[18] as double?, shadowColor: identical(args[19], darticAbsent) ? null : args[19] as Color?, surfaceTintColor: identical(args[20], darticAbsent) ? null : args[20] as Color?, semanticLabel: identical(args[21], darticAbsent) ? null : args[21] as String?, clipBehavior: identical(args[23], darticAbsent) ? null : args[23] as Clip?, shape: identical(args[24], darticAbsent) ? null : args[24] as ShapeBorder?, alignment: identical(args[25], darticAbsent) ? null : args[25] as AlignmentGeometry?, constraints: identical(args[26], darticAbsent) ? null : args[26] as BoxConstraints?, scrollable: args[27] as bool, scrollController: identical(args[28], darticAbsent) ? null : args[28] as ScrollController?, actionScrollController: identical(args[29], darticAbsent) ? null : args[29] as ScrollController?, insetAnimationDuration: args[30] as Duration);
                } else {
                  return AlertDialog.adaptive(key: identical(args[0], darticAbsent) ? null : args[0] as Key?, icon: identical(args[1], darticAbsent) ? null : args[1] as Widget?, iconPadding: identical(args[2], darticAbsent) ? null : args[2] as EdgeInsetsGeometry?, iconColor: identical(args[3], darticAbsent) ? null : args[3] as Color?, title: identical(args[4], darticAbsent) ? null : args[4] as Widget?, titlePadding: identical(args[5], darticAbsent) ? null : args[5] as EdgeInsetsGeometry?, titleTextStyle: identical(args[6], darticAbsent) ? null : args[6] as TextStyle?, content: identical(args[7], darticAbsent) ? null : args[7] as Widget?, contentPadding: identical(args[8], darticAbsent) ? null : args[8] as EdgeInsetsGeometry?, contentTextStyle: identical(args[9], darticAbsent) ? null : args[9] as TextStyle?, actions: identical(args[10], darticAbsent) ? null : args[10] == null ? null : (args[10] as List).cast<Widget>(), actionsPadding: identical(args[11], darticAbsent) ? null : args[11] as EdgeInsetsGeometry?, actionsAlignment: identical(args[12], darticAbsent) ? null : args[12] as MainAxisAlignment?, actionsOverflowAlignment: identical(args[13], darticAbsent) ? null : args[13] as OverflowBarAlignment?, actionsOverflowDirection: identical(args[14], darticAbsent) ? null : args[14] as VerticalDirection?, actionsOverflowButtonSpacing: identical(args[15], darticAbsent) ? null : args[15] as double?, buttonPadding: identical(args[16], darticAbsent) ? null : args[16] as EdgeInsetsGeometry?, backgroundColor: identical(args[17], darticAbsent) ? null : args[17] as Color?, elevation: identical(args[18], darticAbsent) ? null : args[18] as double?, shadowColor: identical(args[19], darticAbsent) ? null : args[19] as Color?, surfaceTintColor: identical(args[20], darticAbsent) ? null : args[20] as Color?, semanticLabel: identical(args[21], darticAbsent) ? null : args[21] as String?, clipBehavior: identical(args[23], darticAbsent) ? null : args[23] as Clip?, shape: identical(args[24], darticAbsent) ? null : args[24] as ShapeBorder?, alignment: identical(args[25], darticAbsent) ? null : args[25] as AlignmentGeometry?, constraints: identical(args[26], darticAbsent) ? null : args[26] as BoxConstraints?, scrollable: args[27] as bool, scrollController: identical(args[28], darticAbsent) ? null : args[28] as ScrollController?, actionScrollController: identical(args[29], darticAbsent) ? null : args[29] as ScrollController?, insetAnimationDuration: args[30] as Duration, insetAnimationCurve: args[31] as Curve);
                }
              }
            }
          } else {
            if (identical(args[27], darticAbsent)) {
              if (identical(args[30], darticAbsent)) {
                if (identical(args[31], darticAbsent)) {
                  return AlertDialog.adaptive(key: identical(args[0], darticAbsent) ? null : args[0] as Key?, icon: identical(args[1], darticAbsent) ? null : args[1] as Widget?, iconPadding: identical(args[2], darticAbsent) ? null : args[2] as EdgeInsetsGeometry?, iconColor: identical(args[3], darticAbsent) ? null : args[3] as Color?, title: identical(args[4], darticAbsent) ? null : args[4] as Widget?, titlePadding: identical(args[5], darticAbsent) ? null : args[5] as EdgeInsetsGeometry?, titleTextStyle: identical(args[6], darticAbsent) ? null : args[6] as TextStyle?, content: identical(args[7], darticAbsent) ? null : args[7] as Widget?, contentPadding: identical(args[8], darticAbsent) ? null : args[8] as EdgeInsetsGeometry?, contentTextStyle: identical(args[9], darticAbsent) ? null : args[9] as TextStyle?, actions: identical(args[10], darticAbsent) ? null : args[10] == null ? null : (args[10] as List).cast<Widget>(), actionsPadding: identical(args[11], darticAbsent) ? null : args[11] as EdgeInsetsGeometry?, actionsAlignment: identical(args[12], darticAbsent) ? null : args[12] as MainAxisAlignment?, actionsOverflowAlignment: identical(args[13], darticAbsent) ? null : args[13] as OverflowBarAlignment?, actionsOverflowDirection: identical(args[14], darticAbsent) ? null : args[14] as VerticalDirection?, actionsOverflowButtonSpacing: identical(args[15], darticAbsent) ? null : args[15] as double?, buttonPadding: identical(args[16], darticAbsent) ? null : args[16] as EdgeInsetsGeometry?, backgroundColor: identical(args[17], darticAbsent) ? null : args[17] as Color?, elevation: identical(args[18], darticAbsent) ? null : args[18] as double?, shadowColor: identical(args[19], darticAbsent) ? null : args[19] as Color?, surfaceTintColor: identical(args[20], darticAbsent) ? null : args[20] as Color?, semanticLabel: identical(args[21], darticAbsent) ? null : args[21] as String?, insetPadding: args[22] as EdgeInsets, clipBehavior: identical(args[23], darticAbsent) ? null : args[23] as Clip?, shape: identical(args[24], darticAbsent) ? null : args[24] as ShapeBorder?, alignment: identical(args[25], darticAbsent) ? null : args[25] as AlignmentGeometry?, constraints: identical(args[26], darticAbsent) ? null : args[26] as BoxConstraints?, scrollController: identical(args[28], darticAbsent) ? null : args[28] as ScrollController?, actionScrollController: identical(args[29], darticAbsent) ? null : args[29] as ScrollController?);
                } else {
                  return AlertDialog.adaptive(key: identical(args[0], darticAbsent) ? null : args[0] as Key?, icon: identical(args[1], darticAbsent) ? null : args[1] as Widget?, iconPadding: identical(args[2], darticAbsent) ? null : args[2] as EdgeInsetsGeometry?, iconColor: identical(args[3], darticAbsent) ? null : args[3] as Color?, title: identical(args[4], darticAbsent) ? null : args[4] as Widget?, titlePadding: identical(args[5], darticAbsent) ? null : args[5] as EdgeInsetsGeometry?, titleTextStyle: identical(args[6], darticAbsent) ? null : args[6] as TextStyle?, content: identical(args[7], darticAbsent) ? null : args[7] as Widget?, contentPadding: identical(args[8], darticAbsent) ? null : args[8] as EdgeInsetsGeometry?, contentTextStyle: identical(args[9], darticAbsent) ? null : args[9] as TextStyle?, actions: identical(args[10], darticAbsent) ? null : args[10] == null ? null : (args[10] as List).cast<Widget>(), actionsPadding: identical(args[11], darticAbsent) ? null : args[11] as EdgeInsetsGeometry?, actionsAlignment: identical(args[12], darticAbsent) ? null : args[12] as MainAxisAlignment?, actionsOverflowAlignment: identical(args[13], darticAbsent) ? null : args[13] as OverflowBarAlignment?, actionsOverflowDirection: identical(args[14], darticAbsent) ? null : args[14] as VerticalDirection?, actionsOverflowButtonSpacing: identical(args[15], darticAbsent) ? null : args[15] as double?, buttonPadding: identical(args[16], darticAbsent) ? null : args[16] as EdgeInsetsGeometry?, backgroundColor: identical(args[17], darticAbsent) ? null : args[17] as Color?, elevation: identical(args[18], darticAbsent) ? null : args[18] as double?, shadowColor: identical(args[19], darticAbsent) ? null : args[19] as Color?, surfaceTintColor: identical(args[20], darticAbsent) ? null : args[20] as Color?, semanticLabel: identical(args[21], darticAbsent) ? null : args[21] as String?, insetPadding: args[22] as EdgeInsets, clipBehavior: identical(args[23], darticAbsent) ? null : args[23] as Clip?, shape: identical(args[24], darticAbsent) ? null : args[24] as ShapeBorder?, alignment: identical(args[25], darticAbsent) ? null : args[25] as AlignmentGeometry?, constraints: identical(args[26], darticAbsent) ? null : args[26] as BoxConstraints?, scrollController: identical(args[28], darticAbsent) ? null : args[28] as ScrollController?, actionScrollController: identical(args[29], darticAbsent) ? null : args[29] as ScrollController?, insetAnimationCurve: args[31] as Curve);
                }
              } else {
                if (identical(args[31], darticAbsent)) {
                  return AlertDialog.adaptive(key: identical(args[0], darticAbsent) ? null : args[0] as Key?, icon: identical(args[1], darticAbsent) ? null : args[1] as Widget?, iconPadding: identical(args[2], darticAbsent) ? null : args[2] as EdgeInsetsGeometry?, iconColor: identical(args[3], darticAbsent) ? null : args[3] as Color?, title: identical(args[4], darticAbsent) ? null : args[4] as Widget?, titlePadding: identical(args[5], darticAbsent) ? null : args[5] as EdgeInsetsGeometry?, titleTextStyle: identical(args[6], darticAbsent) ? null : args[6] as TextStyle?, content: identical(args[7], darticAbsent) ? null : args[7] as Widget?, contentPadding: identical(args[8], darticAbsent) ? null : args[8] as EdgeInsetsGeometry?, contentTextStyle: identical(args[9], darticAbsent) ? null : args[9] as TextStyle?, actions: identical(args[10], darticAbsent) ? null : args[10] == null ? null : (args[10] as List).cast<Widget>(), actionsPadding: identical(args[11], darticAbsent) ? null : args[11] as EdgeInsetsGeometry?, actionsAlignment: identical(args[12], darticAbsent) ? null : args[12] as MainAxisAlignment?, actionsOverflowAlignment: identical(args[13], darticAbsent) ? null : args[13] as OverflowBarAlignment?, actionsOverflowDirection: identical(args[14], darticAbsent) ? null : args[14] as VerticalDirection?, actionsOverflowButtonSpacing: identical(args[15], darticAbsent) ? null : args[15] as double?, buttonPadding: identical(args[16], darticAbsent) ? null : args[16] as EdgeInsetsGeometry?, backgroundColor: identical(args[17], darticAbsent) ? null : args[17] as Color?, elevation: identical(args[18], darticAbsent) ? null : args[18] as double?, shadowColor: identical(args[19], darticAbsent) ? null : args[19] as Color?, surfaceTintColor: identical(args[20], darticAbsent) ? null : args[20] as Color?, semanticLabel: identical(args[21], darticAbsent) ? null : args[21] as String?, insetPadding: args[22] as EdgeInsets, clipBehavior: identical(args[23], darticAbsent) ? null : args[23] as Clip?, shape: identical(args[24], darticAbsent) ? null : args[24] as ShapeBorder?, alignment: identical(args[25], darticAbsent) ? null : args[25] as AlignmentGeometry?, constraints: identical(args[26], darticAbsent) ? null : args[26] as BoxConstraints?, scrollController: identical(args[28], darticAbsent) ? null : args[28] as ScrollController?, actionScrollController: identical(args[29], darticAbsent) ? null : args[29] as ScrollController?, insetAnimationDuration: args[30] as Duration);
                } else {
                  return AlertDialog.adaptive(key: identical(args[0], darticAbsent) ? null : args[0] as Key?, icon: identical(args[1], darticAbsent) ? null : args[1] as Widget?, iconPadding: identical(args[2], darticAbsent) ? null : args[2] as EdgeInsetsGeometry?, iconColor: identical(args[3], darticAbsent) ? null : args[3] as Color?, title: identical(args[4], darticAbsent) ? null : args[4] as Widget?, titlePadding: identical(args[5], darticAbsent) ? null : args[5] as EdgeInsetsGeometry?, titleTextStyle: identical(args[6], darticAbsent) ? null : args[6] as TextStyle?, content: identical(args[7], darticAbsent) ? null : args[7] as Widget?, contentPadding: identical(args[8], darticAbsent) ? null : args[8] as EdgeInsetsGeometry?, contentTextStyle: identical(args[9], darticAbsent) ? null : args[9] as TextStyle?, actions: identical(args[10], darticAbsent) ? null : args[10] == null ? null : (args[10] as List).cast<Widget>(), actionsPadding: identical(args[11], darticAbsent) ? null : args[11] as EdgeInsetsGeometry?, actionsAlignment: identical(args[12], darticAbsent) ? null : args[12] as MainAxisAlignment?, actionsOverflowAlignment: identical(args[13], darticAbsent) ? null : args[13] as OverflowBarAlignment?, actionsOverflowDirection: identical(args[14], darticAbsent) ? null : args[14] as VerticalDirection?, actionsOverflowButtonSpacing: identical(args[15], darticAbsent) ? null : args[15] as double?, buttonPadding: identical(args[16], darticAbsent) ? null : args[16] as EdgeInsetsGeometry?, backgroundColor: identical(args[17], darticAbsent) ? null : args[17] as Color?, elevation: identical(args[18], darticAbsent) ? null : args[18] as double?, shadowColor: identical(args[19], darticAbsent) ? null : args[19] as Color?, surfaceTintColor: identical(args[20], darticAbsent) ? null : args[20] as Color?, semanticLabel: identical(args[21], darticAbsent) ? null : args[21] as String?, insetPadding: args[22] as EdgeInsets, clipBehavior: identical(args[23], darticAbsent) ? null : args[23] as Clip?, shape: identical(args[24], darticAbsent) ? null : args[24] as ShapeBorder?, alignment: identical(args[25], darticAbsent) ? null : args[25] as AlignmentGeometry?, constraints: identical(args[26], darticAbsent) ? null : args[26] as BoxConstraints?, scrollController: identical(args[28], darticAbsent) ? null : args[28] as ScrollController?, actionScrollController: identical(args[29], darticAbsent) ? null : args[29] as ScrollController?, insetAnimationDuration: args[30] as Duration, insetAnimationCurve: args[31] as Curve);
                }
              }
            } else {
              if (identical(args[30], darticAbsent)) {
                if (identical(args[31], darticAbsent)) {
                  return AlertDialog.adaptive(key: identical(args[0], darticAbsent) ? null : args[0] as Key?, icon: identical(args[1], darticAbsent) ? null : args[1] as Widget?, iconPadding: identical(args[2], darticAbsent) ? null : args[2] as EdgeInsetsGeometry?, iconColor: identical(args[3], darticAbsent) ? null : args[3] as Color?, title: identical(args[4], darticAbsent) ? null : args[4] as Widget?, titlePadding: identical(args[5], darticAbsent) ? null : args[5] as EdgeInsetsGeometry?, titleTextStyle: identical(args[6], darticAbsent) ? null : args[6] as TextStyle?, content: identical(args[7], darticAbsent) ? null : args[7] as Widget?, contentPadding: identical(args[8], darticAbsent) ? null : args[8] as EdgeInsetsGeometry?, contentTextStyle: identical(args[9], darticAbsent) ? null : args[9] as TextStyle?, actions: identical(args[10], darticAbsent) ? null : args[10] == null ? null : (args[10] as List).cast<Widget>(), actionsPadding: identical(args[11], darticAbsent) ? null : args[11] as EdgeInsetsGeometry?, actionsAlignment: identical(args[12], darticAbsent) ? null : args[12] as MainAxisAlignment?, actionsOverflowAlignment: identical(args[13], darticAbsent) ? null : args[13] as OverflowBarAlignment?, actionsOverflowDirection: identical(args[14], darticAbsent) ? null : args[14] as VerticalDirection?, actionsOverflowButtonSpacing: identical(args[15], darticAbsent) ? null : args[15] as double?, buttonPadding: identical(args[16], darticAbsent) ? null : args[16] as EdgeInsetsGeometry?, backgroundColor: identical(args[17], darticAbsent) ? null : args[17] as Color?, elevation: identical(args[18], darticAbsent) ? null : args[18] as double?, shadowColor: identical(args[19], darticAbsent) ? null : args[19] as Color?, surfaceTintColor: identical(args[20], darticAbsent) ? null : args[20] as Color?, semanticLabel: identical(args[21], darticAbsent) ? null : args[21] as String?, insetPadding: args[22] as EdgeInsets, clipBehavior: identical(args[23], darticAbsent) ? null : args[23] as Clip?, shape: identical(args[24], darticAbsent) ? null : args[24] as ShapeBorder?, alignment: identical(args[25], darticAbsent) ? null : args[25] as AlignmentGeometry?, constraints: identical(args[26], darticAbsent) ? null : args[26] as BoxConstraints?, scrollable: args[27] as bool, scrollController: identical(args[28], darticAbsent) ? null : args[28] as ScrollController?, actionScrollController: identical(args[29], darticAbsent) ? null : args[29] as ScrollController?);
                } else {
                  return AlertDialog.adaptive(key: identical(args[0], darticAbsent) ? null : args[0] as Key?, icon: identical(args[1], darticAbsent) ? null : args[1] as Widget?, iconPadding: identical(args[2], darticAbsent) ? null : args[2] as EdgeInsetsGeometry?, iconColor: identical(args[3], darticAbsent) ? null : args[3] as Color?, title: identical(args[4], darticAbsent) ? null : args[4] as Widget?, titlePadding: identical(args[5], darticAbsent) ? null : args[5] as EdgeInsetsGeometry?, titleTextStyle: identical(args[6], darticAbsent) ? null : args[6] as TextStyle?, content: identical(args[7], darticAbsent) ? null : args[7] as Widget?, contentPadding: identical(args[8], darticAbsent) ? null : args[8] as EdgeInsetsGeometry?, contentTextStyle: identical(args[9], darticAbsent) ? null : args[9] as TextStyle?, actions: identical(args[10], darticAbsent) ? null : args[10] == null ? null : (args[10] as List).cast<Widget>(), actionsPadding: identical(args[11], darticAbsent) ? null : args[11] as EdgeInsetsGeometry?, actionsAlignment: identical(args[12], darticAbsent) ? null : args[12] as MainAxisAlignment?, actionsOverflowAlignment: identical(args[13], darticAbsent) ? null : args[13] as OverflowBarAlignment?, actionsOverflowDirection: identical(args[14], darticAbsent) ? null : args[14] as VerticalDirection?, actionsOverflowButtonSpacing: identical(args[15], darticAbsent) ? null : args[15] as double?, buttonPadding: identical(args[16], darticAbsent) ? null : args[16] as EdgeInsetsGeometry?, backgroundColor: identical(args[17], darticAbsent) ? null : args[17] as Color?, elevation: identical(args[18], darticAbsent) ? null : args[18] as double?, shadowColor: identical(args[19], darticAbsent) ? null : args[19] as Color?, surfaceTintColor: identical(args[20], darticAbsent) ? null : args[20] as Color?, semanticLabel: identical(args[21], darticAbsent) ? null : args[21] as String?, insetPadding: args[22] as EdgeInsets, clipBehavior: identical(args[23], darticAbsent) ? null : args[23] as Clip?, shape: identical(args[24], darticAbsent) ? null : args[24] as ShapeBorder?, alignment: identical(args[25], darticAbsent) ? null : args[25] as AlignmentGeometry?, constraints: identical(args[26], darticAbsent) ? null : args[26] as BoxConstraints?, scrollable: args[27] as bool, scrollController: identical(args[28], darticAbsent) ? null : args[28] as ScrollController?, actionScrollController: identical(args[29], darticAbsent) ? null : args[29] as ScrollController?, insetAnimationCurve: args[31] as Curve);
                }
              } else {
                if (identical(args[31], darticAbsent)) {
                  return AlertDialog.adaptive(key: identical(args[0], darticAbsent) ? null : args[0] as Key?, icon: identical(args[1], darticAbsent) ? null : args[1] as Widget?, iconPadding: identical(args[2], darticAbsent) ? null : args[2] as EdgeInsetsGeometry?, iconColor: identical(args[3], darticAbsent) ? null : args[3] as Color?, title: identical(args[4], darticAbsent) ? null : args[4] as Widget?, titlePadding: identical(args[5], darticAbsent) ? null : args[5] as EdgeInsetsGeometry?, titleTextStyle: identical(args[6], darticAbsent) ? null : args[6] as TextStyle?, content: identical(args[7], darticAbsent) ? null : args[7] as Widget?, contentPadding: identical(args[8], darticAbsent) ? null : args[8] as EdgeInsetsGeometry?, contentTextStyle: identical(args[9], darticAbsent) ? null : args[9] as TextStyle?, actions: identical(args[10], darticAbsent) ? null : args[10] == null ? null : (args[10] as List).cast<Widget>(), actionsPadding: identical(args[11], darticAbsent) ? null : args[11] as EdgeInsetsGeometry?, actionsAlignment: identical(args[12], darticAbsent) ? null : args[12] as MainAxisAlignment?, actionsOverflowAlignment: identical(args[13], darticAbsent) ? null : args[13] as OverflowBarAlignment?, actionsOverflowDirection: identical(args[14], darticAbsent) ? null : args[14] as VerticalDirection?, actionsOverflowButtonSpacing: identical(args[15], darticAbsent) ? null : args[15] as double?, buttonPadding: identical(args[16], darticAbsent) ? null : args[16] as EdgeInsetsGeometry?, backgroundColor: identical(args[17], darticAbsent) ? null : args[17] as Color?, elevation: identical(args[18], darticAbsent) ? null : args[18] as double?, shadowColor: identical(args[19], darticAbsent) ? null : args[19] as Color?, surfaceTintColor: identical(args[20], darticAbsent) ? null : args[20] as Color?, semanticLabel: identical(args[21], darticAbsent) ? null : args[21] as String?, insetPadding: args[22] as EdgeInsets, clipBehavior: identical(args[23], darticAbsent) ? null : args[23] as Clip?, shape: identical(args[24], darticAbsent) ? null : args[24] as ShapeBorder?, alignment: identical(args[25], darticAbsent) ? null : args[25] as AlignmentGeometry?, constraints: identical(args[26], darticAbsent) ? null : args[26] as BoxConstraints?, scrollable: args[27] as bool, scrollController: identical(args[28], darticAbsent) ? null : args[28] as ScrollController?, actionScrollController: identical(args[29], darticAbsent) ? null : args[29] as ScrollController?, insetAnimationDuration: args[30] as Duration);
                } else {
                  return AlertDialog.adaptive(key: identical(args[0], darticAbsent) ? null : args[0] as Key?, icon: identical(args[1], darticAbsent) ? null : args[1] as Widget?, iconPadding: identical(args[2], darticAbsent) ? null : args[2] as EdgeInsetsGeometry?, iconColor: identical(args[3], darticAbsent) ? null : args[3] as Color?, title: identical(args[4], darticAbsent) ? null : args[4] as Widget?, titlePadding: identical(args[5], darticAbsent) ? null : args[5] as EdgeInsetsGeometry?, titleTextStyle: identical(args[6], darticAbsent) ? null : args[6] as TextStyle?, content: identical(args[7], darticAbsent) ? null : args[7] as Widget?, contentPadding: identical(args[8], darticAbsent) ? null : args[8] as EdgeInsetsGeometry?, contentTextStyle: identical(args[9], darticAbsent) ? null : args[9] as TextStyle?, actions: identical(args[10], darticAbsent) ? null : args[10] == null ? null : (args[10] as List).cast<Widget>(), actionsPadding: identical(args[11], darticAbsent) ? null : args[11] as EdgeInsetsGeometry?, actionsAlignment: identical(args[12], darticAbsent) ? null : args[12] as MainAxisAlignment?, actionsOverflowAlignment: identical(args[13], darticAbsent) ? null : args[13] as OverflowBarAlignment?, actionsOverflowDirection: identical(args[14], darticAbsent) ? null : args[14] as VerticalDirection?, actionsOverflowButtonSpacing: identical(args[15], darticAbsent) ? null : args[15] as double?, buttonPadding: identical(args[16], darticAbsent) ? null : args[16] as EdgeInsetsGeometry?, backgroundColor: identical(args[17], darticAbsent) ? null : args[17] as Color?, elevation: identical(args[18], darticAbsent) ? null : args[18] as double?, shadowColor: identical(args[19], darticAbsent) ? null : args[19] as Color?, surfaceTintColor: identical(args[20], darticAbsent) ? null : args[20] as Color?, semanticLabel: identical(args[21], darticAbsent) ? null : args[21] as String?, insetPadding: args[22] as EdgeInsets, clipBehavior: identical(args[23], darticAbsent) ? null : args[23] as Clip?, shape: identical(args[24], darticAbsent) ? null : args[24] as ShapeBorder?, alignment: identical(args[25], darticAbsent) ? null : args[25] as AlignmentGeometry?, constraints: identical(args[26], darticAbsent) ? null : args[26] as BoxConstraints?, scrollable: args[27] as bool, scrollController: identical(args[28], darticAbsent) ? null : args[28] as ScrollController?, actionScrollController: identical(args[29], darticAbsent) ? null : args[29] as ScrollController?, insetAnimationDuration: args[30] as Duration, insetAnimationCurve: args[31] as Curve);
                }
              }
            }
          }
        },
        '_#fromFields#27': (args) => AlertDialog(actions: args[0] == null ? null : (args[0] as List).cast<Widget>(), actionsAlignment: args[1] as MainAxisAlignment?, actionsOverflowAlignment: args[2] as OverflowBarAlignment?, actionsOverflowButtonSpacing: args[3] as double?, actionsOverflowDirection: args[4] as VerticalDirection?, actionsPadding: args[5] as EdgeInsetsGeometry?, alignment: args[6] as AlignmentGeometry?, backgroundColor: args[7] as Color?, buttonPadding: args[8] as EdgeInsetsGeometry?, clipBehavior: args[9] as Clip?, constraints: args[10] as BoxConstraints?, content: args[11] as Widget?, contentPadding: args[12] as EdgeInsetsGeometry?, contentTextStyle: args[13] as TextStyle?, elevation: args[14] as double?, icon: args[15] as Widget?, iconColor: args[16] as Color?, iconPadding: args[17] as EdgeInsetsGeometry?, insetPadding: args[18] as EdgeInsets?, scrollable: args[19] as bool, semanticLabel: args[20] as String?, shadowColor: args[21] as Color?, shape: args[22] as ShapeBorder?, surfaceTintColor: args[23] as Color?, title: args[24] as Widget?, titlePadding: args[25] as EdgeInsetsGeometry?, titleTextStyle: args[26] as TextStyle?),
      };
}
