// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7

import 'package:dartic/dartic.dart';
import 'package:dartic/dartic_internal.dart';
import 'package:flutter/src/widgets/app.dart';
import 'dart:collection';
import 'package:flutter/foundation.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:flutter/src/widgets/actions.dart';
import 'package:flutter/src/widgets/banner.dart';
import 'package:flutter/src/widgets/basic.dart';
import 'package:flutter/src/widgets/binding.dart';
import 'package:flutter/src/widgets/default_text_editing_shortcuts.dart';
import 'package:flutter/src/widgets/focus_scope.dart';
import 'package:flutter/src/widgets/focus_traversal.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:flutter/src/widgets/localizations.dart';
import 'package:flutter/src/widgets/media_query.dart';
import 'package:flutter/src/widgets/navigator.dart';
import 'package:flutter/src/widgets/notification_listener.dart';
import 'package:flutter/src/widgets/pages.dart';
import 'package:flutter/src/widgets/performance_overlay.dart';
import 'package:flutter/src/widgets/restoration.dart';
import 'package:flutter/src/widgets/router.dart';
import 'package:flutter/src/widgets/scrollable_helpers.dart';
import 'package:flutter/src/widgets/semantics_debugger.dart';
import 'package:flutter/src/widgets/shared_app_data.dart';
import 'package:flutter/src/widgets/shortcuts.dart';
import 'package:flutter/src/widgets/tap_region.dart';
import 'package:flutter/src/widgets/text.dart';
import 'package:flutter/src/widgets/title.dart';
import 'package:flutter/src/widgets/transitions.dart';
import 'package:flutter/src/widgets/value_listenable_builder.dart';
import 'package:flutter/src/widgets/widget_inspector.dart';
import 'package:flutter/src/widgets/spell_check.dart';
import 'dart:math' as math;
import 'package:flutter/painting.dart';
import 'package:flutter/src/widgets/editable_text.dart';
import 'package:flutter/src/widgets/drag_target.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/src/widgets/debug.dart';
import 'package:flutter/src/widgets/overlay.dart';
import 'package:flutter/src/widgets/view.dart';
import 'package:flutter/src/widgets/focus_manager.dart';
import 'dart:async';
import 'dart:ui';
import 'dart:ui' as ui;
import 'package:flutter/scheduler.dart';
import 'package:flutter/semantics.dart';
import 'package:flutter/src/widgets/_window_io.dart';
import 'package:flutter/src/widgets/_window_io.dart' as window_impl;
import 'dart:io';
import 'package:flutter/src/widgets/_window.dart';
import 'package:flutter/src/widgets/_window_win32.dart';
import 'package:flutter/src/foundation/_features.dart';
import 'package:flutter/src/widgets/inherited_model.dart';
import 'package:flutter/src/widgets/image.dart';
import 'package:flutter/src/painting/_web_image_info_io.dart';
import 'package:flutter/src/widgets/_web_image_io.dart';
import 'package:flutter/src/widgets/disposable_build_context.dart';
import 'package:flutter/src/widgets/placeholder.dart';
import 'package:flutter/src/widgets/scroll_aware_image_provider.dart';
import 'package:flutter/src/widgets/ticker_provider.dart';
import 'dart:developer';
import 'dart:developer' as developer;
import 'package:flutter/src/widgets/lookup_boundary.dart';
import 'package:flutter/src/widgets/table.dart';
import 'package:flutter/src/widgets/platform_menu_bar.dart';
import 'package:flutter/src/widgets/service_extensions.dart';
import 'dart:convert';
import 'package:meta/meta_meta.dart';
import 'package:flutter/src/widgets/gesture_detector.dart';
import 'package:flutter/src/widgets/icon_data.dart';
import 'package:flutter/src/widgets/scroll_notification.dart';
import 'package:flutter/src/widgets/scroll_metrics.dart';
import 'package:flutter/animation.dart';
import 'package:flutter/src/widgets/visibility.dart';
import 'package:flutter/src/widgets/widget_span.dart';
import 'package:flutter/src/widgets/text_editing_intents.dart';
import 'package:flutter/src/widgets/routes.dart';
import 'package:flutter/src/widgets/display_feature_sub_screen.dart';
import 'package:flutter/src/widgets/modal_barrier.dart';
import 'package:flutter/src/widgets/page_storage.dart';
import 'package:flutter/src/widgets/primary_scroll_controller.dart';
import 'package:flutter/src/widgets/scroll_controller.dart';
import 'package:flutter/src/painting/text_span.dart';
import 'package:flutter/src/services/text_input.dart';
import 'package:flutter/src/painting/text_style.dart';
import 'package:flutter/src/services/spell_check.dart';
import 'package:flutter/src/painting/image_provider.dart';
import 'package:flutter/src/foundation/diagnostics.dart';
import 'package:flutter/src/painting/basic_types.dart';
import 'package:flutter/src/painting/image_stream.dart';
import 'package:flutter/src/animation/animation.dart';

abstract final class WidgetsTopLevelBindings {
  static void register(DarticPluginContext ctx) {
    ctx.registerBinding('package:flutter/src/widgets/app.dart::::basicLocaleListResolution#2', (args) => basicLocaleListResolution(args[0] == null ? null : (args[0] as List).cast<Locale>(), (args[1] as Iterable).cast<Locale>()));
    ctx.registerBinding('package:flutter/src/widgets/spell_check.dart::::buildTextSpanWithSpellCheckSuggestions#5', (args) => buildTextSpanWithSpellCheckSuggestions(args[0] as TextEditingValue, args[1] as bool, args[2] as TextStyle?, args[3] as TextStyle, args[4] as SpellCheckResults));
    ctx.registerBinding('package:flutter/src/widgets/drag_target.dart::::childDragAnchorStrategy#3', (args) => childDragAnchorStrategy(args[0] as Draggable<Object>, args[1] as BuildContext, args[2] as Offset));
    ctx.registerBinding('package:flutter/src/widgets/focus_manager.dart::::combineKeyEventResults#1', (args) => combineKeyEventResults((args[0] as Iterable).cast<KeyEventResult>()));
    ctx.registerBinding('package:flutter/src/widgets/_window_io.dart::::createDefaultOwner#0', (args) => createDefaultOwner());
    ctx.registerBinding('package:flutter/src/widgets/_window.dart::::createDefaultWindowingOwner#0', (args) => createDefaultWindowingOwner());
    ctx.registerBinding('package:flutter/src/widgets/image.dart::::createLocalImageConfiguration#2', (args) => createLocalImageConfiguration(args[0] as BuildContext, size: args[1] as Size?));
    ctx.registerBinding('package:flutter/src/widgets/debug.dart::::debugAssertAllWidgetVarsUnset#1', (args) => debugAssertAllWidgetVarsUnset(args[0] as String));
    ctx.registerBinding('package:flutter/src/widgets/debug.dart::::debugCheckHasDirectionality#4', (args) => debugCheckHasDirectionality(args[0] as BuildContext, why: args[1] as String?, hint: args[2] as String?, alternative: args[3] as String?));
    ctx.registerBinding('package:flutter/src/widgets/debug.dart::::debugCheckHasMediaQuery#1', (args) => debugCheckHasMediaQuery(args[0] as BuildContext));
    ctx.registerBinding('package:flutter/src/widgets/debug.dart::::debugCheckHasOverlay#1', (args) => debugCheckHasOverlay(args[0] as BuildContext));
    ctx.registerBinding('package:flutter/src/widgets/debug.dart::::debugCheckHasTable#1', (args) => debugCheckHasTable(args[0] as BuildContext));
    ctx.registerBinding('package:flutter/src/widgets/debug.dart::::debugCheckHasWidgetsLocalizations#1', (args) => debugCheckHasWidgetsLocalizations(args[0] as BuildContext));
    ctx.registerBinding('package:flutter/src/widgets/debug.dart::::debugChildrenHaveDuplicateKeys#3', (args) => debugChildrenHaveDuplicateKeys(args[0] as Widget, (args[1] as Iterable).cast<Widget>(), message: args[2] as String?));
    ctx.registerBinding('package:flutter/src/widgets/focus_manager.dart::::debugDescribeFocusTree#0', (args) => debugDescribeFocusTree());
    ctx.registerBinding('package:flutter/src/widgets/binding.dart::::debugDumpApp#0', (args) { debugDumpApp(); return null; });
    ctx.registerBinding('package:flutter/src/widgets/focus_manager.dart::::debugDumpFocusTree#0', (args) { debugDumpFocusTree(); return null; });
    ctx.registerBinding('package:flutter/src/widgets/widget_inspector.dart::::debugIsLocalCreationLocation#1', (args) => debugIsLocalCreationLocation(args[0] as Object));
    ctx.registerBinding('package:flutter/src/widgets/widget_inspector.dart::::debugIsWidgetLocalCreation#1', (args) => debugIsWidgetLocalCreation(args[0] as Widget));
    ctx.registerBinding('package:flutter/src/widgets/debug.dart::::debugItemsHaveDuplicateKeys#1', (args) => debugItemsHaveDuplicateKeys((args[0] as Iterable).cast<Widget>()));
    ctx.registerBinding('package:flutter/src/widgets/widget_inspector.dart::::debugTransformDebugCreator#1', (args) => debugTransformDebugCreator((args[0] as Iterable).cast<DiagnosticsNode>()));
    ctx.registerBinding('package:flutter/src/widgets/debug.dart::::debugWidgetBuilderValue#2', (args) { debugWidgetBuilderValue(args[0] as Widget, args[1] as Widget?); return null; });
    ctx.registerBinding('package:flutter/src/widgets/scroll_notification.dart::::defaultScrollNotificationPredicate#1', (args) => defaultScrollNotificationPredicate(args[0] as ScrollNotification));
    ctx.registerBinding('package:flutter/src/widgets/basic.dart::::getAxisDirectionFromAxisReverseAndDirectionality#3', (args) => getAxisDirectionFromAxisReverseAndDirectionality(args[0] as BuildContext, args[1] as Axis, args[2] as bool));
    ctx.registerBinding('package:flutter/src/widgets/default_text_editing_shortcuts.dart::::intentForMacOSSelector#1', (args) => intentForMacOSSelector(args[0] as String));
    ctx.registerBinding('package:flutter/src/widgets/drag_target.dart::::pointerDragAnchorStrategy#3', (args) => pointerDragAnchorStrategy(args[0] as Draggable<Object>, args[1] as BuildContext, args[2] as Offset));
    ctx.registerBinding('package:flutter/src/widgets/image.dart::::precacheImage#4', (args) => precacheImage(args[0] as ImageProvider<Object>, args[1] as BuildContext, size: args[2] as Size?, onError: (args[3] as Function?) == null ? null : (a, b) => (args[3] as Function?)!(a, b)));
    ctx.registerBinding('package:flutter/src/widgets/binding.dart::::runApp#1', (args) { runApp(args[0] as Widget); return null; });
    ctx.registerBinding('package:flutter/src/widgets/binding.dart::::runWidget#1', (args) { runWidget(args[0] as Widget); return null; });
    ctx.registerBinding('package:flutter/src/widgets/routes.dart::::showGeneralDialog#12', (args) => showGeneralDialog(context: args[0] as BuildContext, pageBuilder: (a, b, c) => (args[1] as Function)(a, b, c) as Widget, barrierDismissible: args[2] as bool, barrierLabel: args[3] as String?, barrierColor: args[4] as ui.Color, transitionDuration: args[5] as Duration, transitionBuilder: (args[6] as Function?) == null ? null : (a, b, c, d) => (args[6] as Function?)!(a, b, c, d), useRootNavigator: args[7] as bool, fullscreenDialog: args[8] as bool, routeSettings: args[9] as RouteSettings?, anchorPoint: args[10] as ui.Offset?, requestFocus: args[11] as bool?));
  }
}
