// GENERATED by dartic gen --emit-tests. DO NOT EDIT.
// Regenerate: dartic gen <config> --emit-tests
// Compile fixtures: dartic gen-verify compile
import 'dart:io';
import 'package:dartic/dartic.dart';
import 'package:dartic_stdlib/dartic_stdlib.dart';
import 'package:test/test.dart';

List<String> _runFixture(String name) {
  final bytes = File('test/gen_verify/fixtures/$name.darb').readAsBytesSync();
  final printLog = <String>[];
  final engine = DarticEngine(
    plugins: [DarticStdlibPlugin()],
    config: DarticConfig(
      onPrint: (v) => printLog.add('$v'),
      fuelBudget: 500000,
    ),
  );
  engine.loadBytecode(bytes);
  engine.call('main');
  engine.dispose();
  return printLog;
}

void main() {
  group('Auto-gen E2E Bridge verification', () {
    test('Stream bridge: super calls', () {
      final log = _runFixture('stream_verify');
      expect(log.last, equals('OK'));
    });

    test('StreamSubscription bridge: super calls', () {
      final log = _runFixture('stream_subscription_verify');
      expect(log.last, equals('OK'));
    });

    test('EventSink bridge: super calls', () {
      final log = _runFixture('event_sink_verify');
      expect(log.last, equals('OK'));
    });

    test('StreamSink bridge: super calls', () {
      final log = _runFixture('stream_sink_verify');
      expect(log.last, equals('OK'));
    });

    test('StreamConsumer bridge: super calls', () {
      final log = _runFixture('stream_consumer_verify');
      expect(log.last, equals('OK'));
    });

    test('ListBase bridge: super calls', () {
      final log = _runFixture('list_base_verify');
      expect(log.last, equals('OK'));
    });

    test('MapBase bridge: super calls', () {
      final log = _runFixture('map_base_verify');
      expect(log.last, equals('OK'));
    });

    test('SetBase bridge: super calls', () {
      final log = _runFixture('set_base_verify');
      expect(log.last, equals('OK'));
    });

    test('Duration bridge: super calls', () {
      final log = _runFixture('duration_verify');
      expect(log.last, equals('OK'));
    });

    test('Iterable bridge: super calls', () {
      final log = _runFixture('iterable_verify');
      expect(log.last, equals('OK'));
    });

    test('Iterator bridge: super calls', () {
      final log = _runFixture('iterator_verify');
      expect(log.last, equals('OK'));
    });

    test('Error bridge: super calls', () {
      final log = _runFixture('error_verify');
      expect(log.last, equals('OK'));
    });

    test('ArgumentError bridge: super calls', () {
      final log = _runFixture('argument_error_verify');
      expect(log.last, equals('OK'));
    });

    test('RangeError bridge: super calls', () {
      final log = _runFixture('range_error_verify');
      expect(log.last, equals('OK'));
    });

    test('IndexError bridge: super calls', () {
      final log = _runFixture('index_error_verify');
      expect(log.last, equals('OK'));
    });

    test('StateError bridge: super calls', () {
      final log = _runFixture('state_error_verify');
      expect(log.last, equals('OK'));
    });

    test('UnsupportedError bridge: super calls', () {
      final log = _runFixture('unsupported_error_verify');
      expect(log.last, equals('OK'));
    });

    test('UnimplementedError bridge: super calls', () {
      final log = _runFixture('unimplemented_error_verify');
      expect(log.last, equals('OK'));
    });

    test('FormatException bridge: super calls', () {
      final log = _runFixture('format_exception_verify');
      expect(log.last, equals('OK'));
    });

    test('Exception bridge: super calls', () {
      final log = _runFixture('exception_verify');
      expect(log.last, equals('OK'));
    });

    test('ConcurrentModificationError bridge: super calls', () {
      final log = _runFixture('concurrent_modification_error_verify');
      expect(log.last, equals('OK'));
    });

    test('AssertionError bridge: super calls', () {
      final log = _runFixture('assertion_error_verify');
      expect(log.last, equals('OK'));
    });

    test('TypeError bridge: super calls', () {
      final log = _runFixture('type_error_verify');
      expect(log.last, equals('OK'));
    });

    test('Stopwatch bridge: super calls', () {
      final log = _runFixture('stopwatch_verify');
      expect(log.last, equals('OK'));
    });

  });
}
