// GENERATED by dartic gen --emit-tests. DO NOT EDIT.
// Regenerate: dartic gen <config> --emit-tests
import 'package:test/test.dart';
// ignore_for_file: implementation_imports
import 'package:dartic_stdlib/src/bindings/async/event_sink_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/async/stream_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/async/stream_consumer_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/async/stream_sink_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/async/stream_subscription_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/collection/list_base_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/collection/map_base_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/collection/set_base_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/core/argument_error_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/core/assertion_error_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/core/concurrent_modification_error_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/core/duration_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/core/error_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/core/format_exception_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/core/index_error_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/core/iterable_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/core/iterator_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/core/range_error_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/core/state_error_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/core/stopwatch_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/core/type_error_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/core/unimplemented_error_bindings.g.dart';
import 'package:dartic_stdlib/src/bindings/core/unsupported_error_bindings.g.dart';

void main() {
  group('Binding completeness', () {
    test('StreamBindings.methodMap has expected keys', () {
      final map = StreamBindings.methodMap();
      expect(map.keys, containsAll([
        'asBroadcastStream#2',
        'listen#4',
        'where#1',
        'map#1',
        'asyncMap#1',
        'asyncExpand#1',
        'handleError#2',
        'expand#1',
        'pipe#1',
        'transform#1',
        'reduce#1',
        'fold#2',
        'join#1',
        'contains#1',
        'forEach#1',
        'every#1',
        'any#1',
        'cast#0',
        'toList#0',
        'toSet#0',
        'drain#1',
        'take#1',
        'takeWhile#1',
        'skip#1',
        'skipWhile#1',
        'distinct#1',
        'firstWhere#2',
        'lastWhere#2',
        'singleWhere#2',
        'elementAt#1',
        'timeout#2',
        'isBroadcast#0',
        'length#0',
        'isEmpty#0',
        'first#0',
        'last#0',
        'single#0',
      ]));
    });

    test('StreamSubscriptionBindings.methodMap has expected keys', () {
      final map = StreamSubscriptionBindings.methodMap();
      expect(map.keys, containsAll([
        'cancel#0',
        'onData#1',
        'onError#1',
        'onDone#1',
        'pause#1',
        'resume#0',
        'asFuture#1',
        'isPaused#0',
      ]));
    });

    test('EventSinkBindings.methodMap has expected keys', () {
      final map = EventSinkBindings.methodMap();
      expect(map.keys, containsAll(['add#1', 'addError#2', 'close#0']));
    });

    test('StreamSinkBindings.methodMap has expected keys', () {
      final map = StreamSinkBindings.methodMap();
      expect(map.keys, containsAll([
        'close#0',
        'add#1',
        'addError#2',
        'addStream#1',
        'done#0',
      ]));
    });

    test('StreamConsumerBindings.methodMap has expected keys', () {
      final map = StreamConsumerBindings.methodMap();
      expect(map.keys, containsAll(['addStream#1', 'close#0']));
    });

    test('ListBaseBindings.methodMap has expected keys', () {
      final map = ListBaseBindings.methodMap();
      expect(map.keys, containsAll([
        'elementAt#1',
        'followedBy#1',
        'forEach#1',
        'contains#1',
        'every#1',
        'any#1',
        'firstWhere#2',
        'lastWhere#2',
        'singleWhere#2',
        'join#1',
        'where#1',
        'whereType#0',
        'map#1',
        'expand#1',
        'reduce#1',
        'fold#2',
        'skip#1',
        'skipWhile#1',
        'take#1',
        'takeWhile#1',
        'toList#1',
        'toSet#0',
        'add#1',
        'addAll#1',
        'remove#1',
        'removeWhere#1',
        'retainWhere#1',
        'clear#0',
        'cast#0',
        'removeLast#0',
        'sort#1',
        'shuffle#1',
        'asMap#0',
        'sublist#2',
        'getRange#2',
        'removeRange#2',
        'fillRange#3',
        'setRange#4',
        'replaceRange#3',
        'indexOf#2',
        'indexWhere#2',
        'lastIndexOf#2',
        'lastIndexWhere#2',
        'insert#2',
        'removeAt#1',
        'insertAll#2',
        'setAll#2',
        'toString#0',
        'iterator#0',
        'isEmpty#0',
        'isNotEmpty#0',
        'first#0',
        'last#0',
        'single#0',
        'reversed#0',
        'length#0',
        'first=#1',
        'last=#1',
        'length=#1',
        '+#1',
        '[]#1',
        '[]=#2',
      ]));
    });

    test('MapBaseBindings.methodMap has expected keys', () {
      final map = MapBaseBindings.methodMap();
      expect(map.keys, containsAll([
        'remove#1',
        'clear#0',
        'cast#0',
        'forEach#1',
        'addAll#1',
        'containsValue#1',
        'putIfAbsent#2',
        'update#3',
        'updateAll#1',
        'map#1',
        'addEntries#1',
        'removeWhere#1',
        'containsKey#1',
        'toString#0',
        'keys#0',
        'entries#0',
        'length#0',
        'isEmpty#0',
        'isNotEmpty#0',
        'values#0',
        '[]#1',
        '[]=#2',
      ]));
    });

    test('SetBaseBindings.methodMap has expected keys', () {
      final map = SetBaseBindings.methodMap();
      expect(map.keys, containsAll([
        'add#1',
        'contains#1',
        'lookup#1',
        'remove#1',
        'toSet#0',
        'cast#0',
        'followedBy#1',
        'whereType#0',
        'clear#0',
        'addAll#1',
        'removeAll#1',
        'retainAll#1',
        'removeWhere#1',
        'retainWhere#1',
        'containsAll#1',
        'union#1',
        'intersection#1',
        'difference#1',
        'toList#1',
        'map#1',
        'toString#0',
        'where#1',
        'expand#1',
        'forEach#1',
        'reduce#1',
        'fold#2',
        'every#1',
        'join#1',
        'any#1',
        'take#1',
        'takeWhile#1',
        'skip#1',
        'skipWhile#1',
        'firstWhere#2',
        'lastWhere#2',
        'singleWhere#2',
        'elementAt#1',
        'iterator#0',
        'length#0',
        'isEmpty#0',
        'isNotEmpty#0',
        'single#0',
        'first#0',
        'last#0',
      ]));
    });

    test('DurationBindings.methodMap has expected keys', () {
      final map = DurationBindings.methodMap();
      expect(map.keys, containsAll([
        'compareTo#1',
        'toString#0',
        'abs#0',
        'inDays#0',
        'inHours#0',
        'inMinutes#0',
        'inSeconds#0',
        'inMilliseconds#0',
        'inMicroseconds#0',
        'hashCode#0',
        'isNegative#0',
        '+#1',
        '-#1',
        '*#1',
        '~/#1',
        '<#1',
        '>#1',
        '<=#1',
        '>=#1',
        'unary-#0',
        '#6',
      ]));
    });

    test('IterableBindings.methodMap has expected keys', () {
      final map = IterableBindings.methodMap();
      expect(map.keys, containsAll([
        'cast#0',
        'followedBy#1',
        'map#1',
        'where#1',
        'whereType#0',
        'expand#1',
        'contains#1',
        'forEach#1',
        'reduce#1',
        'fold#2',
        'every#1',
        'join#1',
        'any#1',
        'toList#1',
        'toSet#0',
        'take#1',
        'takeWhile#1',
        'skip#1',
        'skipWhile#1',
        'firstWhere#2',
        'lastWhere#2',
        'singleWhere#2',
        'elementAt#1',
        'toString#0',
        'iterator#0',
        'length#0',
        'isEmpty#0',
        'isNotEmpty#0',
        'first#0',
        'last#0',
        'single#0',
      ]));
    });

    test('IteratorBindings.methodMap has expected keys', () {
      final map = IteratorBindings.methodMap();
      expect(map.keys, containsAll(['moveNext#0', 'current#0']));
    });

    test('ErrorBindings.methodMap has expected keys', () {
      final map = ErrorBindings.methodMap();
      expect(map.keys, containsAll(['stackTrace#0', '#0']));
    });

    test('ArgumentErrorBindings.methodMap has expected keys', () {
      final map = ArgumentErrorBindings.methodMap();
      expect(map.keys, containsAll([
        'toString#0',
        'invalidValue#0',
        'name#0',
        'message#0',
        'stackTrace#0',
        '#2',
        'value#3',
        'notNull#1',
      ]));
    });

    test('RangeErrorBindings.methodMap has expected keys', () {
      final map = RangeErrorBindings.methodMap();
      expect(map.keys, containsAll([
        'start#0',
        'end#0',
        'invalidValue#0',
        'name#0',
        'message#0',
        'stackTrace#0',
        '#1',
        'value#3',
        'range#5',
        'index#5',
      ]));
    });

    test('IndexErrorBindings.methodMap has expected keys', () {
      final map = IndexErrorBindings.methodMap();
      expect(map.keys, containsAll([
        'indexable#0',
        'length#0',
        'invalidValue#0',
        'start#0',
        'end#0',
        'name#0',
        'message#0',
        'stackTrace#0',
        '#5',
        'withLength#5',
      ]));
    });

    test('StateErrorBindings.methodMap has expected keys', () {
      final map = StateErrorBindings.methodMap();
      expect(map.keys, containsAll([
        'toString#0',
        'message#0',
        'stackTrace#0',
        '#1',
      ]));
    });

    test('UnsupportedErrorBindings.methodMap has expected keys', () {
      final map = UnsupportedErrorBindings.methodMap();
      expect(map.keys, containsAll([
        'toString#0',
        'message#0',
        'stackTrace#0',
        '#1',
      ]));
    });

    test('UnimplementedErrorBindings.methodMap has expected keys', () {
      final map = UnimplementedErrorBindings.methodMap();
      expect(map.keys, containsAll([
        'toString#0',
        'message#0',
        'stackTrace#0',
        '#1',
      ]));
    });

    test('FormatExceptionBindings.methodMap has expected keys', () {
      final map = FormatExceptionBindings.methodMap();
      expect(map.keys, containsAll([
        'toString#0',
        'message#0',
        'source#0',
        'offset#0',
        '#3',
      ]));
    });

    test('ConcurrentModificationErrorBindings.methodMap has expected keys', () {
      final map = ConcurrentModificationErrorBindings.methodMap();
      expect(map.keys, containsAll([
        'toString#0',
        'modifiedObject#0',
        'stackTrace#0',
        '#1',
      ]));
    });

    test('AssertionErrorBindings.methodMap has expected keys', () {
      final map = AssertionErrorBindings.methodMap();
      expect(map.keys, containsAll([
        'toString#0',
        'message#0',
        'stackTrace#0',
        '#1',
      ]));
    });

    test('TypeErrorBindings.methodMap has expected keys', () {
      final map = TypeErrorBindings.methodMap();
      expect(map.keys, containsAll(['stackTrace#0', '#0']));
    });

    test('StopwatchBindings.methodMap has expected keys', () {
      final map = StopwatchBindings.methodMap();
      expect(map.keys, containsAll([
        'start#0',
        'stop#0',
        'reset#0',
        'frequency#0',
        'elapsedTicks#0',
        'elapsed#0',
        'elapsedMicroseconds#0',
        'elapsedMilliseconds#0',
        'isRunning#0',
        '#0',
      ]));
    });

  });
}
