// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7

// ignore_for_file: implementation_imports, unused_import, unnecessary_import, unnecessary_cast, invalid_use_of_protected_member, deprecated_member_use, sort_child_properties_last

import 'package:dartic/dartic.dart';
import 'package:dartic/dartic_internal.dart';
import 'package:flutter/src/semantics/semantics.dart';
import 'dart:math' as math;
import 'dart:ui' show CheckedState, Locale, Offset, Rect, SemanticsAction, SemanticsFlag, SemanticsFlags, SemanticsInputType, SemanticsRole, SemanticsUpdate, SemanticsUpdateBuilder, SemanticsValidationResult, StringAttribute, TextDirection, Tristate, VoidCallback;
import 'package:collection/collection.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/painting.dart' show MatrixUtils, TransformProperty;
import 'package:flutter/services.dart';
import 'package:vector_math/vector_math_64.dart';
import 'package:flutter/src/semantics/binding.dart' show SemanticsBinding;
import 'package:flutter/src/semantics/semantics_event.dart';
import 'package:flutter/src/services/text_editing.dart';

abstract final class SemanticsConfigurationBindings {
  static void register(DarticPluginContext ctx) {
    ctx.registerClass(
      name: 'package:flutter/src/semantics/semantics.dart::SemanticsConfiguration',
      type: SemanticsConfiguration,
      test: (o) => o is SemanticsConfiguration,
      methods: methodMap(),
    );
  }

  static Map<String, Object? Function(List<Object?>)> methodMap() => {
        'getActionHandler#1': (args) => (args[0] as SemanticsConfiguration).getActionHandler(args[1] as SemanticsAction),
        'tagsChildrenWith#1': (args) => (args[0] as SemanticsConfiguration).tagsChildrenWith(args[1] as SemanticsTag),
        'addTagForChildren#1': (args) { (args[0] as SemanticsConfiguration).addTagForChildren(args[1] as SemanticsTag); return null; },
        'isCompatibleWith#1': (args) => (args[0] as SemanticsConfiguration).isCompatibleWith(args[1] as SemanticsConfiguration?),
        'absorb#1': (args) { (args[0] as SemanticsConfiguration).absorb(args[1] as SemanticsConfiguration); return null; },
        'copy#0': (args) => (args[0] as SemanticsConfiguration).copy(),
        'toString#0': (args) => (args[0] as SemanticsConfiguration).toString(),
        'isSemanticBoundary#0': (args) => (args[0] as SemanticsConfiguration).isSemanticBoundary,
        'localeForSubtree#0': (args) => (args[0] as SemanticsConfiguration).localeForSubtree,
        'locale#0': (args) => (args[0] as SemanticsConfiguration).locale,
        'isBlockingUserActions#0': (args) => (args[0] as SemanticsConfiguration).isBlockingUserActions,
        'explicitChildNodes#0': (args) => (args[0] as SemanticsConfiguration).explicitChildNodes,
        'isBlockingSemanticsOfPreviouslyPaintedNodes#0': (args) => (args[0] as SemanticsConfiguration).isBlockingSemanticsOfPreviouslyPaintedNodes,
        'hasBeenAnnotated#0': (args) => (args[0] as SemanticsConfiguration).hasBeenAnnotated,
        'onTap#0': (args) => (args[0] as SemanticsConfiguration).onTap,
        'onLongPress#0': (args) => (args[0] as SemanticsConfiguration).onLongPress,
        'onScrollLeft#0': (args) => (args[0] as SemanticsConfiguration).onScrollLeft,
        'onDismiss#0': (args) => (args[0] as SemanticsConfiguration).onDismiss,
        'onScrollRight#0': (args) => (args[0] as SemanticsConfiguration).onScrollRight,
        'onScrollUp#0': (args) => (args[0] as SemanticsConfiguration).onScrollUp,
        'onScrollDown#0': (args) => (args[0] as SemanticsConfiguration).onScrollDown,
        'onScrollToOffset#0': (args) => (args[0] as SemanticsConfiguration).onScrollToOffset,
        'onIncrease#0': (args) => (args[0] as SemanticsConfiguration).onIncrease,
        'onDecrease#0': (args) => (args[0] as SemanticsConfiguration).onDecrease,
        'onCopy#0': (args) => (args[0] as SemanticsConfiguration).onCopy,
        'onCut#0': (args) => (args[0] as SemanticsConfiguration).onCut,
        'onPaste#0': (args) => (args[0] as SemanticsConfiguration).onPaste,
        'onShowOnScreen#0': (args) => (args[0] as SemanticsConfiguration).onShowOnScreen,
        'onMoveCursorForwardByCharacter#0': (args) => (args[0] as SemanticsConfiguration).onMoveCursorForwardByCharacter,
        'onMoveCursorBackwardByCharacter#0': (args) => (args[0] as SemanticsConfiguration).onMoveCursorBackwardByCharacter,
        'onMoveCursorForwardByWord#0': (args) => (args[0] as SemanticsConfiguration).onMoveCursorForwardByWord,
        'onMoveCursorBackwardByWord#0': (args) => (args[0] as SemanticsConfiguration).onMoveCursorBackwardByWord,
        'onSetSelection#0': (args) => (args[0] as SemanticsConfiguration).onSetSelection,
        'onSetText#0': (args) => (args[0] as SemanticsConfiguration).onSetText,
        'onDidGainAccessibilityFocus#0': (args) => (args[0] as SemanticsConfiguration).onDidGainAccessibilityFocus,
        'onDidLoseAccessibilityFocus#0': (args) => (args[0] as SemanticsConfiguration).onDidLoseAccessibilityFocus,
        'onFocus#0': (args) => (args[0] as SemanticsConfiguration).onFocus,
        'onExpand#0': (args) => (args[0] as SemanticsConfiguration).onExpand,
        'onCollapse#0': (args) => (args[0] as SemanticsConfiguration).onCollapse,
        'childConfigurationsDelegate#0': (args) => (args[0] as SemanticsConfiguration).childConfigurationsDelegate,
        'sortKey#0': (args) => (args[0] as SemanticsConfiguration).sortKey,
        'indexInParent#0': (args) => (args[0] as SemanticsConfiguration).indexInParent,
        'scrollChildCount#0': (args) => (args[0] as SemanticsConfiguration).scrollChildCount,
        'scrollIndex#0': (args) => (args[0] as SemanticsConfiguration).scrollIndex,
        'platformViewId#0': (args) => (args[0] as SemanticsConfiguration).platformViewId,
        'maxValueLength#0': (args) => (args[0] as SemanticsConfiguration).maxValueLength,
        'currentValueLength#0': (args) => (args[0] as SemanticsConfiguration).currentValueLength,
        'isMergingSemanticsOfDescendants#0': (args) => (args[0] as SemanticsConfiguration).isMergingSemanticsOfDescendants,
        'customSemanticsActions#0': (args) => (args[0] as SemanticsConfiguration).customSemanticsActions,
        'identifier#0': (args) => (args[0] as SemanticsConfiguration).identifier,
        'role#0': (args) => (args[0] as SemanticsConfiguration).role,
        'label#0': (args) => (args[0] as SemanticsConfiguration).label,
        'attributedLabel#0': (args) => (args[0] as SemanticsConfiguration).attributedLabel,
        'value#0': (args) => (args[0] as SemanticsConfiguration).value,
        'attributedValue#0': (args) => (args[0] as SemanticsConfiguration).attributedValue,
        'increasedValue#0': (args) => (args[0] as SemanticsConfiguration).increasedValue,
        'attributedIncreasedValue#0': (args) => (args[0] as SemanticsConfiguration).attributedIncreasedValue,
        'decreasedValue#0': (args) => (args[0] as SemanticsConfiguration).decreasedValue,
        'attributedDecreasedValue#0': (args) => (args[0] as SemanticsConfiguration).attributedDecreasedValue,
        'hint#0': (args) => (args[0] as SemanticsConfiguration).hint,
        'attributedHint#0': (args) => (args[0] as SemanticsConfiguration).attributedHint,
        'tooltip#0': (args) => (args[0] as SemanticsConfiguration).tooltip,
        'hintOverrides#0': (args) => (args[0] as SemanticsConfiguration).hintOverrides,
        'scopesRoute#0': (args) => (args[0] as SemanticsConfiguration).scopesRoute,
        'namesRoute#0': (args) => (args[0] as SemanticsConfiguration).namesRoute,
        'isImage#0': (args) => (args[0] as SemanticsConfiguration).isImage,
        'liveRegion#0': (args) => (args[0] as SemanticsConfiguration).liveRegion,
        'textDirection#0': (args) => (args[0] as SemanticsConfiguration).textDirection,
        'isSelected#0': (args) => (args[0] as SemanticsConfiguration).isSelected,
        'isExpanded#0': (args) => (args[0] as SemanticsConfiguration).isExpanded,
        'isEnabled#0': (args) => (args[0] as SemanticsConfiguration).isEnabled,
        'isChecked#0': (args) => (args[0] as SemanticsConfiguration).isChecked,
        'isCheckStateMixed#0': (args) => (args[0] as SemanticsConfiguration).isCheckStateMixed,
        'isToggled#0': (args) => (args[0] as SemanticsConfiguration).isToggled,
        'isInMutuallyExclusiveGroup#0': (args) => (args[0] as SemanticsConfiguration).isInMutuallyExclusiveGroup,
        'isFocusable#0': (args) => (args[0] as SemanticsConfiguration).isFocusable,
        'isFocused#0': (args) => (args[0] as SemanticsConfiguration).isFocused,
        'isButton#0': (args) => (args[0] as SemanticsConfiguration).isButton,
        'isLink#0': (args) => (args[0] as SemanticsConfiguration).isLink,
        'linkUrl#0': (args) => (args[0] as SemanticsConfiguration).linkUrl,
        'isHeader#0': (args) => (args[0] as SemanticsConfiguration).isHeader,
        'headingLevel#0': (args) => (args[0] as SemanticsConfiguration).headingLevel,
        'isSlider#0': (args) => (args[0] as SemanticsConfiguration).isSlider,
        'isKeyboardKey#0': (args) => (args[0] as SemanticsConfiguration).isKeyboardKey,
        'isHidden#0': (args) => (args[0] as SemanticsConfiguration).isHidden,
        'isTextField#0': (args) => (args[0] as SemanticsConfiguration).isTextField,
        'isReadOnly#0': (args) => (args[0] as SemanticsConfiguration).isReadOnly,
        'isObscured#0': (args) => (args[0] as SemanticsConfiguration).isObscured,
        'isMultiline#0': (args) => (args[0] as SemanticsConfiguration).isMultiline,
        'isRequired#0': (args) => (args[0] as SemanticsConfiguration).isRequired,
        'hasImplicitScrolling#0': (args) => (args[0] as SemanticsConfiguration).hasImplicitScrolling,
        'textSelection#0': (args) => (args[0] as SemanticsConfiguration).textSelection,
        'scrollPosition#0': (args) => (args[0] as SemanticsConfiguration).scrollPosition,
        'scrollExtentMax#0': (args) => (args[0] as SemanticsConfiguration).scrollExtentMax,
        'scrollExtentMin#0': (args) => (args[0] as SemanticsConfiguration).scrollExtentMin,
        'controlsNodes#0': (args) => (args[0] as SemanticsConfiguration).controlsNodes,
        'validationResult#0': (args) => (args[0] as SemanticsConfiguration).validationResult,
        'inputType#0': (args) => (args[0] as SemanticsConfiguration).inputType,
        'tagsForChildren#0': (args) => (args[0] as SemanticsConfiguration).tagsForChildren,
        'hashCode#0': (args) => (args[0] as SemanticsConfiguration).hashCode,
        'isSemanticBoundary=#1': (args) { (args[0] as SemanticsConfiguration).isSemanticBoundary = args[1] as bool; return args[1]; },
        'localeForSubtree=#1': (args) { (args[0] as SemanticsConfiguration).localeForSubtree = args[1] as Locale?; return args[1]; },
        'locale=#1': (args) { (args[0] as SemanticsConfiguration).locale = args[1] as Locale?; return args[1]; },
        'isBlockingUserActions=#1': (args) { (args[0] as SemanticsConfiguration).isBlockingUserActions = args[1] as bool; return args[1]; },
        'explicitChildNodes=#1': (args) { (args[0] as SemanticsConfiguration).explicitChildNodes = args[1] as bool; return args[1]; },
        'isBlockingSemanticsOfPreviouslyPaintedNodes=#1': (args) { (args[0] as SemanticsConfiguration).isBlockingSemanticsOfPreviouslyPaintedNodes = args[1] as bool; return args[1]; },
        'onTap=#1': (args) { (args[0] as SemanticsConfiguration).onTap = args[1] as VoidCallback?; return args[1]; },
        'onLongPress=#1': (args) { (args[0] as SemanticsConfiguration).onLongPress = args[1] as VoidCallback?; return args[1]; },
        'onScrollLeft=#1': (args) { (args[0] as SemanticsConfiguration).onScrollLeft = args[1] as VoidCallback?; return args[1]; },
        'onDismiss=#1': (args) { (args[0] as SemanticsConfiguration).onDismiss = args[1] as VoidCallback?; return args[1]; },
        'onScrollRight=#1': (args) { (args[0] as SemanticsConfiguration).onScrollRight = args[1] as VoidCallback?; return args[1]; },
        'onScrollUp=#1': (args) { (args[0] as SemanticsConfiguration).onScrollUp = args[1] as VoidCallback?; return args[1]; },
        'onScrollDown=#1': (args) { (args[0] as SemanticsConfiguration).onScrollDown = args[1] as VoidCallback?; return args[1]; },
        'onScrollToOffset=#1': (args) { (args[0] as SemanticsConfiguration).onScrollToOffset = args[1] as ScrollToOffsetHandler?; return args[1]; },
        'onIncrease=#1': (args) { (args[0] as SemanticsConfiguration).onIncrease = args[1] as VoidCallback?; return args[1]; },
        'onDecrease=#1': (args) { (args[0] as SemanticsConfiguration).onDecrease = args[1] as VoidCallback?; return args[1]; },
        'onCopy=#1': (args) { (args[0] as SemanticsConfiguration).onCopy = args[1] as VoidCallback?; return args[1]; },
        'onCut=#1': (args) { (args[0] as SemanticsConfiguration).onCut = args[1] as VoidCallback?; return args[1]; },
        'onPaste=#1': (args) { (args[0] as SemanticsConfiguration).onPaste = args[1] as VoidCallback?; return args[1]; },
        'onShowOnScreen=#1': (args) { (args[0] as SemanticsConfiguration).onShowOnScreen = args[1] as VoidCallback?; return args[1]; },
        'onMoveCursorForwardByCharacter=#1': (args) { (args[0] as SemanticsConfiguration).onMoveCursorForwardByCharacter = args[1] as MoveCursorHandler?; return args[1]; },
        'onMoveCursorBackwardByCharacter=#1': (args) { (args[0] as SemanticsConfiguration).onMoveCursorBackwardByCharacter = args[1] as MoveCursorHandler?; return args[1]; },
        'onMoveCursorForwardByWord=#1': (args) { (args[0] as SemanticsConfiguration).onMoveCursorForwardByWord = args[1] as MoveCursorHandler?; return args[1]; },
        'onMoveCursorBackwardByWord=#1': (args) { (args[0] as SemanticsConfiguration).onMoveCursorBackwardByWord = args[1] as MoveCursorHandler?; return args[1]; },
        'onSetSelection=#1': (args) { (args[0] as SemanticsConfiguration).onSetSelection = args[1] as SetSelectionHandler?; return args[1]; },
        'onSetText=#1': (args) { (args[0] as SemanticsConfiguration).onSetText = args[1] as SetTextHandler?; return args[1]; },
        'onDidGainAccessibilityFocus=#1': (args) { (args[0] as SemanticsConfiguration).onDidGainAccessibilityFocus = args[1] as VoidCallback?; return args[1]; },
        'onDidLoseAccessibilityFocus=#1': (args) { (args[0] as SemanticsConfiguration).onDidLoseAccessibilityFocus = args[1] as VoidCallback?; return args[1]; },
        'onFocus=#1': (args) { (args[0] as SemanticsConfiguration).onFocus = args[1] as VoidCallback?; return args[1]; },
        'onExpand=#1': (args) { (args[0] as SemanticsConfiguration).onExpand = args[1] as VoidCallback?; return args[1]; },
        'onCollapse=#1': (args) { (args[0] as SemanticsConfiguration).onCollapse = args[1] as VoidCallback?; return args[1]; },
        'childConfigurationsDelegate=#1': (args) { (args[0] as SemanticsConfiguration).childConfigurationsDelegate = args[1] as ChildSemanticsConfigurationsDelegate?; return args[1]; },
        'sortKey=#1': (args) { (args[0] as SemanticsConfiguration).sortKey = args[1] as SemanticsSortKey?; return args[1]; },
        'indexInParent=#1': (args) { (args[0] as SemanticsConfiguration).indexInParent = args[1] as int?; return args[1]; },
        'scrollChildCount=#1': (args) { (args[0] as SemanticsConfiguration).scrollChildCount = args[1] as int?; return args[1]; },
        'scrollIndex=#1': (args) { (args[0] as SemanticsConfiguration).scrollIndex = args[1] as int?; return args[1]; },
        'platformViewId=#1': (args) { (args[0] as SemanticsConfiguration).platformViewId = args[1] as int?; return args[1]; },
        'maxValueLength=#1': (args) { (args[0] as SemanticsConfiguration).maxValueLength = args[1] as int?; return args[1]; },
        'currentValueLength=#1': (args) { (args[0] as SemanticsConfiguration).currentValueLength = args[1] as int?; return args[1]; },
        'isMergingSemanticsOfDescendants=#1': (args) { (args[0] as SemanticsConfiguration).isMergingSemanticsOfDescendants = args[1] as bool; return args[1]; },
        'customSemanticsActions=#1': (args) { (args[0] as SemanticsConfiguration).customSemanticsActions = (args[1] as Map).cast<CustomSemanticsAction, VoidCallback>(); return args[1]; },
        'identifier=#1': (args) { (args[0] as SemanticsConfiguration).identifier = args[1] as String; return args[1]; },
        'role=#1': (args) { (args[0] as SemanticsConfiguration).role = args[1] as SemanticsRole; return args[1]; },
        'label=#1': (args) { (args[0] as SemanticsConfiguration).label = args[1] as String; return args[1]; },
        'attributedLabel=#1': (args) { (args[0] as SemanticsConfiguration).attributedLabel = args[1] as AttributedString; return args[1]; },
        'value=#1': (args) { (args[0] as SemanticsConfiguration).value = args[1] as String; return args[1]; },
        'attributedValue=#1': (args) { (args[0] as SemanticsConfiguration).attributedValue = args[1] as AttributedString; return args[1]; },
        'increasedValue=#1': (args) { (args[0] as SemanticsConfiguration).increasedValue = args[1] as String; return args[1]; },
        'attributedIncreasedValue=#1': (args) { (args[0] as SemanticsConfiguration).attributedIncreasedValue = args[1] as AttributedString; return args[1]; },
        'decreasedValue=#1': (args) { (args[0] as SemanticsConfiguration).decreasedValue = args[1] as String; return args[1]; },
        'attributedDecreasedValue=#1': (args) { (args[0] as SemanticsConfiguration).attributedDecreasedValue = args[1] as AttributedString; return args[1]; },
        'hint=#1': (args) { (args[0] as SemanticsConfiguration).hint = args[1] as String; return args[1]; },
        'attributedHint=#1': (args) { (args[0] as SemanticsConfiguration).attributedHint = args[1] as AttributedString; return args[1]; },
        'tooltip=#1': (args) { (args[0] as SemanticsConfiguration).tooltip = args[1] as String; return args[1]; },
        'hintOverrides=#1': (args) { (args[0] as SemanticsConfiguration).hintOverrides = args[1] as SemanticsHintOverrides?; return args[1]; },
        'scopesRoute=#1': (args) { (args[0] as SemanticsConfiguration).scopesRoute = args[1] as bool; return args[1]; },
        'namesRoute=#1': (args) { (args[0] as SemanticsConfiguration).namesRoute = args[1] as bool; return args[1]; },
        'isImage=#1': (args) { (args[0] as SemanticsConfiguration).isImage = args[1] as bool; return args[1]; },
        'liveRegion=#1': (args) { (args[0] as SemanticsConfiguration).liveRegion = args[1] as bool; return args[1]; },
        'textDirection=#1': (args) { (args[0] as SemanticsConfiguration).textDirection = args[1] as TextDirection?; return args[1]; },
        'isSelected=#1': (args) { (args[0] as SemanticsConfiguration).isSelected = args[1] as bool; return args[1]; },
        'isExpanded=#1': (args) { (args[0] as SemanticsConfiguration).isExpanded = args[1] as bool?; return args[1]; },
        'isEnabled=#1': (args) { (args[0] as SemanticsConfiguration).isEnabled = args[1] as bool?; return args[1]; },
        'isChecked=#1': (args) { (args[0] as SemanticsConfiguration).isChecked = args[1] as bool?; return args[1]; },
        'isCheckStateMixed=#1': (args) { (args[0] as SemanticsConfiguration).isCheckStateMixed = args[1] as bool?; return args[1]; },
        'isToggled=#1': (args) { (args[0] as SemanticsConfiguration).isToggled = args[1] as bool?; return args[1]; },
        'isInMutuallyExclusiveGroup=#1': (args) { (args[0] as SemanticsConfiguration).isInMutuallyExclusiveGroup = args[1] as bool; return args[1]; },
        'isFocusable=#1': (args) { (args[0] as SemanticsConfiguration).isFocusable = args[1] as bool; return args[1]; },
        'isFocused=#1': (args) { (args[0] as SemanticsConfiguration).isFocused = args[1] as bool?; return args[1]; },
        'isButton=#1': (args) { (args[0] as SemanticsConfiguration).isButton = args[1] as bool; return args[1]; },
        'isLink=#1': (args) { (args[0] as SemanticsConfiguration).isLink = args[1] as bool; return args[1]; },
        'linkUrl=#1': (args) { (args[0] as SemanticsConfiguration).linkUrl = args[1] as Uri?; return args[1]; },
        'isHeader=#1': (args) { (args[0] as SemanticsConfiguration).isHeader = args[1] as bool; return args[1]; },
        'headingLevel=#1': (args) { (args[0] as SemanticsConfiguration).headingLevel = args[1] as int; return args[1]; },
        'isSlider=#1': (args) { (args[0] as SemanticsConfiguration).isSlider = args[1] as bool; return args[1]; },
        'isKeyboardKey=#1': (args) { (args[0] as SemanticsConfiguration).isKeyboardKey = args[1] as bool; return args[1]; },
        'isHidden=#1': (args) { (args[0] as SemanticsConfiguration).isHidden = args[1] as bool; return args[1]; },
        'isTextField=#1': (args) { (args[0] as SemanticsConfiguration).isTextField = args[1] as bool; return args[1]; },
        'isReadOnly=#1': (args) { (args[0] as SemanticsConfiguration).isReadOnly = args[1] as bool; return args[1]; },
        'isObscured=#1': (args) { (args[0] as SemanticsConfiguration).isObscured = args[1] as bool; return args[1]; },
        'isMultiline=#1': (args) { (args[0] as SemanticsConfiguration).isMultiline = args[1] as bool; return args[1]; },
        'isRequired=#1': (args) { (args[0] as SemanticsConfiguration).isRequired = args[1] as bool?; return args[1]; },
        'hasImplicitScrolling=#1': (args) { (args[0] as SemanticsConfiguration).hasImplicitScrolling = args[1] as bool; return args[1]; },
        'textSelection=#1': (args) { (args[0] as SemanticsConfiguration).textSelection = args[1] as TextSelection?; return args[1]; },
        'scrollPosition=#1': (args) { (args[0] as SemanticsConfiguration).scrollPosition = args[1] as double?; return args[1]; },
        'scrollExtentMax=#1': (args) { (args[0] as SemanticsConfiguration).scrollExtentMax = args[1] as double?; return args[1]; },
        'scrollExtentMin=#1': (args) { (args[0] as SemanticsConfiguration).scrollExtentMin = args[1] as double?; return args[1]; },
        'controlsNodes=#1': (args) { (args[0] as SemanticsConfiguration).controlsNodes = args[1] == null ? null : (args[1] as Set).cast<String>(); return args[1]; },
        'validationResult=#1': (args) { (args[0] as SemanticsConfiguration).validationResult = args[1] as SemanticsValidationResult; return args[1]; },
        'inputType=#1': (args) { (args[0] as SemanticsConfiguration).inputType = args[1] as SemanticsInputType; return args[1]; },
        '==#1': (args) => (args[0] as SemanticsConfiguration) == (args[1] as Object),
        '#0': (args) => SemanticsConfiguration(),
      };
}
