// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7

// ignore_for_file: implementation_imports, unused_import, unnecessary_import, unnecessary_cast, invalid_use_of_protected_member, deprecated_member_use, sort_child_properties_last

import 'package:dartic/dartic.dart';
import 'package:dartic/dartic_internal.dart';
import 'package:flutter/src/material/material_localizations.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/src/material/debug.dart';
import 'package:flutter/src/material/time.dart';
import 'package:flutter/src/material/typography.dart';

abstract final class DefaultMaterialLocalizationsBindings {
  static void register(DarticPluginContext ctx) {
    ctx.registerClass(
      name: 'package:flutter/src/material/material_localizations.dart::DefaultMaterialLocalizations',
      type: DefaultMaterialLocalizations,
      test: (o) => o is DefaultMaterialLocalizations,
      methods: methodMap(),
      superclasses: ['package:flutter/src/material/material_localizations.dart::MaterialLocalizations'],
    );
    ctx.registerBinding('package:flutter/src/material/material_localizations.dart::DefaultMaterialLocalizations::load#1', (args) => DefaultMaterialLocalizations.load(args[0] as Locale));
    ctx.registerBinding('package:flutter/src/material/material_localizations.dart::DefaultMaterialLocalizations::delegate#0', (args) => DefaultMaterialLocalizations.delegate);
  }

  static Map<String, Object? Function(List<Object?>)> methodMap() => {
        'formatHour#2': (args) => (args[0] as DefaultMaterialLocalizations).formatHour(args[1] as TimeOfDay, alwaysUse24HourFormat: identical(args[2], darticAbsent) ? false : args[2] as bool),
        'formatMinute#1': (args) => (args[0] as DefaultMaterialLocalizations).formatMinute(args[1] as TimeOfDay),
        'formatYear#1': (args) => (args[0] as DefaultMaterialLocalizations).formatYear(args[1] as DateTime),
        'formatCompactDate#1': (args) => (args[0] as DefaultMaterialLocalizations).formatCompactDate(args[1] as DateTime),
        'formatShortDate#1': (args) => (args[0] as DefaultMaterialLocalizations).formatShortDate(args[1] as DateTime),
        'formatMediumDate#1': (args) => (args[0] as DefaultMaterialLocalizations).formatMediumDate(args[1] as DateTime),
        'formatFullDate#1': (args) => (args[0] as DefaultMaterialLocalizations).formatFullDate(args[1] as DateTime),
        'formatMonthYear#1': (args) => (args[0] as DefaultMaterialLocalizations).formatMonthYear(args[1] as DateTime),
        'formatShortMonthDay#1': (args) => (args[0] as DefaultMaterialLocalizations).formatShortMonthDay(args[1] as DateTime),
        'parseCompactDate#1': (args) => (args[0] as DefaultMaterialLocalizations).parseCompactDate(args[1] as String?),
        'dateRangeStartDateSemanticLabel#1': (args) => (args[0] as DefaultMaterialLocalizations).dateRangeStartDateSemanticLabel(args[1] as String),
        'dateRangeEndDateSemanticLabel#1': (args) => (args[0] as DefaultMaterialLocalizations).dateRangeEndDateSemanticLabel(args[1] as String),
        'formatDecimal#1': (args) => (args[0] as DefaultMaterialLocalizations).formatDecimal(args[1] as int),
        'formatTimeOfDay#2': (args) => (args[0] as DefaultMaterialLocalizations).formatTimeOfDay(args[1] as TimeOfDay, alwaysUse24HourFormat: identical(args[2], darticAbsent) ? false : args[2] as bool),
        'scrimOnTapHint#1': (args) => (args[0] as DefaultMaterialLocalizations).scrimOnTapHint(args[1] as String),
        'aboutListTileTitle#1': (args) => (args[0] as DefaultMaterialLocalizations).aboutListTileTitle(args[1] as String),
        'licensesPackageDetailText#1': (args) => (args[0] as DefaultMaterialLocalizations).licensesPackageDetailText(args[1] as int),
        'pageRowsInfoTitle#4': (args) => (args[0] as DefaultMaterialLocalizations).pageRowsInfoTitle(args[1] as int, args[2] as int, args[3] as int, args[4] as bool),
        'tabLabel#2': (args) => (args[0] as DefaultMaterialLocalizations).tabLabel(tabIndex: args[1] as int, tabCount: args[2] as int),
        'selectedRowCountTitle#1': (args) => (args[0] as DefaultMaterialLocalizations).selectedRowCountTitle(args[1] as int),
        'timeOfDayFormat#1': (args) => (args[0] as DefaultMaterialLocalizations).timeOfDayFormat(alwaysUse24HourFormat: identical(args[1], darticAbsent) ? false : args[1] as bool),
        'remainingTextFieldCharacterCount#1': (args) => (args[0] as DefaultMaterialLocalizations).remainingTextFieldCharacterCount(args[1] as int),
        'toString#0': (args) => (args[0] as DefaultMaterialLocalizations).toString(),
        'narrowWeekdays#0': (args) => (args[0] as DefaultMaterialLocalizations).narrowWeekdays,
        'firstDayOfWeekIndex#0': (args) => (args[0] as DefaultMaterialLocalizations).firstDayOfWeekIndex,
        'dateSeparator#0': (args) => (args[0] as DefaultMaterialLocalizations).dateSeparator,
        'dateHelpText#0': (args) => (args[0] as DefaultMaterialLocalizations).dateHelpText,
        'selectYearSemanticsLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).selectYearSemanticsLabel,
        'unspecifiedDate#0': (args) => (args[0] as DefaultMaterialLocalizations).unspecifiedDate,
        'unspecifiedDateRange#0': (args) => (args[0] as DefaultMaterialLocalizations).unspecifiedDateRange,
        'dateInputLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).dateInputLabel,
        'dateRangeStartLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).dateRangeStartLabel,
        'dateRangeEndLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).dateRangeEndLabel,
        'invalidDateFormatLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).invalidDateFormatLabel,
        'invalidDateRangeLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).invalidDateRangeLabel,
        'dateOutOfRangeLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).dateOutOfRangeLabel,
        'saveButtonLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).saveButtonLabel,
        'datePickerHelpText#0': (args) => (args[0] as DefaultMaterialLocalizations).datePickerHelpText,
        'dateRangePickerHelpText#0': (args) => (args[0] as DefaultMaterialLocalizations).dateRangePickerHelpText,
        'calendarModeButtonLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).calendarModeButtonLabel,
        'inputDateModeButtonLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).inputDateModeButtonLabel,
        'timePickerDialHelpText#0': (args) => (args[0] as DefaultMaterialLocalizations).timePickerDialHelpText,
        'timePickerInputHelpText#0': (args) => (args[0] as DefaultMaterialLocalizations).timePickerInputHelpText,
        'timePickerHourLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).timePickerHourLabel,
        'timePickerMinuteLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).timePickerMinuteLabel,
        'invalidTimeLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).invalidTimeLabel,
        'dialModeButtonLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).dialModeButtonLabel,
        'inputTimeModeButtonLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).inputTimeModeButtonLabel,
        'openAppDrawerTooltip#0': (args) => (args[0] as DefaultMaterialLocalizations).openAppDrawerTooltip,
        'backButtonTooltip#0': (args) => (args[0] as DefaultMaterialLocalizations).backButtonTooltip,
        'clearButtonTooltip#0': (args) => (args[0] as DefaultMaterialLocalizations).clearButtonTooltip,
        'closeButtonTooltip#0': (args) => (args[0] as DefaultMaterialLocalizations).closeButtonTooltip,
        'deleteButtonTooltip#0': (args) => (args[0] as DefaultMaterialLocalizations).deleteButtonTooltip,
        'moreButtonTooltip#0': (args) => (args[0] as DefaultMaterialLocalizations).moreButtonTooltip,
        'nextMonthTooltip#0': (args) => (args[0] as DefaultMaterialLocalizations).nextMonthTooltip,
        'previousMonthTooltip#0': (args) => (args[0] as DefaultMaterialLocalizations).previousMonthTooltip,
        'nextPageTooltip#0': (args) => (args[0] as DefaultMaterialLocalizations).nextPageTooltip,
        'previousPageTooltip#0': (args) => (args[0] as DefaultMaterialLocalizations).previousPageTooltip,
        'firstPageTooltip#0': (args) => (args[0] as DefaultMaterialLocalizations).firstPageTooltip,
        'lastPageTooltip#0': (args) => (args[0] as DefaultMaterialLocalizations).lastPageTooltip,
        'showMenuTooltip#0': (args) => (args[0] as DefaultMaterialLocalizations).showMenuTooltip,
        'drawerLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).drawerLabel,
        'menuBarMenuLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).menuBarMenuLabel,
        'popupMenuLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).popupMenuLabel,
        'dialogLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).dialogLabel,
        'alertDialogLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).alertDialogLabel,
        'searchFieldLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).searchFieldLabel,
        'currentDateLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).currentDateLabel,
        'selectedDateLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).selectedDateLabel,
        'scrimLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).scrimLabel,
        'bottomSheetLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).bottomSheetLabel,
        'licensesPageTitle#0': (args) => (args[0] as DefaultMaterialLocalizations).licensesPageTitle,
        'rowsPerPageTitle#0': (args) => (args[0] as DefaultMaterialLocalizations).rowsPerPageTitle,
        'cancelButtonLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).cancelButtonLabel,
        'closeButtonLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).closeButtonLabel,
        'continueButtonLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).continueButtonLabel,
        'copyButtonLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).copyButtonLabel,
        'cutButtonLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).cutButtonLabel,
        'scanTextButtonLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).scanTextButtonLabel,
        'okButtonLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).okButtonLabel,
        'pasteButtonLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).pasteButtonLabel,
        'selectAllButtonLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).selectAllButtonLabel,
        'lookUpButtonLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).lookUpButtonLabel,
        'searchWebButtonLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).searchWebButtonLabel,
        'shareButtonLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).shareButtonLabel,
        'viewLicensesButtonLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).viewLicensesButtonLabel,
        'anteMeridiemAbbreviation#0': (args) => (args[0] as DefaultMaterialLocalizations).anteMeridiemAbbreviation,
        'postMeridiemAbbreviation#0': (args) => (args[0] as DefaultMaterialLocalizations).postMeridiemAbbreviation,
        'timePickerHourModeAnnouncement#0': (args) => (args[0] as DefaultMaterialLocalizations).timePickerHourModeAnnouncement,
        'timePickerMinuteModeAnnouncement#0': (args) => (args[0] as DefaultMaterialLocalizations).timePickerMinuteModeAnnouncement,
        'modalBarrierDismissLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).modalBarrierDismissLabel,
        'menuDismissLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).menuDismissLabel,
        'scriptCategory#0': (args) => (args[0] as DefaultMaterialLocalizations).scriptCategory,
        'signedInLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).signedInLabel,
        'hideAccountsLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).hideAccountsLabel,
        'showAccountsLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).showAccountsLabel,
        'reorderItemUp#0': (args) => (args[0] as DefaultMaterialLocalizations).reorderItemUp,
        'reorderItemDown#0': (args) => (args[0] as DefaultMaterialLocalizations).reorderItemDown,
        'reorderItemLeft#0': (args) => (args[0] as DefaultMaterialLocalizations).reorderItemLeft,
        'reorderItemRight#0': (args) => (args[0] as DefaultMaterialLocalizations).reorderItemRight,
        'reorderItemToEnd#0': (args) => (args[0] as DefaultMaterialLocalizations).reorderItemToEnd,
        'reorderItemToStart#0': (args) => (args[0] as DefaultMaterialLocalizations).reorderItemToStart,
        'expandedIconTapHint#0': (args) => (args[0] as DefaultMaterialLocalizations).expandedIconTapHint,
        'collapsedIconTapHint#0': (args) => (args[0] as DefaultMaterialLocalizations).collapsedIconTapHint,
        'expansionTileExpandedHint#0': (args) => (args[0] as DefaultMaterialLocalizations).expansionTileExpandedHint,
        'expansionTileCollapsedHint#0': (args) => (args[0] as DefaultMaterialLocalizations).expansionTileCollapsedHint,
        'expansionTileExpandedTapHint#0': (args) => (args[0] as DefaultMaterialLocalizations).expansionTileExpandedTapHint,
        'expansionTileCollapsedTapHint#0': (args) => (args[0] as DefaultMaterialLocalizations).expansionTileCollapsedTapHint,
        'expandedHint#0': (args) => (args[0] as DefaultMaterialLocalizations).expandedHint,
        'collapsedHint#0': (args) => (args[0] as DefaultMaterialLocalizations).collapsedHint,
        'refreshIndicatorSemanticLabel#0': (args) => (args[0] as DefaultMaterialLocalizations).refreshIndicatorSemanticLabel,
        'keyboardKeyAlt#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyAlt,
        'keyboardKeyAltGraph#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyAltGraph,
        'keyboardKeyBackspace#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyBackspace,
        'keyboardKeyCapsLock#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyCapsLock,
        'keyboardKeyChannelDown#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyChannelDown,
        'keyboardKeyChannelUp#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyChannelUp,
        'keyboardKeyControl#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyControl,
        'keyboardKeyDelete#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyDelete,
        'keyboardKeyEject#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyEject,
        'keyboardKeyEnd#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyEnd,
        'keyboardKeyEscape#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyEscape,
        'keyboardKeyFn#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyFn,
        'keyboardKeyHome#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyHome,
        'keyboardKeyInsert#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyInsert,
        'keyboardKeyMeta#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyMeta,
        'keyboardKeyMetaMacOs#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyMetaMacOs,
        'keyboardKeyMetaWindows#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyMetaWindows,
        'keyboardKeyNumLock#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumLock,
        'keyboardKeyNumpad1#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumpad1,
        'keyboardKeyNumpad2#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumpad2,
        'keyboardKeyNumpad3#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumpad3,
        'keyboardKeyNumpad4#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumpad4,
        'keyboardKeyNumpad5#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumpad5,
        'keyboardKeyNumpad6#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumpad6,
        'keyboardKeyNumpad7#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumpad7,
        'keyboardKeyNumpad8#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumpad8,
        'keyboardKeyNumpad9#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumpad9,
        'keyboardKeyNumpad0#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumpad0,
        'keyboardKeyNumpadAdd#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumpadAdd,
        'keyboardKeyNumpadComma#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumpadComma,
        'keyboardKeyNumpadDecimal#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumpadDecimal,
        'keyboardKeyNumpadDivide#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumpadDivide,
        'keyboardKeyNumpadEnter#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumpadEnter,
        'keyboardKeyNumpadEqual#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumpadEqual,
        'keyboardKeyNumpadMultiply#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumpadMultiply,
        'keyboardKeyNumpadParenLeft#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumpadParenLeft,
        'keyboardKeyNumpadParenRight#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumpadParenRight,
        'keyboardKeyNumpadSubtract#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyNumpadSubtract,
        'keyboardKeyPageDown#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyPageDown,
        'keyboardKeyPageUp#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyPageUp,
        'keyboardKeyPower#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyPower,
        'keyboardKeyPowerOff#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyPowerOff,
        'keyboardKeyPrintScreen#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyPrintScreen,
        'keyboardKeyScrollLock#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyScrollLock,
        'keyboardKeySelect#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeySelect,
        'keyboardKeyShift#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeyShift,
        'keyboardKeySpace#0': (args) => (args[0] as DefaultMaterialLocalizations).keyboardKeySpace,
        'hashCode#0': (args) => (args[0] as DefaultMaterialLocalizations).hashCode,
        '==#1': (args) => (args[0] as DefaultMaterialLocalizations) == (args[1] as Object),
        '#0': (args) => DefaultMaterialLocalizations(),
        '_#fromFields#0': (args) => DefaultMaterialLocalizations(),
      };
}
