// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7

import 'package:dartic/dartic.dart';
import 'package:dartic/dartic_internal.dart';
import 'package:flutter/src/material/debug.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/src/material/material.dart';
import 'package:flutter/src/material/material_localizations.dart';
import 'package:flutter/src/material/scaffold.dart';
import 'package:flutter/src/material/time.dart';
import 'package:flutter/services.dart';
import 'package:flutter/src/material/about.dart';
import 'dart:developer';
import 'dart:io';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/scheduler.dart';
import 'package:flutter/src/material/app_bar.dart';
import 'package:flutter/src/material/back_button.dart';
import 'package:flutter/src/material/card.dart';
import 'package:flutter/src/material/constants.dart';
import 'package:flutter/src/material/dialog.dart';
import 'package:flutter/src/material/divider.dart';
import 'package:flutter/src/material/floating_action_button_location.dart';
import 'package:flutter/src/material/ink_decoration.dart';
import 'package:flutter/src/material/list_tile.dart';
import 'package:flutter/src/material/page.dart';
import 'package:flutter/src/material/page_transitions_theme.dart';
import 'package:flutter/src/material/progress_indicator.dart';
import 'package:flutter/src/material/scrollbar.dart';
import 'package:flutter/src/material/text_button.dart';
import 'package:flutter/src/material/text_theme.dart';
import 'package:flutter/src/material/theme.dart';
import 'dart:ui';
import 'package:flutter/src/material/color_scheme.dart';
import 'package:flutter/src/material/colors.dart';
import 'package:flutter/src/material/dialog_theme.dart';
import 'package:flutter/src/material/ink_well.dart';
import 'package:flutter/src/material/bottom_sheet.dart';
import 'dart:math' as math;
import 'package:flutter/gestures.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/src/material/bottom_sheet_theme.dart';
import 'package:flutter/src/material/motion.dart';
import 'package:flutter/src/material/date_picker.dart';
import 'package:flutter/src/material/button_style.dart';
import 'package:flutter/src/material/calendar_date_picker.dart';
import 'package:flutter/src/material/date.dart';
import 'package:flutter/src/material/date_picker_theme.dart';
import 'package:flutter/src/material/icon_button.dart';
import 'package:flutter/src/material/icons.dart';
import 'package:flutter/src/material/input_border.dart';
import 'package:flutter/src/material/input_date_picker_form_field.dart';
import 'package:flutter/src/material/input_decorator.dart';
import 'package:flutter/src/material/text_field.dart';
import 'package:flutter/src/material/popup_menu.dart';
import 'package:flutter/src/material/list_tile_theme.dart';
import 'package:flutter/src/material/popup_menu_theme.dart';
import 'package:flutter/src/material/tooltip.dart';
import 'package:flutter/src/material/search.dart';
import 'package:flutter/src/material/app_bar_theme.dart';
import 'package:flutter/src/material/time_picker.dart';
import 'dart:async';
import 'package:flutter/src/material/curves.dart';
import 'package:flutter/src/material/material_state.dart';
import 'package:flutter/src/material/text_form_field.dart';
import 'package:flutter/src/material/time_picker_theme.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:flutter/src/widgets/navigator.dart';
import 'package:flutter/src/widgets/focus_traversal.dart';
import 'package:flutter/src/animation/animation_style.dart';
import 'package:flutter/animation.dart';
import 'package:flutter/src/painting/borders.dart';
import 'package:flutter/painting.dart';
import 'package:flutter/src/rendering/box.dart';
import 'package:flutter/src/animation/animation_controller.dart';
import 'package:flutter/src/widgets/date.dart';
import 'package:flutter/src/services/text_input.dart';
import 'package:flutter/src/foundation/basic_types.dart';
import 'package:flutter/src/widgets/icon.dart';
import 'package:flutter/src/rendering/stack.dart';
import 'package:flutter/src/painting/edge_insets.dart';
import 'package:flutter/src/widgets/media_query.dart';

abstract final class MaterialTopLevelBindings {
  static void register(DarticPluginContext ctx) {
    ctx.registerBinding('package:flutter/src/material/debug.dart::::debugCheckHasMaterial#1', (args) => debugCheckHasMaterial(args[0] as BuildContext));
    ctx.registerBinding('package:flutter/src/material/debug.dart::::debugCheckHasMaterialLocalizations#1', (args) => debugCheckHasMaterialLocalizations(args[0] as BuildContext));
    ctx.registerBinding('package:flutter/src/material/debug.dart::::debugCheckHasScaffold#1', (args) => debugCheckHasScaffold(args[0] as BuildContext));
    ctx.registerBinding('package:flutter/src/material/debug.dart::::debugCheckHasScaffoldMessenger#1', (args) => debugCheckHasScaffoldMessenger(args[0] as BuildContext));
    ctx.registerBinding('package:flutter/src/material/time.dart::::hourFormat#1', (args) => hourFormat(of: args[0] as TimeOfDayFormat));
    ctx.registerBinding('package:flutter/src/material/about.dart::::showAboutDialog#12', (args) { showAboutDialog(context: args[0] as BuildContext, applicationName: args[1] as String?, applicationVersion: args[2] as String?, applicationIcon: args[3] as Widget?, applicationLegalese: args[4] as String?, children: args[5] == null ? null : (args[5] as List).cast<Widget>(), barrierDismissible: args[6] as bool, barrierColor: args[7] as Color?, barrierLabel: args[8] as String?, useRootNavigator: args[9] as bool, routeSettings: args[10] as RouteSettings?, anchorPoint: args[11] as Offset?); return null; });
    ctx.registerBinding('package:flutter/src/material/about.dart::::showAdaptiveAboutDialog#12', (args) { showAdaptiveAboutDialog(context: args[0] as BuildContext, applicationName: args[1] as String?, applicationVersion: args[2] as String?, applicationIcon: args[3] as Widget?, applicationLegalese: args[4] as String?, children: args[5] == null ? null : (args[5] as List).cast<Widget>(), barrierDismissible: args[6] as bool, barrierColor: args[7] as Color?, barrierLabel: args[8] as String?, useRootNavigator: args[9] as bool, routeSettings: args[10] as RouteSettings?, anchorPoint: args[11] as Offset?); return null; });
    ctx.registerBinding('package:flutter/src/material/dialog.dart::::showAdaptiveDialog#12', (args) => showAdaptiveDialog(context: args[0] as BuildContext, builder: (a) => (args[1] as Function)(a) as Widget, barrierDismissible: args[2] as bool?, barrierColor: args[3] as Color?, barrierLabel: args[4] as String?, useSafeArea: args[5] as bool, useRootNavigator: args[6] as bool, routeSettings: args[7] as RouteSettings?, anchorPoint: args[8] as Offset?, traversalEdgeBehavior: args[9] as TraversalEdgeBehavior?, requestFocus: args[10] as bool?, animationStyle: args[11] as AnimationStyle?));
    ctx.registerBinding('package:flutter/src/material/bottom_sheet.dart::::showBottomSheet#11', (args) => showBottomSheet(context: args[0] as BuildContext, builder: (a) => (args[1] as Function)(a) as Widget, backgroundColor: args[2] as Color?, elevation: args[3] as double?, shape: args[4] as ShapeBorder?, clipBehavior: args[5] as Clip?, constraints: args[6] as BoxConstraints?, enableDrag: args[7] as bool?, showDragHandle: args[8] as bool?, transitionAnimationController: args[9] as AnimationController?, sheetAnimationStyle: args[10] as AnimationStyle?));
    ctx.registerBinding('package:flutter/src/material/date_picker.dart::::showDatePicker#29', (args) => showDatePicker(context: args[0] as BuildContext, initialDate: args[1] as DateTime?, firstDate: args[2] as DateTime, lastDate: args[3] as DateTime, currentDate: args[4] as DateTime?, initialEntryMode: args[5] as DatePickerEntryMode, selectableDayPredicate: (args[6] as Function?) == null ? null : (a) => (args[6] as Function?)!(a), helpText: args[7] as String?, cancelText: args[8] as String?, confirmText: args[9] as String?, locale: args[10] as Locale?, barrierDismissible: args[11] as bool, barrierColor: args[12] as Color?, barrierLabel: args[13] as String?, useRootNavigator: args[14] as bool, routeSettings: args[15] as RouteSettings?, textDirection: args[16] as TextDirection?, builder: (args[17] as Function?) == null ? null : (a, b) => (args[17] as Function?)!(a, b), initialDatePickerMode: args[18] as DatePickerMode, errorFormatText: args[19] as String?, errorInvalidText: args[20] as String?, fieldHintText: args[21] as String?, fieldLabelText: args[22] as String?, keyboardType: args[23] as TextInputType?, anchorPoint: args[24] as Offset?, onDatePickerModeChange: (args[25] as Function?) == null ? null : (a) => (args[25] as Function?)!(a), switchToInputEntryModeIcon: args[26] as Icon?, switchToCalendarEntryModeIcon: args[27] as Icon?, calendarDelegate: args[28] as CalendarDelegate<DateTime>));
    ctx.registerBinding('package:flutter/src/material/date_picker.dart::::showDateRangePicker#31', (args) => showDateRangePicker(context: args[0] as BuildContext, initialDateRange: args[1] as DateTimeRange<DateTime>?, firstDate: args[2] as DateTime, lastDate: args[3] as DateTime, currentDate: args[4] as DateTime?, initialEntryMode: args[5] as DatePickerEntryMode, helpText: args[6] as String?, cancelText: args[7] as String?, confirmText: args[8] as String?, saveText: args[9] as String?, errorFormatText: args[10] as String?, errorInvalidText: args[11] as String?, errorInvalidRangeText: args[12] as String?, fieldStartHintText: args[13] as String?, fieldEndHintText: args[14] as String?, fieldStartLabelText: args[15] as String?, fieldEndLabelText: args[16] as String?, locale: args[17] as Locale?, barrierDismissible: args[18] as bool, barrierColor: args[19] as Color?, barrierLabel: args[20] as String?, useRootNavigator: args[21] as bool, routeSettings: args[22] as RouteSettings?, textDirection: args[23] as TextDirection?, builder: (args[24] as Function?) == null ? null : (a, b) => (args[24] as Function?)!(a, b), anchorPoint: args[25] as Offset?, keyboardType: args[26] as TextInputType, switchToInputEntryModeIcon: args[27] as Icon?, switchToCalendarEntryModeIcon: args[28] as Icon?, selectableDayPredicate: (args[29] as Function?) == null ? null : (a, b, c) => (args[29] as Function?)!(a, b, c), calendarDelegate: args[30] as CalendarDelegate<DateTime>));
    ctx.registerBinding('package:flutter/src/material/dialog.dart::::showDialog#13', (args) => showDialog(context: args[0] as BuildContext, builder: (a) => (args[1] as Function)(a) as Widget, barrierDismissible: args[2] as bool, barrierColor: args[3] as Color?, barrierLabel: args[4] as String?, useSafeArea: args[5] as bool, useRootNavigator: args[6] as bool, routeSettings: args[7] as RouteSettings?, anchorPoint: args[8] as Offset?, traversalEdgeBehavior: args[9] as TraversalEdgeBehavior?, fullscreenDialog: args[10] as bool, requestFocus: args[11] as bool?, animationStyle: args[12] as AnimationStyle?));
    ctx.registerBinding('package:flutter/src/material/about.dart::::showLicensePage#6', (args) { showLicensePage(context: args[0] as BuildContext, applicationName: args[1] as String?, applicationVersion: args[2] as String?, applicationIcon: args[3] as Widget?, applicationLegalese: args[4] as String?, useRootNavigator: args[5] as bool); return null; });
    ctx.registerBinding('package:flutter/src/material/popup_menu.dart::::showMenu#18', (args) => showMenu(context: args[0] as BuildContext, position: args[1] as RelativeRect?, positionBuilder: (args[2] as Function?) == null ? null : (a, b) => (args[2] as Function?)!(a, b), items: (args[3] as List).cast<PopupMenuEntry>(), initialValue: args[4], elevation: args[5] as double?, shadowColor: args[6] as Color?, surfaceTintColor: args[7] as Color?, semanticLabel: args[8] as String?, shape: args[9] as ShapeBorder?, menuPadding: args[10] as EdgeInsetsGeometry?, color: args[11] as Color?, useRootNavigator: args[12] as bool, constraints: args[13] as BoxConstraints?, clipBehavior: args[14] as Clip, routeSettings: args[15] as RouteSettings?, popUpAnimationStyle: args[16] as AnimationStyle?, requestFocus: args[17] as bool?));
    ctx.registerBinding('package:flutter/src/material/bottom_sheet.dart::::showModalBottomSheet#21', (args) => showModalBottomSheet(context: args[0] as BuildContext, builder: (a) => (args[1] as Function)(a) as Widget, backgroundColor: args[2] as Color?, barrierLabel: args[3] as String?, elevation: args[4] as double?, shape: args[5] as ShapeBorder?, clipBehavior: args[6] as Clip?, constraints: args[7] as BoxConstraints?, barrierColor: args[8] as Color?, isScrollControlled: args[9] as bool, scrollControlDisabledMaxHeightRatio: args[10] as double, useRootNavigator: args[11] as bool, isDismissible: args[12] as bool, enableDrag: args[13] as bool, showDragHandle: args[14] as bool?, useSafeArea: args[15] as bool, routeSettings: args[16] as RouteSettings?, transitionAnimationController: args[17] as AnimationController?, anchorPoint: args[18] as Offset?, sheetAnimationStyle: args[19] as AnimationStyle?, requestFocus: args[20] as bool?));
    ctx.registerBinding('package:flutter/src/material/search.dart::::showSearch#5', (args) => showSearch(context: args[0] as BuildContext, delegate: args[1] as SearchDelegate, query: args[2] as String?, useRootNavigator: args[3] as bool, maintainState: args[4] as bool));
    ctx.registerBinding('package:flutter/src/material/time_picker.dart::::showTimePicker#21', (args) => showTimePicker(context: args[0] as BuildContext, initialTime: args[1] as TimeOfDay, builder: (args[2] as Function?) == null ? null : (a, b) => (args[2] as Function?)!(a, b), barrierDismissible: args[3] as bool, barrierColor: args[4] as Color?, barrierLabel: args[5] as String?, useRootNavigator: args[6] as bool, initialEntryMode: args[7] as TimePickerEntryMode, cancelText: args[8] as String?, confirmText: args[9] as String?, helpText: args[10] as String?, errorInvalidText: args[11] as String?, hourLabelText: args[12] as String?, minuteLabelText: args[13] as String?, routeSettings: args[14] as RouteSettings?, onEntryModeChanged: (args[15] as Function?) == null ? null : (a) => (args[15] as Function?)!(a), anchorPoint: args[16] as Offset?, orientation: args[17] as Orientation?, switchToInputEntryModeIcon: args[18] as Icon?, switchToTimerEntryModeIcon: args[19] as Icon?, emptyInitialInput: args[20] as bool));
  }
}
