// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7

// ignore_for_file: implementation_imports, unused_import, unnecessary_import, unnecessary_cast, invalid_use_of_protected_member, deprecated_member_use, sort_child_properties_last

import 'package:dartic/dartic.dart';
import 'package:dartic/dartic_internal.dart';
import 'package:flutter/src/material/material_localizations.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter/src/material/debug.dart';
import 'package:flutter/src/material/time.dart';
import 'package:flutter/src/material/typography.dart';

abstract final class MaterialLocalizationsBindings {
  static void register(DarticPluginContext ctx) {
    ctx.registerClass(
      name: 'package:flutter/src/material/material_localizations.dart::MaterialLocalizations',
      type: MaterialLocalizations,
      test: (o) => o is MaterialLocalizations,
      methods: methodMap(),
    );
    ctx.registerBinding('package:flutter/src/material/material_localizations.dart::MaterialLocalizations::of#1', (args) => MaterialLocalizations.of(args[0] as BuildContext));
  }

  static Map<String, Object? Function(List<Object?>)> methodMap() => {
        'aboutListTileTitle#1': (args) => (args[0] as MaterialLocalizations).aboutListTileTitle(args[1] as String),
        'licensesPackageDetailText#1': (args) => (args[0] as MaterialLocalizations).licensesPackageDetailText(args[1] as int),
        'pageRowsInfoTitle#4': (args) => (args[0] as MaterialLocalizations).pageRowsInfoTitle(args[1] as int, args[2] as int, args[3] as int, args[4] as bool),
        'tabLabel#2': (args) => (args[0] as MaterialLocalizations).tabLabel(tabIndex: args[1] as int, tabCount: args[2] as int),
        'selectedRowCountTitle#1': (args) => (args[0] as MaterialLocalizations).selectedRowCountTitle(args[1] as int),
        'scrimOnTapHint#1': (args) => (args[0] as MaterialLocalizations).scrimOnTapHint(args[1] as String),
        'timeOfDayFormat#1': (args) => (args[0] as MaterialLocalizations).timeOfDayFormat(alwaysUse24HourFormat: identical(args[1], darticAbsent) ? false : args[1] as bool),
        'formatDecimal#1': (args) => (args[0] as MaterialLocalizations).formatDecimal(args[1] as int),
        'formatHour#2': (args) => (args[0] as MaterialLocalizations).formatHour(args[1] as TimeOfDay, alwaysUse24HourFormat: identical(args[2], darticAbsent) ? false : args[2] as bool),
        'formatMinute#1': (args) => (args[0] as MaterialLocalizations).formatMinute(args[1] as TimeOfDay),
        'formatTimeOfDay#2': (args) => (args[0] as MaterialLocalizations).formatTimeOfDay(args[1] as TimeOfDay, alwaysUse24HourFormat: identical(args[2], darticAbsent) ? false : args[2] as bool),
        'formatYear#1': (args) => (args[0] as MaterialLocalizations).formatYear(args[1] as DateTime),
        'formatCompactDate#1': (args) => (args[0] as MaterialLocalizations).formatCompactDate(args[1] as DateTime),
        'formatShortDate#1': (args) => (args[0] as MaterialLocalizations).formatShortDate(args[1] as DateTime),
        'formatMediumDate#1': (args) => (args[0] as MaterialLocalizations).formatMediumDate(args[1] as DateTime),
        'formatFullDate#1': (args) => (args[0] as MaterialLocalizations).formatFullDate(args[1] as DateTime),
        'formatMonthYear#1': (args) => (args[0] as MaterialLocalizations).formatMonthYear(args[1] as DateTime),
        'formatShortMonthDay#1': (args) => (args[0] as MaterialLocalizations).formatShortMonthDay(args[1] as DateTime),
        'parseCompactDate#1': (args) => (args[0] as MaterialLocalizations).parseCompactDate(args[1] as String?),
        'dateRangeStartDateSemanticLabel#1': (args) => (args[0] as MaterialLocalizations).dateRangeStartDateSemanticLabel(args[1] as String),
        'dateRangeEndDateSemanticLabel#1': (args) => (args[0] as MaterialLocalizations).dateRangeEndDateSemanticLabel(args[1] as String),
        'remainingTextFieldCharacterCount#1': (args) => (args[0] as MaterialLocalizations).remainingTextFieldCharacterCount(args[1] as int),
        'openAppDrawerTooltip#0': (args) => (args[0] as MaterialLocalizations).openAppDrawerTooltip,
        'backButtonTooltip#0': (args) => (args[0] as MaterialLocalizations).backButtonTooltip,
        'clearButtonTooltip#0': (args) => (args[0] as MaterialLocalizations).clearButtonTooltip,
        'closeButtonTooltip#0': (args) => (args[0] as MaterialLocalizations).closeButtonTooltip,
        'deleteButtonTooltip#0': (args) => (args[0] as MaterialLocalizations).deleteButtonTooltip,
        'moreButtonTooltip#0': (args) => (args[0] as MaterialLocalizations).moreButtonTooltip,
        'nextMonthTooltip#0': (args) => (args[0] as MaterialLocalizations).nextMonthTooltip,
        'previousMonthTooltip#0': (args) => (args[0] as MaterialLocalizations).previousMonthTooltip,
        'firstPageTooltip#0': (args) => (args[0] as MaterialLocalizations).firstPageTooltip,
        'lastPageTooltip#0': (args) => (args[0] as MaterialLocalizations).lastPageTooltip,
        'nextPageTooltip#0': (args) => (args[0] as MaterialLocalizations).nextPageTooltip,
        'previousPageTooltip#0': (args) => (args[0] as MaterialLocalizations).previousPageTooltip,
        'showMenuTooltip#0': (args) => (args[0] as MaterialLocalizations).showMenuTooltip,
        'licensesPageTitle#0': (args) => (args[0] as MaterialLocalizations).licensesPageTitle,
        'rowsPerPageTitle#0': (args) => (args[0] as MaterialLocalizations).rowsPerPageTitle,
        'cancelButtonLabel#0': (args) => (args[0] as MaterialLocalizations).cancelButtonLabel,
        'closeButtonLabel#0': (args) => (args[0] as MaterialLocalizations).closeButtonLabel,
        'continueButtonLabel#0': (args) => (args[0] as MaterialLocalizations).continueButtonLabel,
        'copyButtonLabel#0': (args) => (args[0] as MaterialLocalizations).copyButtonLabel,
        'cutButtonLabel#0': (args) => (args[0] as MaterialLocalizations).cutButtonLabel,
        'scanTextButtonLabel#0': (args) => (args[0] as MaterialLocalizations).scanTextButtonLabel,
        'okButtonLabel#0': (args) => (args[0] as MaterialLocalizations).okButtonLabel,
        'pasteButtonLabel#0': (args) => (args[0] as MaterialLocalizations).pasteButtonLabel,
        'selectAllButtonLabel#0': (args) => (args[0] as MaterialLocalizations).selectAllButtonLabel,
        'lookUpButtonLabel#0': (args) => (args[0] as MaterialLocalizations).lookUpButtonLabel,
        'searchWebButtonLabel#0': (args) => (args[0] as MaterialLocalizations).searchWebButtonLabel,
        'shareButtonLabel#0': (args) => (args[0] as MaterialLocalizations).shareButtonLabel,
        'viewLicensesButtonLabel#0': (args) => (args[0] as MaterialLocalizations).viewLicensesButtonLabel,
        'anteMeridiemAbbreviation#0': (args) => (args[0] as MaterialLocalizations).anteMeridiemAbbreviation,
        'postMeridiemAbbreviation#0': (args) => (args[0] as MaterialLocalizations).postMeridiemAbbreviation,
        'timePickerHourModeAnnouncement#0': (args) => (args[0] as MaterialLocalizations).timePickerHourModeAnnouncement,
        'timePickerMinuteModeAnnouncement#0': (args) => (args[0] as MaterialLocalizations).timePickerMinuteModeAnnouncement,
        'modalBarrierDismissLabel#0': (args) => (args[0] as MaterialLocalizations).modalBarrierDismissLabel,
        'menuDismissLabel#0': (args) => (args[0] as MaterialLocalizations).menuDismissLabel,
        'drawerLabel#0': (args) => (args[0] as MaterialLocalizations).drawerLabel,
        'popupMenuLabel#0': (args) => (args[0] as MaterialLocalizations).popupMenuLabel,
        'menuBarMenuLabel#0': (args) => (args[0] as MaterialLocalizations).menuBarMenuLabel,
        'dialogLabel#0': (args) => (args[0] as MaterialLocalizations).dialogLabel,
        'alertDialogLabel#0': (args) => (args[0] as MaterialLocalizations).alertDialogLabel,
        'searchFieldLabel#0': (args) => (args[0] as MaterialLocalizations).searchFieldLabel,
        'currentDateLabel#0': (args) => (args[0] as MaterialLocalizations).currentDateLabel,
        'selectedDateLabel#0': (args) => (args[0] as MaterialLocalizations).selectedDateLabel,
        'scrimLabel#0': (args) => (args[0] as MaterialLocalizations).scrimLabel,
        'bottomSheetLabel#0': (args) => (args[0] as MaterialLocalizations).bottomSheetLabel,
        'scriptCategory#0': (args) => (args[0] as MaterialLocalizations).scriptCategory,
        'narrowWeekdays#0': (args) => (args[0] as MaterialLocalizations).narrowWeekdays,
        'firstDayOfWeekIndex#0': (args) => (args[0] as MaterialLocalizations).firstDayOfWeekIndex,
        'dateSeparator#0': (args) => (args[0] as MaterialLocalizations).dateSeparator,
        'dateHelpText#0': (args) => (args[0] as MaterialLocalizations).dateHelpText,
        'selectYearSemanticsLabel#0': (args) => (args[0] as MaterialLocalizations).selectYearSemanticsLabel,
        'unspecifiedDate#0': (args) => (args[0] as MaterialLocalizations).unspecifiedDate,
        'unspecifiedDateRange#0': (args) => (args[0] as MaterialLocalizations).unspecifiedDateRange,
        'dateInputLabel#0': (args) => (args[0] as MaterialLocalizations).dateInputLabel,
        'dateRangeStartLabel#0': (args) => (args[0] as MaterialLocalizations).dateRangeStartLabel,
        'dateRangeEndLabel#0': (args) => (args[0] as MaterialLocalizations).dateRangeEndLabel,
        'invalidDateFormatLabel#0': (args) => (args[0] as MaterialLocalizations).invalidDateFormatLabel,
        'invalidDateRangeLabel#0': (args) => (args[0] as MaterialLocalizations).invalidDateRangeLabel,
        'dateOutOfRangeLabel#0': (args) => (args[0] as MaterialLocalizations).dateOutOfRangeLabel,
        'saveButtonLabel#0': (args) => (args[0] as MaterialLocalizations).saveButtonLabel,
        'datePickerHelpText#0': (args) => (args[0] as MaterialLocalizations).datePickerHelpText,
        'dateRangePickerHelpText#0': (args) => (args[0] as MaterialLocalizations).dateRangePickerHelpText,
        'calendarModeButtonLabel#0': (args) => (args[0] as MaterialLocalizations).calendarModeButtonLabel,
        'inputDateModeButtonLabel#0': (args) => (args[0] as MaterialLocalizations).inputDateModeButtonLabel,
        'timePickerDialHelpText#0': (args) => (args[0] as MaterialLocalizations).timePickerDialHelpText,
        'timePickerInputHelpText#0': (args) => (args[0] as MaterialLocalizations).timePickerInputHelpText,
        'timePickerHourLabel#0': (args) => (args[0] as MaterialLocalizations).timePickerHourLabel,
        'timePickerMinuteLabel#0': (args) => (args[0] as MaterialLocalizations).timePickerMinuteLabel,
        'invalidTimeLabel#0': (args) => (args[0] as MaterialLocalizations).invalidTimeLabel,
        'dialModeButtonLabel#0': (args) => (args[0] as MaterialLocalizations).dialModeButtonLabel,
        'inputTimeModeButtonLabel#0': (args) => (args[0] as MaterialLocalizations).inputTimeModeButtonLabel,
        'signedInLabel#0': (args) => (args[0] as MaterialLocalizations).signedInLabel,
        'hideAccountsLabel#0': (args) => (args[0] as MaterialLocalizations).hideAccountsLabel,
        'showAccountsLabel#0': (args) => (args[0] as MaterialLocalizations).showAccountsLabel,
        'reorderItemToStart#0': (args) => (args[0] as MaterialLocalizations).reorderItemToStart,
        'reorderItemToEnd#0': (args) => (args[0] as MaterialLocalizations).reorderItemToEnd,
        'reorderItemUp#0': (args) => (args[0] as MaterialLocalizations).reorderItemUp,
        'reorderItemDown#0': (args) => (args[0] as MaterialLocalizations).reorderItemDown,
        'reorderItemLeft#0': (args) => (args[0] as MaterialLocalizations).reorderItemLeft,
        'reorderItemRight#0': (args) => (args[0] as MaterialLocalizations).reorderItemRight,
        'expandedIconTapHint#0': (args) => (args[0] as MaterialLocalizations).expandedIconTapHint,
        'collapsedIconTapHint#0': (args) => (args[0] as MaterialLocalizations).collapsedIconTapHint,
        'expansionTileExpandedHint#0': (args) => (args[0] as MaterialLocalizations).expansionTileExpandedHint,
        'expansionTileCollapsedHint#0': (args) => (args[0] as MaterialLocalizations).expansionTileCollapsedHint,
        'expansionTileExpandedTapHint#0': (args) => (args[0] as MaterialLocalizations).expansionTileExpandedTapHint,
        'expansionTileCollapsedTapHint#0': (args) => (args[0] as MaterialLocalizations).expansionTileCollapsedTapHint,
        'expandedHint#0': (args) => (args[0] as MaterialLocalizations).expandedHint,
        'collapsedHint#0': (args) => (args[0] as MaterialLocalizations).collapsedHint,
        'refreshIndicatorSemanticLabel#0': (args) => (args[0] as MaterialLocalizations).refreshIndicatorSemanticLabel,
        'keyboardKeyAlt#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyAlt,
        'keyboardKeyAltGraph#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyAltGraph,
        'keyboardKeyBackspace#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyBackspace,
        'keyboardKeyCapsLock#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyCapsLock,
        'keyboardKeyChannelDown#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyChannelDown,
        'keyboardKeyChannelUp#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyChannelUp,
        'keyboardKeyControl#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyControl,
        'keyboardKeyDelete#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyDelete,
        'keyboardKeyEject#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyEject,
        'keyboardKeyEnd#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyEnd,
        'keyboardKeyEscape#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyEscape,
        'keyboardKeyFn#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyFn,
        'keyboardKeyHome#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyHome,
        'keyboardKeyInsert#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyInsert,
        'keyboardKeyMeta#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyMeta,
        'keyboardKeyMetaMacOs#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyMetaMacOs,
        'keyboardKeyMetaWindows#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyMetaWindows,
        'keyboardKeyNumLock#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumLock,
        'keyboardKeyNumpad1#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumpad1,
        'keyboardKeyNumpad2#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumpad2,
        'keyboardKeyNumpad3#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumpad3,
        'keyboardKeyNumpad4#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumpad4,
        'keyboardKeyNumpad5#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumpad5,
        'keyboardKeyNumpad6#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumpad6,
        'keyboardKeyNumpad7#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumpad7,
        'keyboardKeyNumpad8#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumpad8,
        'keyboardKeyNumpad9#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumpad9,
        'keyboardKeyNumpad0#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumpad0,
        'keyboardKeyNumpadAdd#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumpadAdd,
        'keyboardKeyNumpadComma#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumpadComma,
        'keyboardKeyNumpadDecimal#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumpadDecimal,
        'keyboardKeyNumpadDivide#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumpadDivide,
        'keyboardKeyNumpadEnter#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumpadEnter,
        'keyboardKeyNumpadEqual#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumpadEqual,
        'keyboardKeyNumpadMultiply#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumpadMultiply,
        'keyboardKeyNumpadParenLeft#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumpadParenLeft,
        'keyboardKeyNumpadParenRight#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumpadParenRight,
        'keyboardKeyNumpadSubtract#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyNumpadSubtract,
        'keyboardKeyPageDown#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyPageDown,
        'keyboardKeyPageUp#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyPageUp,
        'keyboardKeyPower#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyPower,
        'keyboardKeyPowerOff#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyPowerOff,
        'keyboardKeyPrintScreen#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyPrintScreen,
        'keyboardKeyScrollLock#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyScrollLock,
        'keyboardKeySelect#0': (args) => (args[0] as MaterialLocalizations).keyboardKeySelect,
        'keyboardKeyShift#0': (args) => (args[0] as MaterialLocalizations).keyboardKeyShift,
        'keyboardKeySpace#0': (args) => (args[0] as MaterialLocalizations).keyboardKeySpace,
      };
}
