// GENERATED CODE - DO NOT MODIFY BY HAND
//
// Dart SDK: 3.10.7

import '../../api/plugin_context.dart';
import 'dart:collection';
import 'dart:math';

abstract final class UnmodifiableListViewBindings {
  static void register(DarticPluginContext ctx) {
    ctx.registerClass(
      name: 'dart:collection::UnmodifiableListView',
      type: UnmodifiableListView,
      test: (o) => o is UnmodifiableListView,
      methods: methodMap(),
      superclasses: ['dart:_internal::UnmodifiableListBase', 'dart:collection::ListBase', 'dart:core::List', 'dart:core::Iterable', 'dart:core::_ListIterable', 'dart:_internal::EfficientLengthIterable', 'dart:_internal::HideEfficientLengthIterable', 'dart:_internal::UnmodifiableListMixin'],
    );
  }

  static Map<String, Object? Function(List<Object?>)> methodMap() => {
        'cast#0': (args) => (args[0] as UnmodifiableListView).cast(),
        'elementAt#1': (args) => (args[0] as UnmodifiableListView).elementAt(args[1] as int),
        'followedBy#1': (args) => (args[0] as UnmodifiableListView).followedBy(args[1] as Iterable),
        'forEach#1': (args) { (args[0] as UnmodifiableListView).forEach((a) => (args[1] as Function)(a)); return null; },
        'contains#1': (args) => (args[0] as UnmodifiableListView).contains(args[1] as Object?),
        'every#1': (args) => (args[0] as UnmodifiableListView).every((a) => (args[1] as Function)(a) as bool),
        'any#1': (args) => (args[0] as UnmodifiableListView).any((a) => (args[1] as Function)(a) as bool),
        'firstWhere#2': (args) => (args[0] as UnmodifiableListView).firstWhere((a) => (args[1] as Function)(a) as bool, orElse: (args[2] as Function?) == null ? null : () => (args[2] as Function?)!()),
        'lastWhere#2': (args) => (args[0] as UnmodifiableListView).lastWhere((a) => (args[1] as Function)(a) as bool, orElse: (args[2] as Function?) == null ? null : () => (args[2] as Function?)!()),
        'singleWhere#2': (args) => (args[0] as UnmodifiableListView).singleWhere((a) => (args[1] as Function)(a) as bool, orElse: (args[2] as Function?) == null ? null : () => (args[2] as Function?)!()),
        'join#0': (args) => (args[0] as UnmodifiableListView).join(),
        'join#1': (args) => (args[0] as UnmodifiableListView).join(args[1] as String),
        'where#1': (args) => (args[0] as UnmodifiableListView).where((a) => (args[1] as Function)(a) as bool),
        'whereType#0': (args) => (args[0] as UnmodifiableListView).whereType(),
        'map#1': (args) => (args[0] as UnmodifiableListView).map((a) => (args[1] as Function)(a)),
        'expand#1': (args) => (args[0] as UnmodifiableListView).expand((a) => (args[1] as Function)(a) as Iterable),
        'reduce#1': (args) => (args[0] as UnmodifiableListView).reduce((a, b) => (args[1] as Function)(a, b)),
        'fold#2': (args) => (args[0] as UnmodifiableListView).fold(args[1] as dynamic, (a, b) => (args[2] as Function)(a, b)),
        'skip#1': (args) => (args[0] as UnmodifiableListView).skip(args[1] as int),
        'skipWhile#1': (args) => (args[0] as UnmodifiableListView).skipWhile((a) => (args[1] as Function)(a) as bool),
        'take#1': (args) => (args[0] as UnmodifiableListView).take(args[1] as int),
        'takeWhile#1': (args) => (args[0] as UnmodifiableListView).takeWhile((a) => (args[1] as Function)(a) as bool),
        'toList#1': (args) => (args[0] as UnmodifiableListView).toList(growable: args[1] as bool),
        'toSet#0': (args) => (args[0] as UnmodifiableListView).toSet(),
        'add#1': (args) { (args[0] as UnmodifiableListView).add(args[1] as dynamic); return null; },
        'addAll#1': (args) { (args[0] as UnmodifiableListView).addAll(args[1] as Iterable); return null; },
        'remove#1': (args) => (args[0] as UnmodifiableListView).remove(args[1] as Object?),
        'removeWhere#1': (args) { (args[0] as UnmodifiableListView).removeWhere((a) => (args[1] as Function)(a) as bool); return null; },
        'retainWhere#1': (args) { (args[0] as UnmodifiableListView).retainWhere((a) => (args[1] as Function)(a) as bool); return null; },
        'clear#0': (args) { (args[0] as UnmodifiableListView).clear(); return null; },
        'removeLast#0': (args) => (args[0] as UnmodifiableListView).removeLast(),
        'sort#0': (args) { (args[0] as UnmodifiableListView).sort(); return null; },
        'sort#1': (args) { (args[0] as UnmodifiableListView).sort((args[1] as Function?) == null ? null : (a, b) => (args[1] as Function?)!(a, b)); return null; },
        'shuffle#0': (args) { (args[0] as UnmodifiableListView).shuffle(); return null; },
        'shuffle#1': (args) { (args[0] as UnmodifiableListView).shuffle(args[1] as Random?); return null; },
        'asMap#0': (args) => (args[0] as UnmodifiableListView).asMap(),
        'sublist#1': (args) => (args[0] as UnmodifiableListView).sublist(args[1] as int),
        'sublist#2': (args) => (args[0] as UnmodifiableListView).sublist(args[1] as int, args[2] as int?),
        'getRange#2': (args) => (args[0] as UnmodifiableListView).getRange(args[1] as int, args[2] as int),
        'removeRange#2': (args) { (args[0] as UnmodifiableListView).removeRange(args[1] as int, args[2] as int); return null; },
        'fillRange#2': (args) { (args[0] as UnmodifiableListView).fillRange(args[1] as int, args[2] as int); return null; },
        'fillRange#3': (args) { (args[0] as UnmodifiableListView).fillRange(args[1] as int, args[2] as int, args[3] as Object?); return null; },
        'setRange#3': (args) { (args[0] as UnmodifiableListView).setRange(args[1] as int, args[2] as int, args[3] as Iterable); return null; },
        'setRange#4': (args) { (args[0] as UnmodifiableListView).setRange(args[1] as int, args[2] as int, args[3] as Iterable, args[4] as int); return null; },
        'replaceRange#3': (args) { (args[0] as UnmodifiableListView).replaceRange(args[1] as int, args[2] as int, args[3] as Iterable); return null; },
        'indexOf#1': (args) => (args[0] as UnmodifiableListView).indexOf(args[1] as Object?),
        'indexOf#2': (args) => (args[0] as UnmodifiableListView).indexOf(args[1] as Object?, args[2] as int),
        'indexWhere#1': (args) => (args[0] as UnmodifiableListView).indexWhere((a) => (args[1] as Function)(a) as bool),
        'indexWhere#2': (args) => (args[0] as UnmodifiableListView).indexWhere((a) => (args[1] as Function)(a) as bool, args[2] as int),
        'lastIndexOf#1': (args) => (args[0] as UnmodifiableListView).lastIndexOf(args[1] as Object?),
        'lastIndexOf#2': (args) => (args[0] as UnmodifiableListView).lastIndexOf(args[1] as Object?, args[2] as int?),
        'lastIndexWhere#1': (args) => (args[0] as UnmodifiableListView).lastIndexWhere((a) => (args[1] as Function)(a) as bool),
        'lastIndexWhere#2': (args) => (args[0] as UnmodifiableListView).lastIndexWhere((a) => (args[1] as Function)(a) as bool, args[2] as int?),
        'insert#2': (args) { (args[0] as UnmodifiableListView).insert(args[1] as int, args[2] as dynamic); return null; },
        'removeAt#1': (args) => (args[0] as UnmodifiableListView).removeAt(args[1] as int),
        'insertAll#2': (args) { (args[0] as UnmodifiableListView).insertAll(args[1] as int, args[2] as Iterable); return null; },
        'setAll#2': (args) { (args[0] as UnmodifiableListView).setAll(args[1] as int, args[2] as Iterable); return null; },
        'isEmpty#0': (args) => (args[0] as UnmodifiableListView).isEmpty,
        'isNotEmpty#0': (args) => (args[0] as UnmodifiableListView).isNotEmpty,
        'first#0': (args) => (args[0] as UnmodifiableListView).first,
        'last#0': (args) => (args[0] as UnmodifiableListView).last,
        'single#0': (args) => (args[0] as UnmodifiableListView).single,
        'reversed#0': (args) => (args[0] as UnmodifiableListView).reversed,
        'first=#1': (args) { (args[0] as UnmodifiableListView).first = args[1] as dynamic; return args[1]; },
        'last=#1': (args) { (args[0] as UnmodifiableListView).last = args[1] as dynamic; return args[1]; },
        'length=#1': (args) { (args[0] as UnmodifiableListView).length = args[1] as int; return args[1]; },
        '+#1': (args) => (args[0] as UnmodifiableListView) + (args[1] as List),
        '[]=#2': (args) { (args[0] as UnmodifiableListView)[args[1] as int] = args[2]; return args[2]; },
        '#1': (args) => UnmodifiableListView(args[0] as Iterable),
        '[]#1': (args) => (args[0] as UnmodifiableListView)[args[1] as int],
        'length#0': (args) => (args[0] as UnmodifiableListView).length,
        'iterator#0': (args) => (args[0] as UnmodifiableListView).iterator,
      };
}
